### ISSUE TITLE
Ban/Comm Block Reason: Quotes (") showing up as &quot;

### ISSUE THREAD

**Issue by zAfLu** [sbpp/sourcebans-pp#100]
Hello,

i got some issues with quotes in reason insert by Web bans/Comms.

If i choose "Other" as reason and try to add something like 

> Wrote: "ashdkajshdkjasdkjad" in chat

The Web view will return/show

> `Wrote: &quot;ashdkajshdkjasdkjad&quot; in chat`

If you need other examples just let me know

**Comment by Sarabveer** [comment]
Does this happen with 1.4.11?

**Comment by sarabveer** [comment]
Development is done on 1.0
