### ISSUE TITLE
Webpanel Ban ADD over IPv4 - fine but IPV6 dont?

### ISSUE THREAD

**Issue by Trice1984** [sbpp/sourcebans-pp#1001]
Hello togheter,

when we ban over Webpanel, its all OK by IPV4, when an Admin has  IPV6, the ban dont´t stand in Database or Homepage Bans.

LOG:
Details | Ban  against (STEAM_0:1:46xxxx) has been added. Reason: Ban BHOP Length: 10080

IP | 2003:6:10f:3964:e50f:301e:e6ee:bc4b

But there no Ban Added, 
Have this problem someone too?

Many greetz Trice

----------------------------------------
**Operating System:**   Ubuntu 24.04.1 LTS x86_64
**SourceBans++ Version:**    [SourceBans++]1.8.0 | Git: 1420
**PHP Version:** PHP-8.3 
**MySQL Version:**   MySQL 5.7.44
**Link to your project:** https://sb.xloldies.de/

Same problems are in 2020 and 2023 in Sourceban Issue LOG, but now? Someone have a fix?

**Comment by Rushaway** [comment]
Did you run updater 705.php ? 6e2ae0d

**Comment by Trice1984** [comment]
Hi Rushaway, i Must edit it Manual After The Import from an Older Backup, now its Fine. Thank you
