### ISSUE TITLE
Uncaught ReferenceError: xajax_ServerHostProperty is not defined

### ISSUE THREAD

**Issue by askovpen** [sbpp/sourcebans-pp#101]
2d6c89ba79713dcf9f14e2166c6dae1cd2f0a137 missed define of xajax_*

**Comment by sarabveer** [comment]
huh?

**Comment by askovpen** [comment]
defined ServerHostProperty, instead xajax_ServerHostProperty

**Comment by sarabveer** [comment]
that commit has nothing to do with xajax, which php file are you referring too.

**Comment by askovpen** [comment]
this commit - version (last), which i use.

**Comment by askovpen** [comment]
php 5.5. Version 8adeff9ce690c0c129373330a1d07bcad1ce7e93 work perfect.

**Comment by sarabveer** [comment]
i dont understand, im confused whats ur question

**Comment by askovpen** [comment]
latest version not work. in chrome dev tools js error: Uncaught ReferenceError: xajax_ServerHostProperty is not defined

**Comment by sarabveer** [comment]
i dont get any error

**Comment by sarabveer** [comment]
Fixed in latest commit.
