### ISSUE TITLE
1.8.0 Git: 1428 Displays 'Undefined variable $unwanted_sequence' errors on Home Page

### ISSUE THREAD

**Issue by DNA-styx** [sbpp/sourcebans-pp#1020]
What are the steps to reproduce this issue?
-------------------------------------------
1. Extract ~~1.8.1 git 1431~~ 1.8.0 Git: 1428 (latest as of 24NOV24) to new folder on server
2. Change composer to download v5.3.0 (to avoid being forced up to php 8.2) and install composer
3. Copy config.php from 1.8.0 1411 install
4. Perform upgrade using web interface (all good) - delete install and upgrader folders
5. Point subdomain to new folder
6. Visit web page

What happens?
-------------
Errors are displayed.
![image](https://github.com/user-attachments/assets/a140cc53-21ea-4f61-a56b-2fbac2c50bc4)

What were you expecting to happen?
----------------------------------
No errors.

Any logs, error output, etc.?
----------------------------
Multiple:
`Warning: Undefined variable $unwanted_sequence in /usr/www/xxxxxx/xxxxxxx/pages/page.home.php on line XX`
Where XX is 47 , 105 , 171

Any other comments?
-------------------
I note that each of the lines mentioned in the error use this code
` $cleaned_name       = str_replace($unwanted_sequence, '', $cleaned_name);`

I note that $unwanted_sequence is also used in [page.banlist.php & page.commslist.php](https://github.com/search?q=repo%3Asbpp%2Fsourcebans-pp%20%24unwanted_sequence&type=code)

These two pages do not give the error that the home does.

I note that both the non-erroring pages use this code rather than the one the home page uses:

`$cleaned_name = trim($cleaned_name);`

If I use this code on the home page the errors are removed.

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**
**PHP Version:** 8.1
**MySQL Version:**
**Link to your project:** http://sourcebans.dnagames.site/
**Link to a phpinfo() output:** (on request)

**Comment by Rushaway** [comment]
Thanks for noticing this issue. A fix has been made and a pull request has been opened.

**Comment by DNA-styx** [comment]
FYI @Rushaway , I've just noticed that these errors appear when I run PHP Version 8.2.26 but not PHP Version 8.3.14 or PHP Version 8.4.1

![image](https://github.com/user-attachments/assets/2dcc68d7-2c9a-424e-b61c-3b09ecdd3287)
![image](https://github.com/user-attachments/assets/5bc4a24b-7bf2-4dad-b652-d1f1503bc5cd)
![image](https://github.com/user-attachments/assets/366d9e84-9f6e-4308-879b-19cf8074f03c)
