### ISSUE TITLE
Unable to log in with fresh database install of v1.8.1 git 1431 

### ISSUE THREAD

**Issue by DNA-styx** [sbpp/sourcebans-pp#1022]
What are the steps to reproduce this issue?
-------------------------------------------
1. Download .zip file of code base
2. Perform fresh database Install 
3. Try to log in

What happens?
-------------
Log in fails below error displayed:
Error: the XML response that was returned from the server is invalid. Received: SQL Statement failed on preparation: SELECT aid, password, attempts, lockout_until FROM sb_admins WHERE user = ?'

![image](https://github.com/user-attachments/assets/efd78f29-4eab-49d9-b3f6-d5a131db39f2)

What were you expecting to happen?
----------------------------------
Log in.

Any logs, error output, etc.?
----------------------------
Error: the XML response that was returned from the server is invalid. Received: SQL Statement failed on preparation: SELECT aid, password, attempts, lockout_until FROM sb_admins WHERE user = ?'

Any other comments?
-------------------
Running the updater resolves the issue

![image](https://github.com/user-attachments/assets/fa0fb5d3-8960-45b1-a6ab-91534c3ab070)

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:** v1.8.1 git 1431 
**PHP Version:** 8.2.25
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:** (on request)

**Comment by Rushaway** [comment]
Updater have to be run.
https://github.com/sbpp/sourcebans-pp/blob/php81/CHANGELOG.md#101124-version-181-run-updater-required

**Comment by DNA-styx** [comment]
Ahh, sorry, wasn't aware there was an active change log. Good stuff. Thanks again.
