### ISSUE TITLE
Plugin not working well with CS:S 

### ISSUE THREAD

**Issue by iGreen123** [sbpp/sourcebans-pp#103]
i dont know why admins have onle permission to 1 week ban not longer. Can you tell me how to change or add ban options?

**Comment by sarabveer** [comment]
If you give an admin ban flag, they cannot do perm bans without the unban flag. Other than that, it should be fine.

**Comment by iGreen123** [comment]
And the second is that on css server everything works very well except that admins work only if i add them manualy to admins.cfg or sb_admins.cfg but it dosnt work when i add them from web interface, this problem persists only on css server, in csgo when i add from web interface it works fine. 
I reveice this error everyday:

[sourcebans.smx] Failed to retrieve admins from the database, Subquery returns more than 1 row

the database.cfg is copied from csgo server to be sure everything is good but still i receive this error.

**Comment by iGreen123** [comment]
So they need unban flag to have permanent ban acces, ok, is there a way to change the permanent ban from ''e'' flag to other for ex ''t'' or ''s'' ? Because i dont give unban acces but i want them to have permanent ban acces.

**Comment by sarabveer** [comment]
Flags are set by SourceMod, not SourceBans

**Comment by sarabveer** [comment]
Please download the latest sourcemod, and recompile the plugins with that version of sourcemod, and then also put the new version of sourcemod on the cs:s server.

**Comment by sarabveer** [comment]
Since there was no reply, I am closing the issue.

**Comment by iGreen123** [comment]
thank you very much for you answer, i will try and i will let you know.
i dont have much time thats why sometimes it can take a few days for me to reply, sorry for that :)

**Comment by Sarabveer** [comment]
alright

**Comment by iGreen123** [comment]
i dont know how to compile sourcebans, i have a rented server on a hosting company, server is running linux, can you please tell me how to compile it? and also is that possible that a non-compiled version of sourcebans to make lag spikes on a popular server?

**Comment by iGreen123** [comment]
I succesufuly compiled it but i still receive the same error which i dont receive on csgo server. 

[sourcebans.smx] Failed to retrieve admins from the database, Subquery returns more than 1 row

Also is that posible that this release could make lag spikes? because players started to say that server lags when there are too many people (32/32) and this started after i updated sourcebans :(

**Comment by stickz** [comment]
Sourcemod creates new threads for queries. If your server is multi-threaded then this plugin shouldn't be causing lag spikes, because the queries will execute on a processor core different from the game.

**Comment by iGreen123** [comment]
before i was using 1.4.11 , maybe if i use 1.5.2 it will be better? btw i compiled sb with newest sm and uploaded sb and sm to server and i still receive this :(

[sourcebans.smx] Failed to retrieve admins from the database, Subquery returns more than 1 row

**Comment by stickz** [comment]
You should be using 1.5.3 here.
https://github.com/Sarabveer/SourceBans-Fork/releases

**Comment by iGreen123** [comment]
yes, this is the one that im using since a week, and the coincidence is that server started to lag after updating, but im not sure yet if it is because of sourcebans, ill test tomorrow and i will let you know :)

but im still stuck at the other problem - [sourcebans.smx] Failed to retrieve admins from the database, Subquery returns more than 1 row , can you please help me? thank you in advance :)

**Comment by stickz** [comment]
Is your server multi-threaded and does it have access to more than one processor core?

**Comment by iGreen123** [comment]
I will ask the host and i will be back with an answer :)

**Comment by iGreen123** [comment]
he said yes

**Comment by sarabveer** [comment]
That error means you have multiple admins registered with the same Steam ID.
