### ISSUE TITLE
SourceBans getting hacked really often

### ISSUE THREAD

**Issue by shavitush** [sbpp/sourcebans-pp#106]
Once a month or so my SourceBans++ installation gets hacked, admins get added; logs get removed and I simply can't do anything to solve it because I have no idea what causes it or what to log in order to see what's causing it.

It's one group that does it to my CS:GO community and to some other Israeli one.

They add themselves as admins and massively ban people from inside the servers (I see the bans in the SourceMod log), then the logs get cleaned. Here's the screenshot of what's left in the system log: http://i.imgur.com/sohDWs1.png  
`Admin deleted` is when our community admin deleted the hacker's account, nothing else before.

What I've attempted to do in order to fight them:  
Edited log deletion to do that instead of clearing the logs -

```
//pages/admin.settings.php
//Log stuff
$logs = new CSystemLog();
$page = 1;
if (isset($_GET['page']) && $_GET['page'] > 0)
    $page = intval($_GET['page']);

if(isset($_GET['log_clear']) && $_GET['log_clear'] == "true")
{
    $log = new CSystemLog("w", "Log Clearing Attempt", $userbank->GetProperty('user') . " tried to clear the logs, but the feature is disabled.");
}
```

Made remote MySQL connections possible only from the web host. (So I can only access the database with a tool like `phpmyadmin`)  
Scrambled the MySQL password for every user everytime we got hacked.

I'm not any expert in web stuff, I'd appreciate help, at least in knowing how they do it or how to fix it, thanks :)

**Comment by sarabveer** [comment]
what you can do is make the sb private, and only available to admins via apache .htpassword

this is a temp fix, but sb is full of security flaws that need a rewrite to sb to get fixed.

what you can also do is force everyone to use steam login, so remove email from their account, and generate a random password they dont know.

**Comment by sarabveer** [comment]
also, there was a few security fixes in the dev version, so try using the dev version, and see if you still get hacked.

**Comment by shavitush** [comment]
Steam login doesn't really work for me idk why; how do I switch from the stable version to the dev one without data/theme loss?

**Comment by sarabveer** [comment]
Your not gonna loose data, you just copy over the dev version,  you will lose ur custom theme if you modified the default theme.

**Comment by shavitush** [comment]
I updated it to the dev version, I hope it's fixed, thanks for helping me :)

**Comment by sarabveer** [comment]
Also try using https

You can get a free SSL cert from StartSSL or Let's Encrypt
