### ISSUE TITLE
Add Multi-Language Support

### ISSUE THREAD

**Issue by Speciesx** [sbpp/sourcebans-pp#109]

**Comment by kilroy98** [comment]
If it will be make, I can provide translation on russian (if I correctly understood).

**Comment by Speciesx** [comment]
I've also a nearly complete translated sourcebans in russian.

**Comment by ghost** [comment]
I can also help with Russian, if necessary.

**Comment by sarabveer** [comment]
I can have different releases, but I can't just have more than one language in one version, at SB was not designed for multi-language support.

**Comment by ghost** [comment]
The introduction of multi-language is not planned in the future?

**Comment by Speciesx** [comment]
@Sarabveer 
Then is time for a redesign!

**Comment by sarabveer** [comment]
@Speciesx I'm open to Pull Requests!

**Comment by DarkDeviL** [comment]
If multi-language options should ever be added, the best option would be to:
- screw this one and build a new one based on SourceBans 2.0, which should already support multiple languages.
- write a new web panel from scratch
