### ISSUE TITLE
No map image

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#111]
Not displayed image maps when you use Workshop map.
File is placed in the appropriate folder: http://bans.awp.by/images/maps/awp_lego_2_winter.jpg
I suspect that this is due to a non-standard name of the current map.

Example:
workshop/569848047/awp_lego_2_winter
instead of the ordinary
awp_lego_2_winter

![2](https://cloud.githubusercontent.com/assets/5341200/12335634/3ce463cc-bb11-11e5-9689-d1b559a88cd6.jpg)

SourceBans++ 1.5.3
http://bans.awp.by/

**Comment by sarabveer** [comment]
image needs to be: workshop/569848047/awp_lego_2_winter

because thats what sourcebans is getting from the server
