### ISSUE TITLE
Permanent ban protest show wrong end ban date,Group/Friend Ban and Show player groups error (Git: 324)

### ISSUE THREAD

**Issue by kilroy98** [sbpp/sourcebans-pp#112]
This error observed on archive and current ban protests.
![bandicam 2016-01-15 16-16-37-160](https://cloud.githubusercontent.com/assets/13346898/12355250/1a9c1e34-bba4-11e5-9fca-e2a2e5078028.jpg)

---

GROUP BAN
With that issued the error, ban 4 people. (Tested on link example)
![bandicam 2016-01-15 16-37-15-494](https://cloud.githubusercontent.com/assets/13346898/12355582/4703337a-bba6-11e5-8e19-0d1a91eb239d.jpg)

---

FRIEND BAN
Players also bans, but it gives an error.
![bandicam 2016-01-15 16-41-23-260](https://cloud.githubusercontent.com/assets/13346898/12355664/db634762-bba6-11e5-900d-fd772abc8e86.jpg)

---

SHOW GROUPS
Group does not load. 
![bandicam 2016-01-15 16-45-27-142](https://cloud.githubusercontent.com/assets/13346898/12355744/74db8a3a-bba7-11e5-8bc8-597cb4107167.jpg)
And does not show player nickname, although it should.
![bandicam 2016-01-15 16-58-52-025](https://cloud.githubusercontent.com/assets/13346898/12356073/4d41e4a4-bba9-11e5-978b-1c3fe54ad256.jpg)

---

---

P.S. Google Translate :(
P.S.S. I'm use free hosting.

**Comment by sarabveer** [comment]
set_time_limit() is blocked by your free host, this is not a SourceBans problem
