### ISSUE TITLE
[sourcebans.smx] Failed to retrieve admins from the database, Subquery returns more than 1 row (Duplicate #103)

### ISSUE THREAD

**Issue by iGreen123** [sbpp/sourcebans-pp#114]
I dont reveive any error , just this one:

[sourcebans.smx] Failed to retrieve admins from the database, Subquery returns more than 1 row

and you said that it is because i have multiple admins with the same steam id.

i dont understand how can i have multiple admins with the same steam id? if you try to put an admin with the same steam id it will give an error and wont let me do that, so i think thats imposible.

database is correct, everything is right, maybe i need to do something else?
on csgo server when i add from web interface it modifies the sb_admins.cfg and adds them but on css server it doesnt, please help me!

**Comment by sarabveer** [comment]
Use phpmyadmim or something

**Comment by iGreen123** [comment]
What do you mean? Use it for what?

**Comment by sarabveer** [comment]
Check your database for errors and duplicates

**Comment by iGreen123** [comment]
databases.cfg ? everything is perfect in there because i use the same db from csgo server where it works well

**Comment by iGreen123** [comment]
:(

**Comment by sarabveer** [comment]
Well I can't say anything, the error means you have duplicate admins.

**Comment by iGreen123** [comment]
But how is that possible? you know that when you add an admin with the same steam id it won't let you

**Comment by sarabveer** [comment]
That's what I'm saying, use PHPMyAdmin to check your database

**Comment by iGreen123** [comment]
Ok, that error doesn't matter to me, what is important to me is that the admins work only when i add them directly from admins.cfg, but when i add them from web interface they dont work ( they dont shot up in admins.cfg or sb_admins.cfg )

by the way, admin_groups.cfg will update from web interface, but admins.cfg or sb_admins.cfg wont:(

**Comment by iGreen123** [comment]
by the way, admin_groups.cfg will update from web interface, but admins.cfg wont:(

**Comment by sarabveer** [comment]
admins.cfg is not gonna update because its not used anymore

Also sb_admins won't update until you fix that issue.

I'll say this, make a new database and install a new SB install somewhere else. Then add the admins there, if they work, that means there is something wrong with your old db.

Please use phpmyadmin and inspect your database.

I'm not helping you after this.

**Comment by iGreen123** [comment]
ok, i will find the duplicated steam id using phpmyadmin and i will let you know if the problem dissapears

**Comment by iGreen123** [comment]
i have +60 admins, i cant add them all again one by one, i will let you know if the problem was fixed by removing the duplicated steam id, thank you very much for you help and pacience, i really apreciate that :)

**Comment by iGreen123** [comment]
Sorry for being so late, it did solve the problem on the main css server ( css steam ), however very strange the last css server still has this issue ( css v34 - old version )

**Comment by sarabveer** [comment]
Update SourceMod and CSS, thats all I can say.
