### ISSUE TITLE
Warning: Division by zero

### ISSUE THREAD

**Issue by AticZPrime** [sbpp/sourcebans-pp#115]
I get this error when I look at the ban list : Warning: Division by zero in /home/go_free_servers/client_10/www/sourcebans/pages/page.banlist.php on line 678

$pages = ceil($BanCount/$BansPerPage);
if($pages > 1) {
    $ban_nav .= '&nbsp;<select onchange="changePage(this,\'B\',\''.(isset($_GET['advSearch']) ? $_GET['advSearch'] : '').'\',\''.(isset($_GET['advType']) ? $_GET['advType'] : '').'\');">';
    for($i=1;$i<=$pages;$i++)
    {
        if(isset($_GET["page"]) && $i == $page) {
            $ban_nav .= '<option value="' . $i . '" selected="selected">' . $i . '</option>';
            continue;
        }
        $ban_nav .= '<option value="' . $i . '">' . $i . '</option>';
    }
    $ban_nav .= '</select>';

**Comment by sarabveer** [comment]
PHP Version?

**Comment by AticZPrime** [comment]
The latest version.

**Comment by sarabveer** [comment]
The exact version?

**Comment by AticZPrime** [comment]
Nevermind, I fixed it. I had the SourceBans-Fork-master and I tried with
the SourceBans-Fork-1.5.3 and everything worked.
