### ISSUE TITLE
Support for Disabled Admins

### ISSUE THREAD

**Issue by jljr222** [sbpp/sourcebans-pp#120]
In SourceBans there is an option called:

"EnableAdmins"

Which I have set to 0 because I am using another plugin to sync admins between my XenForo installation and the game server. The problem is that now none of the bans submitted from my admins have a way of being uniquely identified because they technically have no "aid". If they use the admin menu, it sets the aid to 0. If they use sm_addban in-game then it doesn't even work because it tries to set the aid as NULL.

Could a new column in the sb_bans and sb_comms sections be added called adminauthid and record the steam id of the admin issuing the ban or mute? I know it seems redundant, because the sb_admins table will have that information already. Problem is, if you don't have data in those tables you're screwed. Which defeats the purpose of even being able to disabled admins :P.

The only other solution would be to add a new check for aid and have it do the following:

Check to see if the admin has an aid, if not, then check to see if they have a steamid and records that. If they have neither then set it to 0 as CONSOLE.

I may be the only person using SourceBans this way, but it would VERY helpful!

**Comment by sarabveer** [comment]
Development is done on 1.0
