### ISSUE TITLE
empty ban reason

### ISSUE THREAD

**Issue by eNNercY1337** [sbpp/sourcebans-pp#121]
after playing in the update (1.5.4) it seems like that when you ban via chat (/ban @me 1 reason) or also via console that it doesnt provide a reason on sourcebans itself, just remains empty.
if you use the regular menu though it displays the reason. 

both web and servers run the lastest version off from github.

**Comment by sarabveer** [comment]
Any logs, what sourcemod version?

**Comment by eNNercY1337** [comment]
SourceMod v1.7.3-dev+5283 and cant see anything suspicious in the logs.

**Comment by sarabveer** [comment]
Check the sourcemod logs, check the sourcebans log, I can't do much without logs

**Comment by eNNercY1337** [comment]
L 02/15/2016 - 09:56:12: [sourcebans.smx] "kVN.tf - Panda-Community.com<4><[U:1:74739569]><>" banned "kVN.tf - Panda-Community.com<4><[U:1:74739569]><>" (minutes "1") (reason "¤½ test1234")

used the following command > /ban @me 1 test1234

seems like it adds on its own "¤½" to the reason, might be the reason why it cant display it on the web page?

**Comment by sarabveer** [comment]
This is a plugin issue, @stickz, where are you

**Comment by eNNercY1337** [comment]
any ETA when this is getting fixed?

**Comment by sarabveer** [comment]
Tell @stickz

**Comment by jdlovins** [comment]
I would like to add that something similar happens with /mute and /gag.
 [SourceComms] Issued an extended gag on Rick Sanchez for 30 minutes (reason: |7 ayer rea|7 ayer rea|7 ayer rea|7 ayer reason).

it uses that same reason everytime even if you don't list a reason. It also doesn't seem to push it to the database. A temp fix was to restart the TF2 server that had been up for about 2 weeks straight.

**Comment by eNNercY1337** [comment]
i experience the same issue.

no offense but i wonder if the plugin even got tested before it got released lol

**Comment by stickz** [comment]
This reason code is absolutely horrible on the ban command. I am working on simplifying it currently.

**Comment by sarabveer** [comment]
Fixed https://github.com/Sarabveer/SourceBans-Fork/commit/44d22bee2012557675b917438b36484d1765dd2c

**Comment by sarabveer** [comment]
@stickz can you also patch up sourcecomms

**Comment by eNNercY1337** [comment]
sourcebans is also still broken.

**Comment by Joe-Howanski** [comment]
@stickz Currently quotation marks are broken with Team Fortress 2. Putting " into the chat, results in it being changed to '. As a result the plugin refuses any reason believing that there is no quotations around the reason.

If one instead tries to use the console, which does allow quotes, it seems there is now a bug that prevents the plugin from correctly doing so.

Typing in sm_ban player 0 "This is my Reason" results in the Reason menu being brought up for you to select from. Choosing one of the option triggers the ban for that reason, not to the original one in the string.

**Comment by asherkin** [comment]
Yeah, that patch is pretty broken, especially since the required change was much simpler.

```
    // Get the reason
    new String:reason[128];
    if (args >= 3)
    {
        GetCmdArg(3, reason, sizeof(reason));
        for (new i = 4; i <= args; i++)
        {
            GetCmdArg(i, buffer, sizeof(buffer));
            Format(reason, sizeof(reason), "%s %s", reason, buffer);
        }
    }
```

**Comment by sarabveer** [comment]
@asherkin I'm not the best person to contact if anyone has plugin issues

**Comment by stickz** [comment]
@Sarabveer Is sourcecomms broken aswell? It shouldn't be.

**Comment by sarabveer** [comment]
@stickz  it is. according to @eNNercY1337 @jdlovins

**Comment by sarabveer** [comment]
sourcecomms isnt fixed either

**Comment by MtnDewster** [comment]
I'm having an issue with sourcecomms where if we leave the mute/gag reason blank, it inserts it's own which is "|7 layer re layer re layer re ayer reason" and for each new mute it keeps adding on to that.

**Comment by sarabveer** [comment]
@PrinceDrew I know, but I'm not the best sourcepawn scripter out there. im waiting for someone to nicely volunteer to the project.

**Comment by MtnDewster** [comment]
@Sarabveer That's fine, I just wanted to let you know, and anyone reading this, that SourceComms is indeed still broken and what is wrong with it.

**Comment by stickz** [comment]
@Sarabveer Could you revert this commit please for testing purposes?
https://github.com/stickz/SourceBans-Fork/commit/6cc046fa34a8a76f9878dc88a6dda8de392226f5

**Comment by CrazyHackGUT** [comment]
I fixed bug with syntax queries from SourceComms. With logging queries.

Find this line in sourcecomms.sp (string 2889):
`decl String:sQueryMute[1024], String:sQueryGag[1024];`

Replace decl on new.
`new String:sQueryMute[1024], String:sQueryGag[1024];`

Save and compile.
After these simple manipulations, SourceComms started normally add mutes/gags.

My SourceBans (warning, i translating SB++ into russian language): http://bans.g-44.ru/index.php?p=commslist
