### ISSUE TITLE
empty ban reason #2

### ISSUE THREAD

**Issue by eNNercY1337** [sbpp/sourcebans-pp#123]
so after playing in the hotfix and updating web/game and also sourcemod it still doesnt work.
the "Ban Player" disappears after my test ban and throws out weird errors as listed below.

SourceMod v1.7.3-dev+5297
SourceBans++ 1.5.4-git334

errorlog output:

[sourcecomms.smx] Lost connection to DB. Reconnect after delay.
[sourcecomms.smx] Query_AddBlockInsert failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xx.xx.xx.xx', 126, 1)('STEAM_0:1:37369784', 'kVN.tf - Panda-Community.com', U' at line 1
[sourcecomms.smx] Failed to query database. (near "EAM_0": syntax error)
[sourcecomms.smx] Failed to query database. (unrecognized token: "")

[sourcecomms.smx] "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" silenced "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" (minutes "30") (reason "testreason")
[sourcecomms.smx] "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" ungagged "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" (reason "ÿÿÿÿ")
[sourcecomms.smx] "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" unmuted "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" (reason "ÿÿÿÿ")
[sourcecomms.smx] "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" removed gag for STEAM_0:1:37369784 from DB
[sourcecomms.smx] "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" removed mute for STEAM_0:1:37369784 from DB
[sourcebans.smx] "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" banned "kVN.tf - Panda-Community.com<2><[U:1:74739569]><>" (minutes "1") (reason "¤½ testreason")

no idea why it adds "¤½" at the reason when i try to use /ban @me 1 testreason

@Sarabveer @stickz

**Comment by sarabveer** [comment]
Please don't open new issues, pls reopen the old issues. #121
