### ISSUE TITLE
SB_Init was not found

### ISSUE THREAD

**Issue by AzaZPPL** [sbpp/sourcebans-pp#124]
I receive the following errors:

```
L 02/20/2016 - 02:22:55: [SM] Unable to load plugin "sb_bans.smx": Native "SB_Init" was not found
L 02/20/2016 - 02:22:55: [SM] Unable to load plugin "sb_admins.smx": Native "SB_Init" was not found
```

I've added all the plugins in in the plugins folder what am I missing?

**Comment by sarabveer** [comment]
This plugin is for the new sourcebans, which has no webpanel whatsoever.

Unless you want to use sb2, which is dead?

**Comment by AzaZPPL** [comment]
So those two plugins are for the new sourceban? What am I supposed to add to the plugins folder than?

**Comment by sarabveer** [comment]
Idk, why didn't you download 1.5.4?

**Comment by AzaZPPL** [comment]
Yes I downloaded 1.5.4. Those files came out of the plugins folder?

**Comment by AzaZPPL** [comment]
Wait I might just be high

**Comment by sarabveer** [comment]
There not here buddy http://puu.sh/neohS/948388a03e.png

**Comment by AzaZPPL** [comment]
I see I'm an idiot. I accidentally added sourcebans 2.0 before this. After I saw that sourcebans 2.0 is not correct I overwritten it with 1.5.4. But some files was left behind.

My bad.
