### ISSUE TITLE
Nicknames of players and the reason of a ban are displayed incorrectly

### ISSUE THREAD

**Issue by RED4911** [sbpp/sourcebans-pp#13]
Nicknames of players and the reason of a ban are displayed incorrectly. In sourcecomms everything is displayed correctly. In sourcebans it is incorrect.
Set the character set UTF-8 database sourcebans.sp

http://s018.radikal.ru/i528/1502/c4/52bef237b198.jpg

**Comment by sarabveer** [comment]
All the tables have their character set to UTF-8.

What are you asking me?

**Comment by RED4911** [comment]
Yes, everything in UTF -8. File sourcebans.cfg also in UTF -8. Niknames and the reason for the ban is not displayed correctly.

In sourcecomms everything is displayed correctly. In sourcebans it is incorrect.
Set the character set UTF-8 database sourcebans.sp

**Comment by sarabveer** [comment]
I do not see this bug, I can't confirm this as an actual bug since all UTF-8 characters work.

**Comment by Radionucleid** [comment]
Everything in UTF-8, but i have this bug with russian letters in names. SourceBans++ 1.5.5-dev-git402.
![2017-02-25_133724](https://cloud.githubusercontent.com/assets/26021421/23329759/3308ab52-fb60-11e6-9332-345f27e7f288.png)
