### ISSUE TITLE
Short Bans instantly expiring

### ISSUE THREAD

**Issue by Joe-Howanski** [sbpp/sourcebans-pp#135]
I have noticed since updating to SourceBans++ it seems that when bans are short term, like 1-10 minutes. They are listed instantly as expiring.

I'm not sure if this is the case with any other's installations, but I haven't found any other cause than potentially SourceBans++

**Comment by sarabveer** [comment]
See I can't do much

No logs, no game version, is SM up to date?

I can't do much.

**Comment by Joe-Howanski** [comment]
My apologies, Team Fortress 2. SM SourceMod 1.7.3-dev+5229

Example Ban:
https://bans.harpoongaming.com/index.php?p=banlist&advSearch=STEAM_0:0:53002757&advType=steamid&Submit

L 03/14/2016 - 14:55:55: [sourcebans.smx] "Eoj Charlie ⇋HG-A⇌<1248><[U:1:80183736]><>" banned "Sargent¥ (MCT) ⇋HG-A⇌<1225><[U:1:106005514]><>" (minutes "10") (reason "Test")

**Comment by sarabveer** [comment]
Please Update SM

Also looks fine to me, banned 13:55, expired 14:05?

**Comment by Joe-Howanski** [comment]
I believe I may have found the problem, it doesn't seem to be in SB++'s code. My apologies.

**Comment by sarabveer** [comment]
Also make sure u update SM, ur version is old.
