### ISSUE TITLE
Sourcebans not rehashing to multiple servers

### ISSUE THREAD

**Issue by MtnDewster** [sbpp/sourcebans-pp#136]
I have my databases.cfg set up properly and sourcebans installed correctly, but whenever I add access to a server to admins, the changes wont save to the server. The game console receives the "sm_rehash" command through the rcon, but the sb_admins.cfg stays blank. This only happens to servers with ids 2+. My original first set up server works fine and will rehash perfectly like it's supposed to. Thanks for any help!

**Comment by Jacksta214** [comment]
I'm also experiencing this issue, though absolutely none of my servers rehash. sm_rehash just does absolutely nothing and doesn't return.

**Comment by MtnDewster** [comment]
My issue seems to have fixed itself. I found out it fixes the configs on the server when people join, or it just took it a while, but either way people had the permissions they were supposed to.
