### ISSUE TITLE
Weird String on Comm Blocks

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#137]
"ayer reason" appears to be getting concatenated on the end of every block reason.

**Comment by sarabveer** [comment]
sm version, sb++ version? logs?

**Comment by ghost** [comment]
Apologies. I knew I forgot something. Though, the game server doesn't yield error logs relating to this issue except for the standard mute logging.

SB++ version: 1.5.4.2

`sm version
 SourceMod Version Information:
    SourceMod Version: 1.7.3-dev+5290
    SourcePawn Engine: SourcePawn 1.7, jit-x86 (build 1.7.3-dev+5290)
    SourcePawn API: v1 = 4, v2 = 6
    Compiled on: Jan  9 2016 08:58:11
    Built from: https://github.com/alliedmodders/sourcemod/commit/1e71bd1
    Build ID: 5290:1e71bd1
    http://www.sourcemod.net/`

`L 03/22/2016 - 14:23:04: [sourcecomms.smx] "quackerKiller<3512><REDACTED><>" muted "Qz<3519><REDACTED><>" (minutes                                                                                                       "60") (reason "micspam ayer reason")`

**Comment by CosmicHikari** [comment]
Sounds like your translations are messed up or something.

**Comment by sarabveer** [comment]
Does this happen with the new release, if no one replies within 2 days, this issue will be marked resolved.

**Comment by sarabveer** [comment]
@Remonstrate Hello? Can I please know if this issue still exists?
