### ISSUE TITLE
Sourcebans Website Insecurity

### ISSUE THREAD

**Issue by stickz** [sbpp/sourcebans-pp#138]
Sourcebans exposes game-servers to additional backdoors, which, were not previously possible without the bulk collection of server rcon passwords. The login credentials have no basic type of security enforced for securing accounts, which, have access to these.

I would like to request that additional security features be added to the web portion of sourcebans; like, a steam badge for logging into the web panel. This supports two-way authentication (aka steam guard) to better secure game-servers against vulnerabilities like brute-forcing a login password.

**Comment by sarabveer** [comment]
https://github.com/Sarabveer/SourceBans-Fork/commit/0584a64dfe3e2ea9d0cbb2278bf66c9b3618589a
