### ISSUE TITLE
RCON Prompt Not Appearing?

### ISSUE THREAD

**Issue by CosmicHikari** [sbpp/sourcebans-pp#139]
Any ideas as to why my rcon option isnt showing? 

I have all rcon passwords correct, servers are in a server group, webhost can send tcp 27015, 27016, 27017, and 27018 all, because the rehash works, just the rcon feature is missing.

**Comment by sarabveer** [comment]
Wait a few hours

**Comment by CosmicHikari** [comment]
Okay, will do.

**Comment by Dovahkiin-Warrior** [comment]
Ah I found it.

<code>

**Comment by Dovahkiin-Warrior** [comment]
Found it. <code>
        // Only show the RCON link for servers he's access to
        foreach($servers as &$server)
        {
            if(in_array($server['sid'], $server_access))
                $server['rcon_access'] = true;
            else
                $server['rcon_access'] = false;
        }
</code>
When I edited admin.servers.php and changed else rcon_access to TRUE it gave me the rcon, I only did this for debug purposes but it appears to not be understanding that I have ROOT on the server in the admins list. I'll double check my admin settings and group settings.

**Comment by CosmicHikari** [comment]
Nevermind, I forgot to give myself access to my server group.... woops..
