### ISSUE TITLE
auto permanent reban

### ISSUE THREAD

**Issue by nikolya-prodigy** [sbpp/sourcebans-pp#141]
good afternoon
It is need that would automatically receive a permanent ban a player for repeated violations.
Let's say I have installed anti TK ... TK player two gets ban for 1 day
But I would like that after 3 to lock the player and received a permanent record of the old bans were removed

**Comment by CrazyHackGUT** [comment]
TK?

**Comment by sarabveer** [comment]
WTF? Sb is open source, do it yourself and share your work with the world
