### ISSUE TITLE
Sourcesleuth - sm_sleuth_bantype "0" not banning permanent bans

### ISSUE THREAD

**Issue by Technoblazed** [sbpp/sourcebans-pp#144]
When sm_sleuth_bantype "0" is set to 0, it is not running the duplicate account ban for any permanent bans.

**Comment by stickz** [comment]
`sm_sleuth_actions` must be set to 2 for that.
`sm_sleuth_bansallowed` must be a number small than the client's total bans.

Also, make sure you have the `1.5.4.3` release for the plugins.

There's nothing within that plugin which is incorrect; although, the configuration is a bit more confusing than required. And the sourcebans native has been tested countless times.

**Comment by Technoblazed** [comment]
I can confirm after updating, with the following settings:

`sm_sleuth_actions "2"`
`sm_sleuth_bansallowed "0"`
`sm_sleuth_duration "0"`

That if a user is permanently banned from the server and connects on an alternative account, with `sm_sleuth_bantype "0"`, that the new account is not banned. However if the user receives a ban that is not permanent, the user is rebanned permanently. However if `sm_sleuth_bantype` is set to 1, it rebans the permanently banned player.

**Comment by Technoblazed** [comment]
How come this was closed?

**Comment by sarabveer** [comment]
You solved your issue?

**Comment by Technoblazed** [comment]
The issue is still here, it is not rebanning permanently banned players with `sm_sleuth_bantype "0"` set to 0.

**Comment by Technoblazed** [comment]
Would you like to test, and/or is there anything I can do

**Comment by stickz** [comment]
Take a look at line 157
`FormatEx(query, sizeof(query),  "SELECT * FROM %s_bans WHERE ip='%s' AND RemoveType IS NULL AND ends > %d", Prefix, IP, g_cVar_bantype.IntValue == 0 ? GetTime() : 0);`

More specially, the final function argument. This sounds a lot like the issue you're experiencing. 
`g_cVar_bantype.IntValue == 0 ? GetTime() : 0`

**Try swapping the code for this a testing it**

Argument value.
`g_cVar_bantype.IntValue == 0 ? 0 : GetTime()`

Final line value.
`FormatEx(query, sizeof(query),  "SELECT * FROM %s_bans WHERE ip='%s' AND RemoveType IS NULL AND ends > %d", Prefix, IP, g_cVar_bantype.IntValue == 0 ? 0 : GetTime());`

**Comment by stickz** [comment]
Well search up that convar in the code then. I'll give you a hint, it's read from on one line.

**Comment by stickz** [comment]
Set `sm_sleuth_bantype` to 1, the description on the convar is backwards.

**Comment by stickz** [comment]
line 157 is the only line `g_cVar_bantype` which points to `sm_sleuth_bantype` is read from. and the convar creation line is the only setter line for this convar value. 

I don't understand mysql query strings enough to point out why it's doing this.
`FormatEx(query, sizeof(query),  "SELECT * FROM %s_bans WHERE ip='%s' AND RemoveType IS NULL AND ends > %d", Prefix, IP, g_cVar_bantype.IntValue == 0 ? GetTime() : 0);`

This could be backward if you want to try swaping the convar value. (setting it to 1 instead)
`g_cVar_bantype.IntValue == 0 ? GetTime() : 0`

To clarify, that is actually an if statement which looks like this. But it's shortened for various reasons.

```
new time;

if (g_cVar_bantype.IntValue == 0)
{
      time = GetTime();
}

else
{
      time = 0;
}

FormatEx(query, sizeof(query), "SELECT * FROM %s_bans WHERE ip='%s' AND RemoveType IS NULL AND ends > %d", Prefix, IP, time);

```

**Comment by Technoblazed** [comment]
Switched it to 1, and it worked fine, just a misrepresentation in the file :D Thanks :D
