### ISSUE TITLE
Rcon Issues

### ISSUE THREAD

**Issue by marcusisdahl** [sbpp/sourcebans-pp#145]
I cannot seem to get any rcon commands to 3 of my servers, maybe due to updating sourcemod plugin? any ideas would be great. And yes i tried to overwrite the file with this one from git.

Error: the XML response that was returned from the server is invalid. Received: 
Warning: stream_set_timeout() expects parameter 1 to be resource, boolean given in \includes\CServerRcon.php on line 50

Warning: fwrite() expects parameter 1 to be resource, boolean given in \includes\CServerRcon.php on line 71

Warning: fwrite() expects parameter 1 to be resource, boolean given in \includes\CServerRcon.php on line 71
$('dialog-control').setStyle('display', 'block');ShowBox('Error', 'Can\'t kick _name_. Player not on the server anymore!', 'red', '', true);

**Comment by CrazyHackGUT** [comment]
I'l tried kick my friend, and do not see this problem.
![SB Kick](https://crazyhackgut.ru/trash/sb_kick.png)

Disable displaying warnings in your _php.ini_ or add this lines in file _config.php_ before **?>**
`ini_set('error_reporting', E_NONE);`
`ini_set('display_errors', 0);`
`ini_set('display_startup_errors', 0);`
![SB disable warnings](https://crazyhackgut.ru/trash/sb_warning.png)

**Comment by marcusisdahl** [comment]
Hmm no it did not work. LF a fix people!

**Comment by sarabveer** [comment]
The SourceMod plugin has nothing to do with RCON, this is all web side.

**Comment by marcusisdahl** [comment]
Alrighty found a fix, to anyone reading this just add **+ip server_ip** in your startup command! Haven't tried server.cfg, but simply in your startup commands will work.
