### ISSUE TITLE
SourceSleuth not catching duplicate IPs

### ISSUE THREAD

**Issue by jdlovins** [sbpp/sourcebans-pp#147]
I'm running SourceBans 1.5.4.3 and i had banned someone yesterday permanently via steamID & IP address on the website and they logged on an alternate account and didn't get detected. Is this a known issue or something new? It wasn't the first time this has happened to me either.

**Comment by Technoblazed** [comment]
jdlovins, this is a duplicate issue to #144 and has been resolved in the latest version of sourcebans :D Be sure to update.

**Comment by jdlovins** [comment]
I see. So basically just set 
sm_sleuth_actions "1"
sm_sleuth_bansallowed "0"
sm_sleuth_bantype "0"

and it should be good?

**Comment by Technoblazed** [comment]
Yup ;)

**Comment by jdlovins** [comment]
Sounds good. A weird thing is my sourcebans webpage says 
Latest release: 1.5.4.5
but i can only find 1.5.4.4.
Any ideas on that one?

**Comment by sarabveer** [comment]
New release 1.5.4.6
