### ISSUE TITLE
Sourcesleuth caching bans.

### ISSUE THREAD

**Issue by Technoblazed** [sbpp/sourcebans-pp#152]
A user was banned for a day by an automuting console as shown here: 
https://gyazo.com/c63b7b02e9ac2c3865e416905f2ae434

However when connecting 25 hours later, the user was rebanned by sourcesleuth for a duplicate account:
https://gyazo.com/100285df672c260244cbfd6f57aab133

Any ideas?

**Comment by Technoblazed** [comment]
Plugin updated and resolved, appologises

**Comment by Technoblazed** [comment]
Appears to be back again, users connecting after the 24h ban has ended, on their main account, are being rebanned again.

**Comment by CrazyHackGUT** [comment]
Sourcemod version? Logs?

**Comment by Technoblazed** [comment]
SourceMod Version: 1.7.3-dev+5283

There's aren't any logs associated with this, a client was banned at `05-16-16 16:26` for a period of 1 day, the same client on the same steam account attempted to connect at `05-17-16 16:28` and was given a permanent ban as per our sourcesleuth settings. Judging by the period I can only presume that this was a caching issue and the server had not recognised that the client had been unbanned.

**Comment by CrazyHackGUT** [comment]
MySQL also can cache and return cached result. MariaDB exactly caches the results. Check your MySQL Server.

**Comment by sarabveer** [comment]
@Technoblazed Any update?

**Comment by Technoblazed** [comment]
Even with cache disabled, it still seems to be that after the 24 hours people are still getting rebanned ;-;

**Comment by good-live** [comment]
We just had such a situation aswell: https://bans.painlessgaming.eu/index.php?p=banlist&searchText=Ishoxo&Submit=Search (Top 2 bans)
