### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by lowlevl** [sbpp/sourcebans-pp#154]
The var, SBR_VERSION, line 36, in /game_upload/addons/sourcemod/scripting/sourcebans.sp is wrong !

Please change the var from :
<code>#define SBR_VERSION "1.5.4.6"</code>
to :
<code>#define SBR_VERSION "1.5.4.7"</code>

because this causes issues with the updater.

Thanks a lot :D

**Comment by sarabveer** [comment]
No need as 1.5.5 is in dev
