### ISSUE TITLE
Error template at bans and comms details

### ISSUE THREAD

**Issue by kilroy98** [sbpp/sourcebans-pp#156]
![bandicam 2016-05-25 12-52-58-213](https://cloud.githubusercontent.com/assets/13346898/15535920/0383a268-2278-11e6-9d54-a9bc990555ba.jpg) (It is on behalf of a normal user)
**----------------------------------------------------------------------------------------------------------------------**
![bandicam 2016-05-25 12-58-58-283](https://cloud.githubusercontent.com/assets/13346898/15536051/79fe6ed2-2278-11e6-9b76-5a237b9516dd.jpg) ![bandicam 2016-05-25 13-01-08-419](https://cloud.githubusercontent.com/assets/13346898/15536160/d8d4bb46-2278-11e6-8527-a6ed18b1abeb.jpg) 
(This person as administrator)
**----------------------------------------------------------------------------------------------------------------------**
The background is not until the end of the block information.
(I use Google Translate :) )

**Comment by sarabveer** [comment]
Will fix next release

**Comment by sarabveer** [comment]
This issue does not affect the operation of SB ++, closing..
