### ISSUE TITLE
Player not on the server anymore!

### ISSUE THREAD

**Issue by ezekutor** [sbpp/sourcebans-pp#157]
SourceBans 1.5.4.7 + _WEB SERVER_ :
**Nginx version: nginx/1.10.0**
**PHP version: 7.0.4**
**Mysql  Verrsion:  5.7.12**

```
+] SourceBans "Error Connecting()" Debug starting for server xx.xx.xx.xx:27015

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: [$2000$] === Ты готов к бойне? === [$2000$] 

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response! 
```

**Can't kick .:strong:.. Player not on the server anymore!
Can't get player info for .:strong:.. Player is not on the server (xx.xx.xx.xx:27015) anymore!**

SourceMod 1.8.0.5904,

**Comment by sarabveer** [comment]
Will fix next release

**Comment by ShawnCZek** [comment]
Still same problem. 👎

**Comment by Groruk** [comment]
@ShawnCZek if you have a problem open a new issue and fill out the issue template.

Normally this error is displayed if no player is found on the server matching the specified name. Are you sure that the player hasn't left before you issued the kick or maybe a server event (e.g map change) has interrupted the kick process (normally all players get 'disconnected' from the server for the period of a map change, restart, etc).

**Comment by vishal1714** [comment]
Well Same Issue I am facing for a while

Reason I Know -
When We use the Web Interface For Getting The players Information Interface execute the rcon command "Status" and send it to our server and get the information from "status" command If In your server you blocked your status rcon command using any plugins like
status_protector.smx,rcon_lock.smx this plugins block the access of rcon commands.

Solution-
Check the rcon password of your server while adding it in sourcebans it must be correct.
Remove Any plugins which block the rcon commands or rcon "Status" Commands
