### ISSUE TITLE
Sourcecomms issue

### ISSUE THREAD

**Issue by SakuraOran** [sbpp/sourcebans-pp#158]
Think I found an interesting (Bug? pretty sure it's not something I did. well kinda) with sourcecomms. Not sure if it happens with bans as well, but Im guessing it might. What happens is that when the "created" value is 0, it will display the current time, and will keep counting up if you refresh the page. 
https://i.gyazo.com/eb6c3de34fb82e3d97702ea8b56f4e6b.png
(Ignore the "Admin deleted", this is my backup database and doesnt have the admins table). These bans are very old, and were imported from extended comms, and for some reason a bunch of the created values were 0, and I found it odd that for some reason it shows the current time instead

**Comment by sarabveer** [comment]
What did you use to import from Extended Comms? This is a bug with whatever you used to import Comms, SourceBans never enters a 0, so this is not a SB bug, but a bug with the importer.

**Comment by CosmicHikari** [comment]
I thought it was his importer.

**Comment by sarabveer** [comment]
@Dovahkiin-Warrior Then its a bug with his importer.

**Comment by SakuraOran** [comment]
its not an issue with the importer, as the time in extendedcomms still says 0 for like 20% of the rows. Im not too worried about that, im just wondering why, when the created time is 0, it says the current date
