### ISSUE TITLE
weird php error?

### ISSUE THREAD

**Issue by jdlovins** [sbpp/sourcebans-pp#160]
When i go to edit an admins powers i get this

http://i.imgur.com/tgZh8av.png

This is a fresh download with only moving over the config.php file

**Comment by sarabveer** [comment]
Not an error, just a hickup, will be fixed next release

**Comment by jdlovins** [comment]
Alright, thanks for the quick response!

**Comment by jdlovins** [comment]
Also why does it seem its always .1 behind the actual version? I uploaded 1.5.4.7 to my game server and when i sm plugins info sourcebans it returns .6?

**Comment by sarabveer** [comment]
Plugin version wasnt updated
