### ISSUE TITLE
Unable to Add Bans with IPv6 address

### ISSUE THREAD

**Issue by Zaithe** [sbpp/sourcebans-pp#161]
Whenever i try to ban a user i get this error. Using the &debug=1 query string doesn't show an error either. Any ideas what it might be?
![error](http://i.imgur.com/q1Whr0C.png)

**Comment by sarabveer** [comment]
1. Using Really old Version of SB (1.5.2F) Please Update to the Latest One (**YOU CAN GET HACKED IF YOU STAY ON 1.5.2F**)
2. Please show any PHP Errors/Logs after you upgrade and try banning the same person again.

**Comment by Zaithe** [comment]
I already did update, its still the same exact error.

**Comment by sarabveer** [comment]
Did you just now apply the update, please show me any PHP Errors or Logs because I am able to ban fine on my side.

**Comment by Zaithe** [comment]
It was updated over a day ago. Here is the updated site http://chronet.com/bans/. Where can i find the php logs?

**Comment by Zaithe** [comment]
Sorry i am actually a front end web developer helping the owner solve this issue. I do not have access to the site. I've been leading him through everything. I was thinking maybe they can't see the error because they do not have php.ini configured to show errors. 
http://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display 

I will send a request to the owner to retrieve the error logs.  He may have a crappy host that doesn't let you see it. I'll give you an update. Is there anything off the top of your head that you think is most likely the culprit? Maybe ban file corruption or bad database configuration? Thanks for your time!

**Comment by Zaithe** [comment]
After looking at the error logs they found out it was because IPV6 addresses being too long for the database table field - error when inserting if you use IPv6 

Any suggestions on how to fix this problem?

**Comment by sarabveer** [comment]
Will fix next release, try using IPv4 for now.

**Comment by InvexByte** [comment]
SRCDS doesn't even support IPv6.
Are there any games SourceBans supports that does support IPV6, if not this issue should be closed.

**Comment by Groruk** [comment]
@InvexByte pointed this out that Source isn't really supporting IPv6 (even valves / steams backend haven't reached a state where IPv6 is fully supported) so no need to add IPv6 support now (maybe with Source 2).
