### ISSUE TITLE
Plugin error. Banned user still can join the server

### ISSUE THREAD

**Issue by alan1420** [sbpp/sourcebans-pp#163]
Hey, I'm trying your plugin on No More Room in Hell. After I install everything, I tried to block someone. And there is the error from server console

Client "Alan14" connected (36.80.xxx.xxx:10501). << Banned user
L 06/21/2016 - 14:48:08: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 06/21/2016 - 14:48:08: [SM] Native "KickClient" reported: Language phrase "Banned Check Site" not found
L 06/21/2016 - 14:48:08: [SM] Displaying call stack trace for plugin "sourcebans.smx":
L 06/21/2016 - 14:48:08: [SM]   [0]  Line 1573, sourcebans.sp::VerifyBan()
L 06/21/2016 - 14:48:08: [sourcebans.smx] Query Failed: Column 'sid' cannot be null
[DG] Wave: 7
L 06/21/2016 - 14:48:32: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 06/21/2016 - 14:48:32: [SM] Native "PrintToChat" reported: Language phrase "Gagged on connect" not found
L 06/21/2016 - 14:48:32: [SM] Displaying call stack trace for plugin "sourcecomms.smx":
L 06/21/2016 - 14:48:32: [SM]   [0]  Line 1674, sourcecomms.sp::Query_VerifyBlock()

**Comment by CrazyHackGUT** [comment]
`L 06/21/2016 - 14:48:08: [SM] Native "KickClient" reported: Language phrase "Banned Check Site" not found`
`L 06/21/2016 - 14:48:32: [SM] Native "PrintToChat" reported: Language phrase "Gagged on connect" not found`

Check your translations folder.

**Comment by alan1420** [comment]
Oh yeah, It works.
