### ISSUE TITLE
Player can un-silence by reconnect to the server

### ISSUE THREAD

**Issue by alan1420** [sbpp/sourcebans-pp#164]
Hey, looks like I have another problem. When I'm trying to silence someone from webpanel. Then, when he joined the server, He get noticed in the chat, if he was silenced. But, he can still talk and chat.
It also happen when I'm using another method. Admin silence someone in the server. And It works. Then, he disconnect and connect to the same server, and he can talk, even though in the list it said he still silenced and not yet expired.

Sorry for my bad pronunciation.

**Comment by sarabveer** [comment]
Did you choose session?

**Comment by alan1420** [comment]
No, I tried from 5-15 minutes, and still the same
