### ISSUE TITLE
[Suggestion] Add comms in admin panel

### ISSUE THREAD

**Issue by hitmany** [sbpp/sourcebans-pp#167]

**Comment by sarabveer** [comment]
What do you mean?

**Comment by sarabveer** [comment]
![alt text](http://puu.sh/q8kwF/4c3c83c6ed.png)

**Comment by hitmany** [comment]
What is it version?
I am using 1.5.4.7

**Comment by sarabveer** [comment]
all versions since 1.5.0 have had SourceComms integrated.

**Comment by hitmany** [comment]
I dont have this in admin panel
![dfef](https://cloud.githubusercontent.com/assets/8200058/16998836/d8bdbe06-4ec3-11e6-8653-0be773513f86.JPG)

**Comment by sarabveer** [comment]
![alt text](http://puu.sh/q8psK/0d24e663e9.jpg)

Click on Comms

**Comment by hitmany** [comment]
Oh its was hard. Thank you
