### ISSUE TITLE
sb_admcfg.smx (SourceBans: Admin Config Loader)

### ISSUE THREAD

**Issue by hznovich** [sbpp/sourcebans-pp#168]
Good day. Ubuntu 14.04.4, CS:GO, Sourcemod 1.8.0-5918
In console: 
`sb_admcfg.smx (SourceBans: Admin Config Loader): Fatal error during plugin initialization (ext req)`
- sm exts list
- [SM] Displaying 13 extensions:
- [01] Automatic Updater (1.8.0.5918): Updates SourceMod gamedata files
- [02] Webternet (1.8.0.5918): Extension for interacting with URLs
- [03] cURL Extension (1.3.0.0): cURL Extension
- [04] CS Tools (1.8.0.5918): CS extended functionality
- [05] BinTools (1.8.0.5918): Low-level C/C++ Calling API
- [06] SDK Tools (1.8.0.5918): Source SDK Tools
- [07] Top Menus (1.8.0.5918): Creates sorted nested menus
- [08] SDK Hooks (1.8.0.5918): Source SDK Hooks
- [09] Client Preferences (1.8.0.5918): Saves client preference settings
- [10] SQLite (1.8.0.5918): SQLite Driver
- [11] Regex (1.8.0.5918): Provides regex natives for plugins
- [12] GeoIP (1.8.0.5918): Geographical IP information
- [13] MySQL-DBI (1.8.0.5918): MySQL driver implementation for DBI

Any ideas?

**Comment by alan1420** [comment]
Which SBans version do you use? 1.5.4.7 or dev?

**Comment by hznovich** [comment]
1.5.4.7

**Comment by hznovich** [comment]
?

**Comment by sarabveer** [comment]
@asherkin @psychonic

**Comment by asherkin** [comment]
This error state should not be possible, can't do anything without STR.

**Comment by hznovich** [comment]
STR?

**Comment by sarabveer** [comment]
Can you please reinstall SourceMod, and also if you can, Update to latest version.

**Comment by hznovich** [comment]
I reinstall sourcemod, no avail. If on the running server unload the plugin and then load manualy, it starts to work.
PS: Sorry for bad english ((

**Comment by sarabveer** [comment]
Your sourcemod install is corrupted, please copy everything from the sourcemod zip file when you reinstall
