### ISSUE TITLE
It's possible to create web-admin with empty password and sign in with only login

### ISSUE THREAD

**Issue by koteq** [sbpp/sourcebans-pp#170]
When new admin created in `AddAdmin` function there is a check which should prevent creation of web-admins without password specified. The check is performed on `$mask` variable which is empty if you use groups instead of individual permissions. So it's totally possible to create web-admin with empty password which will be correctly hashed and stored in db. More over it's possible to sign up without password using only login. I think it's a major security breach.
1. `MIN_PASS_LENGTH` must be enforced in `sb-callback.php` and in `CUserManager::AddAdmin` for non empty passwords
2. Empty password must be stored as `NULL` in db not as hash of empty string
3. `MIN_PASS_LENGTH` must be enforced if user signs in by login and password

https://github.com/sbpp/sourcebans-pp/blob/81d9b006d13a1d3da8932cc24d402d4d0e1c77ac/web/includes/sb-callback.php#L993-L1002
https://github.com/sbpp/sourcebans-pp/blob/39301095a13dea67fab939e5fb69ef6c3501daba/web/includes/CUserManager.php#L283-L289

**Comment by koteq** [comment]
There is an SQL query to find affected admins accounts:

``` sql
SELECT a.user, g.name FROM sb_admins a
JOIN sb_groups g ON g.gid = a.gid
WHERE a.password = SHA1(SHA1('SourceBans'))
  AND g.type = 1
```

Personally I've had eleven records and I removed password to the records with:

``` sql
UPDATE sb_admins a
JOIN sb_groups g ON g.gid = a.gid
SET a.password = ''
WHERE a.password = SHA1(SHA1('SourceBans'))
  AND g.type = 1
```

Do note that `SourceBans` is a salt which may be different on your installation. You could find it in `init.php`.

**Comment by sarabveer** [comment]
FYI: 1.5.5-dev uses Steam Login by default.

**Comment by koteq** [comment]
I'm still able to sign in with javascript console on 1.5.5-dev-git363.
It's as simple as `xajax_Plogin('gaben', '', false, '', 1);`
