### ISSUE TITLE
Unable to login via steam

### ISSUE THREAD

**Issue by thomasfinstad** [sbpp/sourcebans-pp#172]
I have installed php-curl module and tried to update `steamopenid.php` and `includes/openid.php` to the latest version from github.

All that happens is I get taken to steam as I am supposed to, but when I am returned to sourcebans I am not logged in.

No errors on the page or in any log files I know of (php and nginx).
- SourceBans++ 1.5.4.7
- PHP 7.0.8-0
- Ubuntu 16.04.1 LTS

**Comment by CrazyHackGUT** [comment]
Check `config.php`. There should be a full option "SB_WP_URL". Example:
`define('SB_WP_URL','http://bans.g-44.ru');`

**Comment by shavitush** [comment]
i'm experiencing the same exact issue, php7.0, nginx and also ubunty 16.04

**Comment by thomasfinstad** [comment]
@CrazyHackGUT I thought I would mention that I have set the variable: `define('SB_WP_URL','https://example.com/sourcebans');`
Does it not handle the subdir?

**Comment by shavitush** [comment]
@penetal mine isn't on a subdirectory and it doesn't work either

**Comment by sarabveer** [comment]
It can handle as many subdirs as possible. I don't know why steam login isn't working, you provided no info.

Btw, my login works fine on ubuntu 14.04.5, nginx 1.11.3, and php 7.0.9.

^ see saying that doesn't help you at all

**Comment by shavitush** [comment]
@Sarabveer i assume your web server is running with https, so it's not an issue, right?

**Comment by thomasfinstad** [comment]
@Sarabveer If you want more info than "nothing in logs, no errors showing anywhere I know of" then you wil have to ask for something that will help. I am trying to help debug the problem, but I did not write the code so I do not know which information you need.

**Comment by IncPlusPlus** [comment]
I've had this issue as well. Are you sure you have the correct domain name assigned to your steam Web API key?

**Comment by shavitush** [comment]
definitely is for me
![sublime_text_2016-08-10_04-10-27](https://cloud.githubusercontent.com/assets/3672466/17538698/7531abd4-5eb0-11e6-87a1-c43ea7047193.png)

**Comment by IncPlusPlus** [comment]
@shavitush Well then I am not sure what the issue is. You can log in regularly through the Sourcebans username and password field, correct?

**Comment by shavitush** [comment]
of course!

**Comment by IncPlusPlus** [comment]
@shavitush Have you configured Sourcebans with the Web API key that was generated for you? This would have been asked for in the first time setup of Sourcebans++.

**Comment by shavitush** [comment]
i didn't have the option when i installed sourcebans++; so i just 
manually put it in the .cfg file

**Comment by sarabveer** [comment]
I'm not sure https is the issue here, also api key isnt used for anything, its just there for future features

**Comment by IncPlusPlus** [comment]
@shavitush That would be the only thing that I can think of that could have caused this. I'll check my configs tomorrow for anything useful that you may have not noticed.

**Comment by thomasfinstad** [comment]
@thedudeguy1 Thanks for the reminder about the steamweb key, though @Sarabveer says it is irrelevant it might be relevant other places I've yet to use it, mine was connected to the wrong domain.

In anycase it still does not work, I thought maybe the access log from the webserver could help, though I am not sure it will, here it is:

> 10.0.0.100 - - [15/Aug/2016:11:12:10 +0200] "GET /sourcebans/index.php?p=login HTTP/1.1" 200 3640 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:10 +0200] "GET /sourcebans/themes/default/css/css.php HTTP/1.1" 200 21177 "https://ggnorway.com/sourcebans/index.php?p=login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:12 +0200] "GET /sourcebans/steamopenid.php HTTP/1.1" 302 5 "https://ggnorway.com/sourcebans/index.php?p=login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "GET /sourcebans/steamopenid.php?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197977567420&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197977567420&openid.return_to=https%3A%2F%2Fggnorway.com%2Fsourcebans%2Fsteamopenid.php&openid.response_nonce=2016-08-15T09%3A12%3A15ZIKq1OhN7vOPhxmen%2BiuTQhwDeXE%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=iT9FucbqdvyCiB0CK3GeUGj8yrI%3D HTTP/1.1" 302 5 "https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=https%3A%2F%2Fggnorway.com%2Fsourcebans%2Fsteamopenid.php&openid.realm=https%3A%2F%2Fggnorway.com&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "GET /sourcebans/ HTTP/1.1" 200 5032 "https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=https%3A%2F%2Fggnorway.com%2Fsourcebans%2Fsteamopenid.php&openid.realm=https%3A%2F%2Fggnorway.com&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "GET /sourcebans/themes/default/css/css.php HTTP/1.1" 200 21177 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "POST /sourcebans/index.php HTTP/1.1" 200 153 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "POST /sourcebans/index.php HTTP/1.1" 200 153 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "POST /sourcebans/index.php HTTP/1.1" 200 550 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "POST /sourcebans/index.php HTTP/1.1" 200 153 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "POST /sourcebans/index.php HTTP/1.1" 200 549 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "POST /sourcebans/index.php HTTP/1.1" 200 533 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
> 10.0.0.100 - - [15/Aug/2016:11:12:16 +0200] "POST /sourcebans/index.php HTTP/1.1" 200 545 "https://ggnorway.com/sourcebans/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"

**Comment by sarabveer** [comment]
Steam API Key is NOT used, It was added for future use if needed to use SteamAPI. Steam OpenID DOES NOT need API Key

**Comment by Groruk** [comment]
Can you please download the newest dev build and check if the problem is still persistent.
