### ISSUE TITLE
New steam login button

### ISSUE THREAD

**Issue by popcmp** [sbpp/sourcebans-pp#176]
https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_02.png
https://steamcommunity.com/dev

**Comment by kilroy98** [comment]
This image has long been added.
https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/images/steamlogin.png

**Comment by popcmp** [comment]
Why it's still not in realeses?

**Comment by kilroy98** [comment]
https://github.com/sbpp/sourcebans-pp/commit/1673e3c29378ec7dd718b8e63152e993d4bc6085
