### ISSUE TITLE
[Feature Request] SMTP Mail Send

### ISSUE THREAD

**Issue by zAfLu** [sbpp/sourcebans-pp#177]
It would be nice to change the Mail send from mail() to https://github.com/PHPMailer/PHPMailer

Using different SMTP server would be nice :)

**Comment by zAfLu** [comment]
For a better understanding:

In my case -> I got some different SMTP Server with authentication and php.ini does not allow to configure SMTP with authentication. With PHPMailer you are able to use SMTP authentication for mail sending. This would be a huge benefit.

**Comment by Technoblazed** [comment]
Install postfix, configure for SMTP authentication. Use sparkpost as an example, 100k free emails on your custom domain each month. The webpanel already supports the rest.

**Comment by SugarD-x** [comment]
That workaround doesn't help anyone hosting SourceBans++ on a Windows server.

That being said, I feel this is a fairly high priority thing to have. I'm actually amazed this isn't in there already, being that it is such a common feature among web applications that have to send out emails.

**Comment by Hackmastr** [comment]
https://github.com/sbpp/sourcebans-pp/commit/6eb6828a8c740d3fde3b2a65b9d30dfd7f7536a7

Thanks!
