### ISSUE TITLE
IP Ban Evasion

### ISSUE THREAD

**Issue by keigel2001** [sbpp/sourcebans-pp#18]
Could you edit the IP ban evasion time or better make a cvar for it?
It banned a person who had accidentally the same IP as a ban 2 months ago.
The hoster uses dynamic IPs. I also checked the accounts. I think they aren't related (no mutual friends).

**Comment by sarabveer** [comment]
I personally don't like the current SourceBans plugin we're using right now.

I have stopped development on the plugin, and focusing on replacing it with the 1.5.0 Beta Plugin. As you can see in this branch https://github.com/Sarabveer/SourceBans/tree/1.5betaplugin/.

**Comment by keigel2001** [comment]
Oh, I didn't notice the other branch.
Maybe make an exception, because the beta-stuff isn't ready yet?
Would be greatly appreciated :)
