### ISSUE TITLE
SourceSleuth ignoring IP

### ISSUE THREAD

**Issue by JackHammer29** [sbpp/sourcebans-pp#180]
Hi,

I have a banned user in my database with his IP attached, but he was able to successfully rejoin with another account by using the same IP.

**Comment by jdlovins** [comment]
@JackHammer29 was it a perma ban?

**Comment by JackHammer29** [comment]
@jdlovins Yes

**Comment by jdlovins** [comment]
@JackHammer29 if you know how to compile sourcemod plugins, change line https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_sleuth.sp#L157

to

`FormatEx(query, sizeof(query), "SELECT * FROM %s_bans WHERE ip='%s' AND RemoveType IS NULL AND (ends > %d OR length = 0)", Prefix, IP, g_cVar_bantype.IntValue == 0 ? GetTime() : 0);`

**Comment by sarabveer** [comment]
@jdlovins can you please PR that as a fix?

**Comment by jdlovins** [comment]
@Sarabveer how do I do that? I don't github often

**Comment by sarabveer** [comment]
@jdlovins Fork the repo, make the change, then follow this https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by jdlovins** [comment]
@Sarabveer Will do after this movie then. :)
