### ISSUE TITLE
Connecting with sourcemod SQL admins?

### ISSUE THREAD

**Issue by KroniK907** [sbpp/sourcebans-pp#182]
Sourcemod can store its admins in an either an sqlite database or in a mysql database. 

Would it be possible to set up sourcebans to create either an sqlite file for each server or a mysql database for each server that sourcemod can point to so that I can use sourcebans to set up new rcon users on the server?

Currently all I can do is set up admins and let them run rcon commands through the web interface. I would like to let them actually use the sm_rcon command when in the server.

**Comment by Groruk** [comment]
SQLite files will not work, because most people host their web panel on a different server and establishing a stable connection with a flat file DB over multiple servers is let's say somewhat problematic.

You can give your admins the permission to use sm_rcon when you give them the 'm'-flag.
If they don't have any permission in game check if you added them to the right 'server admin group' and if they have been added as an admin to the right server in the 'admin server access'-panel

**Comment by KroniK907** [comment]
So how does the server check for that -m flag? And I assume you mean to set the -M flag in sourcebans? I was trying for a solution that doesn't require editing .cfg files on the server.

**Comment by Technoblazed** [comment]
If you configure it correctly, you won't need to edit any files server side, it'll all by automatic.

Just make sure that following things are set correctly:
- Server ID
- Server Address
- Rcon port

**Comment by Groruk** [comment]
You can configure everything in your web panel so there isn't any need to change your .cfg files.

Here a quick guide on how you give admins in-game permission for command usage:
1.Go to your SouceBans++ Web panel and login in.

2.Go to 'Admin Panel' -> 'Group Settings' -> 'Add a group'

3.Give it a name (eg. rcon) and select 'Server Admin Group' as Group Type.

4.Select all permissions you want to give to this group (you will also find flag 'm' [Run RCON Commands] there). Then click on Save Changes.

5.Next, you go to 'Admin Panel' -> 'Admin Settings' and choose which admin should get access to the commands/permissions. Just click on the admin's name and under actions choose 'Edit Groups' and select your newly made group under Server Admin Group. Click Save Changes.

6.As the last step, you again click on the admin's name and under actions choose 'Edit Server Access'. There you can choose on which server the admin should get the permissions. Click  Save Changes and your admin should have the corresponding in-game commands/permissions.

**Comment by sarabveer** [comment]
SourceBans or SourceBans++ does not support SourceMod's built in SQL Admins, you will need to use the SourceBans/SourceBans++ plugins.

**Comment by KroniK907** [comment]
@Groruk I have followed your outlined steps and I am still unable to use the sm_rcon or rcon command when in the server. 

Is there some server CVAR that needs to be set to allow sourcebans++ to be the one that checks for rcon privileges, or some .cfg that needs to be adjusted? 

I can use the sm_rcon command if I directly add myself to the admins.cfg in the sourcemod config folder, or use the server's rcon password, but I can't seem to get the server to recognize the admins set in the sourcebans++ web panel. 

Maybe I need to update my sourcebans++ sourcemod plugin or something. I'll make sure its up to date but otherwise I'm not sure what is causing the disconnect.

**Comment by sarabveer** [comment]
@KroniK907 Try adding `-usercon` to the SRCDS Startup Parameters

**Comment by KroniK907** [comment]
So had time to test adding -usercon to the startup and that didn't change anything. 

How exactly does the server know to check sourcebans++ for admin info? Is that built into the sourcebans++ plugin? Is there some conflict with the sourcemod admin system? 

I'm honestly not sure how the server actually checks for admin info. With the sourcemod admin system, its obvious that it checks the admins.cfg file to find the info about what users can use the sm_rcon command. However, I found nothing similar for sourcebans++... How is sourcebans++ actually talking to the server and authenticating admins?

**Comment by Technoblazed** [comment]
Sourcebans++ -> MySQL database -> PROFIT?!? <- Config files updated<- Plugin performing database queries -< Sourcebans plugin

Sourcebans++ does not use the admin files provided with CS:GO, if you use these, editing items on Sourcebans will have no effect.

**Comment by KroniK907** [comment]
Ok that makes sense. How can I test that the plugin is properly connected with the database? Also, does giving server admin allow you to use the "Rcon" command or the "sm_rcon" command?

I have fully updated the ingame plugin and updated my web interface to the most recent version in the releases section here on the github. I have configured the sourcebans.cfg so that everything lines up. Do I need to add the admin groups to the admin_groups.cfg found in /sourcemod/config/sourcebans/ ?

I'm still not able to use rcon in the server. However using the rcon terminal on the web-panel works fine... I'm mostly just confused at this point as to what could be stopping the server from recognizing my steam ID and allowing admin when I join.

**Comment by KroniK907** [comment]
Ok I found the issue. Everything got all screwed up because when I had removed myself from the admins.cfg file I had left a trailing bracket that was throwing a syntax error which wouldn't allow any admins to use the sm_rcon command. I removed the syntax error and now everything works as expected.

Please mark as closed.

**Comment by sarabveer** [comment]
@Groruk @KroniK907 SB++ doesn't use admins.cfg, it uses `sb_admins.cfg` in the `cfg/sourcebans` folder
