### ISSUE TITLE
WebPanel inserts 'rate' instead of IP

### ISSUE THREAD

**Issue by usershtopor** [sbpp/sourcebans-pp#185]
Hi,
I found bug in SB++ 1.5.5-dev-git380
See video
Video on Youtube: https://www.youtube.com/watch?v=Ad9PpLFkdTw

**Comment by Groruk** [comment]
The video is private, so we cant see it. Please change it to unlisted so we can view it.

**Comment by usershtopor** [comment]
ok. see now

**Comment by Technoblazed** [comment]
Went through the relevant codes, Sourcebans doesn't get the IP address from requests, looks like the number that you're getting inserted is your server rate.

**Comment by usershtopor** [comment]
its client rate

**Comment by IncPlusPlus** [comment]
I had this issue as well. [This post](https://forums.alliedmods.net/showpost.php?p=2246110&postcount=15) solved the issue for me.
