### ISSUE TITLE
Rehashing Admin and Group data on all related servers failed: Can't connect.

### ISSUE THREAD

**Issue by NickVst** [sbpp/sourcebans-pp#186]
When trying to add an administrator to a server via the web portal ( _Admin Panel > Admin Settings > {Admin} > Edit Server Access > {Tick server box} > Apply_ ) I get the following message box pop up.

---

The admin server access has been updated successfully

Rehashing Admin and Group data on all related servers...
- - -.- - -.- -.- -:27015 (1/1) _failed: Can't connect_.
**Done**

---

![chrome_2016-10-01_00-14-33](https://cloud.githubusercontent.com/assets/9049281/19008512/1cd5880e-876c-11e6-9122-1c61d6e4b231.png)

I checked that the right ports are open; ufw is completely disabled on the server hosting my TF2 server, and ufw has all outbound connections allowed on my MySQL server.

The MySQL server works as expected, so it's not an issue with remote connections not being allowed on the MySQL server's side.

The RCON password is the right password as well, I made sure of that.

**Comment by Groruk** [comment]
Is your TF2 server also running and have you checked that SourceBans++ has no problems connection to your server? (normally this error shows that either the server is not running or SourceBans cant connect to it.)

**Comment by NickVst** [comment]
I've made sure that the server's running and that the SourceBans plugin is also running. 

I can ping from the server running SourceBans to the server running the TF2 server (`rtt min/avg/max/mdev = 1.195/2.434/6.621/2.097 ms`). 

I've made sure that the gameserver is actually running on port 27015 and has a map selected.

The SourceBans++ web interface shows that it can successfully collect information on the server itself.

![chrome_2016-10-04_17-59-00](https://cloud.githubusercontent.com/assets/9049281/19081920/46b9d042-8a5c-11e6-8d1a-a93766eda858.png)

**Comment by sarabveer** [comment]
use the debug tool included with SB++

**Comment by NickVst** [comment]
[+] SourceBans "Error Connecting()" Debug starting for server xxx.xxx.xxx.xxx:27015

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: xxx

[+] Trying to establish TCP connection
[-] Error connecting #111: Connection refused

![chrome_2016-10-06_13-16-53](https://cloud.githubusercontent.com/assets/9049281/19150463/44cdcf88-8bc7-11e6-89ec-5425578f129b.png)

So TCP traffic isn't getting through. I have once again made sure that the firewall allows outgoing port 27015 both TCP and UDP on the SourceBans web server and that the firewall allows incoming port 27015 both TCP and UDP on the gameserver. 

Hosting it on DigitalOcean if that is of any significance.

**Comment by Technoblazed** [comment]
Luckily for you, all authentication attempts are logged in your machine's log directory, go find your error :D

**Comment by NickVst** [comment]
There are no errors in the logs that I can find that are of any use.
**ufw** logs nothing out of the ordinary. which means that my firewall does not block the request on either end. 
I've then attempted to search the game server's IP in the entire log directory on the web server's side; no luck.
Then, I've attempted to search the web server's IP in the log directory on the game server's side, once again: no luck. 

For good measure, I decided to completely wipe the TF2 server, just in case there was any magic going on in that corner. After reconfiguring everything step-by-step according to SourceBans again, the exact same issue persists.

**Comment by Technoblazed** [comment]
@NickVst fancy posting or messaging me your ip?

**Comment by Technoblazed** [comment]
Port 27015 is closed on 188.---.--.-- TCP. You should probably check your ipconfigs/firewalls again.

**Comment by NickVst** [comment]
But it's not; The web portal on SourceBans can connect to the server and request information from it, which on its own requires port 27015 to be open. 

Also, the IP has changed since the complete server wipe; it's 146.185.174.101 .

Port forwarding checker also suggests that it's closed there, but if it is then the Sourcebans web portal should logically not be able to collect info from it, plus ufw should blurt out errors.

**Comment by Technoblazed** [comment]
```
Starting Nmap 7.01 ( https://nmap.org ) at 2016-10-06 11:04 EDT
Nmap scan report for 146.185.174.101
Host is up (0.088s latency).
PORT      STATE         SERVICE
27015/tcp closed        unknown
27015/udp open|filtered halflife

Nmap done: 1 IP address (1 host up) scanned in 1.33 seconds
```

The fact's don't lie \o/. The server itself uses UDP to transfer data between clients and the server. 

For example one of my servers appears as:

```
Starting Nmap 7.01 ( https://nmap.org ) at 2016-10-06 11:07 EDT
Nmap scan report for ip254.ip-149-56-126.net (149.56.126.254)
Host is up (0.000041s latency).
PORT      STATE         SERVICE
27015/tcp open          unknown
27015/udp open|filtered halflife

Nmap done: 1 IP address (1 host up) scanned in 2.11 seconds
```

**Comment by NickVst** [comment]
```
gameserver@tf01-vanilla:~/hlserver$ sudo nmap localhost -p 27015

Starting Nmap 7.01 ( https://nmap.org ) at 2016-10-06 15:09 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000078s latency).
PORT      STATE  SERVICE
27015/tcp closed unknown

Nmap done: 1 IP address (1 host up) scanned in 0.24 seconds
gameserver@tf01-vanilla:~/hlserver$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
27015                      ALLOW       Anywhere

gameserver@tf01-vanilla:~/hlserver$ sudo iptables -L -v -n

Chain ufw-user-input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    2   120 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:22
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:27015
  248 13144 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:27015
```

Locally nmap also says it's closed, but I force it open in ufw and iptables also says it's open. I don't understand this at all.

**Comment by Technoblazed** [comment]
Btw, it's triple ` at the start and end of message for code blocks ;)

```
iptables -A INPUT -p tcp --dport 27015 -j ACCEPT
```

**Comment by NickVst** [comment]
Figured that out just a little too late, haha.

Entered the command you gave, no change at all. Any other suggestions?

**Comment by Technoblazed** [comment]
I wish ip tables had a gui display, I really hate doing my firewalls on terminals :|

**Comment by NickVst** [comment]
I think I should close the issue now though, as it's clearly not an issue with SourceBans in this case. [I've reposted the issue on AskUbuntu](http://askubuntu.com/questions/833895/ufw-and-iptables-show-port-open-everything-else-suggests-its-closed), as the issue is on an Ubuntu server. Thanks for all your suggestions along the way.

**Comment by Technoblazed** [comment]
:)

**Comment by NickVst** [comment]
Just a quick additional comment incase anyone comes across this issue; RCON breaks on Source servers if you do not specify IP from the command line. If anyone runs into this:

`./srcds_run +ip <your external IP> +port 27015`

Without RCON, nothing is listening on 27015/tcp and the port appears closed.

**Comment by Technoblazed** [comment]
Correction! Add  `-usercon` to your launch parameters.

```
-usercon
Enables RCON for CS:GO Servers
```
