### ISSUE TITLE
IP ban players via steamid

### ISSUE THREAD

**Issue by Technoblazed** [sbpp/sourcebans-pp#187]
Probably simple to do and wouldn't be complicated, and will take a look at a later point, but a cool feature to have would be that if a player is SteamID banned, for example banned after disconnect. At a later point if they reconnect to the server using that SteamID and sourcesleuth detects this, if no IP address is present on the ban, update the ban to include the clients address.

**Comment by sneak-it** [comment]
+1 to this @Technoblazed , would be a really helpful addition, especially when banning cheat groups en masse.

**Comment by rumblefrog** [comment]
I'll take a stab at this
