### ISSUE TITLE
Query Failed: Query was empty - Every map change

### ISSUE THREAD

**Issue by sneak-it** [sbpp/sourcebans-pp#189]
Hi guys, I'm upgrading from a slightly older 1.5.5 version (prior to sbpp_ prefix plugin file names), and now that I have, every map change I get this in sourcebans.log:

[sbpp_main.smx] Query Failed: Query was empty

It doesn't appear to be causing any functionality issues from what I can tell (tested banning & reconnecting on banned account, functions properly).

Edit: Now it is consistently
L 10/08/2016 - 01:41:00: [sbpp_main.smx] Query Failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by sneak-it** [comment]
Update: Hope this helps find the issue, this completely crippled my server and all sql connections today:

> L 10/10/2016 - 07:21:53: Info (map "surf_mesa") (file "errors_20161010.log")
> L 10/10/2016 - 07:21:53: [SM] Exception reported: Invalid database Handle 0 (error: 4)
> L 10/10/2016 - 07:21:53: [SM] Blaming: sbpp_comms.smx
> L 10/10/2016 - 07:21:53: [SM] Call stack trace:
> L 10/10/2016 - 07:21:53: [SM]   [0] SQL_TQuery
> L 10/10/2016 - 07:21:53: [SM]   [1] Line 264, G:\csgo\plugin zips\sourcemod 1.8\scripting\sbpp_comms.sp::OnMapEnd
> L 10/10/2016 - 07:21:53: Error log file session closed.
> L 10/10/2016 - 15:33:45: SourceMod error session started
> L 10/10/2016 - 15:33:45: Info (map "surf_surprise") (file "errors_20161010.log")
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Stack leak detected: sp:-691662848 should be 2790396!
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Invalid plugin address
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the heap
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the stack
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the stack
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the stack
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the stack
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the stack
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the heap
> L 10/10/2016 - 15:33:45: [SM] Exception reported: Not enough space on the stack

etc, spammed a 185mb error log file with over 230,000 lines of not enough space on stack/heap. I'll be reverting to the older version for now until this is fixed.

**Comment by rogeraabbccdd** [comment]
Hello guys, I also have this problem in my server, and here's my error log.

> L 10/19/2016 - 10:09:08: SourceMod error session started
> L 10/19/2016 - 10:09:08: Info (map "de_dust2") (file "errors_20161019.log")
> L 10/19/2016 - 10:09:08: [SM] Exception reported: Invalid database Handle 0 (error: 4)
> L 10/19/2016 - 10:09:08: [SM] Blaming: sbpp_comms.smx
> L 10/19/2016 - 10:09:08: [SM] Call stack trace:
> L 10/19/2016 - 10:09:08: [SM]   [0] SQL_TQuery
> L 10/19/2016 - 10:09:08: [SM]   [1] Line 264, D:\CSGODS\CSGO\csgo\addons\sourcemod\scripting\sbpp_comms.sp::OnMapEnd
> L 10/19/2016 - 10:09:09: Error log file session closed.

Sourcemod version 1.8.0.5492
Sourcebans++ version 1.5.5-dev (Download from sb++ website)

**Comment by coolmans** [comment]
me too
[SM]   [1] Line 264, ***\addons\sourcemod\scripting\sbpp_comms.sp::OnMapEnd
L 11/25/2016 - 09:10:23: [sbpp_main.smx] Query Failed: Query was empty

L 11/25/2016 - 09:50:56: [sbpp_main.smx] Query Failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'd REGEXP '^STEAM_[0-9]:_SERVER$'), '0.0.0.0', 1)' at line 1

**Comment by Fastmancz** [comment]
Problem fixed - [https://forums.alliedmods.net/showpost.php?p=2481652&postcount=933](https://forums.alliedmods.net/showpost.php?p=2481652&postcount=933)

**Comment by koteq** [comment]
Is the change to `SQL_SetCharset` actually needed?
There was another issue related to it, check #179.

**Comment by rogeraabbccdd** [comment]
This issue should be closed because it has been fixed.
