### ISSUE TITLE
Issue Connecting with Server

### ISSUE THREAD

**Issue by Archer-GraphiteNetwork** [sbpp/sourcebans-pp#190]
I am currently having issues connecting my server to a database

I am running the server using SRCDS from my own computer.

Do you guys have any suggestion on how to fix this?

Also

how does sourcemod work? 

I am kinda new to sourcebans

**Comment by Technoblazed** [comment]
Welcome to Sourcebans!

First of all, do you have any error logs in /addons/sourcemod/logs/10092016_error.log

Likely issue here is that you forgot to put in database credentials in /addons/sourcemod/configs/databases.cfg

**Comment by Archer-GraphiteNetwork** [comment]
1. There is no logs directory that is generated
2. i manually added databases.cfg and it didn't work ._.

**Comment by Technoblazed** [comment]
Have you installed sourcemod and metamod onto your server?

Sourcemod: http://www.sourcemod.net/downloads.php?branch=stable
Metamod: http://www.metamodsource.net/
VDF: http://www.metamodsource.net/vdf

**Comment by Archer-GraphiteNetwork** [comment]
I have installed SourceMod but not MetaMod

**Comment by Technoblazed** [comment]
I feel that as you had to create your databases.cfg yourself, you didn't install sourcemod correctly :/

**Comment by Archer-GraphiteNetwork** [comment]
I just have to drag and drop sourcemod file to <MOD>/addons/<drop sourcemod here>

**Comment by Technoblazed** [comment]
So you definitely have a /addons/sourcemod directory, that contains about 10 ish directories then yeah?

**Comment by Archer-GraphiteNetwork** [comment]
![image](https://cloud.githubusercontent.com/assets/22730644/19222546/d51e29d0-8e0f-11e6-9a62-96e9d957eef9.png)

all i have

**Comment by Technoblazed** [comment]
Looks like you got a bad download :/ Can you redownload the latest build, you should see at least 8 folders from the initial zip.

Edit: Wait, are those just the sourcebans files or sourcemod?

**Comment by Archer-GraphiteNetwork** [comment]
Can you link it? I am downloading it from 

![image](https://cloud.githubusercontent.com/assets/22730644/19222562/494a00a4-8e10-11e6-9c30-366833b1fbe7.png)

**Comment by Technoblazed** [comment]
http://www.sourcemod.net/downloads.php?branch=stable

Get the one for your OS, the site you linked is for  Sourcebans which is a plugin for sourcemod :) You'll need both.

**Comment by Archer-GraphiteNetwork** [comment]
So now I replace the Database.cfg code with the one from sourcebans

**Comment by Technoblazed** [comment]
Don't completely replace, just fit it in to the current config

**Comment by Archer-GraphiteNetwork** [comment]
I added it so now should it work?

**Comment by Technoblazed** [comment]
Restart your server, then check the error directory I pointed you to earlier and see if there are any errors.

**Comment by Archer-GraphiteNetwork** [comment]
![image](https://cloud.githubusercontent.com/assets/22730644/19222642/6d9d4162-8e12-11e6-9b34-312aafe51f0e.png)

**Comment by Technoblazed** [comment]
Haven't setup a gmod server with sourcebans or sourcemod before but I imagine it's the same as other source games.

Without physically seeing the server I can't tell you what the issue is. However I'll link you some guides:

https://wiki.garrysmod.com/page/Hosting_A_Dedicated_Server
https://wiki.alliedmods.net/Installing_sourcemod

**Comment by Archer-GraphiteNetwork** [comment]
If anyone knows, when I try to install metamod and sourcemod and when i am told to do meta list it won't work

**Comment by Archer-GraphiteNetwork** [comment]
I've followed all the instructions in the alliedmods wiki and it still doesn't work ._,

**Comment by sarabveer** [comment]
@Archer-GraphiteNetwork WTF!

YOU NEED METAMOD TO RUN SOURCEMOD!
http://www.sourcemm.net/

**Comment by Archer-GraphiteNetwork** [comment]
![image](https://cloud.githubusercontent.com/assets/22730644/19223911/57e7fb4c-8e2f-11e6-8a4a-745aa8d1b7dc.png)

been installed for awhile

**Comment by Archer-GraphiteNetwork** [comment]
![xd](https://cloud.githubusercontent.com/assets/22730644/19224206/d49bc15e-8e35-11e6-9051-61a1f0881039.png)

**Comment by Technoblazed** [comment]
Sourcemod isnt launching correctly, also you're missing your GLST in your launch parameters. http://steamcommunity.com/dev/managegameservers

**Comment by Archer-GraphiteNetwork** [comment]
fixed it

if i did

![image](https://cloud.githubusercontent.com/assets/22730644/19225158/e8aa7ea0-8e4a-11e6-8cb0-538de42afbef.png)

**Comment by Technoblazed** [comment]
GLST is fixed, you're sourcemod still isn't installed correctly.

**Comment by Archer-GraphiteNetwork** [comment]
Do you have any solutions?

**Comment by Technoblazed** [comment]
Create a post here and get someone that knows how GMOD works to take a look at it for you, this isn't the best place to ask for server setup:

https://forums.alliedmods.net/

**Comment by Archer-GraphiteNetwork** [comment]
Ok Thanks.

**Comment by Archer-GraphiteNetwork** [comment]
Is their a specific section where I should put this?

**Comment by sarabveer** [comment]
Is this Garry's Mod, if so, SourceMod does not support GMod, which means SourceBans doesn't work. You will have to use unofficial SB Lua plugins for Gmod.

**Comment by Technoblazed** [comment]
Sourcemod does support GMod :|

**Comment by sarabveer** [comment]
@Technoblazed No it doesn't, and this is confirmed by the SM Devs @asherkin

**Comment by asherkin** [comment]
SourceMod hasn't supported GMod for over 4 years...
