### ISSUE TITLE
sourcebans smx download

### ISSUE THREAD

**Issue by KroniK907** [sbpp/sourcebans-pp#193]
What is the correct location to download the sourcebans smx files? They are not in the current 1.x branch under the plugins folder. Do I have to download a release to get the compiled smx files?

**Comment by Technoblazed** [comment]
Just compile the plugin yourself ;)

**Comment by Groruk** [comment]
I would suggest you download the latest release version (which has the plugin already compiled) because the dev version of the plugin is currently buggy and unstable.

**Comment by KroniK907** [comment]
@Groruk, in future releases, could you provide the .smx as a separate attached item? I already have all the web stuff set up and its a pain to download the full release tar just to get the .smx out of it. 

Just a suggestion.

**Comment by sarabveer** [comment]
I was thinking about making TravisCI copy the compiled plugins somewhere.
