### ISSUE TITLE
Server doesn't connect

### ISSUE THREAD

**Issue by Hexer10** [sbpp/sourcebans-pp#194]
In my sourcebans++ i've added two servers, the first server connect with success in the servers list but the second say: Error Connecting: (18_.__._*_._16:27415) but if I click connect cs:go open normally and the bans from that server are store like the first server they show normally in the dashboard, the game connect well the server i've tryed to add another random server and it connect normally.
[In few words is bugged only in the server list: doesn't not show the only players and doesn't connect.]

Papero
(Sorry for my english)

**Comment by sarabveer** [comment]
Use the debugger provided and show the result here.

**Comment by Hexer10** [comment]
Sorry, i solved the remote server banned (csgo: banned_ip.cfg) the server where is hosted the web server (i dont know why.)

**Comment by sarabveer** [comment]
lol
