### ISSUE TITLE
AJAX Call Failed

### ISSUE THREAD

**Issue by k0nan** [sbpp/sourcebans-pp#195]
Whenever I use the right-click menufeatures on a player from the servers page I get ajax call failed.
Here are some error messages:

http://pastebin.com/1GKRWRyL
http://pastebin.com/K1HT8x16

I've had these issues on the latest versions.. Currently using 1.5.5-dev-git377

**Comment by sarabveer** [comment]
this has been an issue even in 1.4.11, im not really sure how to fix it.

**Comment by AzaZPPL** [comment]
Does this always happen when you right click?

**Comment by sarabveer** [comment]
when I used to run servers, yes.

**Comment by Technoblazed** [comment]
```
 on line 83 $('dialog-control').setStyle('display', 'block'); You have whitespace in your response.
```

Surely you just have to remove the space between the display and block aspects...

**Comment by AzaZPPL** [comment]
`CServerInfo.php` is doing the same thing. There are differences in `CServerInfo.php` and `CServerRcon.php` in the way it checks and uses the socket. Try to change the code in `CServerRcon.php` to make it work like `CServerInfo.php`

**Comment by godrider** [comment]
I fixed this problem with putting -steamport 27015 in the server launch options. I'm using 1.4.11, and this bugged me too.

**Comment by sarabveer** [comment]
Interesting @godrider, can anyone else confirm this?

**Comment by Groruk** [comment]
`stream_set_timeout() expects parameter 1 to be resource, boolean given`
So what happens is that [`fsockopen`](http://php.net/manual/en/function.fsockopen.php) returns `false`, because the connection to the gameserver fails.
The [documentation](https://sbpp.github.io/docs/debugging_connection/) should theoretically help resolve the issue.
