### ISSUE TITLE
Security measures

### ISSUE THREAD

**Issue by shavitush** [sbpp/sourcebans-pp#196]
SHA1 can be cracked quite quickly (and easily, considering many SourceBans users don't change the default salt) - so my suggestion is to add an option to use bcrypt for passwords and even a button in the admin panel so I can force a password reset on admins (if I suspect that someone gained access to their account). Maybe also IP logs?

I tried implementing the bcrypt part myself (I failed horribly, I suck at php). Would be great if it can be added to SB++ :)

**Comment by sarabveer** [comment]
This would require a big change, and probably would break backwards compatible support.

**Comment by shavitush** [comment]
Of course, that's why it only needs to be enabled for new installations (or opt-in)

**Comment by Groruk** [comment]
Added better password hashing algorithm with #258
