### ISSUE TITLE
Sourceban++ show ban time and Ban time in mysql different

### ISSUE THREAD

**Issue by bok141** [sbpp/sourcebans-pp#198]
Sourceban++ show ban time and Ban time in mysql different

i think php timezone problem to open php.ini
but not problem

i live in south korea time zone gmt is gmt+9

pm 09:00 ban 
show time pm 08:00

https://s17.postimg.org/k9qxkj8dr/1234ds.png
ban data in mysql have a unixtime  
https://s17.postimg.org/jms0v0bhr/1234ds3.png
unixtime change datetime 
All right but...
https://s17.postimg.org/5f2c6cysv/1234ds2.png
show ban time is 1 hour late (-1hour)

i not have solve way....
please give me fix way

**Comment by Technoblazed** [comment]
Adminpanel > Settings > Timezone, turn on summertime if you're still in it, but you shouldn't be.

**Comment by bok141** [comment]
not use summer time

But time zone 8 and 9 same...
8 time zone = pm 8:00
9 time zone = pm 8:00
I change timezone 8 and 9
I think Sourceban timezone config problem

**Comment by Technoblazed** [comment]
```
<option value="8" class="">(GMT +8:00) Beijing, Perth, Singapore, Hong Kong</option>
<option value="9" class="">(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk</option>
```
Not an issue with the dropdowns.

**Comment by eNNercY1337** [comment]
check if the webserver time is correct and perhaps sync it.
incase you have access to the actual webserver try the following things, incase its just a regular webspace maybe contact your provider and ask for them to check the time on the local machine.

SSH @Webserver -> `date`
Mo 21. Nov 23:10:55 CET 2016

incase incorrect sync it with an NTP server of your choice for example the ubuntu one.

`/usr/sbin/ntpdate -b -s ntp.ubuntu.com`

maybe aswell double confirm with a php info what timezone is set there aswell check if summertime is enabled which @Technoblazed already stated above.

**Comment by bok141** [comment]
eNNercY1337//
USing WIndows 
WIndows time setting gmt+9 
Technoblazed //
Where in file?
"
<option value="8" class="">(GMT +8:00) Beijing, Perth, Singapore, Hong Kong</option>
<option value="9" class="">(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk</option>
"

**Comment by eNNercY1337** [comment]
> eNNercY1337//
USing WIndows
WIndows time setting gmt+9
Technoblazed //
Where in file?
"
(GMT +8:00) Beijing, Perth, Singapore, Hong Kong (GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk "

does the webserver run on windows or on linux? (not the gameserver)

**Comment by Technoblazed** [comment]
afaik, sourcebans is independent of your webservers settings. Can you provide a screenshot of your sourcebans settings please?

**Comment by bok141** [comment]
eNNercY1337//
Using apache2 in windows
Technoblazed //
I find this setting but now setup timezone gmt+9
I not changed setting

**Comment by bok141** [comment]
+ php.ini time zone setting 
Gmt+9 I not changed

**Comment by bok141** [comment]
Technoblazed//
This screenshot

https://s22.postimg.org/ikcoxksup/2016_11_22_09_56_39.jpg
https://s3.postimg.org/4k6x73hw3/2016_11_22_09_55_19.jpg

**Comment by rumblefrog** [comment]
Addressed in https://github.com/sbpp/sourcebans-pp/pull/363
