### ISSUE TITLE
Discord/Slack API

### ISSUE THREAD

**Issue by ezspot** [sbpp/sourcebans-pp#202]
Maybe implement ban forwards. One dude has already done it, you can find it here!
https://forums.alliedmods.net/showthread.php?t=292663

**Comment by sm9cc** [comment]
I believe this can be closed already, there are already forwards.

SourceComms: SourceComms_OnBlockAdded
SourceBans: SourceBans_OnBanPlayer

**Comment by rumblefrog** [comment]
Yeah, it can be closed, you can just install that plugin without any modification to sourcebans++
