### ISSUE TITLE
Odd OpenID error

### ISSUE THREAD

**Issue by 404UserNotFound** [sbpp/sourcebans-pp#205]
Everything about the site works beautifully except for logging in through Steam;

`Fatal error: Uncaught Error: Call to undefined function bcsub() in /var/www/html/bans/steamopenid.php:70 Stack trace: #0 /var/www/html/bans/steamopenid.php(86): convert64to32('765611980166217...') #1 {main} thrown in /var/www/html/bans/steamopenid.php on line 70`

Not sure what that means, but there you go. Let me know if any other info is needed.

**Comment by Technoblazed** [comment]
```
apt-get install php7.1-bcmath
```

**Comment by 404UserNotFound** [comment]
Thanks, I recently had to re-set up my VPS from scratch due to an odd Wine bug wiping several user accounts on my VPS, and I took the time to finally update the OS from 15.10 which had reached end-of-life recently.

And I believe I am, as I opted to install the latest things whilst following a cheesy little "the perfect ubuntu server setup" guide.

Thanks for the tip, I'll give that a run and see how she handles.

**Comment by Technoblazed** [comment]
Using Wine on a linux server :|

**Comment by 404UserNotFound** [comment]
Trying to run a Killing Floor 2 (windows only) server on Linux.

I've previously used Wine and Xvfb with some trickery to run a TF2Classic (3rd party mod) server on Linux successfully.

This time, somehow the "mysql" account got deleted which was system-made, my servers account got deleted, but no files did, and then I couldn't log in anymore due to "bad ownership" errors because many files and folders lost their owner account due to the wipe.

**Comment by 404UserNotFound** [comment]
Ok so it didn't work;

`E: Unable to locate package php7.1-bcmath
E: Couldn't find any package by glob 'php7.1-bcmath'
E: Couldn't find any package by regex 'php7.1-bcmath'
`

**Comment by Technoblazed** [comment]
I updated my message earlier, 
```
apt-get install php7.0-bcmatch
```

**Comment by 404UserNotFound** [comment]
Yeahhh, I edited my comment a second ago to reflect that :P

**Comment by Technoblazed** [comment]
Comment still says 7.1

**Comment by 404UserNotFound** [comment]
I just re-ran the command with 7.0, got the same messages, only for 7.0. Apparently it doesn't exist for some reason.

**Comment by Technoblazed** [comment]
OS and Distro?

**Comment by 404UserNotFound** [comment]
Ubuntu, Yakkety Yak (16.10 I think? I can't remember version numbers) as said in the initial issue posting.

**Comment by Technoblazed** [comment]
```
apt-get update
apt-get install php7.0-bcmath
```

**Comment by 404UserNotFound** [comment]
Can't be found. I'm guessing maybe OVH (main corp behind Kimsufi/OVH/etc) doesn't have that package in its mirrors.

**Comment by Technoblazed** [comment]
I'm using OVH, one sec.

**Comment by 404UserNotFound** [comment]
Here's what I received when I ran the command. I just recently installed the OS (like 4-5 days ago), so the update packages seemed small; http://i.imgur.com/0Vhxltl.png

**Comment by Technoblazed** [comment]
Update your `/etc/apt/sources.list` to:

```
#------------------------------------------------------------------------------#
#                            OFFICIAL UBUNTU REPOS                             #
#------------------------------------------------------------------------------#


###### Ubuntu Main Repos
deb http://ca.archive.ubuntu.com/ubuntu/ yakkety main restricted universe multiverse
deb-src http://ca.archive.ubuntu.com/ubuntu/ yakkety main restricted universe multiverse

###### Ubuntu Update Repos
deb http://ca.archive.ubuntu.com/ubuntu/ yakkety-security main restricted universe multiverse
deb http://ca.archive.ubuntu.com/ubuntu/ yakkety-updates main restricted universe multiverse
deb http://ca.archive.ubuntu.com/ubuntu/ yakkety-proposed main restricted universe multiverse
deb-src http://ca.archive.ubuntu.com/ubuntu/ yakkety-security main restricted universe multiverse
deb-src http://ca.archive.ubuntu.com/ubuntu/ yakkety-updates main restricted universe multiverse
deb-src http://ca.archive.ubuntu.com/ubuntu/ yakkety-proposed main restricted universe multiverse
```

Screw using OVH repos.

**Comment by 404UserNotFound** [comment]
Beauty. Thanks man!

**Comment by Technoblazed** [comment]
All good?

**Comment by 404UserNotFound** [comment]
Err...not exactly. It read all the package lists and just reported back the exact same message as before.

**Comment by 404UserNotFound** [comment]
Aha, I'm perhaps a dumbass. I was doing "bcmatch". Whoops.

**Comment by Technoblazed** [comment]
:^)

**Comment by 404UserNotFound** [comment]
It found 7.0

**Comment by Technoblazed** [comment]
@Groruk @Sarabveer Any chance on the installer, you could make `bcmath` a requirement on installation.

**Comment by 404UserNotFound** [comment]
```
NOTICE: Not enabling PHP 7.0 FPM by default.
NOTICE: To enable PHP 7.0 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.0-fpm
NOTICE: You are seeing this message because you have apache2 package installed.
Setting up php7.0-bcmath (7.0.13-0ubuntu0.16.10.1) ...
```

```
Creating config file /etc/php/7.0/mods-available/bcmath.ini with new version
Processing triggers for libapache2-mod-php7.0 (7.0.13-0ubuntu0.16.10.1) ...
Processing triggers for php7.0-fpm (7.0.13-0ubuntu0.16.10.1) ...
NOTICE: Not enabling PHP 7.0 FPM by default.
NOTICE: To enable PHP 7.0 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.0-fpm
NOTICE: You are seeing this message because you have apache2 package installed.
```

What do?

**Comment by Technoblazed** [comment]
Do  what it says :^)

```
a2enmod proxy_fcgi setenvif
a2enconf php7.0-fpm
```

**Comment by 404UserNotFound** [comment]
Alright, I just didn't know if it'd blow the server up or something :^) (you never know! it could happen!)

**Comment by drhax9908** [comment]
I know this is 13 days old, but I've worked with Apache before, PHP FPM is for FASTCGI!!! THAT is a pain to set up, because it requires MANUAL editing of the configuration files to use the fpm unix socket. If you wish to use FastCGI and PHP FPM, The following tutorial will help you https://www.howtoforge.com/tutorial/apache-with-php-fpm-on-ubuntu-16-04/

I know it's for ubuntu 16.04, but the steps for apache SHOULD work, and if not, I will try to help you

Best of luck

-DrHax9908

**Comment by Sarabveer** [comment]
yea, I could add the bcmath requirement in the installer

**Comment by TandelK** [comment]
Finally php7.0-bcmath did work for me. Ubuntu 16.04 has lot of changes from Ubuntu 14.04

**Comment by Groruk** [comment]
@TandelK if you are using the newest dev-version (1.6) it's because since this commit 11c98e4 bcmath has been completely removed.
