### ISSUE TITLE
Failed after i complied

### ISSUE THREAD

**Issue by ezspot** [sbpp/sourcebans-pp#206]
31 <Failed> "SourceBans++: Main Plugin" (1.5.5-dev) by SourceBans Development Team, SourceBans++ Dev Team
  32 "SourceBans++: SourceSleuth" ((SB++) 1.5.5-dev) by ecca, SourceBans++ Dev Team
  33 <Failed> "SourceBans++: SourceComms" ((SB++) 1.5.5-dev) by Alex, SourceBans++ Dev Team
Errors:
sbpp_main.smx (SourceBans++: Main Plugin): unexpected error 23 in AskPluginLoad callback
sbpp_comms.smx (SourceBans++: SourceComms): unexpected error 23 in AskPluginLoad callback

Running Sourcemod 1.8.0.6967

**Comment by ezspot** [comment]
Do I need to rename it maybe?

**Comment by ezspot** [comment]
Anyone? :p

**Comment by Groruk** [comment]
Have you modified any of these plugin files, because generally, they compile just fine? Or have you tried using the precompiled 1.5.4.7 files or compile the new 1.6 dev version?

**Comment by ezspot** [comment]
I tryed the precompiled 1.5.4.7

**Comment by ezspot** [comment]
Okay, downloaded Version 1.5.5-dev from the website, and complied it.
