### ISSUE TITLE
error search syslog (by date): admin.settings.php (space must add before word)

### ISSUE THREAD

**Issue by jetsam729** [sbpp/sourcebans-pp#207]
1) » Admin Panel - settings - system log  - Advanced Search (/index.php?p=admin&c=settings#^2)
type any date and get empty subpage 
vers: **1.5.4.7** (line 68) and  **1.5.5-dev-402** (line 65)
correction: must be add space before word "WHERE"

orig line:             $where = **"W**HERE l.created > '$time' AND l.created < '$time2'";
must be:             $where = **"      W**HERE l.created > '$time' AND l.created < '$time2'";

2) there is also no test date input :)
example: check only radiobt "date" and get with defa date "DD.MM.YYYY" (/index.php?p=admin&c=settings&advSearch=**DD**,**MM**,**YYYY**,00,00,23,59&advType=date#^2)
msg: **_Warning: mktime() expects parameter xx to be long, string given in.._**

very simple fix as (example working part): 	
            $date  = explode(",", $value);
// ----------------
__$cDT	= getdate();
		if( !(preg_match('/^\d{1,2}$/',$date[0]) && $date[0]>0 && $date[0]<32) ) $date[0] = $cDT['mday'];
		if( !(preg_match('/^\d{1,2}$/',$date[1]) && $date[1]>0 && $date[1]<13) ) $date[1] = $cDT['mon'];
		if( !(preg_match('/^\d{4,4}$/',$date[2]) && $date[2]>1990 ))		$date[2] = $cDT['year'];
		if( !(preg_match('/^\d{1,2}$/',$date[3]) && $date[3]<24))		$date[3] = 0;
		if( !(preg_match('/^\d{1,2}$/',$date[4]) && $date[4]<60))		$date[4] = 59;
		if( !(preg_match('/^\d{1,2}$/',$date[5]) && $date[5]<24))		$date[5] = 0;
		if( !(preg_match('/^\d{1,2}$/',$date[6]) && $date[6]<60))		$date[6] = 59;_

// ----------------
            $time  = mktime($date[3], $date[4], 0, $date[1], $date[0], $date[2]);

**Comment by Groruk** [comment]
Fixed with 5193ea7
