### ISSUE TITLE
Unable to login via steam

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#210]
First question, why there's only option to login via steam, and there's not casual way of username + password?

Second and most important, what I have to do, to make login via steam to work? Right now when I authenticate on steam side, it redirects me to my website, and does not login - just like you would come there from another website via normal link like sb.example.org

**Comment by Technoblazed** [comment]
1) Once you've logged in, it's in your site settings to enable the username and password.
2) Whether or not you add `STEAM_0` OR `STEAM_1` for the user steamid does make a difference, can you confirm which one you inputted?

**Comment by ghost** [comment]
This is basically the page I can see **after** I log in 
![image](https://cloud.githubusercontent.com/assets/19711901/22620504/b88d42dc-eb0d-11e6-83ee-0eaed677bcea.png)

I've added my real steam id while installing SB.

**Comment by Technoblazed** [comment]
I know the issue, but can you tell me the steamid you put in when you went through installation.

**Comment by ghost** [comment]
This is the one `STEAM_0:0:67192854`, not the `steamID3` nor `steamID64`. There wasn't any guide which could lead me to choosing the correct steamID format.

**Comment by Technoblazed** [comment]
That's odd, the issue is usually when you put STEAM_1 that it errors, could you check your webserver error logs to see if theres anything there?

**Comment by ghost** [comment]
Well mostly what comes to my mind after looking into logs is:
```
2017/02/04 19:01:54 [error] 453#453: *1595 open() "/var/www/sb/admin" failed (2: No such file or directory), client: xx.xxx.xx.xxx, server: sb.example.org, request: "GET /admin HTTP/1.1", host: "sb.example.org"
```

I've changed my IP address, as well as domain address.

**Comment by Technoblazed** [comment]
Well, does /var/www/sb/admin exist :thinking:

**Comment by ghost** [comment]
Not that I know of 😂

**Comment by Technoblazed** [comment]
Well did you install sourcebans correctly?

**Comment by ghost** [comment]
Yes, everything went smoothly (except for missing `php7.0-bcmath` package which wasn't mentioned anywhere)

**Comment by Technoblazed** [comment]
Yeah, I already made a request for that to become a requirement.

**Comment by Technoblazed** [comment]
I would check if your /admin folder exists though, for a start.

**Comment by ghost** [comment]
It doesn't, nor does it here https://github.com/sbpp/sourcebans-pp/tree/v1.x/web

**Comment by Technoblazed** [comment]
And it shouldn't because it's not a thing. Great start.

**Comment by ghost** [comment]
Although, the line responsible for passing through the admin page exists in `includes/page-builder.php`

```php
	case "admin":
		$page = INCLUDES_PATH . "/admin.php";
		break;
```
And the file `admin.php` exists too.

**Comment by Technoblazed** [comment]
Was that the only line in your error log? Nothing else?

**Comment by ghost** [comment]
There was some others, but those were referring to hlstatsx which is in separate directory and is using different database. There's also error regarding the `bcsub()` function which was caused by missing `php7.0-bcmath` package.

**Comment by Technoblazed** [comment]
Honestly have no idea, just keep poking it until it works :man_shrugging:

**Comment by ghost** [comment]
Ain't there any db field switch to turn on casual logging in ?

**Comment by Technoblazed** [comment]
Check the settings table, ill get the name

**Comment by Technoblazed** [comment]
`sb_settings`

`config.enablesteamlogin` -> `1`

**Comment by ghost** [comment]
Oh damn... that should be enabled by default!

Thank you for help provided. I've also realized I had pagination set on 25, and the `config.enablesteamlogin` setting was 26th I believe.

**Comment by Technoblazed** [comment]
https://github.com/sbpp/sourcebans-pp/blob/v1.x/SECURITY.md

**Comment by ghost** [comment]
Well then, someone has to work on their security then 😂
