### ISSUE TITLE
Substitute bcmath functions

### ISSUE THREAD

**Issue by Groruk** [sbpp/sourcebans-pp#212]
Change function to substitute bcmath requirement, so people dont have to cry and install bcmath.

Reference: [steamopenid.php Line: 64](https://github.com/sbpp/sourcebans-pp/blob/002e358be69ce699662ea805a4afc9c77ffd06b8/web/steamopenid.php#L64)

**Comment by Technoblazed** [comment]
Just insert this as a requirement, problem solved:

https://github.com/xPaw/SteamID.php

**Comment by Groruk** [comment]
Using steamID from xPaw is also not going to fix this problem as they use gmp instead of bcmath and gmp is also an optional package in php. Best practice would be to switch to the community ID format instead of using the steam ID format as valve is shifting more and more to community IDs. [SteamID formats](https://developer.valvesoftware.com/wiki/SteamID)

**Comment by Technoblazed** [comment]
Lets be honest, when most people are adding users to sourcebans, they end up having to go and get the steam64 first anyway.
