### ISSUE TITLE
Change Steam IDs to Community IDs

### ISSUE THREAD

**Issue by Groruk** [sbpp/sourcebans-pp#217]
Starting with version 1.6.0 SourceBans++ should relay more on Community IDs [Steam ID formats](https://developer.valvesoftware.com/wiki/SteamID).

**Comment by good-live** [comment]
Why do you want to switch to community ID's?
Steam ID3 would be just fine.

**Comment by Groruk** [comment]
Valve is shifting to community ids so if we want to implement web api calls in the future we might have to switch to community ids, also we dont know if valve is going to support these legacy formats in the future.

**Comment by sarabveer** [comment]
It be good to display all 3 ID formats though. (ID2, ID3, and Community ID)
