### ISSUE TITLE
Create system for reformatting Steam IDs

### ISSUE THREAD

**Issue by Groruk** [sbpp/sourcebans-pp#218]
sbpp/sourcebans-pp#217 
2 Systems (fail-safe) :

1. Check if bcmath or gmp is installed -> reformat them locally
2. Fail-safe: Use an external API for conversion.

If both fail -> throw error stating the user has to install bcmath or gmp

(this system is build like that to account for webhoster which dont allow bcmath or gmp)

**Comment by kbkk** [comment]
I'd consider checking first if the PHP version is 64-bit.

**Comment by Groruk** [comment]
bcmath doesn't need 64bit systems as the library is designed to 'calculate' large numbers as strings (preventing floating point problems), so no need to check as the steamid has to be handled as a string and not as an integer.

**Comment by kbkk** [comment]
No, no, no. What I meant is integers in 64 bit PHP are 64 bit. No need for any library in this case.

**Comment by Groruk** [comment]
If you are calculating uint64 on php you will encounter the [Floating point](https://en.wikipedia.org/wiki/Floating_point) problem. Afaik calculation will not be 100% precise thats why you need to use bcmath to do those kinds of calculations.

**Comment by kbkk** [comment]
Yes, an uint64 might be a problem. But the examples of converting steam ids on the Internet in other languages don't use uint64 but just int64, so we should be fine. And no PHP extensions needed :)
