### ISSUE TITLE
Unable to bind admin CONSOLE to identity STEAM_ID_SERVER

### ISSUE THREAD

**Issue by IzuiSP** [sbpp/sourcebans-pp#222]
sourecbans.log : 
`[sourcebans.smx] Unable to bind admin CONSOLE to identity STEAM_ID_SERVER`

errors_...log : 
`[admin-flatfile.smx] Error(s) detected parsing addons/sourcemod/configs/admins.cfg
[admin-flatfile.smx]  (line 6) Failed to bind auth "steam" to identity "STEAM_ID_SERVER"
[admin-flatfile.smx]  (line 169) Failed to bind auth "steam" to identity "STEAM_ID_SERVER"
`

When I change the "STEAM_ID_SERVER" from PhpMyAdmin to "STEAM_0:0:0" : 
`[sb_admcfg.smx] Error(s) Detected Parsing addons/sourcemod/configs/sourcebans/sb_admins.cfg
[sb_admcfg.smx]  (line 6) Failed to bind auth "steam" to identity "STEAM_ID_SERVER"
[sb_admcfg.smx]  (line 290) Failed to bind auth "steam" to identity "STEAM_ID_SERVER"
`

When I change the "ID" and try "-1" in the sourcebans.cfg :
`[sourcecomms.smx] You must set valid ServerID value in sourcebans.cfg!
`

**Comment by Technoblazed** [comment]
1) Remove `CONSOLE` from your `addons/sourcemod/configs/admins.cfg`
2) Do not change `STEAM_ID_SERVER` in your phpmyadmin. Return it to default.
3) Add the server to your sourcebans installation, navigate to your admin server list, get the ServerID of the server and put it into your `addons/sourcemod/configs/sourccebans/sourcebans.cfg`

**Comment by sarabveer** [comment]
admin-flatfile.smx is not used

**Comment by Technoblazed** [comment]
Flatfile is still used by the server if records exist within it. He must have added console to it or something.

**Comment by IzuiSP** [comment]
I already do it..

**Comment by IzuiSP** [comment]
the errors about STEAM_ID_SERVER still here ..
I asked some friends but no one find how to fix
(I like a lot the fact that you respond quickly, continue like this ! Sourcebans is a great thing !)

**Comment by Technoblazed** [comment]
Can you paste the contents of `addons/sourcemod/configs/admins.cfg` into a pastebin document, then to here please.

**Comment by IzuiSP** [comment]
Sure :

admin.cfg :
`"Admins" {}`

**Comment by Technoblazed** [comment]
And your `addons/sourcemod/configs/sourcebans/sb_admins.cfg `

**Comment by IzuiSP** [comment]
sb_admins.cfg : 
"Admins"
{
	"CONSOLE"
	{
		"auth"		"steam"
		"identity"		"STEAM_ID_SERVER"
	}
}

**Comment by Technoblazed** [comment]
Why on earth is:

```
"Admins"
{
"CONSOLE"
{
"auth"	"steam"
"identity"	"STEAM_ID_SERVER"
}
```
in there?

**Comment by IzuiSP** [comment]
what do you mean

**Comment by Technoblazed** [comment]
That shouldn't be in there, nor do I know how it ended up in there. Edit the file to:
```
"Admins"
{
}
```

**Comment by IzuiSP** [comment]
Cause I tried to add it here, should I need to remove everything's in sb_admins.cfg ?

**Comment by Technoblazed** [comment]
Edit the file to how I did it above, and restart your server. It will reconnect to the database completely and get the current admin list.

**Comment by IzuiSP** [comment]
Okay just a question about : https://github.com/sbpp/sourcebans-pp
`#define VERSION "1.6.0"`
I see in the .sp the version is 1.6.0. Sarabveer has forget to change the numbers or I didn't find the latest version ?

**Comment by Technoblazed** [comment]
v1.x = 1.6

`x` is a placeholder for all subversions.

**Comment by IzuiSP** [comment]
Okay so I just need to use that version right ?
https://github.com/sbpp/sourcebans-pp/archive/1.5.4.7.zip

**Comment by IzuiSP** [comment]
So it change nothing with the latest version, errors still here.... I already see that problem on some forum but no one find how to fix.

**Comment by IzuiSP** [comment]
Sup, I get a new error : 

sourcebans.log :
`Verify Insert Query Failed: Subquery returns more than 1 row`
