### ISSUE TITLE
[Feature Request] Ability to add different Server ID from the same Folder of Different Servers

### ISSUE THREAD

**Issue by TandelK** [sbpp/sourcebans-pp#229]
Currently i run 3 Competitive Servers from the same folder allowing us to use less space on our server. Sourcebans adds only 1 Server ID fro all 3 Servers , is there a way to add all 3 server with different IDs. If not please add a feature that can allow Hosters to add different Server ID via Server.cfg file

**Comment by good-live** [comment]
You could use symlinks to share common files and then use seperate config files for each instance.

**Comment by Hackmastr** [comment]
Fixed in #736.
