### ISSUE TITLE
Problem SB 1.5.4.7 Verify Insert Query Failed: Subquery returns more than 1 row

### ISSUE THREAD

**Issue by IzuiSP** [sbpp/sourcebans-pp#230]
Hello guys, I get that error I don't know how to fix

sourcebans.log : 
L 02/21/2017 - 20:16:18: [sourcebans.smx] Verify Insert Query Failed: Subquery returns more than 1 row
L 02/22/2017 - 12:42:00: [sourcebans.smx] Verify Insert Query Failed: Subquery returns more than 1 row
L 02/23/2017 - 13:48:09: [sourcebans.smx] Verify Insert Query Failed: Subquery returns more than 1 row
L 02/23/2017 - 16:27:24: [sourcebans.smx] Verify Insert Query Failed: Subquery returns more than 1 row

**Comment by Technoblazed** [comment]
Update your sourcebans, this is patched.

**Comment by Groruk** [comment]
If you have nothing important in your SourceBans database/tables I, would recommend to just clear all SourceBans related tables (typically all sb_ tables). Your issue here is that a SQL query returns two or more entries where there should only be one (e.g. could happen if two admins have the same steamid in the database).

**Comment by IzuiSP** [comment]
The version is currently 1.5.4.7. We have 2000 bans and 6000 comms .....
and +200 members register

**Comment by Technoblazed** [comment]
Why the hell do you have 200 members registered? That sounds both insane and stupid at the same time :thinking:

**Comment by Groruk** [comment]
Then we can't help you. Your problems lie in your database, so you need to go through your database and check if any entries cause a conflict.

**Comment by IzuiSP** [comment]
`Why the hell do you have 200 members registered? That sounds both insane and stupid at the same time 🤔`

We use SourceBans to give VIP rights (we have 80% of VIP)
