### ISSUE TITLE
Password Change not working

### ISSUE THREAD

**Issue by Carvalh0XYZ** [sbpp/sourcebans-pp#231]
Error when trying to change the password. You should change the private properties in https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/CUserManager.php

It can access to those private properties. Set them to public or try protected idk.

## Expected Behavior
Changing password in account page. Pressing the button = password changed

## Current Behavior
Error appears when pressing change password button

## Possible Solution
You should change the private properties in https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/CUserManager.php

It can't access to those private properties. Set them to public or try protected idk.

**Comment by Groruk** [comment]
Fixed in ec810d2
