### ISSUE TITLE
[QUESTION] Upgrading from version 1.5.4.6

### ISSUE THREAD

**Issue by gonkong** [sbpp/sourcebans-pp#233]
I want to update the plugin and a web part

I have version 1.5.4.6

What you need to do to upgrade?

Just replace the files or/and need to change the database structure?

**Comment by Groruk** [comment]
https://www.gameconnect.net/projects/sourcebans/manual/#updating

**Comment by gonkong** [comment]
You want to say that the current updater, which is updated 5 months ago, will work correctly?
It is applicable to all updates, and even yesterday?

**Comment by Technoblazed** [comment]
The updater directory is only changed if there's a necessary mysql change or something similar, all the updater does is gets the latest commits and updates your sourcebans.
