### ISSUE TITLE
Comms and Bans Weird Character Problem

### ISSUE THREAD

**Issue by brhndursun** [sbpp/sourcebans-pp#236]
Hello.
I'm currently using Sourcebans version 1.5.4.7 on my website. I was thinking that I'm having an issue with charset from website. Wrong. Sourcecomms works great. Check out the first image of my website. Player that named "Yiğit Efe" has "ğ" character and it works great.
![comms](https://cloud.githubusercontent.com/assets/8144522/23404248/a65f2b22-fdbc-11e6-8b2b-545dcae2eea1.jpg)
After that, check out the ban list.
![bans](https://cloud.githubusercontent.com/assets/8144522/23404266/b54ac6fa-fdbc-11e6-9e1c-8d9d840c7e1c.jpg)
Nothing has changed from sourcebans script file. I'm trying to understand sourcecomms and sourcebans punishment methods. They are using same method to save user to database(?Not Sure). Maybe I did something wrong. I don't know.

Since no one has answered my question on alliedmods forum section, I wanted to post this issue to here. Thanks in advance.

**Comment by Groruk** [comment]
Have you any way to replicate this? I can't figure out a way to reproduce this.

**Comment by galexrt** [comment]
You should run this MySQL query to see what default charset the database uses:
```
SELECT default_character_set_name FROM information_schema.SCHEMATA 
WHERE schema_name = "__INSERT_SOURCEBANS_DATABASE_NAME_HERE__";
```

**Comment by brhndursun** [comment]
@Groruk here is my website. http://dumancsgo.com/index.php
@galexrt query result is latin1. I'm going to change it to utf8 but comms works great. Anyway, let's try it...
