### ISSUE TITLE
Error when adding player/admin

### ISSUE THREAD

**Issue by Carvalh0XYZ** [sbpp/sourcebans-pp#238]
Trying to add players or members and get an error if I dont provide an email / admin password
## Expected Behavior
I'd like to add players without having to specify mail or password.

## Current Behavior
Ajax error

https://puu.sh/urlMf/f6d54cbb0c.png

**Comment by galexrt** [comment]
Use the **full** issue template when creating an issue or else it may be ignored: https://github.com/sbpp/sourcebans-pp/blob/v1.x/ISSUE_TEMPLATE.md

***

Your problem seems to be with your MySQL server: https://dev.mysql.com/doc/refman/5.7/en/gone-away.html
