### ISSUE TITLE
[Suggestion] Remove DB info page from SB

### ISSUE THREAD

**Issue by CrazyHackGUT** [sbpp/sourcebans-pp#245]
I think, we need remove page "Database information" with database login, password, name and host from webpanel. Just for security reasons. But leave this page in installer.

**Comment by Technoblazed** [comment]
Where is this page?

**Comment by CrazyHackGUT** [comment]
Adminpanel -> Servers
I can provide screenshot, but my SourceBans on russian and other style.
GET-params for this page: _p=admin&c=servers&o=dbsetup_

Red link:
![screen](http://i.imgur.com/G4RCm2W.png)
