### ISSUE TITLE
[Game] Natives and Forwards

### ISSUE THREAD

**Issue by Bara** [sbpp/sourcebans-pp#249]
You could add a prefix to the current natives like SourceBans_BanPlayer for example.

And a nice feature are forwards like 
- SourceBans_OnPlayerBan(admin, target, time, reason);
- SourceComms_OnPlayerMute(admin, target, time, reason);
- SourceComms_OnPlayerGag(admin, target, time, reason);

**Comment by CrazyHackGUT** [comment]
What you do not like the prefix SB?
I can add forwards.
