### ISSUE TITLE
Sourcecomms plugin error

### ISSUE THREAD

**Issue by caxanga334** [sbpp/sourcebans-pp#25]
I am getting this error with the latest sourcecomms plugin.
"L 05/10/2015 - 14:00:36: [sourcecomms.smx] You must set valid `ServerID` value in sourcebans.cfg!"
I am using the sourcecomms plugins that comes with this sourcebans.

**Comment by sarabveer** [comment]
Fixed.

https://github.com/Sarabveer/SourceBans/commit/973b3072e2a3d3220d34aa1b02b8d475e3be4bbc
