### ISSUE TITLE
Blocking doesn't find ingame players

### ISSUE THREAD

**Issue by RonMelkhior** [sbpp/sourcebans-pp#259]
When adding a block/gag/mute and it scans for people who are ingame, it doesn't manage to find them even if they are ingame. RCON connection seems to be fine as it works fine with bans, so likely something specific to blocks.

**Comment by alan1420** [comment]
Yeah, me too
If you look at the process. After adding block/ban, webserver will send a 'status' command to rcon then webserver get the result. For some reason, webserver didnt convert the uniqueid back to SteamID since we're adding block/ban based on SteamID/Community not SteamID3(uniqueid)

**Comment by IzuiSP** [comment]
I have another one,
When I click on "Block comms"
The SteamIDV3 spawn instead of the STEAM_0:

So SB warn me : 
Please enter a valid Steam ID or Community ID

**Comment by alan1420** [comment]
Exactly.
