### ISSUE TITLE
Unable to ban via server console (sm_addban)

### ISSUE THREAD

**Issue by caxanga334** [sbpp/sourcebans-pp#26]
I tried to ban using sm_addban via the server console. I got this:
"L 05/17/2015 - 13:30:55: [sb_bans.smx] Failed to insert the ID ban into the database: Column 'aid' cannot be null"
sm_ban works fine, this only happen on sm_addban.
Note: sm_addban still works if banned by an admin and not from the server console
Tested on a CS:S Server
SM Version: 1.7.1-dev+5165
Metamod Version: 1.10.5-dev

**Comment by sarabveer** [comment]
Then just use sm_ban

**Comment by caxanga334** [comment]
The main problem is automatic bans from plugins, sm_addban is an option agains people who evade vote bans. this didn't happen with the old version of the plugin (from the official SB 1.4.11).
Anyway, I going to try go get around this problem.

**Comment by sarabveer** [comment]
I'll look into this, apparently, the is a big bug that was also reported in the 1.5.0beta plugin.

**Comment by sarabveer** [comment]
Well, I removed the 1.5beta plugin, and reverted to the 1.4.11 latest plugin.

**Comment by rumblefrog** [comment]
This seems to be occurring with 1.6.2 still https://github.com/sbpp/sourcebans-pp/commit/68e49ab2f00c65c61f8188e246723a2c418f80de
