### ISSUE TITLE
Error plugin V1.6.0

### ISSUE THREAD

**Issue by D4rk56** [sbpp/sourcebans-pp#264]
> L 04/23/2017 - 21:48:55: SourceMod error session started
> L 04/23/2017 - 21:48:55: Info (map "sinjar") (file "errors_20170423.log")
> L 04/23/2017 - 21:48:55: [SM] Exception reported: Fatal error creating dynamic native!
> L 04/23/2017 - 21:48:55: [SM] Blaming: sbpp_main.smx
> L 04/23/2017 - 21:48:55: [SM] Call stack trace:
> L 04/23/2017 - 21:48:55: [SM] [0] CreateNative
> L 04/23/2017 - 21:48:55: [SM] [1] Line 150, sbpp_main.sp::AskPluginLoad2
> L 04/23/2017 - 21:48:55: [SM] Failed to load plugin "sbpp_main.smx": unexpected error 23 in AskPluginLoad callback.
> L 04/23/2017 - 21:48:55: [SM] Exception reported: Fatal error creating dynamic native!
> L 04/23/2017 - 21:48:55: [SM] Blaming: sbpp_comms.smx
> L 04/23/2017 - 21:48:55: [SM] Call stack trace:
> L 04/23/2017 - 21:48:55: [SM] [0] CreateNative
> L 04/23/2017 - 21:48:55: [SM] [1] Line 169, sbpp_comms.sp::AskPluginLoad2
> L 04/23/2017 - 21:48:55: [SM] Failed to load plugin "sbpp_comms.smx": unexpected error 23 in AskPluginLoad callback.
> L 04/23/2017 - 21:48:55: [SM] Unable to load plugin "sbpp_sleuth.smx": Native "SourceBans_BanPlayer" was not found
> L 04/23/2017 - 22:202: Error log file session closed.

**Comment by Bara** [comment]
You should remove the old files and upload the new files..
Sourcebans (1.6.0/latest version) runs fine on my test server.

**Comment by D4rk56** [comment]
Remove old files and restart "Server Insurgency Standalone"
Work on server CS:GO

> L 04/24/2017 - 13:50:38: SourceMod error session started
L 04/24/2017 - 13:50:38: Info (map "ministry") (file "errors_20170424.log")
L 04/24/2017 - 13:50:38: [SM] Exception reported: Fatal error creating dynamic native!
L 04/24/2017 - 13:50:38: [SM] Blaming: sourcebans.smx
L 04/24/2017 - 13:50:38: [SM] Call stack trace:
L 04/24/2017 - 13:50:38: [SM]   [0] CreateNative
L 04/24/2017 - 13:50:38: [SM]   [1] Line 148, sourcebans.sp::AskPluginLoad2
L 04/24/2017 - 13:50:38: [SM] Failed to load plugin "sourcebans.smx": unexpected error 23 in AskPluginLoad callback.
L 04/24/2017 - 13:50:38: [SM] Exception reported: Fatal error creating dynamic native!
L 04/24/2017 - 13:50:38: [SM] Blaming: sbpp_comms.smx
L 04/24/2017 - 13:50:38: [SM] Call stack trace:
L 04/24/2017 - 13:50:38: [SM]   [0] CreateNative
L 04/24/2017 - 13:50:38: [SM]   [1] Line 169, sbpp_comms.sp::AskPluginLoad2
L 04/24/2017 - 13:50:38: [SM] Failed to load plugin "sbpp_comms.smx": unexpected error 23 in AskPluginLoad callback.

**Comment by Bara** [comment]
[game.zip](https://github.com/sbpp/sourcebans-pp/files/951613/game.zip)
Okay, try  this version (it is just a recompile with latest version and sourcemod 1.9 but should work with sm1.8)

**Comment by D4rk56** [comment]
Same error =/

**Comment by CrazyHackGUT** [comment]
Plugin with SB natives already running on server.
Delete old version, unload (`sm plugins unload`), and retry.

**Comment by D4rk56** [comment]
Same ..

**Comment by rzrhome** [comment]
plugins works all i compile with sourcemod 1.9

**Comment by D4rk56** [comment]
1 - Install SM 1.9
2 - Install plugin compiled by @Bara20 
3 - Restart server, same error =/

Server CSGO it's work, but not Insurgency Standalone.

**Comment by D4rk56** [comment]
It works fine, I forgot to remove a plugin from the old version ..
--> sourcecomms.smx
Sorry .. Close

**Comment by CrazyHackGUT** [comment]
And i said that the old plugins did not deleted...
