### ISSUE TITLE
ajax error

### ISSUE THREAD

**Issue by tiweb442** [sbpp/sourcebans-pp#268]
xajax Error: xajax failed to automatically identify your Request URI.Please set the Request URI explicitly when you instantiate the xajax object.

**Comment by Groruk** [comment]
Can you make a gist with the output of `phpinfo()` and link it here?

**Comment by tibehrius** [comment]
I have the same problem here. The installation usually occurs, but when you delete the "install" and "update" folders, the error is reported: 

"xajax Error: xajax failed to automatically identify your Request URI.Please set the Request URI explicitly when you instantiate the xajax object."

Site: http://sbans.bigcs.com.br/

PHP_INFO:  http://sbans.bigcs.com.br/phpinfo.php

Old version in work: http://www.bigcs.com.br/sb

Thanks!

**Comment by lewisgranty** [comment]
I have the exact same problem. After installing the files on the webserver which is all smooth and fine I delete the directory for the install and upgrade and get that xajax error. Kind of a fix we all need due to the fact we can't use the web panel to manage the servers.

**Comment by Groruk** [comment]
You can try to comment [this](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/init.php#L32) line in init.php and test if it still doesn't work.

**Comment by lewisgranty** [comment]
Worked perfect, thanks.

**Comment by Groruk** [comment]
The issue should be fixed in the newest dev version

**Comment by tibehrius** [comment]
It worked perfectly for me too. Thank you very much ;D
