### ISSUE TITLE
Remote server ban is including rate value instead of IP value (CS:GO)

### ISSUE THREAD

**Issue by Maxximou5** [sbpp/sourcebans-pp#27]
From the web panel
- Clicking on the server
- Right clicking on user in server
- Ban user
- IP value is set to 80000 which is the user's rate and not their actual IP address
  ![ss 2015-05-18 at 06 59 55](https://cloud.githubusercontent.com/assets/5216374/7694087/23b3ad34-fd90-11e4-98b4-2e740cf6260f.png)

**Comment by sarabveer** [comment]
What game is this, CS:GO?

**Comment by Maxximou5** [comment]
Yes, that is correct, it is for CS:GO.

**Comment by sarabveer** [comment]
There was a new update for CS:GO that messed up a lot of stuff.
