### ISSUE TITLE
Unable to add server to a newly added mod, or edit mods

### ISSUE THREAD

**Issue by Neoony** [sbpp/sourcebans-pp#282]
I can create a mod, but I can not edit them.  
After clicking on EDIT on one of the mods I will only get a message: "display('page_admin_edit_mod.tpl');?>"  
![31291d971d67d9ced0b59bfe1cb9663d](https://cloud.githubusercontent.com/assets/24975075/25725358/e4dd1828-311f-11e7-906c-61b748ea5f86.png)  
  
Another thing is. That the newly added mod, simply doesnt show up in the server settings to choose from.  
However. If the sb++ autodetects the server, it will add it as the mod. But I can not edit those settings,  because I cant choose that mod again and the mod setting will get reset to hl2 dm after saving it with blank mod.  
  
## Expected Behavior  
To be able to edit mods and select the new ones in server settings.  
  
## Current Behavior  
Bugged editing of mods.  
And bugged mod choices in server settings.  
  
## Steps to Reproduce (for bugs)  
Edit bug.  
1. Go to Admin Panel » Mod management  
2. Edit a mod.  
  
Server mod choice bug.  
1. Add new mod in Admin Panel » Mod management  
2. Go to server settings Admin Panel » Server management » Edit  
3. Search for newly added mod. (doesnt show up)  
  
## Your Environment  
* Version used: Latest dev at this moment.  Latest Git: 478  
*If you need more details here, I can request them.*

**Comment by Groruk** [comment]
Fixed with 9571b1b
Just try and delete the mod and add it again
