### ISSUE TITLE
Issues with weird names

### ISSUE THREAD

**Issue by AtomiCAST** [sbpp/sourcebans-pp#283]
The issue happens mostly when names (such as name**'**) contain symbols like the example which contains an apostrophe. This prevents the unban and delete ban feature from triggering.

## Expected Behavior
In a normal script it should continue and either delete or unban the player.

## Current Behavior
Once you press the button it does nothing, nada, no page reloading, no request is being made.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Ban somebody with a name that will then convert to `sb&amp;%` (Can't remember the exact name)
2. Search for the ban and press the unban button or the delete button.
3. Type the unban reason and attempt to submit or Press the delete button and wait.
4. Nothing happens.

## Context
The reason is extremely simple, unbanning somebody.

## Your Environment
* Version used: SourceBans++ 1.6.0-git0
* PHP and MySQL version: 5.6.30 / PHP 5.6.30
* Operating System and version: Windows Server 2012
* Link to your project: Local at the moment, not available to public yet.
* Link to gist with phpinfo() output: Not sure how to get this :P

**Comment by Groruk** [comment]
Fixed with 49e2c7d
