### ISSUE TITLE
Unintended characters in server settings

### ISSUE THREAD

**Issue by Neoony** [sbpp/sourcebans-pp#284]
Probably unintended 2 characters showing up on top of server settings page.  
Above "Server Details"  
**"';"**
![d5856bc059f8b119fadcc31beef894a0](https://cloud.githubusercontent.com/assets/24975075/25726330/f1f29dea-3123-11e7-8a44-b5f7548536a8.png)  
  
## Your Environment  
* Version used: Current dev version. Latest Git: 478

**Comment by Groruk** [comment]
Fixed with 2c729e1
