### ISSUE TITLE
Map preview images are resized to incorrect ratios

### ISSUE THREAD

**Issue by Xiaminou** [sbpp/sourcebans-pp#287]
As we've discussed in discord, this could be considered a bug.

## Expected Behavior
Map preview images has the same size ratios.

## Current Behavior
Image is resized (to 4:3?) incorrectly.

![chlbgqa](https://cloud.githubusercontent.com/assets/8670392/25757562/40eb0084-31cb-11e7-9ad8-c9f704f38855.png)

**Comment by Groruk** [comment]
Fixed with 899c22f
