### ISSUE TITLE
/mute @all and /unmute @all

### ISSUE THREAD

**Issue by Xiaminou** [sbpp/sourcebans-pp#289]
Yesterday I tried using /mute @all and found out sourcebans intercept it too. It still worked however when I tried to /unmute @all it didn't work and i had to disable sbpp-comms to unmute all players.

## Expected Behavior
/unmute @all should unmute everyone.

## Current Behavior
/unmute @all does nothing?

## Possible Solution
Sourcebans should not intercept /mute @all or /unmute @all. Let it have the normal sourcemods behavior.
Or at least make it a config option?

**Comment by rumblefrog** [comment]
I think I'll look into this and maybe create a pull request

**Comment by CrazyHackGUT** [comment]
SourceComms don't insert many blocks in DB. But unblocks should work properly.

**Comment by rumblefrog** [comment]
Are there any errors when attempting to unmute?

**Comment by sneak-it** [comment]
Adding some information to this, in-game if /mute @all is issued, everyone is muted. If attempting to use /unmute @all, there is no change, everyone is still muted. It appears to be only a session mute, as players can reconnect and they are unmuted. The only way around this is by issuing a mute with a time attached to it (ex. /mute @all 1), or you will have to manually unmute each player.

**Comment by Groruk** [comment]
If anybody of you can provide me with some more informations about this I would appreciate it:
1. Compile the plugin with debug enabled (uncomment [Line 39 and 40](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L39)) and post the output of `sm_mute @all` / `sm_unmute @all`
2. Provide a full list of running plugins (sm plugins list)
3. Which game has these problems with SourceBans++

**Comment by DJPlaya** [comment]
1. Mute > https://i.imgur.com/ldgXBro.png ,  Unmute > https://i.imgur.com/6UBCchM.png
2. This is not related to other Plugins - Tested on a raw Server
3. Any grrr

**Comment by Groruk** [comment]
@DJPlaya Can you try [this](https://gist.github.com/Groruk/ae6cd7246a2a72160fe0ac959aa0d2bb) plugin version and check if it fixes the problem.
compiled download: [sbpp_comms.zip](https://github.com/sbpp/sourcebans-pp/files/1394646/sbpp_comms.zip)

**Comment by DJPlaya** [comment]
Sometimes it workes, sometimes not, a Reason for this may be:
> Exception reported: Array index is out of bounds
> Blaming: SourceBans\sbpp_comms.smx
> Call stack trace:
>    [1] Line 2250, sbpp_comms.sp::ProcessUnBlock
>    [2] Line 2338, sbpp_comms.sp::ProcessUnBlock
>    [3] Line 557, sbpp_comms.sp::CommandCallback

Also when doing` sm_mute @all`, umuting specific Players `sm_unmute PLAYER` seems to do not work

**Comment by DJPlaya** [comment]
I saw there is a Config Option to enter the Server ID from the Webpanel. We forcefully need to enter it there or is this just for whitelisting comms?
```
	"ServersWhiteList"
	{
	  //-----------------------------------------//
	 //	"id"	"ServerID from sourcebans.cfg"	//
	//-----------------------------------------//
		"id"	"0"		// Web Punishments (from sourcebans web pages)
	}
```

**Comment by niiK0** [comment]
Still not working even with the compiled plugin

**Comment by DJPlaya** [comment]
Did this Bug ever got fixed? I think its actually a high Priority Issue
