### ISSUE TITLE
newOverride

### ISSUE THREAD

**Issue by john96dk** [sbpp/sourcebans-pp#291]
im try to add a new override but is give my a error plzz help

here is a sceen shot 
[https://gyazo.com/d8a490b8737f7c28195b3f71ee96f60d](https://gyazo.com/d8a490b8737f7c28195b3f71ee96f60d)

**Comment by Groruk** [comment]
> plzz help 

Then you should give us some information to work with like what we ask in the **issue template**:

## Your Environment
* Version used:
* PHP and MySQL version:
* Operating System and version:
* Link to gist with phpinfo() output:
