### ISSUE TITLE
Delete demo associated with ban

### ISSUE THREAD

**Issue by IncPlusPlus** [sbpp/sourcebans-pp#297]
I have a system to record GOTV demos of the last few minutes just when a ban is issued. This demo is added to the ban on sourcebans. When a ban is deleted, the demo that is a part of that ban stays on the server and takes up space. A possible improvement would be to delete such demos upon deleting their associated bans.

**Comment by Groruk** [comment]
Demos will automatically be deleted when a ban is deleted [proof](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/pages/page.banlist.php#L165). You just need to add the demos to the database.
