### ISSUE TITLE
Add Option to Change Filepath of favicon.ico

### ISSUE THREAD

**Issue by Hazbelll** [sbpp/sourcebans-pp#298]
## Expected Behavior
*I know development has shifted over to SourceBans 2.0 now, however I was hoping this small change could be included for the old SourceBans in the mean time.*

Currently SourceBans offers an option to change the Filepath used for the Logo shown at the top of the website which works as expected. However such an option does not exist for also configuring the favicon used by the website, instead its hardcoded to use a set filepath to the default favicon.

## Current Behavior
SourceBans currently uses the default favicon.ico file found at `/images/favicon.ico` with no way to modify this. A workaround is to replace the actual file with your own, however this must be performed after every SourceBans update as the old one will overwrite it again.

## Possible Solution
Add an option into SourceBans' Web Panel to define the Filepath of the favicon.ico to use.

## Steps to Reproduce (for bugs)
N/A

## Context
As with the Website Logo, some server communities may wish to replace the favicon with their own to match the rest of their website.

## Your Environment
* Version used: https://github.com/sbpp/sourcebans-pp/commit/331e14ea213ab408cf66271a6e462cad54b2c887
* PHP and MySQL version: PHP v7.0 x64 | MySQL 5.7 x64
* Operating System and version: Microsoft Windows Server 2012 R2 Datacenter x64
* Link to your project: N/A
* Link to gist with phpinfo() output: N/A

**Comment by Groruk** [comment]
Added a workaround for this, so now favicons are saved in the theme. There will be major changes to the whole system in the future where this will be addressed properly.
