### ISSUE TITLE
Group Ban bug

### ISSUE THREAD

**Issue by Truba55** [sbpp/sourcebans-pp#299]
## Current Behavior

This Error apperas https://image.prntscr.com/image/fbcb877ad71742889fbd6255518c6fee.png

## Steps to Reproduce (for bugs)

Goto Group Ban (https://ravens-rising.de/sourcebans/index.php?p=admin&c=bans#^4)
Group Link= http://steamcommunity.com/groups/AdolfHitlerFanclub
Group Ban Reason “Mitglied einer Nationalsozialistischen Steam Gruppe”
Click on Add Group Ban
Then, 20-25 Seconds later this error apperas https://image.prntscr.com/image/fbcb877ad71742889fbd6255518c6fee.png
20-30 Users were Banned.

## Context

Try to ban a Steam Group?

* Version used: 1.6.2
* PHP and MySQL version: PHP: 5.6.30  MySQL: 5.7.18
* Operating System and version: Linux 3.10.0-514.10.2.el7.x86_64
* Link to your project: https://ravens-rising.de/sourcebans/
* Link to gist with phpinfo() output: https://ravens-rising.de/infosystem.php

**Comment by Truba55** [comment]
I replaced the old file with the new one. Result: https://image.prntscr.com/image/48c3cfa91d8c4fedb44b761a12c6e34a.png

**Comment by Groruk** [comment]
You are still using 1.6.0! Update to the newest dev version [here](https://github.com/sbpp/sourcebans-pp/archive/v1.x.zip).

**Comment by Truba55** [comment]
https://image.prntscr.com/image/de35a597c8be420687052491b7b7ed75.png
{
    "version": "1.6.2",
    "git": "498"
}

I think the problem is the special characters.

**Comment by Groruk** [comment]
Newest dev version updates the feature again (now requiring a steam webapi key). 
Your problem most likely comes from a misconfiguration of your web or mysql server.

**Comment by Truba55** [comment]
It works now.

Why is there a limit of 1000?
http://prntscr.com/f98q6k

**Comment by Groruk** [comment]
limitation comes from the old 'memberslistxml' function the only 'api' for groups we currently have (I will try and come up with a better api and implement it in sourcebans)

**Comment by rumblefrog** [comment]
Yikes, I just came across the 1000 members limit.
