### ISSUE TITLE
Cant upload a Demo

### ISSUE THREAD

**Issue by Truba55** [sbpp/sourcebans-pp#302]
## Steps to Reproduce (for bugs)
1. Open https://ravens-rising.de/sourcebans/index.php?p=banlist&advSearch=STEAM_1:1:186240159&advType=steamid&Submit
2. Click on "Edit Details"
3. Click on "Upload Demo"
4. Click on "Datei auswählen" and Choose a .rar File.
5. Click on "Save"
6. After 100 % Waiting 30 Seconds.
7. Close the Tab
8. Record is not uploaded.

Same thing when i try to upload a Demo in the Ban Tab (https://ravens-rising.de/sourcebans/index.php?p=admin&c=bans)

Version used: 1.6.2
PHP and MySQL version: PHP: 5.6.30 MySQL: 5.7.18
Operating System and version: Linux 3.10.0-514.10.2.el7.x86_64
Link to your project: https://ravens-rising.de/sourcebans/
Link to gist with phpinfo() output: https://ravens-rising.de/infosystem.php

**Comment by Groruk** [comment]
Demo upload works fine in all the current versions of SourceBans++.
Keep in mind that uploading a demo can take time (if you have a big demo or a slow internet connection).

The little upload window will close automatically when the upload is finished and this red text will appear (indicating that your demo was successfully uploaded)
![uploaded](https://cloud.githubusercontent.com/assets/5796460/26277652/fd16213c-3d8b-11e7-96f8-26c5f1487a21.PNG)

There is always the possibility that based on your webserver configuration the upload request will be dropped and the upload aborted if it takes too much time.
