### ISSUE TITLE
web page show the "could not find driver"

### ISSUE THREAD

**Issue by bigstar1311** [sbpp/sourcebans-pp#304]
Hello.
Can you help me? 
an error while installing the source ban.
web page show the "could not find driver".
what should i do?

## Your Environment

* Version used: 1.6.1
* PHP and MySQL version: PHP 5.6.0 / MySQL 5.6.20
* Operating System and version: Window 10 Home
* Link to your project:
* Link to gist with phpinfo() output:

**Comment by Groruk** [comment]
Can you link the output of phpinfo()? (preferably in a [Gist](https://gist.github.com/))

**Comment by bigstar1311** [comment]
here. my php info link.

**Comment by Groruk** [comment]
The problem here is that you have disabled the `pdo_mysql` extension; therefore PDO can't use MySQL as a driver and can't establish a connection to a database.
If you enable the `pdo_mysql` extension in PHP, everything should work fine.

**Comment by bigstar1311** [comment]
Thank you so much.
That issue has been resolved.
