### ISSUE TITLE
SourceComms Failing to Account for Unmute @all

### ISSUE THREAD

**Issue by Joe-Howanski** [sbpp/sourcebans-pp#308]
## Expected Behavior
When I mute individuals 1, 2, and 3 for the session: sm_mute name -1, it is supposed to mute them only for the session. When I do sm_unmute @all I believe it is either supposed to completely ignore all of the people with session mutes or it unmutes them and removes them from the database (sets them as unbanned).

## Current Behavior
Currently, if I mute individuals 1, 2, and 3 with individual mutes and then use sm_unmute @all, it unmutes them and allows them to talk, but lists them as banned for the Session in the online web panel. If I try to unmute them it informs me that the player is not muted. If the player disconnects then reconnects to the server, the mute is still applied.

## Possible Solution
I would suggest either not allowing sm_unmute @all or etc to target those with session mutes or making sure that session mutes are properly unbanned by a @all.

## Steps to Reproduce (for bugs)

1. Use sm_mute name -1 on a player.
2. Use sm_unmute @all
3. See if the player is able to talk, or have the player reconnect and check if they can talk.

## Context
This is preventing admins from keeping individuals muted properly through a session, or have players stuck with mutes that should be removed.

## Your Environment

* Version used: Version 1.6.1
* SM Version: 1.8.0.5995
* Operating System and version: Linux Debian

**Comment by Groruk** [comment]
To resolve this I would need some more information:
1. Can you compile the plugin with debug enabled (uncomment [Line 39 and 40](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L39)) and post the output of `sm_mute @all` / `sm_unmute @all`?
2. Can you provide a full list of running plugins (sm plugins list)
3. Which game has these problems with SourceBans++

**Comment by Joe-Howanski** [comment]
1. Done:
>Sourcecomms plugin loading. Version 1.6.1
DB_Connect(handle 0, state 0, lock 0)
DB_Connect(handle 0, state 2, lock 1)
[SourceComms++] Loading configs/sourcebans/sourcebans.cfg config file
[SourceComms++] Loading configs/sourcecomms.cfg config file
Loaded reason. index 0, key "Obscene language", display_text "Obscene language"
Loaded reason. index 1, key "Insult players", display_text "Insult players"
Loaded reason. index 2, key "Admin disrespect", display_text "Admin disrespect"
Loaded reason. index 3, key "Inappropriate Language", display_text "Inappropriate Language"
Loaded reason. index 4, key "Spam in chat/voice", display_text "Spam"
Loaded reason. index 5, key "Trading", display_text "Trading"
Loaded reason. index 6, key "Other", display_text "Other"
Loaded reason. index 7, key "Advertisement", display_text "Advertisement"
Loaded reason. index 8, key "Played music in voice", display_text "Music in voice"
Loaded time. index 0, time -1 minutes, display_text "Session"
Loaded time. index 1, time 30 minutes, display_text "30 minutes"
Loaded time. index 2, time 60 minutes, display_text "60 minutes"
Loaded time. index 3, time 120 minutes, display_text "2 hours"
Loaded time. index 4, time 360 minutes, display_text "6 hours"
Loaded time. index 5, time 720 minutes, display_text "12 hours"
Loaded time. index 6, time 1440 minutes, display_text "24 hours"
Loaded time. index 7, time 2880 minutes, display_text "2 days"
Loaded time. index 8, time 10080 minutes, display_text "7 days"
Loaded time. index 9, time 20160 minutes, display_text "2 weeks"
Loaded time. index 10, time 0 minutes, display_text "Permanent"
Loaded white list server id 0
Loaded DefaultTime value: -1
Loaded DisableUnblockImmunityCheck value: 0
[SM] Loaded plugin sbpp_comms.smx successfully.
] sm_mute @all
[SourceComms++] Muted all players.
] sm_unmute @all
[SourceComms++] Removed an extended mute from Eoj Charlie | Harpoon.tf.
[SourceComms++] Successfully removed mute for Eoj Charlie | Harpoon.tf from DB.
[SourceComms++] Successfully removed mute for Eoj Charlie | Harpoon.tf from DB.
[SourceComms++] Muted all players.
[SourceComms++] Removed an extended mute from Eoj Charlie | Harpoon.tf.
[SourceComms++] Successfully removed mute for Eoj Charlie | Harpoon.tf from DB.
[SourceComms++] Successfully removed mute for Eoj Charlie | Harpoon.tf from DB.
] sm_mute @all
[SourceComms++] Muted all players.
] sm_unmute @all
[SourceComms++] Temporarily removed mute from all players.
] sm_mute slow
[SourceComms++] Muted The Slow Scout ⇋HG-A⇌.
] sm_mute eoj
[SourceComms++] Muted Eoj Charlie | Harpoon.tf.
] sm_unmute @all
[SourceComms++] Temporarily removed mute from all players.
] sm_unmute eoj
[SourceComms++] Player not muted.

2. Running Plugins
>[SM] Listing 70 plugins:
  01 "Admin File Reader" (1.8.0.5995) by AlliedModders LLC
  02 "SourceBans++: Bans Checker" (1.6.1) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  03 "[TF2Items] Give Weapon" (3.14159) by FlaminSarge (orig by asherkin)
  04 "Nextmap" (1.8.0.5995) by AlliedModders LLC
  05 "PremDonor ChatTags" (2.1) by Bottswana
  06 "Basic Info Triggers" (1.8.0.5995) by AlliedModders LLC
  07 "[Any] Deluxe Godmode" (2.3.1) by DarthNinja
  08 "Boxing Events" (4.1.1) by Skipper
  09 "Basic Commands" (1.8.0.5995) by AlliedModders LLC
  10 "[TF2] Trade Requests" (15.0725) by Derek D. Howard
  11 "Fun Commands" (1.8.0.5995) by AlliedModders LLC
  12 "Tidy Chat" (0.4) by linux_lover
  13 "Raffle" (0.9) by NuclearWatermelon
  14 "Client Preferences" (1.8.0.5995) by AlliedModders LLC
  15 "Basic Votes" (1.8.0.5995) by AlliedModders LLC
  16 "Sound Commands" (1.8.0.5995) by AlliedModders LLC
  17 "Web Shortcuts" (0x01) by Kyle Sanderson, Nicholas Hastings
  18 "Fun Votes" (1.8.0.5995) by AlliedModders LLC
  19 "Admin Menu" (1.8.0.5995) by AlliedModders LLC
  20 "Fun Commands X" (2.2) by Spazman0 and Arg!
  21 "Map Reload and AutoReload" (1.0) by Bottswana
  22 "Temp Ban" (1.3.0) by Eoj Charlie, Harpoon Gaming
  23 "[TF2] Rate of Fire" (1.2) by EHG
  24 "[TF2] Enhanced Item Notifications" (1.1.0) by Dr. McKay
  25 "Player-Teleport by Dr. HyperKiLLeR" (1.2.0.0) by Dr. HyperKiLLeR
  26 "Aim Menu" (2.0) by Skipper
  27 "Server Rule Agreement" (3.6.2) by Skipper
  28 "Player Commands" (1.8.0.5995) by AlliedModders LLC
  29 "SourceBans++: SourceSleuth" (1.6.1) by ecca, SourceBans++ Dev Team
  30 "Dueling!" (0.1) by linux_lover
  31 "PremDonor MiscCommands" (2.1) by Bottswana
  32 "PremDonor Class Effects" (2.1) by Bottswana
  33 "Harpoon Adverts" (2.1.0) by Bottswana
  34 "PremDonor Teleport" (2.1) by Bottswana
  35 "TF2Fix" (1.4.8_01) by MasterOfTheXP
  36 "REGEX word filter" (1.2) by Twilight Suzuka
  37 "Anti-Flood" (1.8.0.5995) by AlliedModders LLC
  38 "PremDonor Core" (2.1.2) by Bottswana
  39 "Basic Chat" (1.8.0.5995) by AlliedModders LLC
  40 "Harpoon Server Hop" (2.1.0) by Bottswana
  41 "Basic Comm Control" (1.8.0.5995) by AlliedModders LLC
  42 "[TF2] PowerPlay" (1.5.3) by DarthNinja
  43 "[TF2] TF2Attributes" (1.3) by FlaminSarge & El Diablo
  44 "SourceBans++: Main Plugin" (1.6.1) by SourceBans Development Team, SourceBans++ Dev Team
  45 "Updater" (1.2.2) by GoD-Tony
  46 "Admin Help" (1.8.0.5995) by AlliedModders LLC
  47 "Hammer Triggers" (1.0.0) by Skipper
  48 "Spycrabbing Challenges" (1.0.0) by Skipper
  49 "Simple Chat Me" (1.0.0) by Simple Plugins
  50 "PremDonor Noisemaker" (2.1) by Bottswana
  51 "TF2 Set Class" (1.2.2) by Tylerst
  52 "{MSTR} Rocket" (1.1) by MasterOfTheXP
  53 "SoftPan - Squishy pans make no noise!" (1.0.1) by Bottswana
  54 "PremDonor ModelChanger" (2.1) by Bottswana
  55 "[TF2Items] Manager" (1.4.1) by Damizean & Asherkin
  56 <Failed> "[ANY] Player Analytics" (1.3.1) by Dr. McKay
  57 "Wall Test" (1.0.0) by Skipper
  58 "[TF2] SteamRep Checker (Redux)" (1.2.0) by Dr. McKay
  59 "SourceBans++: Admin Config Loader" (1.6.1) by AlliedModders LLC, SourceBans++ Dev Team
  60 "PremDonor Jetpack" (2.1) by Bottswana/Skipper
  61 "Spycrab Event" (9.1.0) by Skipper
  62 "PremDonor Holy Arrows" (2.1) by DarthNinja/Bottswana
  63 "Reserved Slots" (1.7.3-dev+5301) by AlliedModders LLC
  64 "Server Hud Logo" (2.2) by ReFlex
  65 "Advanced Infinite Ammo" (1.2.9) by Tylerst
  66 "Rami Map Provider" (1.8) by Bottswana
  67 "PremDonor FunCommands" (2.2.0) by Bottswana
  68 "[TF2] DSP Effects" (1.1) by A.I, Hurp Durp
  69 "[ANY] Contract" (1.6) by Arkarr
  70 "SourceBans++: SourceComms" (1.6.1) by Alex, SourceBans++ Dev Team

3. This is within Team Fortress 2.

**Comment by Joe-Howanski** [comment]
@Groruk This may relate to #289

**Comment by Groruk** [comment]
Duplication of #289
