### ISSUE TITLE
web panel installs fine but white screen where login page should be

### ISSUE THREAD

**Issue by bootsy-** [sbpp/sourcebans-pp#310]
## Expected Behavior
sourcebans-pp webpanel @ https://bans.scoutzknivez.co.uk/index.php

## Current Behavior
Blank, white page. Adding '?debug=1' makes no difference.

## Your Environment
* Version used: 1.6.1 full / 1.6.1 webpanel-only
* PHP and MySQL version: PHP 5.6.30 // 5.6.35 - MySQL Community Server (GPL)
* Operating System and version: CENTOS 6.9 x86_64 virtuozzo
* Link to your project: https://bans.scoutzknivez.co.uk/
* Link to gist with phpinfo() output: huh?

When the install and updater folders are present bans.scoutzknivez.co.uk/install works fine through all 5 steps, I navigate to the main URL and I get the "Delete the install folder", I do and get the same message for 'updater', I delete that and am left with a blank page.

**Comment by Groruk** [comment]
Most likely your webhoster is blocking internal functions like `ini_set` or `set_error_handler`. I can't be quite sure what the error here is (because your hoster likely blocks error messages) the only thing I can tell is that it occurs in the `init.php` after [line 103](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/init.php#L103) so you will have to debug it yourself.

**Comment by bootsy-** [comment]
I'm hosting on a Virtual Private Server with GoDaddy, I have CLI (although I don't know how to use it). I had a look at the init.php and can't see anything that looks out of place, then again I don't know PHP, so....

Oh, before I moved to a VPS I got it up and running on GoDaddy's shared hosting, so I think it's doable.

**Comment by galexrt** [comment]
Please create a phpinfo page, like this https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page
And post us the link to it.

P.S. There is no debug mode by using a get param..

**Comment by bootsy-** [comment]
http://bans.scoutzknivez.co.uk/phpinfo.php

**Comment by galexrt** [comment]
Create a file 
```
<?php
echo "TEST BEGIN<br>";
function myErrorHandler($errno, $errstr, $errfile, $errline)
{
    if (!(error_reporting() & $errno)) {
        // This error code is not included in error_reporting, so let it fall
        // through to the standard PHP error handler
        return false;
    }

    switch ($errno) {
    case E_USER_ERROR:
        echo "<b>My ERROR</b> [$errno] $errstr<br />\n";
        echo "  Fatal error on line $errline in file $errfile";
        echo ", PHP " . PHP_VERSION . " (" . PHP_OS . ")<br />\n";
        echo "Aborting...<br />\n";
        exit(1);
        break;

    case E_USER_WARNING:
        echo "<b>My WARNING</b> [$errno] $errstr<br />\n";
        break;

    case E_USER_NOTICE:
        echo "<b>My NOTICE</b> [$errno] $errstr<br />\n";
        break;

    default:
        echo "Unknown error type: [$errno] $errstr<br />\n";
        break;
    }

    /* Don't execute PHP internal error handler */
    return true;
}
set_error_handler("myErrorHandler");
echo "OKAY 1<br>";
ini_set('display_errors', true);
echo "OKAY 2<br>";
```
And post the output of it.

**Comment by bootsy-** [comment]
http://bans.scoutzknivez.co.uk/mytest.php
TEST BEGIN
OKAY 1
OKAY 2

**Comment by Groruk** [comment]
Try changing [line 150 in init.php](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/init.php) from `die();` to `die('ADODB init failed');` and check if any message is coming up on the [page](https://bans.scoutzknivez.co.uk/).

**Comment by bootsy-** [comment]
Nope, no message. I'm thinking at this point it must be some conflict or server calibration issue. I did also try installing to bans.scoutzknivez.co.uk/sb/ but no luck there either.

**Comment by jono666** [comment]
Hi there Bootsy,

Going off your phpinfo.php http://bans.scoutzknivez.co.uk/phpinfo.php your current PHP version is 5.5.35 my guess is that your current version is conflicting with the current sourcebans.

I have had similar issues in the past with cpanel web servers. My suggestion on how to fix it if you are using the latest cpanel. It should come pre-installed with "MultiPHP Manager" using multiPHP manager force php version 5.6 or higher on "scoutzknivez.co.uk". 

Here is a link with instructions https://documentation.cpanel.net/display/ALD/MultiPHP+Manager+for+WHM

Good luck,
Jono

**Comment by rumblefrog** [comment]
Feel free to hop on SBPP Discord, I can assist you faster in there.

**Comment by IncPlusPlus** [comment]
There is also a chance that there is not enough memory available. I remember seeing [this](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/config.php.template#L46) in the config.php during my install. Try experimenting with it. There is a little bit more on why explained in the comment [here](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/install/template/page.5.php#L33)
