### ISSUE TITLE
Can't get playerinfo for -player-. Player not on the server anymore!

### ISSUE THREAD

**Issue by ShawnCZek** [sbpp/sourcebans-pp#314]
## Expected Behavior

If I want to do anything with a player, I will be able to do it - generate profil, block communication etc. Now we must go to the server and ban the player or we must find his SteamID32 and it isn't comfortably.

## Current Behavior

Now it stops on generating a profile and writes this error:
> Can't get playerinfo for -player-. Player not on the server anymore!

## Steps to Reproduce (for bugs)

1. Go on Server list.
2. Right click on the player.
3. Try to Kick, Ban, Block Comms or View Profile.

## Context

I would like to ban or kick the player really easily and not find his SteamID32 or nickname. And if I want to ban his IP address, I can't do it now.

## Your Environment

* Version used: 1.6.1
* PHP and MySQL version: **PHP** 5.6.30-0+deb8u1 (cli), **MySQL** 5.5.55-0+deb8u1
* Operating System and version: Debian 8.8
* Link to your project: http://www.bans.playitordie.eu
* Link to gist with phpinfo() output: N/A

**Comment by rumblefrog** [comment]
seems to be related to #259

**Comment by ShawnCZek** [comment]
Yes, but I got message, here: https://github.com/sbpp/sourcebans-pp/issues/157#issuecomment-306779539, that I should open a new issue, so I did it. Because I am sure the players are still on the server when I do that.

**Comment by vishal1714** [comment]
Well Same Issue I am facing for a while

Reason I Know -
When We use the Web Interface For Getting The players Information Interface execute the rcon command "Status" and send it to our server and get the information from "status" command If In your server you blocked your status rcon command using any plugins like
status_protector.smx,rcon_lock.smx this plugins block the access of rcon commands.

Solution-
Check the rcon password of your server while adding it in sourcebans it must be correct.
Remove Any plugins which block the rcon commands or rcon "Status" Commands.

**Comment by Hexer10** [comment]
I had this issue only when the rcon password wasn't sat properly.

**Comment by CrazyGhostRider** [comment]
I have exactly the same error.
This error can be obtained if there are some symbols in the player's nick.
For example: The nickname of the player is "reifu <3", and the web panel writes that the player with the nickname "reifu" is not found. Same thing with this nickname "<<★СОКОЛ★>>"

At the same time on other nicknames you can do ban/mute/info

P.s. If you manually add a muta, the nickname of the player is reduced to "reifu"

## Possible Solution
Make a check for additional characters
Addition. It's all about the characters "<" and ">".

## Your Environment
Version used: 1.6.2
PHP and MySQL version: PHP 7.1, MySQL 5.5
Operating System and version: Windows 7 "Open Server x64"

**Comment by CrazyGhostRider** [comment]
I had to make a temporary decision, since no one wants to help.
I made an automatic replacement of the characters in the player's nickname from "<", ">" to "˂", "˃" (These are others)

**Comment by rumblefrog** [comment]
From "<", ">" to "˂", "˃"?

**Comment by CrazyGhostRider** [comment]
I did this so that players would not complain about the nickname cut.
The standard ">" — Greater-Than Sign (Unicode number: U+003E)
Replaced with "˃" — Modifier Letter Right Arrowhead [Unicode number: U+02C3 (U+02C2 — "˂")]

P.s. It is possible that the Web panel also deletes other characters. If I find them and the Web panel is not repaired, I'll write these symbols here.

**Comment by rumblefrog** [comment]
As far as I know, the web panel uses `strip_tags()`, which explains why `reifu <3` turned into `reifu`, as it interpreted it as a tag

**Comment by ShawnCZek** [comment]
Yes, I was playing around with servers today and it has been fixed by adding +ip into launching options and setting rcon_password. Thank you very much for help and everyone for info above. :+1:
