### ISSUE TITLE
Update from 1.5.7 to 1.6.1

### ISSUE THREAD

**Issue by nco795** [sbpp/sourcebans-pp#321]
## Current Behavior
My actual sourcebans version is 1.5.4.7
I would like to update to 1.6.1, i uploaded all the 1.6.1 data to my webspace with installed 1.5.4.7.
If i want to upgrade with bans.burgerbude.net/updater it shows me a blank website.

Sourcebans Systemlog shows me an error:
https://gist.github.com/nco795/0f9bc3deba35e1fd13f462cac2de1650

## Steps to Reproduce (for bugs)

1. Try to update from https://github.com/sbpp/sourcebans-pp/releases/tag/1.5.4.7
2. Use this https://github.com/sbpp/sourcebans-pp/releases/tag/1.6.1
3. Getting a blank site if run /updater
4. Sourcebans errorlog: https://gist.github.com/nco795/0f9bc3deba35e1fd13f462cac2de1650

## Your Environment
* Version used: 1.6.1
* PHP and MySQL version:
Server: Localhost via UNIX socket
Server-Typ: MariaDB
Server Version: 10.0.29-MariaDB-0+deb8u1 - (Debian)
Protokoll-Version: 1

* Operating System and version:
Apache/2.4.10 (Debian)

* Link to your project: 
http://bans.burgerbude.net/

* Link to gist with phpinfo() output: https://gist.github.com/nco795/313b901863241451d74542877f970935

**Comment by Groruk** [comment]
Seems to be an odd issue with the updater versioning.
In your database you should have a table called `sb_settings` in there should be a key called `config.version`
try and set the value of this to `356` and run the updater again.

**Comment by nco795** [comment]
Updated successfully. Please delete the /updater folder.
It worked thanks
