### ISSUE TITLE
login session does not persist

### ISSUE THREAD

**Issue by nikooo777** [sbpp/sourcebans-pp#326]
## Expected Behavior

Session storage should allow me to log in once and remain logged in for as long as the session is valid (7 days)

## Current Behavior

When closing the browser (chrome in my case but also verified on firefox) the session is forgotten and a new login is required

## Possible Solution

investigate why the session is not persisted and make sure it is in the next release.

## Steps to Reproduce (for bugs)

1. Log in to SB using steam
2. close the browser completely
3. open the browser once again and navigate to the installation
4. the session is lost and a new login is required

## Context

N/A

## Your Environment

* Version used: 1.6.2
* PHP and MySQL version: Apache/2.4.10 (Debian)
* Operating System and version: Debian 8 64 bit
* Link to your project: https://bans.elite-hunterz.info/
* Link to gist with phpinfo() output: https://gist.github.com/nikooo777/c1bca5ab2bb0cb5d7276c878624df110

**Comment by vfioox** [comment]
https://github.com/sbpp/sourcebans-pp/commit/727fea09a66e109c5867c4117d38fb8cc726e7f5

I suspect this commit broke it. Didn't look into why, at least yet.
