### ISSUE TITLE
sign in through steam error.

### ISSUE THREAD

**Issue by lokothegod** [sbpp/sourcebans-pp#332]
I am trying to get the sign in through steam feature to work, when i sign in to steam it takes me to this url
https://dynamicrp.org/bans/dynamicrp.org, how can i fix this

define('SB_WP_URL', 'dynamicrp.org');       				//URL of SourceBans Site

**Comment by lokothegod** [comment]
i changed it to http://dynamicrp.org/bans and  i fixed it, but it wont sign in any ideas.

**Comment by rumblefrog** [comment]
First, use the issue template that is automatically included when creating an issue in which that you deleted, then we can help.

**Comment by rumblefrog** [comment]
For future people, he's using the wrong protocol
