### ISSUE TITLE
sbpp_sleuth no reban.

### ISSUE THREAD

**Issue by Deniel00** [sbpp/sourcebans-pp#334]
Hi!

## Expected Behavior

The player have any active ban, and the plugin banning this player second account via corresponding ip address. The configs file is correct sets.

## Current Behavior

Now the plugin no baning the second acc. 

## Steps to Reproduce (for bugs)

1. Ban player.
2. This player have second acc, and can join to server
3. The sleuth no banning this player.

## Context

Need automatic reban player on second acc.

## Your Environment

* Version used: 1.6.2 stable
* PHP and MySQL version: PHP Version 5.6.31-1~dotdeb+7.1, mysql 5.5
* Operating System and version: Linux vps-173-227 3.2.0-4-amd64 SMP Debian 3.2.88-1 x86_64
* Link to your project: http://vadkender.netcore-gaming.eu/sourcebans/index.php?p=banlist
* Link to gist with phpinfo() output: http://vadkender.netcore-gaming.eu/sourcebans/phpinfo.php

**Comment by Deniel00** [comment]
Banned on 7. 28. 13:15
![1](https://user-images.githubusercontent.com/12788940/28752076-71fe6f0a-7517-11e7-8d0b-20f202d3f4a9.png)
And today can play
![2](https://user-images.githubusercontent.com/12788940/28752077-72282890-7517-11e7-8ec2-362f49d4914d.png)

And no get ban automatic.

**Comment by rumblefrog** [comment]
Follow the template would ya: https://raw.githubusercontent.com/sbpp/sourcebans-pp/v1.x/.github/ISSUE_TEMPLATE.md

**Comment by Deniel00** [comment]
Updated :)

**Comment by rumblefrog** [comment]
Is SourceSleuth loaded? Check `sm plugins list`, and are there any errors regarding SourceSleuth?

**Comment by Deniel00** [comment]
Loaded, no errors.
Everything "perfect work".
` "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team`

**Comment by rumblefrog** [comment]
By no errors, do you mean there's no logs directory?

**Comment by Deniel00** [comment]
No errors, becouse in logs directory no write errors for this bug.
No no sql connect error, no table found error, no ban problem.
Like not want ban player.

**Comment by rumblefrog** [comment]
I have no idea what's wrong with this one, perhaps others might.

**Comment by Deniel00** [comment]
Okey, i will make own dev for this and testing it. If i found anything will comment there.
Have a nice day!

**Comment by Deniel00** [comment]
Fixed.
`if (TotalBans > g_cVar_bansAllowed.IntValue)`
Edited to:
`if (TotalBans >= g_cVar_bansAllowed.IntValue)`

Becouse the sm_sleuth_bansallowed cvar get 1.
In the database have 1 bans, but in plugin needed 2 bans (>).


--EDIT--
Bad thinging.
sm_sleuth_bansallowed need 0 for instant ban...
But in old version banned player who not have active ban, now change to 0.

**Comment by Caaine** [comment]
not working for me

i banned a player three Times
and the Plugin nothing...

**Comment by rumblefrog** [comment]
@Caaine Mind providing some context instead of complaining.
