### ISSUE TITLE
Verify Insert Query Failed: Incorrect string value

### ISSUE THREAD

**Issue by Aftermoon-dev** [sbpp/sourcebans-pp#339]
## Expected Behavior

Ban Register in SourceBans Website, And DB

## Current Behavior

Try In-Game Ban include Korean Reason, but can't register ban in Database
(If Reason Write English, I can add ban.)
sourcebans.log Error : L 08/14/2017 - 13:06:26: [sbpp_main.smx] Verify Insert Query Failed: Incorrect string value: '\xED \x85 \x8C ...' for column 'reason' at row 1
(I'm Korean, So Our Server's Ban Reason is Korean Lanaguage)

## Steps to Reproduce (for bugs)

1. Ban Player include Korean Language Reason (ex. 테스트)
2. Can't find Ban Infomation.
3. sourcebans.log : L 08/14/2017 - 13:06:26: [sbpp_main.smx] Verify Insert Query Failed: Incorrect string value: '\xED \x85 \x8C ...' for column 'reason' at row 1

## Context

I'm Korean So We need Korean Reason, but We can't add Ban include Korean Language Reason.
I change MySQL characterset
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4

But Nothing Change. We still can't ban user.

## Your Environment

* Version used: 1.6.2
* PHP and MySQL version: PHP : 7.0.22-0ubuntu0.16.04.1 / MySQL : 5.7.19-0ubuntu0.16.04.1 - (Ubuntu)
* Operating System and version: Ubuntu 16.04.3 LTS
* Link to your project: http://sb.hdshouse.me/
* Link to gist with phpinfo() output: http://sb.hdshouse.me/phpinfo.php

**Comment by rumblefrog** [comment]
Can you provide the plugin source where you modified the charset and did you change table collate?

**Comment by Aftermoon-dev** [comment]
I'm not change plugin source. Same Source for 1.6.2.
And I already change table collate (utf8mb4_general_ci)

**Comment by rumblefrog** [comment]
If you didn't change the source, how did you change the client charset?

**Comment by Aftermoon-dev** [comment]
I change MySQL Setting File.

**Comment by rumblefrog** [comment]
Try modifying the sbpp_main.sp on https://github.com/sbpp/sourcebans-pp/blob/ad62c907fb720b41c0c8578ee34de45ae289466f/game/addons/sourcemod/scripting/sbpp_main.sp#L1003

**Comment by sarabveer** [comment]
Also, use `utf8mb4_unicode_ci`

**Comment by Aftermoon-dev** [comment]
Thanks For Answer. I try test now.

**Comment by Aftermoon-dev** [comment]
I change table's collations to utf8mb4_unicode_ci
And I change plugins source in line 1003 -> SQL_SetCharset(DB, "utf8mb4");
Same Error
[sbpp_main.smx] Verify Insert Query Failed: Incorrect string value: '\xE3 \x85 \x81 ...' for column 'reason' at row 1

**Comment by Aftermoon-dev** [comment]
This Error is Maybe SourceMod can't support Unicode Text.

**Comment by CrazyHackGUT** [comment]
SourceMod (and DBI, MySQL extensions) supports Unicode text. The problem is in the MySQL Server configuration.

**Comment by Aftermoon-dev** [comment]
But I try use this code, I can't See Korean Character in Chat.
And, Another DB can write data include Korean Character.
I ask to other Korean CS:GO Server Master, 
They answered to me, Our Server's SourceBans can write Korean Character. (They are use Windows)
I use Newest Stable MetaMod, And SourceMod, Sourcebans++. 
I think it is very Strange :(

````Pawn
#include <sourcemod> 

public OnPluginStart()
{
	RegAdminCmd("sm_testcmd", Test_Command, ADMFLAG_BAN, "sm_ban <#userid|name> <minutes|0> [reason]");
}

public Action:Test_Command(client, args)
{
	decl String:buffer[100];
	GetCmdArg(1, buffer, sizeof(buffer));
	PrintToChatAll("Buffer : %s", buffer);
	return Plugin_Handled;
}
``

**Comment by CrazyHackGUT** [comment]
You entered "Korean character" in quotes?
`sm_testcmd "your korean character"`

**Comment by Aftermoon-dev** [comment]
CS:GO In-Game Chat can't write quotes.

**Comment by CrazyHackGUT** [comment]
In some source games (TF2, for example) too.
Use console.

**Comment by Aftermoon-dev** [comment]
Console can't type korean
(but copy & taste can see Korean in PrintToChat)
