### ISSUE TITLE
SourceBans web panel doesn't seem to support IPv6 connections

### ISSUE THREAD

**Issue by h1nk** [sbpp/sourcebans-pp#340]
Seems that the SourceBans web panel does not support IPv6 connections and that using a DNS record to point the game server will result in an error to connect. The only way I could get the panel to work was to override the DNS record in /etc/hosts to force IPv4 or to use the direct IPv4 address of the game server.

**Comment by Groruk** [comment]
Source isn't supporting IPv6 so there is no real point of adding IPv6 support for the webpanel.

**Comment by RumbleFrog** [comment]
+1

**Comment by rumblefrog** [comment]
+1, it doesn't support IPv6

**Comment by h1nk** [comment]
I still think that it would be nice if the web panel ignored AAAA record resolvement if you have an A and AAAA record pointed at the server that you would like to use, this avoids having to use something like /etc/hosts if you want to use a domain like in my scenario.

**Comment by rumblefrog** [comment]
`socket_addrinfo_lookup()` and `socket_addrinfo_explain()` was introduced in PHP 7.2 RC 1, but that's on the bleeding edge, and most people won't have it. Perhaps in the distant future.

**Comment by sarabveer** [comment]
> `socket_addrinfo_lookup()` and `socket_addrinfo_explain()` was introduced in PHP 7.2 RC 1, but that's on the bleeding edge, and most people won't have it. Perhaps in the distant future.

@RumbleFrog Put it in SB++ 2.0 and make an excuse to force people to use PHP 7.2.x
