### ISSUE TITLE
Ban reasons are encoded when you enter them, but aren't unencoded when displayed.

### ISSUE THREAD

**Issue by popey456963** [sbpp/sourcebans-pp#341]
## Expected Behavior
- Ban reasons are displayed as entered

## Current Behavior
- Ban reasons are displayed URL encoded

## Possible Solution
- URL unencode them?

## Steps to Reproduce (for bugs)
1. Set a custom ban reason to something like "RDM'ing"
2. Ban someone for that reason.
3. Observe how the reason is actually "RDM&amp;&027;ing"

## Context
- Was trying to create a custom ban reason that had a special character in it

**Comment by rumblefrog** [comment]
It's not URL encoding, it's htmlentities, and it's there to prevent XSS

**Comment by rumblefrog** [comment]
https://github.com/sbpp/sourcebans-pp/blob/ad62c907fb720b41c0c8578ee34de45ae289466f/web/themes/default/page_bans.tpl#L254

https://www.smarty.net/docsv2/en/language.modifier.escape

And it seems like it was escaping it improperly.

**Comment by popey456963** [comment]
Oops, sorry for using the wrong terminology.  I just had to solve an issue with MyBB that required using HTML entities in the URL which led my mind to be ever so confused.

My assumption is it's getting escaped twice, once here and another time some other place.  

```
 - '
 - &027;
 - &amp; &027;
```

Then only getting decoded once:

```
 - &027;
```

**Comment by rumblefrog** [comment]
You can try to remove the modifier, but it's best to leave it there for security sakes. A non-pretty ban reason is better than a defaced website :P

**Comment by popey456963** [comment]
@RumbleFrog An excellent point on the current version, I changed it to `RDMing` instead of `RDM'ing`.  Been combing through the code for a bit, removed that statement on a debug version of SB++ & it still comes back to me as the correct (and safe) `&#27;` which displays as `'`.

My confusion is where it's getting encoded again, can't seem to spot it.

**Comment by RumbleFrog** [comment]
It's caused by this: https://github.com/sbpp/sourcebans-pp/blob/c30db93780ae023eb74b1ec099818fb5646f50f3/web/includes/system-functions.php#L703-L706

It escapes it when you input it, then escapes it again on fetch.

**Comment by rumblefrog** [comment]
It escapes it when you input it, then escapes it again on fetch.

Here's my trace

https://github.com/sbpp/sourcebans-pp/blob/002e358be69ce699662ea805a4afc9c77ffd06b8/web/index.php#L35

https://github.com/sbpp/sourcebans-pp/blob/21a754806c63817895642fa90d325b0a3afa5eed/web/includes/page-builder.php#L39

https://github.com/sbpp/sourcebans-pp/blob/21a754806c63817895642fa90d325b0a3afa5eed/web/includes/admin.php#L271

https://github.com/sbpp/sourcebans-pp/blob/fbb2ccc76a0441f8f25ea939f148949a962ece34/web/pages/admin.bans.php#L121

https://github.com/sbpp/sourcebans-pp/blob/d0ee22ce6ed1c4a9b051079d9709a28612207235/web/themes/sb_default/page_admin_bans_add.tpl#L184

https://github.com/sbpp/sourcebans-pp/blob/fbb2ccc76a0441f8f25ea939f148949a962ece34/web/pages/admin.bans.php#L776

https://github.com/sbpp/sourcebans-pp/blob/fbb2ccc76a0441f8f25ea939f148949a962ece34/web/pages/admin.bans.php#L825

https://github.com/sbpp/sourcebans-pp/blob/ad62c907fb720b41c0c8578ee34de45ae289466f/web/includes/sb-callback.php#L49

https://github.com/sbpp/sourcebans-pp/blob/ad62c907fb720b41c0c8578ee34de45ae289466f/web/includes/sb-callback.php#L1637

https://github.com/sbpp/sourcebans-pp/blob/ad62c907fb720b41c0c8578ee34de45ae289466f/web/includes/sb-callback.php#L1695

https://github.com/sbpp/sourcebans-pp/blob/c30db93780ae023eb74b1ec099818fb5646f50f3/web/includes/system-functions.php#L703-L706
