### ISSUE TITLE
"Admin Deleted" on "Banned By"

### ISSUE THREAD

**Issue by Carvalh0XYZ** [sbpp/sourcebans-pp#343]
Hello everyone !

## Expected Behavior

So I have this issue where the row "Banned by" should display the name of the admin that banned the guy. 

## Current Behavior

Instead of showing who banned it just shows "Admin deleted"

## Possible Solution

All of this was introduced when I had to disable the admins support from Sourcebans plugin because it was always adding a "q" at the beggining of my admins.cfg file so it was always breaking all my players ranks etc...
`// Enable admin part of the plugin (1 = enabled, 0 = disabled)`
`"EnableAdmins"	"0"`

## Steps to Reproduce (for bugs)

1. Set EnableAdmins to 0

## Context

I'd like to trace who banned a player without having to deal with "sourcebans admin part of the plugin" overwriting admins.cfg... So maybe I'm just dumb and I can't config sourcebans to properly work with my admins.cfg...I have many ranks linked to "custom-chatcolors" that actually sourcebans can't manage. 

## Your Environment

* Version used: 1.6.2
* PHP and MySQL version: PHP 7.0.8
* Link to your project: [https://p4r4disi4c.xyz/bans/](https://p4r4disi4c.xyz/bans/)

Regards

**Comment by rumblefrog** [comment]
That's the intention really; you're disabling the admin feature entirely by setting that boolean.

**Comment by Carvalh0XYZ** [comment]
Yeah, I though that too...

What would be my best bet then ?

My admins config, hosts different users like with different groups as Owners, VIP, Admins etc...I should take the time to set up each of these groups on sourcebans GUI, + make an user account for each of the guys in my admins.cfg and set the group for each of them ?

Thanks for your help

**Comment by Groruk** [comment]
`Admin deleted` is the default message you could change it in the templates.

To display admin names you have to add the admins into SourceBans++

**Comment by rumblefrog** [comment]
To add on to this, if the `aid` is not inserted at ban time, it will show the default message, which in your case is due to the system being disabled. Unfortunately, SB++ cannot work around this as it's intended.
