### ISSUE TITLE
Login Broken?

### ISSUE THREAD

**Issue by Munzy** [sbpp/sourcebans-pp#346]
Login page isn't showing login prompt.

https://bans.tf2.gaming-servers.net/index.php?p=login

## Expected Behavior
It should be showing a login prompt.

## Current Behavior
It is showing no login prompt.

## Possible Solution
None found. 

## Steps to Reproduce (for bugs)
https://bans.tf2.gaming-servers.net/index.php?p=login

## Context
Can't login without using steam as a login.

**Comment by rumblefrog** [comment]
Uhm, empty issue?

**Comment by rumblefrog** [comment]
Can you go to your Sourceban++'s _settings table and make sure `config.enablesteamlogin` is set to `1`

**Comment by Munzy** [comment]
Thanks.
