### ISSUE TITLE
Freezes when refreshing admin list with sm_rehash - 1.6.2 (SERVER PART)

### ISSUE THREAD

**Issue by WeirdPhrog** [sbpp/sourcebans-pp#348]
My servers (2 css and 1 csgo) gets freezes every time when i refresh admin list with sm_rehash or sb_reloadadmins. With 1.4.11 or 1.5.4 - no lags.

I'm 100% sure that this problem has nothing to do with the web part, so I don't see any reason to write something else about my web part.

**Comment by rumblefrog** [comment]
So can you post about your server instead? How are you expecting us to fix something if we don't have any information?

**Comment by rustov** [comment]
I dont think that it will help you, but ok.

CS:GO server
Linux.
Metamod:Source 1.10.7-dev
SourceMod (1.8.0.6022) by AlliedModders LLC
CS Tools (1.8.0.6022) by AlliedModders LLC
SDK Tools (1.8.0.6022) by AlliedModders LLC
SDK Hooks (1.8.0.6022) by AlliedModders LLC
PTaH (P Tools and Hooks) (1.0.6) by Phoenix (‰7Феникс7‰)
SteamWorks Extension (1.2.1) by Kyle Sanderson
DHooks (2.1.1) by Dr!fter
TAU LIB (1.2) by Phoenix (‰7Феникс7‰)

 "Basic Info Triggers" (1.8.0.6020) by AlliedModders LLC
 "Knife choice CORE - Выбор ножа ЯДРО" (2.4.1) by Phoenix - Феникс
 "Knife choice INTERFASE MONUL - Выбор ножа МОДУЛЬ ИНТЕРФЕЙСА" (1.1) by Phoenix - Феникс
 "Admin Menu" (1.8.0.6020) by AlliedModders LLC
 "Basic Comm Control" (1.8.0.6017) by AlliedModders LLC
 "CS:GO A2S_Rules Hax" (0.0.7) by Dr!fter, KyleS
 "Admin all spec" (1.0.2) by Dr!fter
 "Basic Chat" (1.8.0.6020) by AlliedModders LLC
 "Token Auto Updater" (1.3.1) by ‰7Феникс7‰
 "Player Commands" (1.8.0.6020) by AlliedModders LLC
 "SMAC Rcon Locker" (0.8.6.4+ <Ultr@>) by http://vk.com/counterstrike_ultra
 "Dissolve" (1.0.0.2) by L. Duke
 "gameME Plugin" (4.7.2) by TTS Oetzel & Goerz GmbH
 "SourceBans++: SourceComms" (1.6.2) by Alex, SourceBans++ Dev Team
 "SourceBans++: Bans Checker" (1.6.2) by psychonic, Ca$h Munny, SourceBans++ Dev Team
 "[CS:GO] SpawnTools7" (1.0.1) by meng & IDDQD
 "Реклама" (1.4) by Pheonix (‰7Феникс7‰)
 "Client Preferences" (1.8.0.6020) by AlliedModders LLC
 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
 "BanId Fix" (0.5) by SM9();
 "SourceBans++: Main Plugin" (1.6.2) by SourceBans Development Team, SourceBans++ Dev Team
  "Anti-Flood" (1.8.0.6020) by AlliedModders LLC
  "Weapon Skin" (2.3.5PRE REV 3 PRIVATE) by Phoenix (‰7Феникс7‰)
  "Fun Commands" (1.8.0.6020) by AlliedModders LLC
  "Fun Votes" (1.8.0.6020) by AlliedModders LLC
  "C4Timer CSGO" (1.5.0) by dalto, Panda
  "SourceBans: Admin Config Loader" (1.6.2) by AlliedModders LLC, Sarabveer(VEER)
  "Nextmap" (1.8.0.5985) by AlliedModders LLC
  "Admin File Reader" (1.8.0.6020) by AlliedModders LLC
  "Weapon Restrict" (3.1.7) by Dr!fter
  "Basic Votes" (1.8.0.6020) by AlliedModders LLC
  "Reserved Slots" (1.8.0.6020) by AlliedModders LLC
  "Basic Commands" (1.8.0.6020) by AlliedModders LLC
  "[CSGO] Ammo Manager" (1.0) by inklesspen
  "id.smx"
  "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team
  "Resetscore+" (1.5.1) by AlmazON
  "AFK Manager" (4.1.5) by Rothgar

**Comment by WeirdPhrog** [comment]
Only what I now its no lags with 1.4.11 and 1.5.4. I can show it on my cs:s server if you need

**Comment by WeirdPhrog** [comment]
I did my tests only with the main part of plugin - sbpp_main.smx or sourcebans.smx for older versions. Without other modules.

**Comment by RumbleFrog** [comment]
Can I get a plugin profiler dump?

**Comment by WeirdPhrog** [comment]
What is it? Sorry but i dont understand what you mean

**Comment by RumbleFrog** [comment]
https://wiki.alliedmods.net/SourceMod_Profiler

**Comment by rumblefrog** [comment]
Are you using SQL or flat-file, if SQL, is it local or non-local?

**Comment by WeirdPhrog** [comment]
SQL, non-local. Mysql on web server

**Comment by WeirdPhrog** [comment]
I think maybe your plugin makes request to the database not asynchronously? Or something like that?

**Comment by WeirdPhrog** [comment]
Maybe current version of SB 1.6.2 wait for answer from web server after request for admin rehashing?

**Comment by rumblefrog** [comment]
It's threaded, there's no reason for it to wait.

**Comment by rumblefrog** [comment]
Also, `sb_reloadadmins` is not a valid command

**Comment by WeirdPhrog** [comment]
sm_reloadadmins, sorry

**Comment by rumblefrog** [comment]
Are you using `admin-sql-prefetch.smx`?

**Comment by WeirdPhrog** [comment]
No.

**Comment by rumblefrog** [comment]
Is there anything within the error file?

**Comment by WeirdPhrog** [comment]
No, 0 errors

**Comment by rumblefrog** [comment]
I'm going to definitely need a profile. 

`sm prof start`

*run the rehash/reload command*

`sm prof stop`

`sm prof dump`

And paste back the content

**Comment by WeirdPhrog** [comment]
[dump.txt](https://github.com/sbpp/sourcebans-pp/files/1247456/dump.txt)

**Comment by Groruk** [comment]
How many admins do you have in your SourceBans database?

**Comment by WeirdPhrog** [comment]
27

**Comment by rumblefrog** [comment]
It's def not Sourceban++'s problem:

`basecommands.smx::Command_ReloadAdmins           3       0.003    1208.057   6.92       0.233   0.00       1.172     402.686       0.078     403.002`

**Comment by rumblefrog** [comment]
If you switch to flat file, does the problem persist?

**Comment by WeirdPhrog** [comment]
How to switch to flat file? I'm only used mysql for all my life, sorry :)

**Comment by rumblefrog** [comment]
Unload all of sourcebans++ and see if the problem is still there first.

**Comment by WeirdPhrog** [comment]
Checked, there is no problem. I tested without sb 4-5 hr ago. Without sb everything is fine. It's issue related to sb 1.6.2 main plugin, its 100.0%, I think

**Comment by WeirdPhrog** [comment]
I told you before, there is no problem with older version of SB plugin!

**Comment by Groruk** [comment]
@rustov 
Try this version: https://gist.github.com/Groruk/caadc2dbe46abbf941ace5f91e5bd0aa
Compiled: http://testsite1.gg-dev.org/sbpp_main.smx
And test if the lag is still there.

@RumbleFrog 
SourceBans is intercepting ReloadAdmin via [OnRebuildAdminCache in sbpp_main](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_main.sp#L346)

**Comment by rumblefrog** [comment]
@Groruk But that is threaded 🤔

**Comment by WeirdPhrog** [comment]
Yes, with the new version everything is good! No freezes anymore! Big thanks!

**Comment by rumblefrog** [comment]
@Groruk Wait, `SQL_SetCharset(DB, "utf8");` is not threaded?

**Comment by Groruk** [comment]
Looks like it. Maybe only `SQL_TConnect` and `SQL_TQuery` are threaded.

**Comment by rumblefrog** [comment]
Hmm, I guess you do learn something new every day.

**Comment by WeirdPhrog** [comment]
Can you tell me please what exactly you changed?

**Comment by WeirdPhrog** [comment]
In source code.

**Comment by WeirdPhrog** [comment]
decl String:query[1024];
	SQL_SetCharset(DB, "utf8");
to
	decl String:query[1024];
	FormatEx(query, sizeof(query), "SET NAMES \"UTF8\"");
        SQL_TQuery(DB, ErrorCheckCallback, query);

it's all?

**Comment by rumblefrog** [comment]
Yup, cause apparently `SQL_SetCharset(DB, "utf8");` isn't threaded, and I skipped right over that thinking it was threaded.
