### ISSUE TITLE
sbpp_sleuth option to exclude old bans from lookup

### ISSUE THREAD

**Issue by koteq** [sbpp/sourcebans-pp#352]
### Expected Behavior
The plugin should give an option to exclude old bans in order to decrease false positives.

### Current Behavior
Some players getting false positive bans. Seems their ISP utilizes dynamic IP pools.

### Possible Solution
Introduce new convar and touch [this SQL query](https://github.com/sbpp/sourcebans-pp/blob/68e49ab2f00c65c61f8188e246723a2c418f80de/game/addons/sourcemod/scripting/sbpp_sleuth.sp#L157).

### Context
I do maintain sourcebans instance with 10k bans (4.7k permabans) with bans from early 2013.

**Comment by Alicebnd** [comment]
Yes, this function is very necessary.

**Comment by rumblefrog** [comment]
Honestly, it's called permanent ban, not sure what you're expecting. If you wish to expire it due to reliability concern, simply not ban by IP or just set the time for X years and it'll auto exclude.

**Comment by rumblefrog** [comment]
Here's a quick version I made implementing that. However, it's not tested, you're warned: https://gist.github.com/RumbleFrog/d893be81dd33808bfaa6934c3dbd8c63

It contains two additional ConVars

```
sm_sleuth_excludeold | 0 - Inactivated, 1 - Allow old bans to be excluded from ban check
sm_sleuth_excludetime | Amount of time in seconds to allow old bans to be excluded from ban check
```

**Comment by Alicebnd** [comment]
Big thx.
In my opinion this works.
How to translate this into a release?

**Comment by rumblefrog** [comment]
It's kinda redundant for a release, as I said, you can easily solve this problem by setting ban time to `x` years or not IP ban at all. Check with @Groruk

**Comment by koteq** [comment]
> you can easily solve this problem by setting ban time

I don't like the idea of giving amnesty to hackers.


> not IP ban at all

All the bans are done by SteamID but SB track IP even in that case.

**Comment by rumblefrog** [comment]
Sleuth tracks IP only if the ban is still active, and I'm not sure why you wouldn't use the `x` years, you basically give them amnesty by expiring old bans.

**Comment by Alicebnd** [comment]
>  kinda redundant for a release, as I said, you can easily solve this problem by setting ban time to x years or not IP ban at all. Check with @Groruk 

Ban players by steamid and ip have one fixed parameter - steamid and one dinamic parameter - ip (if banned player have dinamic ip).
In due course under the ban on this ip can get an honest player.
Therefore, sbpp_sleuth must be able to ignore the banned ip depending on the time.
The more time passes since the ban, the more likely join to server a good player with a banned ip.

**Comment by Alicebnd** [comment]
I have a history of bans from 2013.
Do you think how many good players are banned based on the banned dynamic ip's I have during five years?
I do not want to give amnesty to cheaters based on a fixed steamid.
It is necessary to give an amnesty only on the prescription of a ban on a variable ip, which eventually becomes erroneous.
Make edits you need to include in the release.

**Comment by rumblefrog** [comment]
@Groruk 

> Here's a quick version I made implementing that. However, it's not tested, you're warned: https://gist.github.com/RumbleFrog/d893be81dd33808bfaa6934c3dbd8c63
It contains two additional ConVars
```
sm_sleuth_excludeold | 0 - Inactivated, 1 - Allow old bans to be excluded from ban check
sm_sleuth_excludetime | Amount of time in seconds to allow old bans to be excluded from ban check
```


LMK if this works.

**Comment by Alicebnd** [comment]
Its work for me.

**Comment by rumblefrog** [comment]
Created a pull #356, If OP could test it, that'd be great.
