### ISSUE TITLE
Import bans problem

### ISSUE THREAD

**Issue by speedvoltage** [sbpp/sourcebans-pp#355]
## Expected Behavior
When importing banned_user.cfg, the bans should be imported without errors.

## Current Behavior
The page refreshes and nothing happens.
https://imgur.com/a/6G0Qu

## Steps to Reproduce (for bugs)
A fresh installation of Sourcebans++ 1.6.2

## Context
I was trying to import bans from banned_user.cfg

## Your Environment

* Version used: 1.6.2 
* PHP and MySQL version: 5.6.31 / 10.0.31-MariaDB-cll-lve
* Operating System and version: Windows 10 64-Bit
* Link to your project: https://www.kickassfighters.com/sourcebans/

**Comment by rumblefrog** [comment]
Can you attach PHP log?

**Comment by speedvoltage** [comment]
Thanks for the answer. What file am I supposed to be looking for? Where? Sorry if it sounds like an idiot question because I am not quite sure.

**Comment by speedvoltage** [comment]
I just wanted to bring an update. A fresh installation of Sourcebans makes that bug happen, but upgrading from 1.4.11 does not cause problems anymore.

Also, my sourcebans page was moved to sourcebans.kickassfighters.com

**Comment by rumblefrog** [comment]
Just attached the PHP log when you tried to import and you can't directly port 1.4.11 to 1.6.2 since there were changes made to the database, hence why the upgrade works, they modify the existing data structure.

**Comment by speedvoltage** [comment]
Unfortunately, I could not find that log in question and I'm pretty sure I looked at the correct place in the web host.

**Comment by rumblefrog** [comment]
Going to close this, as no additional information is provided for debugging.
