### ISSUE TITLE
Founda little unimportant Bug

### ISSUE THREAD

**Issue by DJPlaya** [sbpp/sourcebans-pp#357]
## Expected Behavior
A clean and good looking Logfile

## Current Behavior
Exception reported: Handle 44950837 is invalid (error 1)
Blaming: SourceBans\sbpp_comms.smx
Call stack trace:
[0] CloseHandle
[1] Line 2836, sbpp_comms.sp::CloseMuteExpireTimer
[2] Line 263, sbpp_comms.sp::OnClientDisconnect

## Possible Solution
Maybe add an if check
`if(Handle == INVALID_HANDLE)`
    return;

## Steps to Reproduce (for bugs)
1. Run a current Sourcemod Version
2. Disconnect from server
3. Profit!

## Context
How has this issue affected you?
-It affects my Autism, i dont like it when the Logs look dirty

-RL? I thought were in Cyberspace here

## Your Environment
* Version used:
* PHP and MySQL version: 5.6
* Operating System and version: Win 7 64 Hyper Server Edition (this dosent even makes sense, srcds runs everywhere the same way)
* Link to your project: öhhh
* Link to gist with phpinfo() output: the whoat?

**Comment by CrazyHackGUT** [comment]
```
Maybe add an if check
if(Handle == INVALID_HANDLE)
return;
```
This is not fix this problem. I'll make a PR for this bug...

**Comment by DJPlaya** [comment]
Nice
