### ISSUE TITLE
Gmod module ulx

### ISSUE THREAD

**Issue by matiasg90** [sbpp/sourcebans-pp#361]
Is the version 1.5.4.3 module updated correctly for version 1.6.3?
https://github.com/sbpp/sourcebans-pp/releases/tag/1.5.4.3

Ulx recently had an update and changed the format of how the ban was saved
https://github.com/TeamUlysses/ulib/commit/0b4cdd0acbf86597446dee4576e7ece9aea15999#diff-f8dbbbdb3b80b4f170a8272978f579eb

**Comment by rumblefrog** [comment]
No, it's not
