### ISSUE TITLE
[Request] Enhance sourcemod interface

### ISSUE THREAD

**Issue by Arkarr** [sbpp/sourcebans-pp#369]
I just read sourcebans.inc ... It's almost empty :( !
I suggest that we could add some more stocks such as "AddAdmin" wich would add an admin to the current server, as well as "RemoveAdmin" wich will do the opposite as AddAdmin.

## Expected Behavior
Simply add new stocks. As I can't find a proper way to add admins in sourceban++ without having to do query by myself, wich sucks.

## Current Behavior
Well, there is nothing like that, yet.

## Possible Solution
Simply add two some functions to the file.

## Context
That would really increase the number of modules for SourceBans++, at least, that's what I believe.

**Comment by rumblefrog** [comment]
The feasibility of such native is almost negligible. You should not rely on calling natives to add admins.

**Comment by Arkarr** [comment]
Oh okay.. I'll do my own plugin for that then. Can anybody tell/give me of an admin row in the sourceban database ?

**Comment by Groruk** [comment]
https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/install/includes/struc.sql#L3-L18

**Comment by Arkarr** [comment]
Thanks, but, what's extraflag nor srv_flags, are those sourcemod flags ?

**Comment by rumblefrog** [comment]
Yes, those are Sourcemod letter flags.
