### ISSUE TITLE
Add the ability to choose rights per servers

### ISSUE THREAD

**Issue by IzuiSP** [sbpp/sourcebans-pp#370]
Hey,

Is it possible to add the ability to choose rights per servers pls ? Like a special feature.
If I have 4 servers, I should be able to choose which rights will be enable on which server.
It would be really appreciated.

Best regards.

**Comment by Mr-Deej** [comment]
OK with the most recent pre-release `1.6.3 Pre-Release` you can choose what server a person can have "rights"(permissions) to here is a link to a print screen that can show you what it looks like  [Image](http://prntscr.com/iik8fa)

**Comment by CrazyHackGUT** [comment]
@Mr-Deej he says about **different permissions on all servers**.

**Comment by Mr-Deej** [comment]
Then he could make separate groups for separate servers

**Comment by IzuiSP** [comment]
Clients can't get multiple groups..

**Comment by Mr-Deej** [comment]
Like S1Mod or S2Mod he wanted per server so the user would have the s2 mod he would have access to s1 and the group would only be used on the 2nd server. If he chose to allow them access on both servers then the person would have s2mod on 1st server and 2nd server

**Comment by IzuiSP** [comment]
ehh too complicated.
I have 4 servers.
I gave admin rights to the S1 (Server1)
btw if I want gave him only VIP rights on S2 I can't. I'm forced to share his admin rights on both servers

**Comment by IzuiSP** [comment]
Would be useful to be able to define which rights the client will get on which servers
Different rights for different servers.
Dev a thing like allow client to get multiple groups its the best way
On creating groups, you should be able to choose on which server the group will be applicated

**Comment by Mr-Deej** [comment]
Or define a custom group with sourxe mod and just add them to that one per server and use sourcevans for moderator etc
