### ISSUE TITLE
Username:Password function

### ISSUE THREAD

**Issue by nco795** [sbpp/sourcebans-pp#371]
## Expected Behavior
I updated to Sourcebans 1.6.2, an there is no Username:Password login.
There is only the Steamlogin that doesnt save the logged in session.
Not all of my admins are logged in with thier steamaccount to the Browser.

Have a look: http://bans.burgerbude.net/

## Possible Solution
Just re add the Username:Password function.

## Steps to Reproduce (for bugs)
Install the 1.6.2

## Your Environment
I need the Username:Password login for my admins not every guy is logged in with Steamaccount.

**Comment by Groruk** [comment]
![login](https://user-images.githubusercontent.com/5796460/33230651-cf99d032-d1e7-11e7-98b7-0ad115158f06.jpg)
enable that.

**Comment by nco795** [comment]
Oh okay haha sorry for that ;D
You can close thanks for the fast answer^^

**Comment by rumblefrog** [comment]
It'd be really appreciative if you made any attempt at looking at one of our help docs: https://sbpp.github.io/faq/
