### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by dzinks2009** [sbpp/sourcebans-pp#372]
Hello, will the sourcebans be updated for PHP version 7.2? Most of the functions are deprecated and I'm sad.

For ex.
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /var/www/html/bans/includes/adodb/adodb.inc.php on line 1152

**Comment by Groruk** [comment]
SourceBans++ is developed on the latest stable version of PHP (in this case 7.1.12). Please switch to this version if you want SourceBans++ to function correctly.
