### ISSUE TITLE
Too short session time

### ISSUE THREAD

**Issue by gonkong** [sbpp/sourcebans-pp#374]
**Expected Behavior**

Session storage should allow me to log in once and remain logged in for as long as the session is valid (7 days)

**Current Behavior**
When closing the chrome the session is forgotten about 3-5 hours and a new login is required

**Possible Solution**
investigate why the session is not persisted and make sure it is in the next release.

**Steps to Reproduce (for bugs)**
Log in to SB (classic login)
close the browser completely
open the browser once again and navigate to the installation
the session is lost and a new login is required

Context
N/A

**Your Environment**
Version used: 1.6.3-git577
PHP and MySQL version: PHP Version 5.6.30-0, Apache/2.4.10 (Debian)
Operating System and version: Debian 8 64 bit
Link to your project: ***
Link to gist with phpinfo() output: 
https://pastebin.com/M459Yk4i

**Comment by rumblefrog** [comment]
Let's use the issue template. Such little context, you can't expect us to help you.

**Comment by gonkong** [comment]
**Expected Behavior**

Session storage should allow me to log in once and remain logged in for as long as the session is valid (7 days)

**Current Behavior**
When closing the chrome the session is forgotten about 3-5 hours and a new login is required

**Possible Solution**
investigate why the session is not persisted and make sure it is in the next release.

**Steps to Reproduce (for bugs)**
Log in to SB (classic login)
close the browser completely
open the browser once again and navigate to the installation
the session is lost and a new login is required

Context
N/A

**Your Environment**
Version used: 1.6.3-git577
PHP and MySQL version: PHP Version 5.6.30-0, Apache/2.4.10 (Debian)
Operating System and version: Debian 8 64 bit
Link to your project: http://bans.mfsproject.ru
Link to gist with phpinfo() output: 
https://pastebin.com/M459Yk4i

**Comment by iXyles** [comment]
I can tell we got the same issues in our SB, something broke in the 1.6.2 patch, tried the 1.6.3 also but no difference.

**Comment by rumblefrog** [comment]
@groruk

**Comment by Groruk** [comment]
Can you try and setup a separate SourceBans++ environment with the newest [dev version](https://github.com/sbpp/sourcebans-pp/archive/v1.x.zip) and see if the session time has been fixed?
The newest dev version will have some bugs which makes it currently not suitable for production use, but I want to see if the new SessionManager has fixed the old problem.

**Comment by geominorai** [comment]
Nope.  It still logs me out within 5 minutes of the initial login despite continuously clicking through the site.

**Comment by Groruk** [comment]
Can you add
```PHP
var_dump($_SESSION);
var_dump($_COOKIE);
```
to the bottom of the [index.php](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/index.php)
and link your installation together with a `phpinfo()` output page, please?

**Comment by geominorai** [comment]
https://bans.jumpacademy.tf/test/web/
https://bans.jumpacademy.tf/test/web/phpinfo.php

**Comment by Groruk** [comment]
Seems like this session problem correlates with apache 
(almost all people who are having these problems are running apaches), 
guess I have to conduct further research into this over the next days.

**Comment by Groruk** [comment]
So after some testing with Apache (and a whole ton of different configs), I couldn't replicate your issue (it seems that your Apache installation has problems with [setcookie()](http://php.net/manual/en/function.setcookie.php) and [session_set_cookie_params()](http://php.net/manual/en/function.session-set-cookie-params.php) and to be more specific it has issue with setting parameters like `http_only`, `expires`, `path` and `secure`)

I have seen, that your Apache is self-compiled and uses some old APIs (dated to 2005), so I would suggest to use a precompiled Apache (via a package manager or even try out nginx) and see if that fixes issues.

I will close this issue, so if you encounter these issues on nginx or a prebuild apache (or you find the exact root of the problem), feel free to open a new issue specifically for this issue.

**Comment by CosmicHikari** [comment]
@Groruk I'm still having this issue, clean install of the latest apache. #553 appears to be a bug in Chrome and not apache, as switching to Firefox makes the issue nullified.
