### ISSUE TITLE
PHP 5.X versions 

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#376]
I use SourceBans in conjunction with HLStatsX: CE, HLStatsX: CE runs only up to version 5.6 of PHP.

Would it be possible to let SouceBans work from these versions onwards as well?

Currently if I put any version below 7.X it gives error.

I tested the SourceBans with PHP version 5.6 and the following error:
> AJAX Call Failed!
>  Error: the XML response that was returned from the server is invalid. Received: 
> Warning: mysqli_real_connect(): Headers and client library minor version mismatch. Headers:50173 Library:50312 in /home/u269629430/public_html/sourcebans/includes/adodb/drivers/adodb-mysqli.inc.php on line 124
> #3 - ZK Servidores [ ARENA X1 ]17/12]]>]]>am_multimap2$('dialog-control').setStyle('display', 'block');$('dialog-placement').setStyle('display', 'none');

Thanks in advance!!!

**Comment by rumblefrog** [comment]
You have to downgrade your MySQL client binaries, as it was compiled for v7
