### ISSUE TITLE
How to change Blocks List ??

### ISSUE THREAD

**Issue by Beaast-exe** [sbpp/sourcebans-pp#377]
How can i change "Block Comms" Reasons list ??
That: http://prntscr.com/hsvpty
## Expected Behavior

My Servers are PORTUGUESE and i want to change that to portuguese because some of my admins dont speak english and i have to translate it to they.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* PHP and MySQL version: 
--- PHP 7.0.22-0
--- mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper
* Operating System and version:
--- Ubuntu 64 Bits 16.04 (Digitalocean.com Machine)
* Link to your project:
--- http://bananasonfire.tk/bans/
* Link to gist with phpinfo() output:

**Comment by CrazyHackGUT** [comment]
Here:
https://github.com/sbpp/sourcebans-pp/blob/39301095a13dea67fab939e5fb69ef6c3501daba/web/themes/default/page_admin_comms_add.tpl#L69-L75
Also you can add own reasons.
