### ISSUE TITLE
 strpos(): Offset not contained in string in

### ISSUE THREAD

**Issue by Infin48** [sbpp/sourcebans-pp#380]
## Context
I Install Sourcebans to my website and when i try "Sign to through STEAM" show error:
Warning: strpos(): Offset not contained in string in /data/web/virtuals/137665/virtual/www/subdom/bans/includes/openid.php on line 86

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/137665/virtual/www/subdom/bans/includes/openid.php:86) in /data/web/virtuals/137665/virtual/www/subdom/bans/steamopenid.php on line 43

## Your Environment
* Version used: 1.6.2
* PHP and MySQL version: PHP: 7 MYSQL: 5.6.12
* Operating System and version: Linux
* Link to your project: http://www.bans.spacegaming.cz/
* Link to gist with phpinfo() output: http://www.bans.spacegaming.cz/steamopenid.php

Thanks, 
Infin.

**Comment by Groruk** [comment]
Have you correctly set `SB_WP_URL` in your `config.php` to the root of your SourceBans++ installation ?
