### ISSUE TITLE
Update steam

### ISSUE THREAD

**Issue by Fonto12** [sbpp/sourcebans-pp#381]
The servers have updated their steam but your app hasnt done it yet, please do this as soon as possible.

## Expected Behavior
 Working server with players playing in it and the manager  giving information about the server 

## Current Behavior
 Players can not join the servers and they appear as an error connecting in the sourcebans manager

## Possible Solution
 Seam update for Sourcebans

## Steps to Reproduce (for bugs)
 http://republicgaming.gaming.bz/saucybans/index.php

1.
2.
3.
4.

## Context
 Me and the rest of the players can no join our servers

## Your Environment

* Version used:  1.5.4.7
* PHP and MySQL version:
* Operating System and version:
* Link to your project:
* Link to gist with phpinfo() output:

**Comment by Groruk** [comment]
Firstly version 1.5.4.7 is completely outdated.
Secondly what do you want to tell us? Where exactly is your problem?

**Comment by rumblefrog** [comment]
Issue at its finest, entire template is basically empty

**Comment by rumblefrog** [comment]
# Close This Issue

OP is inactive and it's invalid :P
