### ISSUE TITLE
Replace Functions Deprecated By PHP 7.2

### ISSUE THREAD

**Issue by OmarAssadi** [sbpp/sourcebans-pp#382]
## Expected Behavior
SourceBans, ideally, should not be using any deprecated functions provided by PHP.

## Current Behavior
When the Smarty compiler is called, you'll get deprecation notices for "create_function()" and "each()" on lines 269 and 559 of Smarty_Compiler.class.php, respectively.

## Possible Solution
A. Update Smarty to the latest version of Smarty 2

B. Patch the deprecated functions with the code provided here: https://github.com/smarty-php/smarty/commit/4ab9757b492f08a38f68123a6e7c1df7110bbc49

## Steps to Reproduce (for bugs)
1. Install PHP 7.2
2. Install SourceBans++
3. Visit homepage

## Your Environment
* Version used: current master - a80f906.
* PHP and MySQL version: PHP 7.2, MariaDB 10.2
* Operating System and version: Debian 9
* Link to your project: https://blacktea.su/sourcebans - not relevant, though.
* Link to gist with phpinfo() output: https://gist.github.com/54/cd5136f3a5824312f10659a733849671

**Comment by rumblefrog** [comment]
Ideally, that's what we want, but most of the users are on PHP 5.X still.

**Comment by CrazyHackGUT** [comment]
@RumbleFrog this changes will not break compatibility with PHP 5.X.

**Comment by Groruk** [comment]
Problem is that not only smarty contains deprecated functions, but also ADODB and probably also Xajax. So it will take more effort than that to make SourceBans++ ready for PHP 7.2

**Comment by OmarAssadi** [comment]
@Groruk Yeah, I was looking yesterday. It shouldn't be a massive job, though. It looks like the majority are each() calls in adodb.

**Comment by rumblefrog** [comment]
@CrazyHackGUT I know it won't, but most users are on PHP 5.X, it wouldn't make sense to focus on something when only around 5% of the users experience this issue.

**Comment by jarromie** [comment]
5% of users is still an incredibly large amount of users

**Comment by rumblefrog** [comment]
@whocodes But it would make sense to focus on something 90% of the people are experiencing right?

**Comment by filipnyquist** [comment]
No, it would make sense to follow the PHP schedule of updates. ;)

**Comment by caxanga334** [comment]
https://secure.php.net/supported-versions.php
PHP 5.X will reach EOL in 11 months.
