### ISSUE TITLE
BUG Plugins Servers Arena X1 CSGO

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#385]
My Arena X1 - CSGO servers are showing some errors in the plugins:- **sbpp_comms.smx**
- **sourcebans.smx**
```
L 01/13/2018 - 03:57:13: [SM] Blaming: sbpp_comms.smx
L 01/13/2018 - 03:57:13: [SM] Call stack trace:
L 01/13/2018 - 03:57:13: [SM]   [0] CreateNative
L 01/13/2018 - 03:57:13: [SM]   [1] Line 169, sbpp_comms.sp::AskPluginLoad2
L 01/13/2018 - 03:57:13: [SM] Failed to load plugin "sbpp_comms.smx": unexpected error 23 in AskPluginLoad callback.
L 01/13/2018 - 03:57:13: [SM] Exception reported: Fatal error creating dynamic native!
L 01/13/2018 - 03:57:13: [SM] Blaming: sourcebans.smx
L 01/13/2018 - 03:57:13: [SM] Call stack trace:
L 01/13/2018 - 03:57:13: [SM]   [0] CreateNative
L 01/13/2018 - 03:57:13: [SM]   [1] Line 148, sourcebans.sp::AskPluginLoad2
L 01/13/2018 - 03:57:13: [SM] Failed to load plugin "sourcebans.smx": unexpected error 23 in AskPluginLoad callback.
```
What could it be? Would it be correct?

NOTE: Even with these errors, the bans on the x1 arena servers work standard, show the bans and any block in the players in the site, but that is the error in the console of the Game Panel.

**Comment by Groruk** [comment]
> L 01/13/2018 - 03:57:13: [SM] Blaming: sourcebans.smx

with 1.6 all plugins got renamed, so you have to manually remove the old versions:
- `SourceSleuth.smx`
- `sb_admcfg.smx`
- `sbchecker.smx`
- `sourcebans.smx`
- `sourcecomms.smx`

**Comment by crashzk** [comment]
Thank you...

**Comment by Bara** [comment]
How about a stock like this old function https://github.com/GameConnect/sourcebansv1/blob/master/game_upload/addons/sourcemod/scripting/sourcebans.sp#L253-L267 ? Prevent issues like this one.
