### ISSUE TITLE
BUG Ban Duplicate Account

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#386]
I am using SourceBans on the CSGO server.

It's working properly, I'm just having problem in duplicate account banishes.

It happens like this, if I apply a temporary ban on some player and it tries to connect with another account instead of raising the ban only it simply takes permanent ban straight.

Example, apply 2 hour ban on player "Zord" if he enters another account this ban should fold, turn 4 hours only instead ban zero occurs.

What could it be, would it be some BUG?

How can I fix it?

**SouceBans version:  Version 1.6.2
Link SourceBans: https://zkservidores.com/sourcebans
A player Steam with example, with duplicate account ban: [STEAM_1:1:212683342](https://zkservidores.com/sourcebans/index.php?p=banlist&searchText=STEAM_1%3A1%3A212683342&Submit=Search)**

**Comment by rumblefrog** [comment]
This is intended feature I believe.

**Comment by crashzk** [comment]
I made some changes to the SourceBans config and apparently it worked now.

Thank you!
