### ISSUE TITLE
Bugs in the nick with characters

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#390]
I would like to know if I would have any solution for the following BUG.

When players with characters are banned from the servers it shows in WebInterface the nick of them bugged.

Here's an example image:
https://image.prntscr.com/image/k6FWs2o7Sv_bU3lLEtKMNQ.png

* Version used: Version 1.6.2
* https://www.zkservidores.com/sourcebans/

**Comment by CrazyHackGUT** [comment]
Database encoding is UTF-8?

**Comment by crashzk** [comment]
No...

utf8mb4_unicode_ci

@CrazyHackGUT

**Comment by CrazyHackGUT** [comment]
Check connection and tables encoding.

**Comment by crashzk** [comment]
I checked and made the changes back in all the tables for the encoding **utf8mb4_unicode_ci**.

I'll be checking and return with the results!

**Comment by crashzk** [comment]
I made the changes in the tables again for the **utf8mb4_unicode_ci encoding**, only though some buga characters.

@CrazyHackGUT
