### ISSUE TITLE
Tons of spamming warnings

### ISSUE THREAD

**Issue by lugui1998** [sbpp/sourcebans-pp#393]
I don't know what is causing it, probably different reaseons, I cant describe it better, here is a screenshot: http://prntscr.com/ia0jsd

It happened just after I updated to 1.6.2(I overwritten all the files ecept the config, and oppened the updater directory on my browser)
After that, I deleted the updaters and install directory and just openned the sourcebans home page.

Sourcebans: 1.6.2.
PHP: 7.2
Database: MariaDB 10.1.30-MariaDB-1~xenial
Ubuntu 16.04
https://lugui.in/sourcebans/
https://lugui.in/info.php

**Comment by rumblefrog** [comment]
7.2 Smarty deprecation warnings, upgrade to 1.6.3 pre-release

**Comment by Groruk** [comment]
https://github.com/sbpp/sourcebans-pp/releases/tag/1.6.3 this version is compatible with PHP 7.2

**Comment by lugui1998** [comment]
Thankyou
