### ISSUE TITLE
Sourcebans-pp 1.6.2 and Donation Control

### ISSUE THREAD

**Issue by m1000rr** [sbpp/sourcebans-pp#396]
I run into issues with [Donation-Control](https://bitbucket.org/brewskii187/donations-control) after upgrading from sb++ 1.5.4.7 to sb++1.6.2 . What happen is I can't login into donations admin panel anymore. I am quessing this is somehow related to new salt function. Can anyone give me a quide how to sort out this problem?

**Comment by Groruk** [comment]
[Donation-Control++](https://github.com/sbpp/donations-control-pp) just gonna leave this here.

**Comment by m1000rr** [comment]
@Groruk Good point. I saw this one here recently. Just want to know if upgrading to it is straight forward or it needs to be installed from scratch? Don't want to mess up with my current setup.

**Comment by Groruk** [comment]
Since there are no database changes in the current version of Donation-Control++ it's just a case of replacing existing Donation-Control files with the ones of Donation-Control++
