### ISSUE TITLE
Multiple bans, without adding a new one every time

### ISSUE THREAD

**Issue by 5H4D0W5T4LK3R** [sbpp/sourcebans-pp#400]
Hi

Is there a way, where you can ban someone which has multiple IP's without having to make a new entry for every single individual IP.

**Comment by rumblefrog** [comment]
Ban them by their SteamID?

**Comment by 5H4D0W5T4LK3R** [comment]
We already banned 4 of his accounts, keeps on making a new ones and come back. If that's the only way, thanks then :>

**Comment by rumblefrog** [comment]
I mean, another option is to block their region, using my [CIDR Blocker](https://forums.alliedmods.net/showthread.php?t=300291). Not recommended though.

**Comment by Bara** [comment]
or https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_sleuth.sp if he has the same ip.
