### ISSUE TITLE
Lost your password

### ISSUE THREAD

**Issue by ByKyTa** [sbpp/sourcebans-pp#401]
Error: the XML response that was returned from the server is invalid. Received: 
Warning: mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set() in C:\xampp\htdocs\ban\includes\sb-callback.php on line 161
$('msg-red').setStyle('display', 'none');ShowBox('Check E-Mail', 'Please check your email inbox (and spam) for a link which will help you reset your password.', 'blue', '');

https://imgur.com/a/mTcT9

**Comment by Groruk** [comment]
`Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini` 
 Setup your mailserver correctly, not a problem with SourceBans++.
