### ISSUE TITLE
Can't connect server

### ISSUE THREAD

**Issue by ByKyTa** [sbpp/sourcebans-pp#403]
![image](https://user-images.githubusercontent.com/33537916/36637757-d726ac32-1a15-11e8-887d-ac7b812e3a47.png)
I don't know my SB can't connect

**Comment by Groruk** [comment]
Here is a starting point: https://sbpp.github.io/docs/debugging_connection/
If that doesn't help then you will have to give atleast some info to identify your problem.

**Comment by ByKyTa** [comment]
$serverip   = "ByKyTaGaming.Com";
$serverport = 27011;
$serverrcon = "*****"; 
Config that right ?

**Comment by ByKyTa** [comment]
[-] Error connecting #10061: No connection could be made because the target machine actively refused it.

**Comment by rumblefrog** [comment]
Does that domain's A record resolves properly to the server
