### ISSUE TITLE
ReportPlayer Ingame and as Function for Devs

### ISSUE THREAD

**Issue by DJPlaya** [sbpp/sourcebans-pp#407]
Hi,
basically some of my Plugins use the SB_ReportPlayer Function which is pretty usefull for as Example report advertising or spamming Clients.
Sadly i cannot upgrade to SB++ cause this feature seems to be missing from the Plugin side completely (still present on the Webinterface).
Could you maybe relive it?

Thx

**Comment by rumblefrog** [comment]
I'll see to this

**Comment by rumblefrog** [comment]
@DJPlaya If possible, could you compile and test `report-player-native` branch

**Comment by rumblefrog** [comment]
A `sbpp_report.sp` has also been created and takes advantage of the new native if you wish to test it that way
