### ISSUE TITLE
[SUGGESTIONS] Updates and correction of Bugs

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#409]
**SourceBans Version 1.6.2**

The Web Interface shows the date of the ban and other information for each ban on a player.

Could it also add beyond the date of banishment the time and up to the map that it was banned?

I found it to be two Bugs, the first would be to remember username and password, even marking it does not stay connected, I have to always enter the username and password to enter.

The other one would be the image of the site, on the main page it shows the logo of the sourcebans, but when I click on any other link, the image of the logo disappears, without image.

**Comment by rumblefrog** [comment]
Session problem is also indicated in #374 

Can you link me your SB installation for the logo part?

**Comment by crashzk** [comment]
The one to remember password, thank you, had not seen the topic.

Regarding the logo, I found the problem, it would be in the theme that I use myself, thank you!
