### ISSUE TITLE
Function create_function() is deprecated

### ISSUE THREAD

**Issue by Hypermortem** [sbpp/sourcebans-pp#410]
/includes/smarty/Smarty_Compiler.class.php on line 269

PHP Version I'm Running: 7.2

**Comment by sarabveer** [comment]
#399 @Goruk

**Comment by Groruk** [comment]
Use [this](https://github.com/sbpp/sourcebans-pp/archive/v1.x.zip) version, also those deprecation warnings show only ones when smarty is caching templates for the first time.

Also next time use the `issue template` please.
