### ISSUE TITLE
Deprecating SBBanPlayer is fine in forks, but then please change your library name

### ISSUE THREAD

**Issue by DarkDeviL** [sbpp/sourcebans-pp#414]
As the title says, in the commit on [March 30, 2017](https://github.com/sbpp/sourcebans-pp/commit/33cd5423f890b9a76608adf24608844bcacab6b7#diff-e17c8e284e1f27f4e8e43b4b1399bd56):

Native "SBBanPlayer" was marked as deprecated.

Based on a quick view, it still seems like both the old and new native does the exact same thing, and as such, the deprecation wasn't necessary at all.

Deprecating the "SBBanPlayer" means that there will a lot of issues with warnings for people trying to compile plugins build for the official SourceBans, and essentially removing it completely will lead to issues, as this fork still share the same library name "sourcebans".

As such, a possible solution is to change the sourcebans.inc include file name as well as the contents from "sourcebans" to something like "sourcebanspp" or "sourcebansplusplus"

All existing plugins would of course need to be re-written a little bit to support SourceBans++ then, but it is then possible to support both the official SourceBans, SourceBans++ (even if SBBanPlayer is removed completely), as well as other potential SourceBans "forks", when none of those have the same library name (and natives).

**Comment by rumblefrog** [comment]
@Groruk What you think?

**Comment by rumblefrog** [comment]
@DarkDeviL Does #415 suit the solution you are seeking?

**Comment by DarkDeviL** [comment]
Merging #415 will indeed fix this :)
