### ISSUE TITLE
Tip for the Web Interface

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#423]
Currently it shows the banned date of the player, server and other information.

It could put to show also the time of the ban, which map he took the ban and if possible also put the date and time of the unban also ..

**Comment by rumblefrog** [comment]
We'll have to wait until after the database change and see what we can do about this.

**Comment by Groruk** [comment]
>which map he took the ban

I don't really see a reason to add the map on which a person gets banned to the ban info.

>It could put to show also the time of the ban [...] also put the date and time of the unban also

Time of the ban and unban are already shown on SourceBans++. The time of a ban / unban is saved via a `unix timestamp` and is converted with the [date()](http://be2.php.net/manual/en/function.date.php) function in PHP.

Example:
![capture](https://user-images.githubusercontent.com/5796460/37743401-398dc0ce-2d6a-11e8-9182-f3a4899d6693.PNG)

Just check that you have set the correct date / time format for `date()` in the webpanel settings
![1](https://user-images.githubusercontent.com/5796460/37743527-cb75bbc2-2d6a-11e8-8a43-212441640c66.PNG)

[Here](http://php.net/manual/en/function.date.php) is also a reference for the different characters in the format for `date()`.
