### ISSUE TITLE
[SourceBans] This player has not been verified. Please wait thirty seconds before retrying.

### ISSUE THREAD

**Issue by kratos1812** [sbpp/sourcebans-pp#432]
When i write "sm_ban player 1 hacking" in console i get this message
"[SourceBans] This player has not been verified. Please wait thirty seconds before retrying."

What can I do?

If I ban the player from sm_admin it works

**Comment by Groruk** [comment]
This one has been resolved on the [SourceBans++ Discord](https://discord.gg/4Bhj6NU), but for completeness here is the rundown:

His log: [SourceBans.log](https://cdn.discordapp.com/attachments/298925185367539714/429577382634979328/sourcebans.log)
From that we can see, that SourceBans++ isn't installed correctly and missing the database structure and connection. 
Also there are different version of SourceBans `sourcebans.smx` and SourceBans++ `sbpp_main.smx` running.

So to fix this just [install SourceBans++ correctly](https://sbpp.github.io/docs/quickstart/) and remove [all old versions of SourceBans](https://sbpp.github.io/docs/updating/)

**Comment by rumblefrog** [comment]
This was a somewhat painful one. I was on my phone trying to debug this, not realizing the log was 4 Mb, so I spent 5 minutes scrolling to the end.
