### ISSUE TITLE
Updater Produces Blank Page

### ISSUE THREAD

**Issue by jljr222** [sbpp/sourcebans-pp#437]
## Expected Behavior
Essentially it's just a blank after uploading the files for 1.6.3 when updating from 1.6.2. Usually, it would show the updating process. I'm getting nothing at the moment.

## Current Behavior
It's blank.

## Possible Solution
Not sure...

## Steps to Reproduce (for bugs)
1. Upload files to your install and overwrite them.
2. Delete the install directoy.
3. Head to http://install.com/updater/
4. Blank page.

## Context
Updating to 1.6.3

## Your Environment
* Version used: 1.6.3
* PHP and MySQL version: PHP 7.0
* Operating System and version: CentOS
* Link to your project: https://bans.bor3dgaming.com
* Link to gist with phpinfo() output:

**Comment by rumblefrog** [comment]
Please attach PHP error log

**Comment by jljr222** [comment]
There is no error_log generated. Should there be one?

**Comment by rumblefrog** [comment]
Typically yeah, make sure your logging is on

**Comment by jljr222** [comment]
It is, I tried again and when I go to:

https://bans.bor3dgaming.com/updater/

It's still blank. No error log is being generated for PHP.

**Comment by lukefor** [comment]
I came across this issue due to having previously installed some sort of server redirect plugin that added columns to sb_servers. The error was due to invalid values being present causing the utf8mb4 alter table query to bomb out

The real issue here is that it seems there is a lack of error handling in the updater. I wasn't able to get to output any errors even when adjusting display_errors, error_reporting, etc. 

It also doesn't seem to check for config.php being writable, but I don't think that can cause it to silently bomb out in the same way that a database error can

**Comment by rumblefrog** [comment]
Typically when a page blanks out, which usually means PHP terminates earlier than expected, which will log to the error log, if configured to.

**Comment by lukefor** [comment]
Yeah checked the error log and nothing unfortunately, only tracked down the issue with a bit of manual debugging

**Comment by jljr222** [comment]
So how would I go about fixing this issue to ensure my install is properly updated?

**Comment by rumblefrog** [comment]
Well, I can't help if nothing is provided, you can try setting error handlers like this one: https://stackoverflow.com/a/18208549

**Comment by lukefor** [comment]
You can reproduce by changing any of the mysql queries in the update scripts to something invalid

**Comment by jljr222** [comment]
@RumbleFrog I added that code and it didn't do anything.

**Comment by rumblefrog** [comment]
Perhaps you can try dump the database and I'll try it on my side

**Comment by jljr222** [comment]
Little hesitant on that because it contains all of my passwords etc. Luke also had a similar issue so there has to be more than just me randomly.

**Comment by rumblefrog** [comment]
You can truncate those, Luke has modified columns, that's why I'm asking for the database.

**Comment by jljr222** [comment]
@RumbleFrog 

I just noticed this in the log, sorry:
```
[256] mysqli error: [1060: Duplicate column name 'type'] in EXECUTE("ALTER TABLE `sb_bans` ADD `type` TINYINT NOT NULL DEFAULT '0'")Fatal error on line 79 in file /***/bans/includes/adodb/adodb-errorhandler.inc.php
--
Parent Function | /***/bans/includes/adodb/adodb-errorhandler.inc.php - 79
/***/bans/includes/adodb/adodb.inc.php - 1250
/***/bans/includes/adodb/adodb.inc.php - 1214
/***/bans/updater/data/112.php - 33
```

**Comment by rumblefrog** [comment]
What's your `config.version`?

**Comment by jljr222** [comment]
It's set to 1

**Comment by rumblefrog** [comment]
It should be around `532` for 1.6.2 upgrading to 1.6.3

**Comment by jljr222** [comment]
Did you mean the config.version in the sb_settings table? That's what the value is set to.

**Comment by rumblefrog** [comment]
Yeah, otherwise you're going to run all the parent updater files

**Comment by jljr222** [comment]
Here is what I have after making that change:

```
Warning: require_once(../includes/random_compat/lib/random.php): failed to open stream: No such file or directory in /***/bans/updater/data/601.php on line 7

Fatal error: require_once(): Failed opening required '../includes/random_compat/lib/random.php' (include_path='.:/php/includes:/***/bans/includes/adodb') in /***/bans/updater/data/601.php on line 7
```

**Comment by lukefor** [comment]
I also hit the same issues after resolving the database error, i.e. version getting set to 1 and the include error  for random.php

**Comment by rumblefrog** [comment]
Did you guys delete everything and upload 1.6.3? If upgrading straight from 1.6.2, the random library should be there. You can download it from 1.6.2 tag. It was removed in 1.6.3, as we have dropped support for older PHP versions.

**Comment by jljr222** [comment]
I did when trying to figure out why I couldn't update.

**Comment by lukefor** [comment]
Yeah wiped before upgrading

**Comment by rumblefrog** [comment]
You guys can (a) download 1.6.2 again, and overwrite it with 1.6.3 files again, or (b) upload the missing files from 1.6.2

**Comment by jljr222** [comment]
I just did that, but still got this:

`Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'config.enablecomms' for key 'setting' in /***/bans/includes/Database.php:70 Stack trace: #0 /***/bans/includes/Database.php(70): PDOStatement->execute() #1 /***/bans/updater/data/603.php(4): Database->execute() #2 /***/bans/includes/CUpdate.php(61): include('/***/pub...') #3 /***/bans/updater/index.php(51): CUpdater->doUpdates() #4 {main} thrown in /***/bans/includes/Database.php on line 70`

**Comment by rumblefrog** [comment]
Your database is all over the place, but 603 is the last updater data as of current, looks like you already have the update applied somehow. In that case, you may update the version to 603 in the table, and the update should be done as there are no more in the series.

**Comment by jljr222** [comment]
OK, I manually changed it. I've never done anything custom to my installation or edited the DB directly. I don't know how it got to be like this...

**Comment by rumblefrog** [comment]
It's most likely due to another attempt to run the installer or somehow updater partially completed.
