### ISSUE TITLE
Issue with SourceQuery (Error connectig) SB++ 1.6.1-1.6.3

### ISSUE THREAD

**Issue by Allower** [sbpp/sourcebans-pp#441]
## Expected Behavior

Normal Server info show
## Current Behavior

**sb_debug_connection.php** - shows good result and all admins/bans/rcon works fine

![qjlmu6z 1](https://user-images.githubusercontent.com/7057182/38692355-1f4e62d0-3e8c-11e8-9f78-d96140f91157.png)

But, getting server info for "**Servers**" tab is failed:

![cthx54u 1](https://user-images.githubusercontent.com/7057182/38692370-2a916ec6-3e8c-11e8-9074-4c7ff25a8bd2.png)
## Possible Solution

No ideas
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

**how to fix?**
## Your Environment

* Version used:
**1.6.1** to **1.6.3**
* PHP and MySQL version:
PHP: **5.6.30-0+deb8u1**
MySQL: **5.5.54-0+deb8u1**
* Operating System and version:
**Linux**
* Link to your project:
**http://n14.serva4ok.ru/server664837/www/sourcebans/**
* Link to gist with phpinfo() output:
**http://n14.serva4ok.ru/server664837/www/phpinfo.php**

**Comment by rumblefrog** [comment]
Can you provide potential PHP log?

**Comment by CrazyHackGUT** [comment]
GMP installed? SourceQuery requires GMP module or 64-bit PHP. If GMP not installed and PHP don't supports 64-bit numbers, he throws Exception.

**Comment by Groruk** [comment]
> GMP installed? SourceQuery requires GMP module or 64-bit PHP. If GMP not installed and PHP don't supports 64-bit numbers, he throws Exception.

Most likely the issue.
Missing libs or extensions are the cause of most 'issues' with SourceBans++.

That's why we ask for the `phpinfo()` output in the [Issue Template](https://github.com/sbpp/sourcebans-pp/blob/v1.x/.github/ISSUE_TEMPLATE.md#your-environment) to be sure the environment is setup correctly, but most people seem to be allergic to issue templates.

**Comment by Allower** [comment]
Sorry Groruk for that mistake.

I created phpinfo file on web ftp, where i buy hosting for our server.

Link below:
http://n14.serva4ok.ru/server664837/www/phpinfo.php

**Comment by Allower** [comment]
I'm so sorry guys for bad description and no have more info about php and links to project

I have updated issue description and created phpinfo file where SB++ web part is placed. Now you can check. All links provided.

And thank you all for answers.

**Comment by rumblefrog** [comment]
Typically FTP is used for shared hosting, and it seems like GMP is not enabled.

**Comment by Allower** [comment]
Okay i'm already send message to the technical support and they answer me. But i think I'll have to wait quite a long time before they do support for new versions of SB ++

Before they enable GMP Module

**Question:** can I manually return the old SourceQuery code or because of this there will be compatibility problems?

**Comment by rumblefrog** [comment]
There shouldn't be an issue with downgrading
