### ISSUE TITLE
Block Count dont works

### ISSUE THREAD

**Issue by anaether** [sbpp/sourcebans-pp#442]
Im running the latest sourcebans++ version (1.6.3). The block count into the webinterface are not working. Im also a developer and have tested for my server my plugin to prevent surf cheats and got by special commands an ban. So i have seen when i have tried to connect to my server that sourcebans dont count the blocks right in the webinterface. The gameserver and webserver side doesnt have any issue. I checked these and there was no logs. 

Operation System: Debian 8 64bit.
Sourcemod Version: SM 1.9 dev
Metamod Version: MM 1.11 dev

good regards, 
cRUSHER

**Comment by rumblefrog** [comment]
Did it at least kick the client? Did you check `sourcebans.log`?

**Comment by rumblefrog** [comment]
Closing this as a stale w/o response

**Comment by anaether** [comment]
yeah logs dont show anything. Sourcebans working with db on gameservers and also adds users admin permission right in the right files. Only the block count dont works

**Comment by rumblefrog** [comment]
Can you check if this gets called? By adding a debug line somewhere within the function.

https://github.com/sbpp/sourcebans-pp/blob/16e1db5395e41bc7a208b107de96e5437bb9063e/game/addons/sourcemod/scripting/sbpp_main.sp#L1620

**Comment by rumblefrog** [comment]
I also request that you try this on stable SM & MM as well.

**Comment by CrazyHackGUT** [comment]
Stable SM (1.8 on this moment) has problems with DB. Sometimes server just crashes. 

In 1.9 this partially fixed.

**Comment by CrazyHackGUT** [comment]
I've found this discussion on Discord, in SM server.
![img](https://i.imgur.com/A2R1HYP.png)

https://github.com/alliedmodders/sourcemod/pull/577

**Comment by rumblefrog** [comment]
That's with transaction though?
