### ISSUE TITLE
Error: the XML response 

### ISSUE THREAD

**Issue by szogi1910** [sbpp/sourcebans-pp#445]
Hello
I have two problems after sourcebans++ update.
The server is not added automatically.
When I add it manually to the page I have the errors

`Error: the XML response that was returned from the server is invalid. Received: 0/15]]>]]>de_dust2$('mapimg_3').setProperty('src', 'images/maps/de_dust2.jpg').setProperty('alt', 'de_dust2').setProperty('title', 'de_dust2');$('sinfo_3').setStyle('display', 'none');$('noplayer_3').setStyle('display', 'block');$('serverwindow_3').setStyle('height', '64px');
`

**Comment by rumblefrog** [comment]
Please provide log

**Comment by Groruk** [comment]
Also provide additional info like:
- PHP and MySQL version
- Operating System and version
- A link to your sourcebans++ installation
- A phpinfo() output

basically everything that is asked for in the [Issue Template](https://github.com/sbpp/sourcebans-pp/blob/v1.x/.github/ISSUE_TEMPLATE.md)

**Comment by szogi1910** [comment]
the problem has been fixed.
the error was caused by the custom character.
