### ISSUE TITLE
Correction of the gag option

### ISSUE THREAD

**Issue by Majkovsky** [sbpp/sourcebans-pp#446]
When a player gets a chat gag, they have the additional option of writing to administrators on say @ or say_team @. Please add the option to block it too.

**Comment by Groruk** [comment]
SourceBans++ uses the [basecomm.inc](https://sm.alliedmods.net/new-api/basecomm) functions to mute or gag players which only checks the voice and text chats, not console commands.
If people abuse the `send message to admin` option you can just [disable it](https://github.com/alliedmodders/sourcemod/blob/master/plugins/basechat.sp#L64) with `sm_chat_mode 0`
