### ISSUE TITLE
[BUG] - Unexpected ban appears on SourceBans

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#449]
* **Link to your project: https://www.zkservidores.com/sourcebans/index.php?p=banlist**
* **Server Game: CSGO**

When I apply ban without a reason, for example: `sm_ban crashzk 15`

The ban does not show on SourceBans, so appearing would have to put some reason.

I believe I could in these cases put a pattern, eg, Breaking Rules, Others, etc.

**Comment by rumblefrog** [comment]
Pretty sure this is intended, as reason is non-nullable

https://github.com/sbpp/sourcebans-pp/blob/6f2b5b36e9e55b1add38994ebdc9afe0e6da302f/web/install/includes/struc.sql#L47

**Comment by Groruk** [comment]
SourceBans & SourceBans++ are designed to only add bans that have a reason.

https://github.com/sbpp/sourcebans-pp/blob/6f2b5b36e9e55b1add38994ebdc9afe0e6da302f/game/addons/sourcemod/scripting/sbpp_main.sp#L446-L458

https://github.com/sbpp/sourcebans-pp/blob/6f2b5b36e9e55b1add38994ebdc9afe0e6da302f/game/addons/sourcemod/scripting/sbpp_main.sp#L2464-L2478

**Comment by crashzk** [comment]
Doubt, even banning not showing in Web Interface the player is still banned correct?

**Comment by rumblefrog** [comment]
You can check the local SQLite cache to see if it's in there, in case remote calls fails.

Are there any error logs?

**Comment by crashzk** [comment]
I checked the player is banned from the server but does not show it in WebInterface.

The banned player in question did not receive the reason for the ban, but was banned anyway.

It has no error log.

And the ban is not applied by the surcebans but by the sourcemod, it is banished in the sourcemod.

And when we apply a ban with reason, all right, the ban appears both for sourcebans and sourcemod.

**Comment by rumblefrog** [comment]
Can you check the SQLite cache

**Comment by crashzk** [comment]
It would be some of these:
[Desktop.zip](https://github.com/sbpp/sourcebans-pp/files/1976139/Desktop.zip)

If so, how can I check them out.

If not, where can I find this SQLite cache.

**Comment by rumblefrog** [comment]
Doesn't seem to be in there, most likely need to turn on debug mode and start adding debug lines to figure out what happened

**Comment by crashzk** [comment]
In case to enable debug mode it would be here: [Debug mode] (http://prntscr.com/jdykei) In WebInterface.

Right?

**Comment by rumblefrog** [comment]
Plugin side

**Comment by crashzk** [comment]
I understand, could report as active, so I could analyze and send it to you.
