### ISSUE TITLE
Console Added to Admin List

### ISSUE THREAD

**Issue by jljr222** [sbpp/sourcebans-pp#450]
CONSOLE is getting added to the sb_admins.cfg file for all of my servers. I did not have this issue until upgrading to 1.6.3. I have tried going in and manually removing it, but it is added back.

I checked the database for SB and CONSOLE still has an id of 0.

## Expected Behavior
CONSOLE would be skipped when adding admins to sb_admins.cfg file.

## Current Behavior
CONSOLE is added to the sb_admins.cfg file as if it's an admin.

## Possible Solution
I'm going to try re-installing at some point and seeing if this happens.

## Steps to Reproduce (for bugs)
Not sure how to reproduce as it just...does it automatically.

## Context
Many errors in my error logs.

## Your Environment
* Version used: 1.63
* PHP and MySQL version: PHP 7 and MySQL 6
* Operating System and version: CentOS 7
* Link to your project: https://bans.bor3dgaming.com
* Link to gist with phpinfo() output: https://bans.bor3dgaming.com/php-info.php

**Comment by rumblefrog** [comment]
May I see `_admins_servers_groups` table

**Comment by rumblefrog** [comment]
If possible a DB dump w/ hash field truncated

**Comment by jljr222** [comment]
After my re-install, it has not happened yet. If it happens again I'll re-open.
