### ISSUE TITLE
How to Modify the Web Panel Translation

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#451]
I would like to know how I can modify the language of the Web Panel, in this specific one: https://prnt.sc/j9aepy

I would like to rename the case.

**Comment by CrazyHackGUT** [comment]
Modify [here](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/system-functions.php#L148-154) and [here](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/system-functions.php#L181-195)

**Comment by crashzk** [comment]
Worked, thank you.

I would have another question, how can I change the banlist names shown here: http://prntscr.com/j9lhl0

Switch to Permanent, Expired, set to my liking.

And to finish, after I modified the language of the administration tab, one of the links bugou: http://prntscr.com/j9lih4

Would I have to increase this space in order to correct this?

**Comment by rumblefrog** [comment]
https://github.com/sbpp/sourcebans-pp/blob/3e76d97b8647c520da0c3f2d93305da7154e0865/web/pages/page.banlist.php#L528

With regard to the nav bar, it only has a certain width to work with, and the overflow will go to the next line

**Comment by crashzk** [comment]
The navigation bar would have how to increase this width, or would it be impossible?

**Comment by rumblefrog** [comment]
Not really, you could change `#mainwrapper` CSS to remove the width restriction, but that'd look bad IMO. You could also make the fonts smaller.

**Comment by crashzk** [comment]
Perfect, thanks!
