### ISSUE TITLE
[Feature Request] Web Panel Comms Ban

### ISSUE THREAD

**Issue by JoinedSenses** [sbpp/sourcebans-pp#452]
Hello.

Correct me if I'm wrong. I currently see no method to add a comm ban via sb++ web panel. If it's not a current feauture, it'd be totally sweet if it were added.

Thanks

**Comment by rumblefrog** [comment]
`index.php?p=admin&c=comms`

**Comment by JoinedSenses** [comment]
Thanks, dunno why I didn't think to try that. It doesnt seem to appear on the admin page

https://i.imgur.com/xugTWyv.png

**Comment by rumblefrog** [comment]
It's at the top https://i.imgur.com/YyaLL4m.png

Poor original design I suppose, will be fixed with new template engine
