### ISSUE TITLE
[BUG] Banishing does not show in Web Interface

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#453]
* SourceBans++ Version: 1.6.3
* SourceMod Version (for plugin issues): 1.8 - build 6041:
* Link to your project (for web panel issues): https://www.zkservidores.com/sourcebans/

I noticed the following BUG, ​​when some ADMIN will ban some player by the command **!admin** and goes in the option to ban the player is banned only that does not show the ban in the Web Interface.

The ban only shows in the Web Interface when it applies ban by the chat, and only by the chat with the command **!ban**.

The right thing would not be to appear banning in the Web Interface anyway, even if the ban is applied by the **chat** or by the command **!admin**?

**Comment by rumblefrog** [comment]
`motra`?

Can you provide logs.

**Comment by crashzk** [comment]
Fixed, follows the server error log: 
[errors_20180428.log](https://github.com/sbpp/sourcebans-pp/files/1958334/errors_20180428.log)

I believe you have no error related to SourceBans ++.

Only error I saw from SourceBans is related to this plugin: https://forums.alliedmods.net/showthread.php?t=183355?t=183355

But even without it the banishes applied by !admin does not show in the Web Interface, only the bans by chat with the command !ban <NICK> <TIME> <REASON>

**Comment by rumblefrog** [comment]
Could you fix the translation

**Comment by crashzk** [comment]
I just did this and the problem continues, I do not know if it helps, but in the previous version of Sourcebans++ 1.6.2 also had this problem.

**Comment by rumblefrog** [comment]
That log file only contains things from `04/03/2018`, when its name is 0428?

**Comment by crashzk** [comment]
Wrong, it is 04/28/2018.
```
L 04/28/2018 - 19:48:44: [SM] Fatal error encountered parsing translation file "sourcebans.phrases.txt"
L 04/28/2018 - 19:48:44: [SM] Error (line 87, column 61): Line contained too many invalid tokens
L 04/28/2018 - 19:48:54: [teamlogos.smx] Teamname config not found for logo ''
L 04/28/2018 - 19:48:54: [teamlogos.smx] Teamname config not found for logo ''
L 04/28/2018 - 20:10:50: Error log file session closed.
L 04/28/2018 - 20:10:50: SourceMod error session started
L 04/28/2018 - 20:10:50: Info (map "de_dust2") (file "errors_20180428.log")
L 04/28/2018 - 20:10:50: [SM] Fatal error encountered parsing translation file "sourcebans.phrases.txt"
L 04/28/2018 - 20:10:50: [SM] Error (line 87, column 61): Line contained too many invalid tokens
L 04/28/2018 - 20:10:50: [SM] Exception reported: Fatal error creating dynamic native!
L 04/28/2018 - 20:10:50: [SM] Blaming: lbd_sourcebans.smx
L 04/28/2018 - 20:10:50: [SM] Call stack trace:
L 04/28/2018 - 20:10:50: [SM]   [0] CreateNative
L 04/28/2018 - 20:10:50: [SM]   [1] Line 129, lbd_sourcebans.sp::AskPluginLoad2
L 04/28/2018 - 20:10:50: [SM] Failed to load plugin "lbd_sourcebans.smx": unexpected error 23 in AskPluginLoad callback.
L 04/28/2018 - 20:10:54: [teamlogos.smx] Teamname config not found for logo ''
L 04/28/2018 - 20:10:54: [teamlogos.smx] Teamname config not found for logo ''
L 04/28/2018 - 20:21:32: Error log file session closed.
L 04/28/2018 - 20:21:32: SourceMod error session started
L 04/28/2018 - 20:21:32: Info (map "de_dust2") (file "errors_20180428.log")
L 04/28/2018 - 20:21:32: [SM] Fatal error encountered parsing translation file "sourcebans.phrases.txt"
L 04/28/2018 - 20:21:32: [SM] Error (line 87, column 61): Line contained too many invalid tokens
L 04/28/2018 - 20:21:36: [teamlogos.smx] Teamname config not found for logo ''
L 04/28/2018 - 20:21:36: [teamlogos.smx] Teamname config not found for logo ''
L 04/28/2018 - 20:21:41: [teamlogos.smx] Teamname config not found for logo 'hellr'
L 04/28/2018 - 20:21:41: [teamlogos.smx] Teamname config not found for logo 'hellr'
L 04/28/2018 - 20:24:26: Error log file session closed.
L 04/28/2018 - 20:24:26: SourceMod error session started
L 04/28/2018 - 20:24:26: Info (map "de_dust2") (file "errors_20180428.log")
L 04/28/2018 - 20:24:26: [SM] Fatal error encountered parsing translation file "sourcebans.phrases.txt"
L 04/28/2018 - 20:24:26: [SM] Error (line 87, column 61): Line contained too many invalid tokens
L 04/28/2018 - 20:24:29: [teamlogos.smx] Teamname config not found for logo ''
L 04/28/2018 - 20:24:29: [teamlogos.smx] Teamname config not found for logo ''
```
[errors_20180428.log](https://github.com/sbpp/sourcebans-pp/files/1958347/errors_20180428.log)

**Comment by rumblefrog** [comment]
My bad, looking at another guy's log file. I need to try to reproduce this, any particular reproduce steps?

**Comment by crashzk** [comment]
Talk to me in private? If so, yes, no problem.

In any case if you want to reproduce yourself just try to ban a guy by the !admin command, and go in the option to ban a player, the ban is applied by SourceMod, there does not show in the Web Interface.

But if you banish it !ban it applies the ban through SourceBans and SourceMod until, but this shows in the Web Interface.

**Comment by rumblefrog** [comment]
![5ae5f53a0b890b5c0bbf298c](https://user-images.githubusercontent.com/6960234/39408818-5dcb3b7a-4baa-11e8-8617-3389cf4ad271.png)

Banned via menu, unable to reproduce the bug

**Comment by crashzk** [comment]
I do not know if it has anything to do, but my server would be CSGO.

**Comment by Bara** [comment]
Shouldn't be relevant, but what this "lbd_sourcebans.smx"?
L 04/28/2018 - 20:10:50: [SM] Failed to load plugin "lbd_sourcebans.smx": unexpected error 23 in AskPluginLoad callback.

**Comment by crashzk** [comment]
This would be of another plugin, cusa the function is to limit the ban time for each flag, it would be this plugin: https://forums.alliedmods.net/showthread.php?t=183355

I put it up recently, before that the problem continued.

But I have already corrected this BUG in question.

**Comment by rumblefrog** [comment]
The game should not differ, unless the SM backend implementation is different,

**Comment by crashzk** [comment]
I'll be doing some prints to show the BUG on my server, so check it out here.
