### ISSUE TITLE
[ SUGGESTION ] Ban by time configured by flags

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#454]
It would be possible to put time option for certain flags, examples:
**- Those who have the flag "B" will only apply ban until X time minus the Permanent;**
**- Anyone with the flag "Z" can apply time and permanent ban;**

And so on.

It would be possible?

**Comment by rumblefrog** [comment]
You can try this https://forums.alliedmods.net/showthread.php?t=183355?t=183355

But you'll need to modify it

**Comment by crashzk** [comment]
I even use it, but this error in the server log:
```
L 04/28/2018 - 20:10:50: [SM] Exception reported: Fatal error creating dynamic native!
L 04/28/2018 - 20:10:50: [SM] Blaming: lbd_sourcebans.smx
L 04/28/2018 - 20:10:50: [SM] Call stack trace:
L 04/28/2018 - 20:10:50: [SM]   [0] CreateNative
L 04/28/2018 - 20:10:50: [SM]   [1] Line 129, lbd_sourcebans.sp::AskPluginLoad2
L 04/28/2018 - 20:10:50: [SM] Failed to load plugin "lbd_sourcebans.smx": unexpected error 23 in AskPluginLoad callback.
```
The following is the complete error log: 
[errors_20180428.log](https://github.com/sbpp/sourcebans-pp/files/1958337/errors_20180428.log)

But anyway the plugin usually works apparently.

**Comment by rumblefrog** [comment]
You'll need to replace the main plugin with that, and it will cause other plugins that uses any of the new native to malfunction

**Comment by crashzk** [comment]
So I need to get lbd_sourcebans.smx and put the version of you, correct?

**Comment by rumblefrog** [comment]
Delete sbpp_main.smx and replace it with lbd_sourcebans.smx

**Comment by crashzk** [comment]
Perfect, I'll be testing and returning with the results.

**Comment by crashzk** [comment]
Worked, thank you!

**Comment by crashzk** [comment]
Problem solved, thank you!
