### ISSUE TITLE
[BUG] Bad preg_match filter in page.lostpassword.php

### ISSUE THREAD

**Issue by GoofyNest** [sbpp/sourcebans-pp#455]
* SourceBans++ Version: 1.6.3
* 1.8 - build 6041:
* PHP and MySQL version: PHP 5.6, doesn't matter.
* Linux Ubuntu 16.04
* Link to your project (for web panel issues): N/A
* Link to gist with phpinfo() output (for web panel issues): N/A

My domain contains - and your filter detect my domain as a potential SQL injection on resetting password.

`preg_match("/[\w\.]*/", $_SERVER['HTTP_HOST'], $match);`
Should be
`preg_match("/[\w\.-]*/", $_SERVER['HTTP_HOST'], $match);`

/pages/page.lostpassword.php
line 40

**Comment by RumbleFrog** [comment]
Section in question:

https://github.com/sbpp/sourcebans-pp/blob/d84b24a73914f7a0dffaa353257543f9ae0708b4/web/pages/page.lostpassword.php#L40-L51

Is there even a case where you regex match `HTTP_HOST` and it's not equal to `HTTP_HOST` when comparing? Feels like this is unnecessary.

**Comment by rumblefrog** [comment]
Section in question:

https://github.com/sbpp/sourcebans-pp/blob/d84b24a73914f7a0dffaa353257543f9ae0708b4/web/pages/page.lostpassword.php#L40-L51

Is there even a case where you regex match `HTTP_HOST` and it's not equal to `HTTP_HOST` when comparing? Feels like this is unnecessary. @Groruk
