### ISSUE TITLE
SourceComms_OnBlockAdded returning client and target -1

### ISSUE THREAD

**Issue by danielsartor** [sbpp/sourcebans-pp#463]
I'm trying to use the forward to send details of mutes/gags to my discord.

I'm using the following functions on my plugin: https://pastebin.com/MFQt3Vde

When you mute/gag someone, it prints -1 for client and target. The client will be muted and sent to the sourcebans panel with the correct name and admin. Also, the mute applies to the client ingame, the problem is that I can't retrieve the client and target on the forward.

sbpp version 1.6.3
sourcemod version 1.8.0.6040

Regards.

**Comment by rumblefrog** [comment]
Can you check the indexes prior to the forward fire 

Somewhere around https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L1260

**Comment by danielsartor** [comment]
For some reason now is working. I think I had to restart the server, because changing maps or reloading the plugin was not working.
