### ISSUE TITLE
[Feature Request] Detailed KickClient() message

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#468]
Is your feature request related to a problem? Please describe.
-------------------------------------------------------------

Banned users should have an easy way to get an detailed description about their ban without having to open the in-game overlay
or alt + tab to open a web browser if they have disabled the overlay.

Describe the solution you'd like
--------------------------------

Give a banned user a more detailed kick description about their ban.

Example
-------
![Example](https://i.imgur.com/FYcQUwV.png "Ban detail example")

Additional context
------------------

- This would be a massive Quality of Life change

**Comment by rumblefrog** [comment]
What does a normal CSGO ban screen look like?

**Comment by JamsRepos** [comment]
"You have been banned from this server".

**Comment by crashzk** [comment]
"You have been banned from this server, for more information go to: WEB SOURCEBANS LINK."

Something like.

**Comment by rumblefrog** [comment]
Yeah, I, unfortunately, cannot help with this issue, as I know nothing about CSGO

**Comment by crashzk** [comment]
I understand, I'll be checking in the background and anything put something here for now thank you!

**Comment by Groruk** [comment]
Since there were some confusions about what OP meant (would have been easily avoided if the issue template was used) I updated the issue to feature a more detailed description.

**Comment by rumblefrog** [comment]
In that case, you may want to try if `KickClient()`'s format arg supports new lines

**Comment by crashzk** [comment]
Any news on this suggestion?

In any case I'm seeing if I can make the changes to see if it works, do you have to make changes only in line [#2554](https://github.com/sbpp/sourcebans-pp/blob/89eb6f449eb660cb9b53a63525508fe15028f5b9/game/addons/sourcemod/scripting/sbpp_main.sp#L2554)?

**Comment by rumblefrog** [comment]
Can you first provide how to format this for CSGO in code? Then we can proceed.

**Comment by Groruk** [comment]
Added with #504
