### ISSUE TITLE
"Servers" page, kick don't work

### ISSUE THREAD

**Issue by Allower** [sbpp/sourcebans-pp#474]
What are the steps to reproduce this issue?
-------------------------------------------
1. Go to servers
2. Choose server
3. Right click on target
4. Choose Kick

What happens?
-------------
Message says something like this:
"Player 'PLAYERNAME' has been kicked from the server."

Server not kick a player, player or bot still on server

What were you expecting to happen?
----------------------------------
Kick player from server

Any logs, error output, etc.?
----------------------------

Last logs from gameserver:

L 05/23/2018 - 05:22:07: World triggered "Round_Start"
L 05/23/2018 - 05:22:07: rcon from "193.26.217.146:59079": command "hlx_sm_psay "4,3" "HLstatsX:CE disabled! Need at least 4 active players (2/4)""
L 05/23/2018 - 05:22:08: "Antoha<4><STEAM_1:0:73206432><TERRORIST>" picked up "ak47"
L 05/23/2018 - 05:22:24: "Antoha<4><STEAM_1:0:73206432><TERRORIST>" left buyzone with [ weapon_knife_t weapon_glock weapon_ak47 ]
L 05/23/2018 - 05:22:25: "Antoha<4><STEAM_1:0:73206432><TERRORIST>" left buyzone with [ weapon_knife_t weapon_glock weapon_ak47 ]
L 05/23/2018 - 05:22:25: rcon from "193.26.217.146:59129": command "status"
L 05/23/2018 - 05:22:27: rcon from "193.26.217.146:59129": command "kickid STEAM_0:0:73206432 "You have been banned by this server, check http://n14.serva4ok.ru/server664837/www/sourcebans/index.php for more info.""
L 05/23/2018 - 05:22:38: rcon from "193.26.217.146:59144": command "status"
L 05/23/2018 - 05:22:40: rcon from "193.26.217.146:59144": command "kickid STEAM_0:1:31019185 "You have been banned by this server, check http://n14.serva4ok.ru/server664837/www/sourcebans/index.php for more info.""
L 05/23/2018 - 05:22:47: "Emperor Palputin<3><STEAM_1:1:31019185><CT>" dropped "hkp2000"
L 05/23/2018 - 05:22:47: "Emperor Palputin<3><STEAM_1:1:31019185><CT>" dropped "knife"
L 05/23/2018 - 05:22:47: World triggered "killlocation" (attacker_position "-859 13 -116") (victim_position "-859 13 -116")
L 05/23/2018 - 05:22:47: "Emperor Palputin<3><STEAM_1:1:31019185><CT>" [-859 13 -116] committed suicide with "world"
L 05/23/2018 - 05:22:47: Team "TERRORIST" triggered "SFUI_Notice_Terrorists_Win" (CT "0") (T "1")
L 05/23/2018 - 05:22:47: Team "CT" scored "0" with "1" players
L 05/23/2018 - 05:22:47: Team "TERRORIST" scored "1" with "1" players
L 05/23/2018 - 05:22:47: World triggered "Round_End"
L 05/23/2018 - 05:22:56: Starting Freeze period
L 05/23/2018 - 05:22:57: World triggered "Round_Start"
L 05/23/2018 - 05:22:57: rcon from "193.26.217.146:59079

Any other comments?
-------------------
If you try kick bot, this says:
"Can't kick 'BOTNAME'. Player not on the server anymore!"

This is bug or so it should be with bots?

What versions of software are you using?
----------------------------------------
**Operating System:**
Linux
**SourceBans++ Version:**
SB++ 1.6.3
**PHP Version:**
5.6.30-0+deb8u1
**MySQL Version:**
5.5.54-0+deb8u1
**Link to your project:**
http://n14.serva4ok.ru/server664837/www/sourcebans/
**Link to a phpinfo() output:**
http://n14.serva4ok.ru/server664837/www/phpinfo.php

**Comment by rumblefrog** [comment]
I believe this is because SB fetches Steam ID via name, which can be unreliable in cases like name changer, and even less reliable with special characters. It's a pending rework, as you should **NEVER** query by name

**Comment by Allower** [comment]
Hi.
Thanks for fast reply.

And what about kicking bot where is message: Player not on the server anymore!

Is this a bug or just standart bot ignoring?

**Comment by rumblefrog** [comment]
I don't believe bots have a SteamID

**Comment by Groruk** [comment]
>If you try kick bot, this says:
"Can't kick 'BOTNAME'. Player not on the server anymore!"
This is bug or so it should be with bots?

Firstly: Bots don't have a steam id and therefore cant be kicked in a reliable way.
Secondly: There are commands specifically designed for bots in the source engine e.g `bot_kick`, `bot_add`, etc.
(Also bots cant be banned, muted, gagged or made admins that is all intended)

**Comment by Groruk** [comment]
@RumbleFrog in this case it's again the fault of the Steam2 ID format (it tries to kick the players e.g `kickid STEAM_0:0:73206432` and `kickid STEAM_0:1:31019185`, but cant find them, because ingame Steam2 IDs become `STEAM_1`).
I hope the fix is as easy as converting the Steam2 ID to Steam3 ID before the kick and let the source engine deal with the ID conversion.

**Comment by Allower** [comment]
Thank you both, now everything is clear!

About player kick bug, why not just use user #id method? kickid #1 #2 #200 or this is so hard and needs refresh if player reconnects to server? (to get new #id of course)

**Comment by Groruk** [comment]
While #userid would work the Steam Id would be more reliable, because the status command output varies from game to game:

### TF2 Example
![270f1e36df907e2776cffca38216af4a](https://user-images.githubusercontent.com/5796460/40435085-2beb25c0-5eb0-11e8-9659-9a7d057432be.png)

### CSGO Example
![90737](https://user-images.githubusercontent.com/5796460/40435094-2f98d01e-5eb0-11e8-8ae9-a7c7cdfc8fa8.jpg)

you can see that CSGO implements a secondary value for real players (not bots) so if a game or mod implements a custom status output we would need to adjust the `status regex` for this, while the patterns for steam id would be the same (Steam2, Steam3 or Steam64).
