### ISSUE TITLE
Doubt with Report option

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#479]
What happens?
-------------
When the players use the !report command it does the report, but I noticed that there are some reports that are phrases, like a player typed just complaining with the player and made a report automatically.

I do not know if it would be a BUG in question, but I wonder if this is normal, how this report option actually works.

Here is an example print:
http://prntscr.com/jsc23d
http://prntscr.com/jsc27b

Any other comments?
-------------------
Anyway, could you explain me better how this function works or if it is a BUG itself.

What versions of software are you using?
----------------------------------------
**Operating System:** 
**SourceBans++ Version:** 1.6.3
**SourceMod Version:** 1.8 - build 6046
**MetaMod Version:** 1.10 - build 961

**Comment by rumblefrog** [comment]
So I'm not sure what the question is, and I don't see what's wrong in those screenshots.

Once you used the report command, a menu will appear prompting you to select a target, and afterward it requires you to type a reason in chat for the report.

**Comment by xLeviNx** [comment]
Just following up on this cause I noticed this recently. This is due to bInReason not being initialized, so it ends up being true for some of the clients, meaning it randomly triggers the report. Just need to add a small fix to it to make it work.
