### ISSUE TITLE
option to disable commbans message when players join the server

### ISSUE THREAD

**Issue by Xiaminou** [sbpp/sourcebans-pp#481]
[This pull request](https://github.com/sbpp/sourcebans-pp/pull/398/commits/9b74a18be762485b99d7043f03b52d283d443f5b) adds a message that is displayed when someone with commbans joins the server. However if you have a lot of players with commbans on your server is ends up spamming quite a bit, and I've been told there is no option to disable it.

I suggest adding a cvar to disable these messages.

**Comment by rumblefrog** [comment]
Comm checker was added by #398

**Comment by Groruk** [comment]
Duplicate of #425
