### ISSUE TITLE
Server connection error

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#482]
What happens?
-------------
I did all the installation of the plugins and the web archives, so far so good.

But it is not connecting to the servers, it is giving connection error.

I tested the connection with `sb_debug_connection.php` and had the following result: https://www.zkservidores.com/sourcebans/sb_debug_connection.php

I have already contacted the Host of the Game Servers and My Hosting that I use and none of them have any blocks.

What could it be, could it be corrected?

What versions of software are you using?
----------------------------------------
**SourceBans++ Version:** 1.6.3
**PHP Version:** 7.0
**MySQL Version:** 10.2
**Link to your project:** https://www.zkservidores.com/sourcebans/

**Comment by rumblefrog** [comment]
Have you checked UFW/IPTables

**Comment by crashzk** [comment]
> Have you checked UFW/IPTables

@RumbleFrog no, could you explain how to do this process?

**Comment by rumblefrog** [comment]
It's different for each OS. For Ubuntu you can check this wiki: https://help.ubuntu.com/community/UFW

**Comment by crashzk** [comment]
> It's different for each OS. For Ubuntu you can check this wiki: https://help.ubuntu.com/community/UFW

Perfect, this in case I check into my hosting web host right?

**Comment by rumblefrog** [comment]
More like your game

**Comment by CrazyHackGUT** [comment]
Create a ticket in web host support. Describe your problem. Request open **incoming UDP** and **outgoing TCP**.

**Comment by crashzk** [comment]
This is the problem, I contacted the web host, requested the release of the UDP and TCP ports, and they already did that too.

I have already contacted both the web host and host game and both have already checked that there is no firewall blocking, no UDP and TCP blocking, both checked and released, ie all requirements are already met.

@CrazyHackGUT

**Comment by rumblefrog** [comment]
Is that server publicly reachable? Meaning you can connect to it.

![5b2546121a9fc305af020f81](https://user-images.githubusercontent.com/6960234/41500852-a22765f4-7167-11e8-8963-66872d8fa3bf.png)

**Comment by crashzk** [comment]
Yes, the server is public, any player can access them.

All my servers are publicly accessible, it follows the list of them:
```
143.202.38.73:27052
143.202.38.73:27058
185.50.105.218:27178
185.50.105.218:27198
```
All of these I can add in SourceBans, but all show the connection error.

@RumbleFrog

**Comment by geominorai** [comment]
@paulocrash Looks like `sb_debug_connection.php` points to your first game server's IP address but with a different port.

Assuming your database is on the same server as web server, I can't connect to it either from my Brazil VPS (before even any login attempt).  Perhaps check if your web host allows for external database connections.

**Comment by rumblefrog** [comment]
@paulocrash Are you sure you have the right port in the debug file?

**Comment by crashzk** [comment]
Yes, it points to another port, in case this server was deactivated, I already did another test in the debug file with one of my current servers.

Here's the new debug file with one of the current servers: https://www.zkservidores.com/sourcebans/sb_debug_connection.php

As you can see the problem continues.

@RumbleFrog  @geominorai

**Comment by geominorai** [comment]
@paulocrash Looks like your web server can reach the game server.

What did you set as the `host` and `port` for `sourcebans` in your game server's `database.cfg`?

**Comment by rumblefrog** [comment]
I'd like you to check on the servers that are not reachable, for their banned ips, shown here: https://sbpp.github.io/docs/debugging_connection/

**Comment by crashzk** [comment]
@geominorai follows the host information from database.cfg:
```
"sourcebans"
	{
		"driver"			"default"
		"host"				"sql50.main-hosting.eu"
		//"timeout"			"0"
		"port"				"3306"
	}
```
@RumbleFrog I already did all the FAQ processes that you quoted, I even did, the host of the servers too, the UDP and TCP ports the Web Host also did and even then the problem continues.

**Comment by geominorai** [comment]
I can reach your database server from my Brazil VPS.  I assume you have your login set correctly?

The database host points to a Brazil IP address despite having an `eu` domain extension, so it does not seem to be caused by network distance, at least.

**Comment by crashzk** [comment]
Can in case you need that information, username and password only or something else? @geominorai

**Comment by rumblefrog** [comment]
Here's my view: https://sbpp.ngrok.io/index.php?p=home

Two of the servers aren't reachable via my panel or the SB Discord bot.

**Comment by geominorai** [comment]
@paulocrash I just entered your game server in HLSW and I don't see any convars indicating Sourcemod is installed.

**Comment by crashzk** [comment]
@geominorai as not, I have installed yes:
```
 SourceMod Version Information:
    SourceMod Version: 1.8.0.6047
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6047)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Jun  3 2018 09:41:09
    Built from: https://github.com/alliedmodders/sourcemod/commit/5e14ad8
    Build ID: 6047:5e14ad8
    http://www.sourcemod.net/
L 06/16/2018 - 15:23:52: rcon from "143.202.38.73:39088": command "sm version"
```
@RumbleFrog then the problem would be the correct web host, since one of the servers still shows.

The servers that do not show in case would have to talk to the Host in this case.

**Comment by geominorai** [comment]
What's your indicator for a connection error on the game server side?
Have you tried running `sm_rehash` in the server console?

**Comment by rumblefrog** [comment]
Why are we diving into Sourcemod for A2S query errors?

**Comment by crashzk** [comment]
@geominorai I used the command and nothing, it's still the same thing.
> What's your indicator for a connection error on the game server side?

What do you mean, I do not understand, pardon?

**Comment by crashzk** [comment]
> Why are we diving into Sourcemod for A2S query errors?

Sorry, I did not understand what you mean, sorry about my bad english. :)

**Comment by rumblefrog** [comment]
Server query via A2S is independent of game server Sourcemod or SQL database

**Comment by geominorai** [comment]
I believe his current issue is having trouble connecting from the game server to the database rather than web server to game server, aside from the last two unreachable game servers. 

@paulocrash What error messages are you getting on the game server logs?

**Comment by crashzk** [comment]
@geominorai I do not believe this is it, since it does not show any error of the logs referring to SourceBans, I believe even if it is some block of the web host, as @RumbleFrog did the test in hosting it and it worked I will be reporting to the support of my host web and ask for it to verify the background since in other hosting company the problem does not happen.

In any case, the server error log is attached:
[errors_20180616.log](https://github.com/sbpp/sourcebans-pp/files/2108491/errors_20180616.log)

**Comment by geominorai** [comment]
Do you get any errors if you reload the main plugin with `sm plugins reload sbpp_main`?

If not, then it's talking to the database properly especially since you were able to trigger a manual refresh with `sm_rehash`.

**Comment by geominorai** [comment]
Oh you were referring to the SourceBans page not refreshing live server info. My bad.

**Comment by rumblefrog** [comment]
Yes, the page that request live server info.

**Comment by crashzk** [comment]
Problem solved!

As @RumbleFrog and @CrazyHackGUT mentioned, it would be problem with the same hosting host, I changed the host and problem solved.

**OBS: They blocked all UDP and TCP ports.**
