### ISSUE TITLE
Admin STEAM_1 ID not converted

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#486]
What are the steps to reproduce this issue?
-------------------------------------------
1. Set admin user steam ID to STEAM_1:...
2. Log out
3. Try to log in through Steam

What happens?
-------------
Nothing. Silent fail.

What were you expecting to happen?
----------------------------------
Logged in.

Any logs, error output, etc.?
----------------------------

n/a

Any other comments?
-------------------
As of 1.6.3, if the code is designed to do this, it doesn't work. It took me quite some time to figure out that the reason the Steam login did nothing (log in -> back to main page of Sourcebans NOT logged in) was it being STEAM_1 (which doesn't get converted) instead of STEAM_0. (Other ID formats - at least SteamID64 - DO get converted)

It should also say something when an unknown user logs in, but I'll open a separate issue for that. (ETA: #487)

Per #484 STEAM_1 should function. If not, it should be documented nearby. (@Groruk , did you even bother to verify that it worked before closing that issue? Just wondering. Also, this template was a huge waste of my time that frankly shouldn't be necessary.)

What versions of software are you using?
----------------------------------------
**Operating System:** Linux (Debian jessie)
**SourceBans++ Version:** 1.6.3
**PHP Version:** 5.6.33
**MySQL Version:** MariaDB 10.0.32
**Link to your project:** nope.
**Link to a phpinfo() output:** nope.

**Comment by Groruk** [comment]
> As of 1.6.3, if the code is designed to do this, it doesn't work. It took me quite some time to figure out that the reason the Steam login did nothing (log in -> back to main page of Sourcebans NOT logged in) was it being STEAM_1 (which doesn't get converted) instead of STEAM_0. (Other ID formats - at least SteamID64 - DO get converted)

1.6.3 doesn't auto convert `STEAM_1` to `STEAM_0`... The library for that was introduced in commit e0ba2c20c90b1eec30806c7187731555d5199d6b and the code implementation in 2c5e2f8f94a4fab9274270b71cc621569de8e0be, both after the 1.6.3 release.

----

> Per #484 STEAM_1 should function. If not, it should be documented nearby.

Yes it does in the newest dev release.

----

> Also, this template was a huge waste of my time that frankly shouldn't be necessary.

5 minutes are a `huge waste` of your time... ok then.
