### ISSUE TITLE
Server Connection Issue

### ISSUE THREAD

**Issue by Beaast-exe** [sbpp/sourcebans-pp#491]
What are the steps to reproduce this issue?
-------------------------------------------
1. Login as admin
2. Go to a server page
3. Try to kick/ban anyone

What happens?
-------------
It appears an error of connection.

What were you expecting to happen?
----------------------------------
Banning/Kicking the player

Any logs, error output, etc.?
----------------------------
```
AJAX Call Failed!
 Error: the XML response that was returned from the server is invalid. Received: 
Warning: stream_set_timeout() expects parameter 1 to be resource, boolean given in /var/www/maingaming/bans/includes/CServerRcon.php on line 58

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/maingaming/bans/includes/CServerRcon.php on line 79

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/maingaming/bans/includes/CServerRcon.php on line 79
$('dialog-control').setStyle('display', 'block');ShowBox('Error', 'Can\'t kick BeaastHosting.tk GOTV. Player not on the server anymore!', 'red', '', true);
```

Any other comments?
-------------------
Debug connection output
```
[+] SourceBans "Error Connecting()" Debug starting for server 80.241.215.242:27001

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: Main Gaming #1 | Competitivo | !ws !knife !gloves 

[+] Trying to establish TCP connection
[-] Error connecting #111: Connection refused
```

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 16.04 - x64
**SourceBans++ Version:** 1.6.3
**PHP Version:** PHP 7.2.6-1+ubuntu16.04.1+deb.sury.org+1
**MySQL Version:**  10.3.7-MariaDB
**Link to your project:** https://bans.maingamingcm.tk
**Link to a phpinfo() output:** https://bans.maingamingcm.tk/phpinfo.php

**Comment by Groruk** [comment]
Duplication of #474

**Comment by Groruk** [comment]
>[+] Trying to establish TCP connection
[-] Error connecting #111: Connection refused

>Warning: stream_set_timeout() expects parameter 1 to be resource, boolean given in /var/www/maingaming/bans/includes/CServerRcon.php on line 58

Seems like your TCP traffic is getting blocked, check your firewall settings on both the gameserver and webserver side.
Here are some further debug steps: https://sbpp.github.io/docs/debugging_connection/

**Comment by Beaast-exe** [comment]
i dont have firewall
and the gameserver is in the same vps

**Comment by CrazyHackGUT** [comment]
CSGO? CSGO by default disables RCON (TCP). You should enable him manually with command start argument `-usercon`

**Comment by Beaast-exe** [comment]
Solved by putting **-usercon** in launch parameters
