### ISSUE TITLE
Server Crashing after panorama update/csgo

### ISSUE THREAD

**Issue by last2fall** [sbpp/sourcebans-pp#492]
My server is basically crashing after i try to kick/ban anybody using sourcebans, no error logs or either any logs at all, it just shuts the server and gives no logs at all, any ideas?

**Comment by Groruk** [comment]
First off: We can't help you if you don't provide any information.
Secondly: Please use the [Issue Template](https://github.com/sbpp/sourcebans-pp/blob/v1.x/.github/ISSUE_TEMPLATE/Plugin_bug_report.md)

And lastly: This is likely an issue with SourceMod itself, based on all these issue threads:
https://forums.alliedmods.net/showthread.php?t=308870
https://forums.alliedmods.net/showthread.php?t=308887
https://forums.alliedmods.net/showthread.php?t=308888
https://forums.alliedmods.net/showthread.php?t=308877

So you will need to wait until SourceMod is pushing a fix for this.
