### ISSUE TITLE
Doubt with the ban list

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#493]
What happens?
-------------
When I apply a ban on the servers **(in-game)**, there are times when it does not display it on the SourceBans Banned List, but it is still banned from the server.

For example, I apply the ban on a player:
```sm_ban "TEST" "150" "Breaking Rules"```

It is banned but does not show in the ban list.

**OBS: I do not know if it would have to see, but in my SourceBans is not showing the servers online, due to a blocking of my host, I am already solving this.**

Remembering that this error happened even when displaying the online servers in SourceBans, and many of the BUGS applied by the chat ```!admin``` command did not appear as well.

Most bans to appear would have to be enforced by the ``` sm_ban```  command.

Bans directly applied by SourceBans work normal, show in the banned list and they get banned on the servers.

What were you expecting to happen?
----------------------------------
My question is as follows, even if I do not show the online server on SourceBans the plugins are all on the servers, banishment and other punishment applications should not show anyway on SourceBans?

Any logs, error output, etc.?
----------------------------
[errors_20180704.log](https://github.com/sbpp/sourcebans-pp/files/2173194/errors_20180704.log)
[errors_20180705.log](https://github.com/sbpp/sourcebans-pp/files/2173195/errors_20180705.log)
[errors_20180706.log](https://github.com/sbpp/sourcebans-pp/files/2173196/errors_20180706.log)
[errors_20180707.log](https://github.com/sbpp/sourcebans-pp/files/2173197/errors_20180707.log)

No error apparently related to any SourceBans plugin.

What versions of software are you using?
----------------------------------------
**Operating System:** Linux
**SourceBans++ Version:** 1.6.3
**PHP Version:** 7.2
**MySQL Version:** MARIADB 10.2
**Link to your project:** http://www.zkservidores.com/sourcebans/

**Comment by crashzk** [comment]
Would it be a BUG of the Web Interface or the plugin itself?

**Comment by CrazyHackGUT** [comment]
Plugin.
Seems like plugin can't connect to DB and insert the ban.

**Comment by crashzk** [comment]
Strange is that even without showing the ban of the Web Interface list, the player gets banned from the servers.

In any case I'll be seeing in the plugin part, thanks!
