### ISSUE TITLE
Doubt with the ban list

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#494]
What happens?
-------------
When I apply a ban on the servers **(in-game)**, there are times when it does not display it on the SourceBans Banned List, but it is still banned from the server.

For example, I apply the ban on a player:
```sm_ban "TEST" "150" "Breaking Rules"```

It is banned but does not show in the ban list.

**OBS: I do not know if it would have to see, but in my SourceBans is not showing the servers online, due to a blocking of my host, I am already solving this.**

Remembering that this error happened even when displaying the online servers in SourceBans, and many of the BUGS applied by the chat ```!admin``` command did not appear as well.

Most bans to appear would have to be enforced by the ``` sm_ban```  command.

Bans directly applied by SourceBans work normal, show in the banned list and they get banned on the servers.

What were you expecting to happen?
----------------------------------
My question is as follows, even if I do not show the online server on SourceBans the plugins are all on the servers, banishment and other punishment applications should not show anyway on SourceBans?

Any logs, error output, etc.?
----------------------------
[errors_20180704.log](https://github.com/sbpp/sourcebans-pp/files/2173194/errors_20180704.log)
[errors_20180705.log](https://github.com/sbpp/sourcebans-pp/files/2173195/errors_20180705.log)
[errors_20180706.log](https://github.com/sbpp/sourcebans-pp/files/2173196/errors_20180706.log)
[errors_20180707.log](https://github.com/sbpp/sourcebans-pp/files/2173197/errors_20180707.log)

No error apparently related to any SourceBans plugin.

What versions of software are you using?
----------------------------------------
**Operating System:** Linux
**SourceBans++ Version:** 1.6.3
**PHP Version:** 7.2
**MySQL Version:** MARIADB 10.2
**Link to your project:** http://www.zkservidores.com/sourcebans/

**It would be a duplicate of #493, but I believe it's Plugin's BUG as I was told.**

**Comment by Groruk** [comment]
>It would be a duplicate of #493, but I believe it's Plugin's BUG as I was told.

So why exactly did you open the same issue twice?

---

You can run the plugin in `debug mode` (i.e uncommenting the [debug](https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_main.sp#L56) Line & compiling the plugin).
That will log most of the function calls and query calls made by SourceBans++.

With your problem it should show, that SourceBans++ is storing the bans in the SQLite backup db, because it most likely loses connection to the MySQL database during operation.
The cause for the problem could be a whole array of different factors, e.g: 
  - poor / inconsistent connection between gameserver and database server 
  - [Too many connections](https://dev.mysql.com/doc/refman/5.5/en/too-many-connections.html) to the database server
  - Internal database issues, etc.

Could also be a bug in SourceBans++, but seeing that this is not widespread I would think it's an infrastructure issue.

**Comment by M-archand** [comment]
I noticed this happened to a permanent in game ban I submitted yesterday. Not showing on the website. This is the first time I've ever seen this happen to me.

**Comment by crashzk** [comment]
I think I've already identified the problem...

As SourceBans has its own menu of applying banishes by typing in chat `!admin` you can disable the default SourceMod plugin which would be` basebans.smx`, disabling it works everything normal, either by applying ban through `!admin` and applying by command `sm_ban`.

So just disable the default SourceMod plugin `basebans.smx` if you are finalizing the SourceBans on your servers and the problem is solved.

**Comment by CrazyHackGUT** [comment]
SourceBans automatically try disable `basebans.smx`:
https://github.com/sbpp/sourcebans-pp/blob/57c1576191ad75dbe44490f95e8fef4d6aee0373/game/addons/sourcemod/scripting/sbpp_main.sp#L273-L283
If this doesn't happened, maybe you have wrong permissions on file.

**Comment by crashzk** [comment]
> SourceBans automatically try disable `basebans.smx`:
> [sourcebans-pp/game/addons/sourcemod/scripting/sbpp_main.sp](https://github.com/sbpp/sourcebans-pp/blob/57c1576191ad75dbe44490f95e8fef4d6aee0373/game/addons/sourcemod/scripting/sbpp_main.sp#L273-L283)
> 
> Lines 273 to 283 in [57c1576](/sbpp/sourcebans-pp/commit/57c1576191ad75dbe44490f95e8fef4d6aee0373)
> 
>  BuildPath(Path_SM, filename, sizeof(filename), "plugins/basebans.smx"); 
>  if (FileExists(filename)) 
>  { 
>  	char newfilename[200]; 
>  	BuildPath(Path_SM, newfilename, sizeof(newfilename), "plugins/disabled/basebans.smx"); 
>  	ServerCommand("sm plugins unload basebans"); 
>  	if (FileExists(newfilename)) 
>  		DeleteFile(newfilename); 
>  	RenameFile(newfilename, filename); 
>  	LogToFile(logFile, "plugins/basebans.smx was unloaded and moved to plugins/disabled/basebans.smx"); 
>  } 
> 
> If this doesn't happened, maybe you have wrong permissions on file.

Strange because my never deactivated and do not even try to disable ...

Regarding the permissions I left default, I never modified it.

http://prntscr.com/la419z

Was that the case, or would it have nothing to do with it?
