### ISSUE TITLE
Hide player IPs option should default to on (privacy/GDPR concerns)

### ISSUE THREAD

**Issue by lukefor** [sbpp/sourcebans-pp#496]
Is your feature request related to a problem? Please describe.
-------------------------------------------------------------
For all the years I've run sourcebans, I had no idea IPs of banned players were available publicly until a user raised it with me today. This is a huge privacy concern, especially with GDPR etc.

It's a bit scary that a steam user's IP address is potentially just a google search away

I can't see a good reason why this option should default to showing IPs publicly

Describe the solution you'd like
--------------------------------
As per title

Describe alternatives you've considered
---------------------------------------
N/A

Additional context
------------------
N/A

**Comment by geominorai** [comment]
I also had a user inform me of this and had to change the setting to hide IP addresses in light of GDPR.

Either IP addresses should be hidden by default like suggested, or a checkbox should be added to one of the `/install` pages.

**Comment by Bara** [comment]
Also the country flag.
