### ISSUE TITLE
Sourcebans Settings page not working

### ISSUE THREAD

**Issue by josegoncalvestorres** [sbpp/sourcebans-pp#499]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install Sourcebans 1.7 (Latest version here on GitHub)
2. Go to the settings of sourcebans

What happens?
It gives me this error and dont let me edit anything..

What were you expecting to happen?
----------------------------------

Any logs, error output, etc.?
----------------------------
http://prntscr.com/kgac91
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''30'' at line 4' in /var/www/html/novo/includes/Database.php:77 Stack trace: #0 /var/www/html/novo/includes/Database.php(77): PDOStatement->execute() #1 /var/www/html/novo/includes/Database.php(82): Database->execute() #2 /var/www/html/novo/includes/Log.php(40): Database->resultset() #3 /var/www/html/novo/pages/admin.settings.php(93): Log::getAll(0, '30', '') #4 /var/www/html/novo/includes/page-builder.php(126): require_once('/var/www/html/n...') #5 /var/www/html/novo/index.php(37): build('SourceBans++ Se...', '/admin.settings...') #6 {main} thrown in /var/www/html/novo/includes/Database.php on line 77

Any other comments?
No

What versions of software are you using?
----------------------------------------
**Operating System: Debian 8**
**SourceBans++ Version: 1.6.3 (But it shows 1.7 on footer)**
**PHP Version: 5.6**
**MySQL Version: 5.5.60-0+deb8u1 - (Debian)**
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by CrazyHackGUT** [comment]
https://github.com/sbpp/sourcebans-pp/blob/cdce21c308d63d772e668a5d13077039175d3570/web/includes/Log.php#L30-L41
Dumb query build.
On some PHP versions, PDO adds a quotes anyway to query.

Also i don't understand, why `:search` adds with `str_replace`, when we can just bind this param.

**Comment by josegoncalvestorres** [comment]
But how can I fix?
