### ISSUE TITLE
[Feature Request] New bans time option for certain flags

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#500]
Describe the solution you'd like
---------------------------------------
One option would be to set the ban time for each ADMIN/VIP/ROOT.

**Some examples:**
Players with the flag **"b"**, category **"VIP"**
- Apply ban for up to **45 minutes maximum**;

Players with the flag **"o"**, category **"ADMIN"**
- Apply ban up to **6 hours maximum**;

Players with the flag **"z"**, category **"OWNER/ROOT"**
- Apply permanent ban and any length of time set in the SourceBans settings;

The flags and banned time, we can configure any value in the SourceBans Web Interface or in the SourceBans configurations on the Servers. So we can control who can ban and for how long.

Additional context
------------------
An example of a plugin that has this function would be the **Limit Ban Duration**: https://forums.alliedmods.net/showthread.php?p=1693332 **_(Unfortunately it stopped working and the plugin bugou, no longer works with the new version of SourceBans)_**

**Comment by crashzk** [comment]
Would this upgrade/addition be possible in future upgrades?

**Comment by crashzk** [comment]
I noticed that you can do this upgrade in a different way ...

Use the same way of comms, that only those who have the flag "p" can ban permanent.

> "MaxLength"  "45" // Max allowed punishment length (in minutes) for admins without ADMFLAG_CUSTOM2 (p). 0 disables restriction. Any value > 0 restricts permanent punishment.

**Comment by rumblefrog** [comment]
Can you try this one: https://github.com/Sithranduil/LimitBanDuration

**Comment by crashzk** [comment]
> Can you try this one: https://github.com/Sithranduil/LimitBanDuration

Yes I have seen this plugin, I'm even testing it... Is that in case I want the least plugin on the server, at last I'll be watching.

If this update is possible in the future, thank you for now!
