### ISSUE TITLE
Invoked on and Expires on blank

### ISSUE THREAD

**Issue by josegoncalvestorres** [sbpp/sourcebans-pp#502]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install sourcebans
2. Give mutes bans or gags

What happens?
The Invoked on and Expires on is blank, there is no data there but in mysql database I have. And When editing a ban it gives me and error but aplyes anyway..

Any logs, error output, etc.?
None
Fatal error: Cannot use object of type ADORecordSet_mysqli as array in /var/www/html/pages/admin.edit.ban.php on line 206

What versions of software are you using?
----------------------------------------
**Operating System: Debian 8**
**SourceBans++ Version: 1.7**
**PHP Version:5.6**

**Comment by rumblefrog** [comment]
User switched to 1.6.3 stable to fix this, as 1.7 is not a release yet, but I'm going to keep this open just in case the issue is still present beyond that commit.
