### ISSUE TITLE
Webscript does not support NAT servers

### ISSUE THREAD

**Issue by CosmicHikari** [sbpp/sourcebans-pp#503]
What are the steps to reproduce this issue?
-------------------------------------------
1. Download SRCDS TF2 (232250) to a NAT attached systen
2. Install SourceBans++ Plugin
3. Install web script to same machine as server
4. Add server's external IP to webscript

What happens?
-------------
When I add my server's IP (behind NAT router) to sourcebans webscript the ip MUST be the LAN IP otherwise the connection fails.

What were you expecting to happen?
----------------------------------
I'd expect that because NAT ruling blocks the ability for a LAN IP to connect to its external IP, the webscript would support an "ip alias" that could allow the webscript to still ping the server.

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------
A fix for this might be a bit challenging, but I was just wondering if there's a way to make it so that I can run sourcebans on the same machine as my server while behind NAT so I can ping the server as its lan IP but show the ip on the site as its external IP. It's hard to explain but I'd like to put my LAN server IP in and let the public IP (different from internal) to be shown, since public can't connect to my LAN ip.

What versions of software are you using?
----------------------------------------
**Operating System:** CentOS Linux 7
**SourceBans++ Version:** 1.6.3
**PHP Version:** 7.2
**MySQL Version:** 5.56
**Link to your project:** https://bans.firehostredux.net
**Link to a phpinfo() output:**

**Comment by CrazyHackGUT** [comment]
This is not SourceBans problem.
You should add forwarding rule on your router for pinging ability.

I think, SB++ devs will not do this.

**Comment by CosmicHikari** [comment]
This is not a forwarding rule issue. This is the fact that the server running the sourcebans is not allowed to ping its own ip. NAT routers do not allow their INTERNAL NETWORK to ping their EXTERNAL NETWORK, it is strictly forbidden.

To clarify:

192.168.5.5 cannot ping its external ip of 47.182.52.124 (Not real ips, just example)

**Comment by geominorai** [comment]
This is not an issue specific to SB++.  

See https://www.experts-exchange.com/questions/23141193/Can't-Ping-Public-IP-Address-from-internal-network.html

**Comment by rumblefrog** [comment]
I believe that is the expected behavior of NAT, and this doesn't specifically apply to SB++.

You can try using IPTables and see if you can reroute it internally. We don't have many people running both the server and the web server behind a NAT, so the far reach of this is quite limited.

**Comment by Groruk** [comment]
[NAT Loopback](https://en.wikipedia.org/wiki/Network_address_translation#NAT_loopback) is what your are looking for.

That would allow a server from inside the network to access a service with the external IP.
