### ISSUE TITLE
Error detected in plugin startup

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#507]
What happens?
-------------
There are times that SourceBans does not work on my servers.
```
Errors:
sbpp_main.smx (SourceBans++: Main Plugin): Error detected in plugin startup (see error logs)
sbpp_report.smx (SourceBans++ Report Plugin): Could not find required plugin "sourcebans++"
sbpp_discord.smx (SourceBans++ Discord Plugin): Could not find required plugin "sourcebans++"
sbpp_checker.smx (SourceBans++: Bans Checker): Failed to connect to SourceBans DB, [2003]: Can't connect to MySQL server on '142.44.191.236' (4)
```
These errors shows from time to time, there are moments that only restart the servers already solve, other times I send the plugins again and restart the servers and resolve.

But I did all those processes and it still does not work.

I checked the server error log and it only shows this:
```
L 09/03/2018 - 14:16:09: [SM] Exception reported: Script execution timed out
L 09/03/2018 - 14:16:09: [SM] Blaming: sbpp_main.smx
L 09/03/2018 - 14:16:09: [SM] Call stack trace:
L 09/03/2018 - 14:16:09: [SM]   [1] Line 235, .\sbpp_main.sp::OnPluginStart
```
```
L 09/03/2018 - 17:04:01: [SM] Exception reported: Failed to connect to SourceBans DB, [2003]: Can't connect to MySQL server on '142.44.191.236' (4)
L 09/03/2018 - 17:04:01: [SM] Blaming: sbpp_checker.smx
L 09/03/2018 - 17:04:01: [SM] Call stack trace:
L 09/03/2018 - 17:04:01: [SM]   [0] SetFailState
L 09/03/2018 - 17:04:01: [SM]   [1] Line 75, .\sbpp_checker.sp::OnDatabaseConnected
```
I already checked with the host of my hosting and have no blocking on their part.

I already checked with the host of the game servers and also no blocking on their part.

Any logs, error output, etc.?
----------------------------

The complete error log is attached: [errors_20180903.log](https://github.com/sbpp/sourcebans-pp/files/2346572/errors_20180903.log)

What versions of software are you using?
----------------------------------------
**Operating System:** Linux - CSGO
**SourceBans++ Version:** 1.6.3
**SourceMod Version:** 1.9.0-git6248-linux
**MetaMod Version:** 1.10.7-git966-linux

**Comment by geominorai** [comment]
This is not a SBPP bug.  Your web server is not accepting external database connections on the database port.  It does not even respond to telnet on port 3306 either inside or outside of Brazil.

**Comment by crashzk** [comment]
@geominorai yes, about sbpp_checker.smx yes, I'm already seeing this with the hosting host ...

The question would be the other bug:
```
L 09/03/2018 - 14:16:09: [SM] Exception reported: Script execution timed out
L 09/03/2018 - 14:16:09: [SM] Blaming: sbpp_main.smx
L 09/03/2018 - 14:16:09: [SM] Call stack trace:
L 09/03/2018 - 14:16:09: [SM]   [1] Line 235, .\sbpp_main.sp::OnPluginStart
```
Or would it be due to the sbpp_checker.smx bug?

**Comment by geominorai** [comment]
Looks more like the plugin took too long trying to connect to a database that was not responding and Sourcemod timed out the plugin.

**Comment by CrazyHackGUT** [comment]
SB connects to MySQL DB asynchronously, but not to SQLite.

**Comment by crashzk** [comment]
Solved, apparently the problem was a blockage of my game servers, in case it was more of an IP that had to be released on the firewall, I freed everyone and so far running smoothly.

Thank you all!
