### ISSUE TITLE
Error Connecting [Fixed]

### ISSUE THREAD

**Issue by Karmatik** [sbpp/sourcebans-pp#508]
What happens?
-------------
Hi, I'm having something I think it's an error, because I have opened (In my apache and wifi ports config) opened the ports 27017, and SourceBans keep saying "Error Connecting"

Any logs, error output, etc.?
-------------------
In http://mywebsyte/sb_debug_connection.php:

```
[+] SourceBans "Error Connecting()" Debug starting for server 192.168.1.53:27017

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: JLovers.tf | Jail Lovers | Jailbreak Sv| Jailbreak 2.0 

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[-] Error reading.
```

Any other comments?
-------------------
I tried everything, Im not sure if rcon is need, and if its needed I don't know how to set up, because every tries i tried to set up rcon, it ended with error "Socket bind failed (WSAEACCES)"

What versions of software are you using?
----------------------------------------
**Operating System:*Windows 10 - TF2*
**SourceBans++ Version:*1.6.3*
**PHP Version:*7.2.9*
**MySQL Version:*5.0 12-dev*

PD: Sorry for my bad English, I'm Spanish

**Comment by CrazyHackGUT** [comment]
Rcon required only for KickIt and admin rehashing

**Comment by Karmatik** [comment]
@CrazyHackGUT ok, so rcon is not need, but that doesn't explain what error or bug im having

**Comment by CrazyHackGUT** [comment]
TCP port just is busy by another soft. 
Try use another port.

**Comment by Karmatik** [comment]
@CrazyHackGUT Already did it, keep saying "Error connecting"

**Comment by CrazyHackGUT** [comment]
Try start server from administrator.

**Comment by Karmatik** [comment]
@CrazyHackGUT Nope, it doesn't works, keep saying "Error connecting"

**Comment by Karmatik** [comment]
@CrazyHackGUT Its very strange because right now, I have opened port 27021, in my Apache config i have "Listen 27021" and my tf server is using port 27021, i followed the instructions has the tutorial said "Web port: TCP Game port", And yes, I started my sv as administrator as well

```
[+] SourceBans "Error Connecting()" Debug starting for server ***.***.*.**:27021

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: ***************************

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[o] Stopping here since no rcon password specified.
```

**Comment by geominorai** [comment]
In your original post, it looked like your game server IP was on a LAN address.  Perhaps this is like another case of #503?

**Comment by Karmatik** [comment]
@geominorai No look, I have the ports opened

[IMGUR CAPTURE](https://imgur.com/v1kcOpS)

**Comment by Karmatik** [comment]
In the image the ip is 192.168.1.52 but I already changed it to the correct and keep the same

**Comment by Karmatik** [comment]
@geominorai Now with the public IP and the port forwarding confirmed

```
[+] SourceBans "Error Connecting()" Debug starting for server 84.121.66.230:27021

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: JLovers.tf | Jail Lovers | Jailbreak Sv| Jailbreak 

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[o] Stopping here since no rcon password specified.
```

**Comment by Karmatik** [comment]
I don't know if that's usual but, when I install sourcebans on my http that error is showed

```
There were some warnings while inspecting your setup. The installation can carry on, but some features may not work properly. 
Please refer to the documentation to find possible fixes for these problems.
```

**Comment by CrazyHackGUT** [comment]
**You don't should hang two services on 1 port**. This is reason, why server can't bind TCP port. **Apache already listens this port, and OS refuses request to port.**

Leave default value (`80`) in Apache.

**Comment by Karmatik** [comment]
@CrazyHackGUT Wow, that works, thanks

**Comment by CrazyHackGUT** [comment]
Just close the issue.
![default](https://user-images.githubusercontent.com/12576822/45195439-9a4ed280-b268-11e8-89f4-fae3eaad1789.png)

**Comment by Karmatik** [comment]
Thx everyone for his help
