### ISSUE TITLE
Dissappearing navigation

### ISSUE THREAD

**Issue by 8guawong** [sbpp/sourcebans-pp#511]
What are the steps to reproduce this issue?
-------------------------------------------
1. Goto admin panel
2. Goto main settings
3. Uncheck Enable protest/submit ban/commlist (uncheck one is enough) and save changes
4. 

What happens?
-------------
I think using picture is easier to see the problem

Normal: https://i.imgur.com/9c8ghzi.png
After doing the steps above
Bug: https://i.imgur.com/SMlgnng.png

What were you expecting to happen?
----------------------------------
Only links that was unchecked dissappear

Any logs, error output, etc.?
----------------------------
not sure 

Any other comments?
-------------------
nope

What versions of software are you using?
----------------------------------------
**Operating System: linux**
**SourceBans++ Version: latest as in pic**
**PHP Version: 5.6**
**MySQL Version: :mysql Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3**
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by geominorai** [comment]
You're running the dev version from the repo that has recent changes that are not ready to be deployed in production.  Roll back to an older one, or use a release from https://github.com/sbpp/sourcebans-pp/releases

**Comment by 8guawong** [comment]
yes i know but thought i should still report it  just in case so this bug won't make it in to the next release
