### ISSUE TITLE
File Permissions in Quick Start guide are incorrect?

### ISSUE THREAD

**Issue by xanenightwing** [sbpp/sourcebans-pp#513]
What are the steps to reproduce this issue?
-------------------------------------------
1. attempt to install Sourcebans++ web interface
2. get to the step of adjusting file permissions on web end (either 644 or 774, depending on file/folder)
3. installer verifies the file permissions as suggested by quick start as incorrect

What happens?
-------------
when using the file permissions for the web interface as instructed by the Quick Start Guide, (644 for Config.php, /demos, /images/games, and /images/maps. 774 for /themes_c), the "verification" step says that those files still aren't writable, despite being owned (on linux) by the same user that owns the rest of the files in that web directory area (not counting the occasional root ownership). I have changed the file permissions to 666 for config.php, /demos, /images/games, and /images/maps and to 777 for /themes_c

Any other comments?
-------------------
I would suggest either updating the file permissions on the quick start guide or fixing the permissions that the installer is looking for in the installer files. everything is working now, but having to fix this all manually, without any kind of assistance, is annoying

What versions of software are you using?
----------------------------------------
**Operating System:** Debian Linux 9.5
**SourceBans++ Version:** 1.6.3
**PHP Version:** 7.0.31-1
**MySQL Version:** MariaDB 10.3.9
**Link to your project:** http://nexxy.co/sourcebans
**Link to a phpinfo() output:** http://nexxy.co/phpinfo.php

**Comment by xanenightwing** [comment]
yeah, I just found out that unless the files in /images/games and /images/maps won't be visible to anyone unless they're also in the permission state of 777. so that's broken, too, I guess

**Comment by Groruk** [comment]
Linux Permissions can vary from system to system.
Based on how your system is configured and how your user setup for PHP and Nginx/Apache/Caddy looks like
(Both running on the same user or strictly on separate users or under root what you should never do) these permissions can be different.

---

`777` => would mean that every user on the system can read/write and execute the file which is never a good idea concerning security
`666` => all users can read/write the file (also not a good idea for config files)

---

The permissions shown in the documentation are for the most common type of running PHP and Nginx/Apache/Caddy configuration: Both running on the same user (normally the user created during the webserver installation)

---

If you want to read up on linux permissions:
[Linux Permissions Cheat Sheet](https://github.com/lansana/unix-permissions-cheat-sheet)

**Comment by CrazyHackGUT** [comment]
`User/Group: www-data(33)/33`
I'm sure: `www-data` user doesn't include in your user group (by example, on Ubuntu it has the same name as the user (user `kruzya` and him group `kruzya`)).

That's why setting rights 774 did not help. Linux restricts access from apache (and PHP too). He sees that for others there is only access to reading, and blocks any try execute or write to files.

So reason for "incorrect file permissions" only your hands. You can't set up web-server correctly.
Quick Start designed mainly for shared web-hosting (where you don't have `root` access, and where web server already configured correctly).

**Comment by rumblefrog** [comment]
Yeah previously said, you might want to check the file ownership and perhaps chown them to the correct user.

**Comment by xanenightwing** [comment]
The files are all owned by www-data now, and the files/folders mentioned by
the quickstart guide are set as recommended. everything seems to be working
as intended, but now when I try to view a mod icon that wasn't previously
loaded, it gives me a 403 error. if I set the /images/games directory to
744, I no longer get the 403 error. changing it back to 644, however,
brings back the 403 error. Again, all the files are owned by the user:group
of www-data:www-data. additionally, I am now unable to even browse the web
interface in an FTP client  using my own user (I don't have www-data set up
with any login permissions) since the file permissions are all screwed up
(I do have SSH access, so it's really not an issue), and can only do a few
things through FTP in general. I have my own user in the www-data group,
which is the group/user that apache runs under. I'm not really sure what
else to try, so any extra help is appreciated.

**Comment by CrazyHackGUT** [comment]
On directory you have 774?

**Comment by xanenightwing** [comment]
> On directory you have 774?

on the Maps and Games images directories? no, 744, which is User (Read, Write, Execute), Group/Public (Read). if I turn off the User execute, they no longer are visible to the public, which I find very strange, not to mention the fact that images aren't executable.
