### ISSUE TITLE
There is not possible sign in on 1.6.3 web, 1.6.2 is OK.

### ISSUE THREAD

**Issue by KtsCZ** [sbpp/sourcebans-pp#514]
What are the steps to reproduce this issue?
-------------------------------------------
1. Sign in
2. get home page, but i am not sign in

What happens?
I cant sign in. I try install 1.6.3 web -> dont work, install 1.6.2 web (this is ok) and update on 1.6.3 -> dont work.

What were you expecting to happen?
sign in :)

Any logs, error output, etc.?
```
[Tue Sep 18 15:44:38.472463 2018] [:error] [pid 14920] [client 93.91.243.84:57422] 
PHP Notice:  Undefined index: apikey in /mnt/new_backup/hosted/game_servers/227793_web/install/template/page.6.php on line 79, referer: http://227793_web.
fakaheda.eu/install/index.php?step=5

[Tue Sep 18 15:44:38.472482 2018] [:error] [pid 14920] [client 93.91.243.84:57422] 
PHP Notice:  Undefined index: sb-wp-url in /mnt/new_backup/hosted/game_servers/227793_web/install/template/page.6.php on line 80, referer: http://227793_w
eb.fakaheda.eu/install/index.php?step=5

[Tue Sep 18 15:44:38.472487 2018] [:error] [pid 14920] [client 93.91.243.84:57422] 
PHP Notice:  Undefined index: sb-email in /mnt/new_backup/hosted/game_servers/227793_web/install/template/page.6.php on line 81, referer: http://227793_we
b.fakaheda.eu/install/index.php?step=5
```

But this work with 1.6.2 web

What versions of software are you using?
----------------------------------------
**Operating System:** - ubuntu 14.04.1
**SourceBans++ Version:** 1.6.3
**PHP Version:** PHP 5.5.26-1+deb.sury.org~precise+1 (cli) (built: Jun 15 2015 10:04:01)
**MySQL Version:** mysql  Ver 14.14 Distrib 5.6.35
**Link to your project:** http://227793_web.fakaheda.eu/index.php
**Link to a phpinfo() output:** http://227793_web.fakaheda.eu/phpinfo.php

**Comment by Groruk** [comment]
What kind of login do you mean? Steam, username & password or both?

If you specifically mean the steam login, then double check your `SB_WP_URL` (it is currently pointing to `http:///steamopenid.php`) in your `config.php` that it is pointing to you `your-domain.tld` and that it is also using the right protocol `http` or `https`

---

> PHP Version: PHP 5.5.26-1+deb.sury.org~precise+1 (cli) (built: Jun 15 2015 10:04:01)

Also you should consider updating PHP at this point, because SourceBans++ has a requirement of PHP 5.6 or higher

**Comment by KtsCZ** [comment]
username & password, I don't try steam login. 
You can send me your login and password in hash and i can add it to database.

**Comment by D4rk56** [comment]
Same problem

NGINX : 1.14.0
Php : 7.2.10

**Comment by CrazyHackGUT** [comment]
Can't reproduce on fresh install on localhost.
![default](https://user-images.githubusercontent.com/12576822/46729962-e215af00-cc97-11e8-9821-8ee112407019.png)
Nginx 1.12, PHP 7.2.0

**P.S.**: I've noticed about this problem with nginx when user adds many domains to server. PHP receives only one server (domain name), and sends cookie for this one server (domain name).
On issue starter i see this issue: SB generates always new session.
Just compare `SourceBans_Session` cookie on XAJAX requests (on `Server` page, for example), and on generic (web-page) requests. You should see: SB sends new session **always**.

**Comment by Groruk** [comment]
The newest [dev version](https://github.com/sbpp/sourcebans-pp/archive/v1.x.zip) has some changes regarding the SessionManager.

Could you setup a separate SourceBans++ environment with that dev version (the dev version has some bugs currently which makes it not suitable for production) and check if the session problems still occur?

**Comment by D4rk56** [comment]
Work for me ! Thanks

**Comment by Groruk** [comment]
#554 added a new token based login system to the current dev version.
This should fix all of the inconsistency that the session based system implementation had.

If you still have issues you can use issue #553 to further discuss those issues.
