### ISSUE TITLE
BoxToMask error

### ISSUE THREAD

**Issue by merzi** [sbpp/sourcebans-pp#52]
There is a small failure in BoxToMask function (sourcebans.js) on line 482.
The function checks the element with the id p29 for the right ADMIN_EDIT_GROUPS but the element p24 represents this right.

to fix this issue you must change the line to this:
if(document.getElementById('p24').get('checked'))

**Comment by sarabveer** [comment]
Can you show me a screenshot of this issue. Or how does this affect SourceBans performance?

**Comment by merzi** [comment]
this issue appears if you set the right Add New Mods and don't set the right Edit Groups (screenshot 1) or if you trying to set the right Edit Groups and don't set the right Add New Mods . 

![sourceban_rights_issue1](https://cloud.githubusercontent.com/assets/8248252/9152253/29079ab2-3e21-11e5-82d3-c5b045cbdef8.png)

in the first case it set the both rights (screenshot 2). in the second case it doesn't set it.
![sourceban_rights_issue2](https://cloud.githubusercontent.com/assets/8248252/9152278/6993df86-3e22-11e5-99a7-3af56248514b.png)

**Comment by sarabveer** [comment]
ok, wait for commit.

You could have made a PR
