### ISSUE TITLE
sizeof() parameter not implementing Countable error - Server Admin Page

### ISSUE THREAD

**Issue by SugarD-x** [sbpp/sourcebans-pp#527]
What are the steps to reproduce this issue?
-------------------------------------------
1. Add a server through the web interface.
2. Access the server's Admins page through the link displayed under Server Management.

What happens?
-------------
Upon opening the Admins page, the following error is displayed above the admin list:
`Warning: sizeof(): Parameter must be an array or an object that implements Countable in <website root>\sourcebans\pages\admin.srvadmins.php on line 43`

What were you expecting to happen?
----------------------------------
No error should be displayed.

Any logs, error output, etc.?
----------------------------

Not applicable.

Any other comments?
-------------------
None.

What versions of software are you using?
----------------------------------------
**Operating System:** Windows Server 2012 R2
**SourceBans++ Version:** 1.6.3
**PHP Version:** 7.2.8
**MySQL Version:** 8.0.12
**Link to your project:** http://www.asshatgaming.com/sourcebans
**Link to a phpinfo() output:** Data can be provided upon request.

**Comment by Groruk** [comment]
Already addressed in the newest dev version with 53080d53e5b535d00654989ca315c3036bba1d7d
