### ISSUE TITLE
Cannot login with steam.

### ISSUE THREAD

**Issue by Hexer10** [sbpp/sourcebans-pp#534]
What are the steps to reproduce this issue?
-------------------------------------------
1. Login with steam.

What happens?
-------------
I get redirected to the homepage, without being logged in.

What were you expecting to happen?
----------------------------------
To login with steam.

Any logs, error output, etc.?
----------------------------
Nginx(php) error log:
```
2018/11/13 19:13:48 [error] 1983#0: 
*194 FastCGI sent in stderr: "PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/sb/steamopenid.php on line 79" 

while reading response header from upstream, 
client: 2.xxx.xxx.xxx, 
server: sb.hexah.net, 
request: 
	"GET /steamopenid.php
		?openid.ns = http://specs.openid.net/auth/2.0
		&openid.mode = id_res
		&openid.op_endpoint = https://steamcommunity.com/openid/login
		&openid.claimed_id = https://steamcommunity.com/openid/id/76561198237617428
		&openid.identity = https://steamcommunity.com/openid/id/76561198237617428
		&openid.return_to = https://sb.hexah.net/steamopenid.php
		&openid.response_nonce = 2018-11-13T19:13:47Zp9rDORuG4U5tSE8WrV6o/hK9UnY%3D
		&openid.assoc_handle = 1234567890
		&openid.signed = signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle
		&openid.sig = uhddFi0xM57hrKCi0AAT3VaK6Ok%3D HTTP/2.0", 
			upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", 
			host: "sb.hexah.net", 
			referrer: "https://steamcommunity.com/openid/login
				?openid.ns = http://specs.openid.net/auth/2.0
				&openid.mode = checkid_setup
				&openid.return_to = https://sb.hexah.net/steamopenid.php
				&openid.realm = https://sb.hexah.net
				&openid.ns.sreg = http://openid.net/extensions/sreg/1.1
				&openid.claimed_id = http://specs.openid.net/auth/2.0/identifier_select
				&openid.identity = http://specs.openid.net/auth/2.0/identifier_select"
```

What versions of software are you using?
----------------------------------------
**Operating System:** CentOs 7.2
**SourceBans++ Version:** 1.6.3
**PHP Version:** PHP 7.2.11 
**MySQL Version:** mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
**Link to your project:** https://sb.hexah.net
**Link to a phpinfo() output:** https://www.hexah.net/phpinfo.php

**Comment by Groruk** [comment]
Normally means, that there is no matching SteamID in the `_admins` table.

Make sure that all SteamIDs in the `_admins` table start with `STEAM_0` and not `STEAM_1`

**Comment by Hexer10** [comment]
Yeah that was the issue, I supposed it wanted the steamid64
