### ISSUE TITLE
Webpanel's "Sign-in through Steam" does not work with SteamID64

### ISSUE THREAD

**Issue by FlowingSPDG** [sbpp/sourcebans-pp#535]
Webpanel's Steam login needs SteamID(STEAM_0:1:XXXXXXXX) but SteamID64 is not supported.
sometimes SteamID64 is easier to understand.
Also ,most CSGO config uses SteamID64 (e.g sv_load_forced_client_names_file).

Please Support SteamID64 for webpanel login.
(sorry for bad english)

**Comment by Groruk** [comment]
What do you mean with not supported?

SourceBans++ auto converts SteamIDs to the right format with the upcoming v1.7 (it even has a [fancy conversion lib](https://github.com/sbpp/sourcebans-pp/tree/v1.x/web/includes/SteamID) to do so).

**Comment by FlowingSPDG** [comment]
When SteamID64 is set in "Admin STEAM ID", I can't login thru SteamLogin.
![steamid2](https://user-images.githubusercontent.com/30292185/48771722-6df21080-ed05-11e8-9c92-b692f997315a.png)


But if Normal SteamID is set. I can login.
![steamid](https://user-images.githubusercontent.com/30292185/48771590-28354800-ed05-11e8-97b0-ab3aca9ce66c.png)
Sorry it was poor information :(

**Comment by Groruk** [comment]
Again, with version 1.7 all SteamIDs will get auto converted.
The feature isn't implemented in the current release version 1.6.3

**Comment by FlowingSPDG** [comment]
Okay,Thanks <3 I'll wait for it
