### ISSUE TITLE
sb-callback.php, system-functions.php erros

### ISSUE THREAD

**Issue by alphaearth** [sbpp/sourcebans-pp#537]
Error: the XML response that was returned from the server is invalid. Received: 
Catchable fatal error: Argument 1 passed to trunc() must be an instance of string, string given, called in /home/nottooea/ceza.nottooeasy.tk/includes/sb-callback.php on line 1383 and defined in /home/nottooea/ceza.nottooeasy.tk/includes/system-functions.php on line 104
You have whitespace in your response.

**Comment by CrazyHackGUT** [comment]
Upgrade to PHP 7.x. PHP 5.x doesn't full support for pointing argument types. 5.x allows setting only arrays and classes instance. Strings and integers added in 7.0 or 7.1...
Or you can manually just edit this code.
https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/system-functions.php#L104-L107
Delete `string` and `int`.
```php
function trunc($text, $len)
{
    return (strlen($text) > $len) ? substr($text, 0, $len).'...' : $text;
}
```

I really interested, @Groruk, why SB++ require PHP 5.6 for work, and use feature from 7.x?

**Comment by Groruk** [comment]
[PHP EOL Chart](http://php.net/supported-versions.php)

both `PHP 5.6` and `7.0` will move to End of Life at the end of this year, so it would be the perfect moment to bump the minimum version to `7.1`.

Also the `Requirements` section in the the [README](https://github.com/sbpp/sourcebans-pp/blob/v1.x/README.md) are for [released](https://github.com/sbpp/sourcebans-pp/releases) version and will eventually be bumped when SourceBans++ 1.7 is near a pre-release or release state.

**Comment by geominorai** [comment]
Looking forward to php7's built-in polyfill for #350

**Comment by alphaearth** [comment]
solved
