### ISSUE TITLE
AJAX Call Failed!

### ISSUE THREAD

**Issue by ConnorH-QUT** [sbpp/sourcebans-pp#539]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install sourcebans++ 1.6.3
2. Log in to web panel
3. Click on Admin Panel
4. Observe error

What happens?
-------------
Not really sure what sort of issue it is creating, but whenever I click "Admin Panel" on the sourcebans web panel I just installed, an error pops up labelled "AJAX Call Failed!" (full error message below).

What were you expecting to happen?
----------------------------------
I was expecting it to open without an error.

Any logs, error output, etc.?
----------------------------
https://gist.github.com/MGAU-Sparrow/5a408f0c41101703b8485b317de1b275

What versions of software are you using?
----------------------------------------
Operating System: Linux
SourceBans++ Version: 1.6.3

PHP Version: native (7.0)
MySQL Version: Not sure
Link to your project: Not sure
Link to a phpinfo() output: Not sure

![sbans error](https://user-images.githubusercontent.com/45658556/49582073-92a1e580-f99f-11e8-8cef-50aee82b238d.png)

**Comment by Groruk** [comment]
Seems like PHP can't find your SSL cert file.

You can use `openssl_get_cert_locations()` to check if your PHP installation is pointing to the correct file / dir location (normally it should point to your OpenSSL dir, but that can vary from distro to distro)
```PHP
php -r "print_r(openssl_get_cert_locations());"
```

**Comment by ConnorH-QUT** [comment]
Sorry, but how do I do that? I’m fairly new to this. Is there a website you can link me that shows how to do it?

**Comment by Zm0n** [comment]
Hmm, I just started getting this error as well. It's been running fine on my website with an SSL cert prior to this, and nothing else has changed PHP wise recently.

edit: And now it seems to be working again. Odd.

**Comment by ConnorH-QUT** [comment]
yeah, seems to have fixed itself overnight without my doing anything. I suppose I'll just close this then.
