### ISSUE TITLE
Error logs spamming multiple times

### ISSUE THREAD

**Issue by nanociaglia** [sbpp/sourcebans-pp#540]
L 12/10/2018 - 00:43:08: [SM] Exception reported: Array index out-of-bounds (index 379, limit 66)
L 12/10/2018 - 00:43:08: [SM] Blaming: sbpp_comms.smx
L 12/10/2018 - 00:43:08: [SM] Call stack trace:
L 12/10/2018 - 00:43:08: [SM]   [1] Line 2320, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:43:08: [SM]   [2] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:43:08: [SM]   [3] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback
L 12/10/2018 - 00:43:59: [SM] Exception reported: Array index out-of-bounds (index 379, limit 66)
L 12/10/2018 - 00:43:59: [SM] Blaming: sbpp_comms.smx
L 12/10/2018 - 00:43:59: [SM] Call stack trace:
L 12/10/2018 - 00:43:59: [SM]   [1] Line 2320, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:43:59: [SM]   [2] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:43:59: [SM]   [3] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback
L 12/10/2018 - 00:48:58: [SM] Exception reported: Array index out-of-bounds (index 379, limit 66)
L 12/10/2018 - 00:48:58: [SM] Blaming: sbpp_comms.smx
L 12/10/2018 - 00:48:58: [SM] Call stack trace:
L 12/10/2018 - 00:48:58: [SM]   [1] Line 2320, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:48:58: [SM]   [2] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:48:58: [SM]   [3] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback
L 12/10/2018 - 00:49:07: [SM] Exception reported: Array index out-of-bounds (index 379, limit 66)
L 12/10/2018 - 00:49:07: [SM] Blaming: sbpp_comms.smx
L 12/10/2018 - 00:49:07: [SM] Call stack trace:
L 12/10/2018 - 00:49:07: [SM]   [1] Line 2320, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:49:07: [SM]   [2] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:49:07: [SM]   [3] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback
L 12/10/2018 - 00:51:08: [SM] Exception reported: Array index out-of-bounds (index 379, limit 66)
L 12/10/2018 - 00:51:08: [SM] Blaming: sbpp_comms.smx
L 12/10/2018 - 00:51:08: [SM] Call stack trace:
L 12/10/2018 - 00:51:08: [SM]   [1] Line 2320, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:51:08: [SM]   [2] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 00:51:08: [SM]   [3] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback

Using last version. I think this happen when you mute all people in the server, i guess.,

**Comment by CrazyHackGUT** [comment]
https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_comms.sp#L2408
Replace `GetClientUserId(target)` to `target`. This may help, i think.

**Comment by nanociaglia** [comment]
L 12/10/2018 - 16:32:23: [SM] Exception reported: Client 39 is not connected
L 12/10/2018 - 16:32:23: [SM] Blaming: sbpp_comms.smx
L 12/10/2018 - 16:32:23: [SM] Call stack trace:
L 12/10/2018 - 16:32:23: [SM]   [0] GetClientUserId
L 12/10/2018 - 16:32:23: [SM]   [1] Line 2828, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::GetClientUserId2
L 12/10/2018 - 16:32:23: [SM]   [2] Line 2468, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 16:32:23: [SM]   [3] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 16:32:23: [SM]   [4] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback
L 12/10/2018 - 16:32:31: [SM] Exception reported: Client 39 is not connected
L 12/10/2018 - 16:32:31: [SM] Blaming: sbpp_comms.smx
L 12/10/2018 - 16:32:31: [SM] Call stack trace:
L 12/10/2018 - 16:32:31: [SM]   [0] ReplyToCommand
L 12/10/2018 - 16:32:31: [SM]   [1] Line 2436, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 16:32:31: [SM]   [2] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 12/10/2018 - 16:32:31: [SM]   [3] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback

nope, it doesn't work either

**Comment by nanociaglia** [comment]
any help?

**Comment by rumblefrog** [comment]
Late reply, but you could add an IsClientConnected check prior to that to return.

**Comment by nanociaglia** [comment]
Where? Also should i keep that CrazyHackGUT said?

**Comment by rumblefrog** [comment]
Try removing his suggestion and just adding a check prior to L2408

**Comment by rumblefrog** [comment]
L2383, switch to `IsClientConnected` instead of `IsClientInGame`, apparently in-game doesn't have be connected

**Comment by nanociaglia** [comment]
```
L 01/03/2019 - 22:28:21: [SM] Exception reported: Client index 118 is invalid
L 01/03/2019 - 22:28:21: [SM] Blaming: sbpp_comms.smx
L 01/03/2019 - 22:28:21: [SM] Call stack trace:
L 01/03/2019 - 22:28:21: [SM]   [0] IsClientInGame
L 01/03/2019 - 22:28:21: [SM]   [1] Line 2363, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 01/03/2019 - 22:28:21: [SM]   [2] Line 2408, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::ProcessUnBlock
L 01/03/2019 - 22:28:21: [SM]   [3] Line 557, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\sbpp_comms.sp::CommandCallback
```
