### ISSUE TITLE
after big update with xajax, RCON CONSOLE NOT WORKS

### ISSUE THREAD

**Issue by vem882** [sbpp/sourcebans-pp#55]
all rcon password is correct, but stil then i type commands i see that:

> Error: No RCON password!
> You have to add the RCON password for this server in the 'edit server' 
> page to use this console!

**Comment by sarabveer** [comment]
Fixed in this commit: https://github.com/Sarabveer/SourceBans-Fork/commit/92df7d628f229822549a80efe239345635f64579
