### ISSUE TITLE
mail(): Multiple or mailformed newlines found in additional_header

### ISSUE THREAD

**Issue by BlagoYar** [sbpp/sourcebans-pp#551]
What are the steps to reproduce this issue?
-------------------------------------------
1. I filled all the fields in the "Complaint to the player" 
2. After clicking "Send" a message appeared that the complaint was sent (and this is so) (for verification)

What happens?
-------------
After clicking "Send" also an error occurred, repeated 5 times (see screenshot)
[ScreenShot](https://media.discordapp.net/attachments/298925185367539714/535873157152768021/ScreenShot_-_7.png?width=887&height=499)
I also have permanent errors in the log:
[ScreenShot](https://www.dropbox.com/s/evon22scb0yuhkg/bans.nkm18.ru.error.zip?dl=0)

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 7 x64 SP1
**SourceBans++ Version:** 1.6.3
**PHP Version:** 5.5.38
**MySQL Version:** 5.5.60-MariaDB
**Link to your project:** [Link](https://bans.nkm18.ru)
**Link to a phpinfo() output:** [ScreenShot](https://www.dropbox.com/s/hrmpf8azfpbf0fc/phpinfo%28%29.pdf?dl=0)
Or
[Link to phpinfo one the project](https://bans.nkm18.ru/phpinfo.php)

**Comment by rumblefrog** [comment]
Can you try to replicate with the default theme

**Comment by CrazyHackGUT** [comment]
This is not related with theme, because headers can't be modified with tpl-files.

**Comment by rumblefrog** [comment]
Trying to keep issues consistent with reproduce env but I think I'll let Gro look into it

**Comment by BlagoYar** [comment]
> Can you try to replicate with the default theme
Yes, the same
https://farm5.staticflickr.com/4880/46819032121_3b68e3d16e_o.png

**Comment by Groruk** [comment]
Interesting.

Since it's the first time coming up here, can you verify that [`mail()`](http://php.net/manual/en/function.mail.php) is working outside of SourceBans++, just to make sure that it isn't some kind of configuration issue.

**Comment by CrazyHackGUT** [comment]
```php
<?php
$to = 'your@email.here';
$subject = 'It\'s working?';
$message = 'Hello, world?';

var_dump(mail($to, $subject, $message));
```

You can use this code for testing `mail()`.

**Comment by BlagoYar** [comment]
> ```
> <?php
> $to = 'your@email.here';
> $subject = 'It\'s working?';
> $message = 'Hello, world?';
> 
> var_dump($mail($to, $subject, $message));
> ```
> 
> You can use this code for testing `mail()`.

How to?
What to do with it?

**Comment by CrazyHackGUT** [comment]
Copy this code, insert in any file with extension PHP, save, and open in browser.

Don't forget replace email.

**Comment by BlagoYar** [comment]
> Copy this code, insert in any file with extension PHP, save, and open in browser.

I thought it needed to be inserted into some file or replaced somewhere, since you do not have
**?>**

Therefore I tried both with closing and without.
I inserted, upload to root of site and
HTTP ERROR 500

**Comment by CrazyHackGUT** [comment]
```
?>
```
This is not required.
If you're using not old PHP.

Anyway, i updated code. Small mistake. I written `$mail` as function name. Required just `mail`, without dollar.

**Comment by BlagoYar** [comment]
> Anyway, i updated code. Small mistake. I written `$mail` as function name. Required just `mail`, without dollar.

Did not quite understand. What should be done? Change `$mail` to `mail`? Where should it be done?

**Comment by CrazyHackGUT** [comment]
Just replace:
```php
var_dump($mail($to, $subject, $message));
```
to:
```php
var_dump(mail($to, $subject, $message));
```

**Comment by BlagoYar** [comment]
> Just replace:
> to:
```
> var_dump(mail($to, $subject, $message));
```
After that, only two words
`bool(true)`

Letter came. What does it mean? `$mail` need to change to `mail ` in some file?
