### ISSUE TITLE
PHP Warning:  Division by zero

### ISSUE THREAD

**Issue by BlagoYar** [sbpp/sourcebans-pp#555]
What are the steps to reproduce this issue?
-------------------------------------------
1. I go to the page [muts](https://bans.nkm18.ru/index.php?p=commslist) 

What happens?
-------------
Warnings appear in the logs of my hoster

Any logs, error output, etc.?
----------------------------
[Logs of muts](https://www.dropbox.com/s/hcj6a7iy4l7zerv/bans.nkm18.ru.error.log?dl=0)

What versions of software are you using?
----------------------------------------
**Operating System:** RedHat Linux 3.10.0-962.3.2.lve1.5.24.8.el7.x86_64
**SourceBans++ Version:** 1.6.3
**PHP Version:** 5.5.38
**MySQL Version:** 5.5.60-MariaDB
**Link to your project:** https://bans.nkm18.ru
**Link to a phpinfo() output:** [Archive with phpinfo](https://www.dropbox.com/s/hrmpf8azfpbf0fc/phpinfo%28%29.pdf?dl=0)
Or
[Link to site with phpinfo](https://bans.nkm18.ru/phpinfo.php)

**Comment by Groruk** [comment]
```
[Thu Jan 31 09:52:34.062316 2019] 
[lsapi:notice] [pid 2163797] [client 46.149.94.232:45118] [host bans.nkm18.ru] 
Backend log: PHP Warning:  Division by zero in /var/www/u2703/data/www/bans.nkm18.ru/includes/smarty/plugins/function.math.php(94) : eval()'d code on line 1\n, referer: https://bans.nkm18.ru/index.php?p=servers
```

The warning points to [Smartys math functions](https://www.smarty.net/docsv2/en/language.function.math.tpl).
Now the default theme within SourceBans++ [isn't](https://github.com/sbpp/sourcebans-pp/search?l=Smarty&q=math) using these Smarty math functions, 
but your [custom theme is](https://github.com/brhndursun/SourceBans-StarTheme/search?l=Smarty&q=math).

So you should ask the theme author for a fix, not us.

**Comment by BlagoYar** [comment]
Thanks
