### ISSUE TITLE
AJAX Call FAiled sourcebans 1.6.3

### ISSUE THREAD

**Issue by msaad2110** [sbpp/sourcebans-pp#559]
Hi there,
I'm facing Ajax failed issue
here is the screenshot of it:
https://imgur.com/a/vcqED5Z

PHP Version : 7.0.33

Rest are versions are latest.
Kindly check this out.

**Comment by Groruk** [comment]
Removing line 14 from [includes/Database.php](https://github.com/sbpp/sourcebans-pp/blob/1.6.3/web/includes/Database.php#L14) should fix that issue.

---

> Rest are versions are latest.

![capture](https://user-images.githubusercontent.com/5796460/52420230-f22c8680-2af1-11e9-9b40-cbd5d8035ed2.PNG)

**Comment by msaad2110** [comment]
Hi,
It worked.
Thanks alot <3
