### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'aid' cannot be null in 

### ISSUE THREAD

**Issue by michaelrevou** [sbpp/sourcebans-pp#560]
What are the steps to reproduce this issue?
-------------------------------------------
1.sourcebans/index.php?p=admin&c=bans
2. try import bans
3. and get this error
4.

What happens?
-------------

```
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048
Column 'aid' cannot be null in 
```

What were you expecting to happen?
----------------------------------
import banlist

Any logs, error output, etc.?
----------------------------

```
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048
Column 'aid' cannot be null in 
```
Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**
**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by Groruk** [comment]
>**Operating System:**
**SourceBans++ Version:**
**PHP Version:**
**MySQL Version:**

If you open a issue, please include the basic information of the issue template, to make it easier to fix the issue. Especially the version of SourceBans++ used would be nice.

**Comment by michaelrevou** [comment]
Never mind I fixed it: here is fix: 

admin.bans.php
Line 99: 
Replace with: 
':aid' => (isset($_SESSION['aid']) ? $_SESSION['aid'] : ''),
