### ISSUE TITLE
Error map image doesn't load

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#563]
What are the steps to reproduce this issue?
-------------------------------------------
1.I click the server name
2.The map image isn't the map name, and a map image already existst for that map

What happens?
-------------
The map image isn't working properly

What were you expecting to happen?
----------------------------------
An error with something of sbpp webpannel coding

Any logs, error output, etc.?
----------------------------
Nop

Any other comments?
-------------------
Nop

What versions of software are you using?
----------------------------------------
**Operating System:** Windows10
**SourceBans++ Version:** Latest (1.6.3) Dev Version ("Not dev" version doesn't work for me)
**PHP Version:** 7.2.11
**MySQL Version:** (MariaDB) 10.1.36
**Link to your project:** https://jlovers.ml/
**Link to a phpinfo() output:** sorry but I don't know what this is

**Comment by Groruk** [comment]
> 2.The map image isn't the map name

So you get a wrong image or no image at all? (additional information would help in that case)
Or do you mean the wrong version of the map is being displayed (css and csgo have that problem, because both games use the same map names).

`map image isn't the map name`
if you get a wrong map you should debug the [GetMapImage()](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/system-functions.php#L180-L184) function, to see if either the wrong map named is passed as a parameter or the `SB_MAP_LOCATION` path isn't correct.

---

> and a map image already existst for that map

You can upload your own map images (`admin panel` > `server management` > `upload map image`), that will also override the old image with the new one (useful if you want to swap out css map images for csgo images)

**Comment by ghost** [comment]
> > 2.The map image isn't the map name
> 
> So you get a wrong image or no image at all? (additional information would help in that case)
> Or do you mean the wrong version of the map is being displayed (css and csgo have that problem, because both games use the same map names).
> 
> `map image isn't the map name`
> if you get a wrong map you should debug the [GetMapImage()](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/system-functions.php#L180-L184) function, to see if either the wrong map named is passed as a parameter or the `SB_MAP_LOCATION` path isn't correct.
> 
> > and a map image already existst for that map
> 
> You can upload your own map images (`admin panel` > `server management` > `upload map image`), that will also override the old image with the new one (useful if you want to swap out css map images for csgo images)

No, I get the default "No map image" sb image

**Comment by ghost** [comment]
Ok, checking the page_servers.tpl I found this

`<img id="mapimg_{$server.sid}" style="border-radius: 6px; padding-left: 1px;" width='340' src='images/maps/nomap.jpg'>`

So, the fix should be switch "nomap" for something like {$server.map} or the "placeholder" to get the map name, I don't know what it is

**Comment by Groruk** [comment]
Map image is set during an [ajax request](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/sb-callback.php#L1262). You will have to debug GetMapImage() to see why it can't find the map image.

**Comment by ghost** [comment]
> Map image is set during an [ajax request](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/sb-callback.php#L1262). You will have to debug GetMapImage() to see why it can't find the map image.

Ok, I enabled DebugMode (Admin panel > Web panel settings > Debugmode) but I'm not sure if that's the Debugmode you're talking about, anyways, it doesn't shows me nothing when I click on the server

**Comment by ghost** [comment]
Ok, I looked to older versions and "GetMapImage" function, literally doesn't works on lastest version, I' changed the function to the old, I mean

`function GetMapImage($map)
{
    if (@file_exists(SB_MAP_LOCATION . "/" . $map . ".jpg")) {
        return "images/maps/" . $map . ".jpg";
    }
    return "images/maps/nomap.jpg";
}`

And now it's working, closing issue...

**Comment by ErikMinekus** [comment]
This is still a bug. GetMapImage should return the URL, not the file path. See commit https://github.com/sbpp/sourcebans-pp/commit/6e441a5521fba45147b772c0322d5af8819c1860.

**Comment by TheByKotik** [comment]
I think problem here:
https://github.com/sbpp/sourcebans-pp/blob/a7de6e41f41a641c655b436485bb63a5aefa91b6/web/init.php#L39

`ROOT .` looks here like mistake. Try remove it.
```
define('SB_MAP_LOCATION',  'images/maps');
```

**Comment by borzaka** [comment]
I had problems with it, this is my Directories settings that works:

```
// ---------------------------------------------------
//  Directories
// ---------------------------------------------------
define('ROOT', dirname(__FILE__) . "/");
define('SCRIPT_PATH', 'scripts');
define('TEMPLATES_PATH', 'pages');
define('INCLUDES_PATH', ROOT . 'includes');
define('SB_DEMO_LOCATION', 'demos');
define('SB_ICON_LOCATION', 'images/games');
define('SB_MAP_LOCATION', 'images/maps');
define('SB_ICONS', SB_ICON_LOCATION);
define('SB_DEMOS', ROOT . SB_DEMO_LOCATION);

define('SB_THEMES', ROOT . 'themes/');
define('SB_CACHE', ROOT . 'cache/');
```

**Comment by CrazyHackGUT** [comment]
> `ROOT .` looks here like mistake. Try remove it.

And get broken ability to image upload from Admin panel. Nice idea.

**Comment by TheByKotik** [comment]
> > `ROOT .` looks here like mistake. Try remove it.
> 
> And get broken ability to image upload from Admin panel. Nice idea.

If we [look here](https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/init.php#L33), we can see a simple structure.

```
define('SB_DEMO_LOCATION', 'demos');
define('SB_DEMOS', ROOT . SB_DEMO_LOCATION);
```
And
```
define('SB_ICON_LOCATION', 'images/games');
define('SB_ICONS', ROOT . SB_ICON_LOCATION);
```
But `define('SB_MAP_LOCATION', ROOT . 'images/maps');` break this code structure.

**Comment by CrazyHackGUT** [comment]
> If we look here

You don't should look only on variables nearby. In `pages/admin.uploadmapimg.php` this define is used for moving map image to right place:
https://github.com/sbpp/sourcebans-pp/blob/4c39df177bfa1a236e0a2230e628692c201ae3bc/web/pages/admin.uploadmapimg.php#L31-L37
If you remove `ROOT . ` from this place, this script will try move image to `/pages/images/maps/` instead `/images/maps/`.
