### ISSUE TITLE
Latest Git - Too many MySQL connections on dashboard

### ISSUE THREAD

**Issue by Zm0n** [sbpp/sourcebans-pp#564]
Hey guys, decided to download the latest git just to see if anything has changed from 1.6.3. Noticed I'm getting this on the main dashboard page:

"Error: the XML response that was returned from the server is invalid. Received: SQLSTATE[42000] [1203] User already has more than 'max_user_connections' active connections" 

 Downgraded back to 1.6.3 and that error goes away. Noticed the rest of my site is fine, only occurring on SB. Was anything changed between the official 1.6.3 release and the newest Git in regard to any new connections with the DB? Of course I know it's not an actual release and all, so I expect there to be bugs.

**Comment by Groruk** [comment]
More or less intended.
Prior to 711f3e576ba95362b0c1481d907fe8d2f7694805 SourceBans++ used a persistent PDO connection, which could give some users problems regarding connection timeouts.
Switching to non persistent connections means every ajax request creates it's own database connection, so hitting max connections is now a more common thing.

Increasing the `max_user_connections` is currently the way to go, 
until the whole ajax / SQL subsystem of SourceBans++ is reworked.
