### ISSUE TITLE
AJAX Call failed at login

### ISSUE THREAD

**Issue by SirFulgeruL** [sbpp/sourcebans-pp#565]
What are the steps to reproduce this issue?
-------------------------------------------
1.Login in
2.
3.
4.

What happens?
-------------
When I log in normaly I get a popup with AJAX Call Failed. When I press Ok on the popup it doesn't redirect me but If i go on the index page I am logged in.

What were you expecting to happen?
----------------------------------
Normaly log in and be redirected on the index page or whatever page u get redirected on when you login

Any logs, error output, etc.?
----------------------------

Error: the XML response that was returned from the server is invalid. Received: 
Warning: Missing argument 5 for Plogin(), called in /home/sirfulgerul/web/crowned.ro/public_html/ban/includes/xajax.inc.php on line 1095 and defined in /home/sirfulgerul/web/crowned.ro/public_html/ban/includes/sb-callback.php on line 97
$('msg-red').setStyle('display', 'none');

Any other comments?
-------------------
A picture of the popup: http://img.crowned.ro/brave_4Vru1WoYuJ.png

What versions of software are you using?
----------------------------------------
**Operating System:** Debian 9
**SourceBans++ Version:** 1.6.3

**PHP Version:** 7.0.27
**MySQL Version:** 10.1.26-MariaDB-0+deb9u1 Debian 9.1
**Link to your project:**crowned.ro/ban
**Link to a phpinfo() output:** http://crowned.ro/ban/asd.php

**SourceMod Version:** -
**MetaMod Version:** -

**Comment by Groruk** [comment]
Try the [newest dev version](https://github.com/sbpp/sourcebans-pp/archive/v1.x.zip), most login / authentication functions have been heavily modified in #554.

**Comment by SirFulgeruL** [comment]
@Groruk , the newest dev version works fine but I want to add the "star" theme to it. I tried to add it on the dev version and it doesn't show it properly. Most likely the theme isn't updated for the new version.
Later edit: The issues got fixed when I added the "star" theme as default.

**Comment by Groruk** [comment]
You will have to ask the [original author of the theme](https://github.com/brhndursun/SourceBans-StarTheme) for support on newer (dev) versions.
