### ISSUE TITLE
Bans and mute not saving, charset problem

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#567]
What are the steps to reproduce this issue?
-------------------------------------------
1. Ban a player with special characters in his name.
2. Mute or gag a player with special characters in his name.

What happens?
-------------
All was working fine, no bugs or problems, then my host updated the Mysql Servers from 5.6 to version 5.7...And now the servers uses utf8mb4 for connection and as default collation...I use sourcemod 1.7.3 and sourcebans 1.5.4.6 because its the more stable and no issues...So after updating Mysql, i start getting errors with the names with special characters...I changed the collation in phpmyadmin for the database to be utf8mb4, i changed the source code in plugins too, but still getting this error.

What were you expecting to happen?
----------------------------------
i think the process for saving names to database should be fixed or changed.

Any logs, error output, etc.?
----------------------------
 [sourcecomms.smx] Lost connection to DB. Reconnect after delay.
 [sourcecomms.smx] Query_AddBlockInsert failed: Incorrect string value: '\xF0\x9F\x8E\xB2Ti...' for column 'name' at row 1

Any other comments?
-------------------
In web page too, when trying to ban or mute a player with special characters in his name, i get an error and can't proceed.

What versions of software are you using?
----------------------------------------
**Operating System: Debian
**SourceBans++ Version: 1.5.4.6
**SourceMod Version: 1.7
**MetaMod Version: 1.10.6

**Comment by Groruk** [comment]
> SourceBans++ Version: 1.5.4.6

Have you tried one of the newer [releases](https://github.com/sbpp/sourcebans-pp/releases), or in this case the [newest dev version](https://github.com/sbpp/sourcebans-pp/archive/v1.x.zip) ([compiled plugin artifacts](https://ci.appveyor.com/project/Sarabveer/sourcebans-pp/builds/23012406/artifacts) of the newest plugin)?

Webpanel support for UTF8MB4 was added in 1.6.0 and an experimental support for the plugins in the current dev version 1.7.0

**Comment by ghost** [comment]
i did try last version 1.6.3 but im not interested and no time to update all my plugins to sourcemod 1.8 first, and second the current version i use now is stable and no problems, just now when the host updated the mysql server and the problem it's a shared host, so i can't roll back to version 5.6 of mysql.so is there a way to fix the version 1.5.4.6 tu support mysql 5.7 or the utf8mb4 encoding ?

**Comment by ghost** [comment]
and does the version 1.6.0 support sourcemod 1.7 ? because 1.6.3 only works with sourcemod 1.8

**Comment by Groruk** [comment]
> and does the version 1.6.0 support sourcemod 1.7 ? because 1.6.3 only works with sourcemod 1.8

From the 1.6.0 readme:
```
Requirements

* Source Dedicated Server
  o MetaMod: Source
  o SourceMod: Greater Than or Equal To 1.7
```

but utf8mb4 support for the plugin was first introduced in the current dev release which requires the current stable release of SourceMod (1.9) or higher

----

1.5.4.6 is now almost 3 years old and if you attempt to reverse patch the utf8mb4 support into that version then good luck, because you will most certainly be alone in that endeavor.
There were too many changes in the code between then and now that you would have to closely debug your SourceBans++ version to find out exactly where the whole thing is failing, but the right thing to do in this case is to bite the bullet and upgrade SourceBans++ and your whole tech stack.

**Comment by ghost** [comment]
its mentioned equal to 1.7 but when install the version 1.6.3 it does not load with sourcemod 1.7 because i think metamod 1.10.7 or higher is required too.

**Comment by ghost** [comment]
why i want to use the version 1.5.4.6, is because its stable, no bugs or problems and all functions are working fine...updates should improve or fix problems if they exist already, but as i see with new releases, many new bugs and problems....beside that my game servers are stable now with sourcemod 1.7 and metamod 1.10.6....if i will update those, im not sure if servers will be stable as now, and its so much work to do.
so either i update the whole config ( plugins, sourcemod, sourcebans... ) or i set up my own webhost in a vds and manage everything, or i will try to fix the actual version i use now to support utf8mb4.

**Comment by CrazyHackGUT** [comment]
> utf8mb4 support for the plugin was first introduced in the current dev release which requires the current stable release of SourceMod (1.9) or higher

Not true. SourceMod supports UTF8MB4 only from 1.10.
Library for working with MySQL updated only in 1.10 branch.
