### ISSUE TITLE
Make the ban notice the same when you connect as when you get the ban

### ISSUE THREAD

**Issue by eyal282** [sbpp/sourcebans-pp#570]
Attach the website whenever you try to connect to the server when you're banned, not right on the ban notice, otherwise you can by a single mistaken press never be able to appeal a possibly false ban.

**Comment by sneak-it** [comment]
This is already the current behavior.

Initial ban:
![](https://share.snksrv.com/i/ENNeJj.png)

Subsequent connection:
![](https://share.snksrv.com/i/WBoPxj.png)
