### ISSUE TITLE
Lag occurs when robots has spawned on the MvM server

### ISSUE THREAD

**Issue by MarvelousMLG** [sbpp/sourcebans-pp#573]
What are the steps to reproduce this issue?
-------------------------------------------
1.Build a MvM server
2.Download latest version of Sourcemod and Metamod
3.Add Sourcebans plugin
4.Test play on your server

What happens?
As a title, Lag occurs when robots has spawned on the MvM server.

What were you expecting to happen?
It works normally but It happens everytime.

Any logs, error output, etc.?
----------------------------
Here is the plugins what I use

[SM] Listing 24 plugins:
  01 "Admin File Reader" (1.9.0.6281) by AlliedModders LLC
  02 "Admin Help" (1.9.0.6281) by AlliedModders LLC
  03 "Admin Menu" (1.9.0.6281) by AlliedModders LLC
  04 "Advertisements" (2.0.2) by Tsunami
  05 "Anti-Flood" (1.9.0.6281) by AlliedModders LLC
  06 "Basic Chat" (1.9.0.6281) by AlliedModders LLC
  07 "Basic Comm Control" (1.9.0.6281) by AlliedModders LLC
  08 "Basic Commands" (1.9.0.6281) by AlliedModders LLC
  09 "Basic Info Triggers" (1.9.0.6281) by AlliedModders LLC
  10 "Basic Votes" (1.9.0.6281) by AlliedModders LLC
  11 "Client Preferences" (1.9.0.6281) by AlliedModders LLC
  12 "Fun Commands" (1.9.0.6281) by AlliedModders LLC
  13 "Fun Votes" (1.9.0.6281) by AlliedModders LLC
  14 <Failed> "Nextmap" (1.9.0.6281) by AlliedModders LLC
  15 "Player Commands" (1.9.0.6281) by AlliedModders LLC
  16 "Reserved Slots" (1.9.0.6281) by AlliedModders LLC
  17 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
  18 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  19 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
  20 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
  21 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
  22 "SourceBans++: SourceSleuth" (1.6.3) by ecca, SourceBans++ Dev Team
  23 "Sound Commands" (1.9.0.6281) by AlliedModders LLC

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** Windows Server 2019
**SourceBans++ Version:** v1.6.3
**SourceMod Version:** 1.9.0.6281
**MetaMod Version:** 1.10.7-dev

**Comment by sneak-it** [comment]
Why do you think Sourcebans causes this issue?

**Comment by MarvelousMLG** [comment]
Sorry for late for responding, because lag won't occurs if sourcebans plugins is disabled.

**Comment by CrazyHackGUT** [comment]
Try unload all SB++ plugins except `sbpp_main.smx`

**Comment by rumblefrog** [comment]
Perhaps an SM profiling may be required. Can you also monitor any resources spikes?
