### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by Drmohammad11** [sbpp/sourcebans-pp#580]
hi guys!

Any logs, error output, etc.?
----------------------------
L 07/19/2019 - 15:13:29: SourceMod error session started
L 07/19/2019 - 15:13:29: Info (map "awp_lego_2011") (file "errors_20190719.log")
L 07/19/2019 - 15:13:29: [SM] Exception reported: Invalid Handle in InsertUnbanCallback
L 07/19/2019 - 15:13:29: [SM] Blaming: sbpp_main.smx
L 07/19/2019 - 15:13:29: [SM] Call stack trace:
L 07/19/2019 - 15:13:29: [SM]   [0] ThrowError
L 07/19/2019 - 15:13:29: [SM]   [1] Line 1356, sbpp_main.sp::InsertUnbanCallback
L 07/19/2019 - 18:08:33: Error log file session closed.

What versions of software are you using?
----------------------------------------
**Operating System:** win 2008 r2
**SourceBans++ Version:** SourceBans++ 1.7.0 | Git: 931
**SourceMod Version:** SourceMod 1.9 | build 6281
**MetaMod Version:** MetamodSource 1.10 LastVersion

**Comment by CrazyHackGUT** [comment]
https://github.com/sbpp/sourcebans-pp/blob/d17de7cb5b9b49ee69c50331cfaf100d8be73ed1/game/addons/sourcemod/scripting/sbpp_main.sp#L1354-L1357
lol

**Comment by CrazyHackGUT** [comment]
https://github.com/sbpp/sourcebans-pp/blob/d17de7cb5b9b49ee69c50331cfaf100d8be73ed1/game/addons/sourcemod/scripting/sbpp_main.sp#L1298
Try remove this line, recompile and check.

**Comment by TheByKotik** [comment]
This function is very strange.
We delete datapack and pass it like argument.
https://github.com/sbpp/sourcebans-pp/blob/d17de7cb5b9b49ee69c50331cfaf100d8be73ed1/game/addons/sourcemod/scripting/sbpp_main.sp#L1298
https://github.com/sbpp/sourcebans-pp/blob/d17de7cb5b9b49ee69c50331cfaf100d8be73ed1/game/addons/sourcemod/scripting/sbpp_main.sp#L1335
I'm think function should be like this:
https://gist.github.com/TheByKotik/6aaa3fe5db778db6635c4f324e1925d6

**Comment by geominorai** [comment]
@TheByKotik Can't free it there while the threaded query is still running.  The callback function still needs it even after the current function finishes running.

**Comment by TheByKotik** [comment]
> @TheByKotik Can't free it there while the threaded query is still running. The callback function still needs it even after the current function finishes running.

I know what no need delete in there.
I suggested a fix above.
(But did not create PR besause not test it).

**Comment by geominorai** [comment]
Oh, my bad.  The suggested fix also works.
