### ISSUE TITLE
steam login error

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#583]
What are the steps to reproduce this issue?
-------------------------------------------
1.tried to login thru the steam login on the login page
2.
3.
4.

What happens?
-------------
shows a error

What were you expecting to happen?
----------------------------------
for it to log in thru steam

Any logs, error output, etc.?
----------------------------

Warning: count(): Parameter must be an array or an object that implements Countable in /home/wp_izjzhj/zenteral.club/bans/steamopenid.php on line 79

Warning: Cannot modify header information - headers already sent by (output started at /home/wp_izjzhj/zenteral.club/bans/steamopenid.php:79) in /home/wp_izjzhj/zenteral.club/bans/steamopenid.php on line 93

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:linux**
**SourceBans++ Version:1.6.3**

**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**SourceMod Version:**
**MetaMod Version:**

**Comment by Groruk** [comment]
```PHP
Warning: count(): Parameter must be an array or an object that implements Countable in /home/wp_izjzhj/zenteral.club/bans/steamopenid.php on line 79
```

---

https://github.com/sbpp/sourcebans-pp/blob/16e1db5395e41bc7a208b107de96e5437bb9063e/web/steamopenid.php#L76-L79

For `count` to fail in L79 the `$result` of PDO's fetch would be false and that would mean:
a) The MySQL query failed
	-> In that case check your PHP error log for more information

or b) There is no admin in your SourceBans++ database that would match the SteamID that tries to login
	-> In that case check your `sb_admins` table and make sure the correct SteamID is set AND make sure that the SteamID starts with `STEAM_0` and not `STEAM_1`

**Comment by ghost** [comment]
it was the steamid, thank you so much

**Comment by sashajov** [comment]
`AND make sure that the SteamID starts with STEAM_0 and not STEAM_1`
@Groruk I love you :D

**Comment by rafarrw** [comment]
` AND make sure that the SteamID starts with STEAM_0 and not STEAM_1`
@Groruk thanks, it solved my problem 😄 👍
