### ISSUE TITLE
Current license incompatible with GPLv3

### ISSUE THREAD

**Issue by Headline** [sbpp/sourcebans-pp#584]
Hello. 

If this wasn't brought to your attention I'd like to do so formally on here.

The Creative Commons BY-SA 4.0 license is only one-way compatible with GPLv3. This means that a Creative Commons BY-SA 4.0 work may be distributed under the terms of GPLv3, however a GPLv3 work cannot be released under the terms of Creative Commons BY-SA 4.0. 

By this project existing as a SourceMod plugin, you have no choice but to release your work under the terms of the GNU GPL v3.

I suggest this be changed as soon as possible, thanks.

**Comment by Groruk** [comment]
Thank you, for letting me know.

One of those stupid mistakes, where I didn't check license compatibility when I started to maintain this project and kept on using (and updating) the old license.
Should have checked that in the first place.

Sorry for the incontinence.

**Comment by CrazyHackGUT** [comment]
Well, this is all nice, but... You can't just change license, because this is a fork.
Original SourceBans is distributed by [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/). Maybe we should open him and read before any changes like this?

>  If you remix, transform, or build upon the material, you must distribute your contributions **under the same license as the original**.

**Comment by Groruk** [comment]
Based on the wording of the `Sourcemod License`, the original CC-BY-NC-SA 3.0 license could have been incompatible from the get go.

https://github.com/alliedmodders/sourcemod/blob/master/licenses/LICENSE.txt

> You must obey the GNU General Public License in all respects for all other code used.

"All other code" can be interpreted very differently, it could only include the code working with Sourcemod or the whole project, not a clear formulation.

> As a final exception to the above, any derivative works created prior to this 
date (July 31, 2007) may be exclusively licensed under the GNU General Public 
License version 2 (without an "or any higher version" clause) if and only if 
the work was already GNU General Public License 2.0 exclusive.  This clause is 
provided for backwards compatibility only.

The backwards clause of the license is also only allowing GPLv2, which would also be incompatible with CC-BY-NC-SA 3.0

**Comment by Headline** [comment]
@CrazyHackGUT in this case you *can* just switch the license. Regardless of what was said this project is and always has been GPLv3.

**Comment by peace-maker** [comment]
The web part of the project is independent from SourceMod and has it's own license. The plugins were always under GPL. So this is actually an invalid change.

Please make sure the SB++ fork conforms to the original CC-BY-NC-SA 3.0 license of the web panel. This [came up before](https://forums.alliedmods.net/showthread.php?p=2226940#post2226940), when this fork was started and caused some bad blood.

Awesome work by the way! 😃
