### ISSUE TITLE
i cannot ban player on Ban Submissions

### ISSUE THREAD

**Issue by Drmohammad11** [sbpp/sourcebans-pp#587]
What are the steps to reproduce this issue?
-------------------------------------------
1. go to web panel sb
2. admin panel > bans
3. click Ban submissions
4. ban a player on listed

What happens?
-------------
not work !!

What were you expecting to happen?
----------------------------------
the player ban

Any logs, error output, etc.?
----------------------------
notthing error!!
http://uupload.ir/files/yh9c_2.png

What versions of software are you using?
----------------------------------------
**Operating System:** win 2008 r2
**SourceBans++ Version:** SourceBans++ 1.7.0 | Git: 931
**PHP Version:** 7.1
**MySQL Version:** 5.6
**Link to your project:** ---
**Link to a phpinfo() output:** ---

**Comment by rumblefrog** [comment]
So what happens when you click ban? Does it just refresh the page? Can you provide a gif perhaps?

**Comment by Drmohammad11** [comment]
when i click on ban nothing happens !!
