### ISSUE TITLE
How to disable logging? Now sourcebans.log is flooding by all DB queries...

### ISSUE THREAD

**Issue by WeirdPhrog** [sbpp/sourcebans-pp#588]
How to disable logging? Now sourcebans.log is flooding by all DB queries...

**Comment by Groruk** [comment]
Either: 
a) use the plugins from the SourceBans++ [release page](https://github.com/sbpp/sourcebans-pp/releases), they are compiled with debugging turned off.

or 

b) comment out the `#define DEBUG` line in your `sbpp_main.sp` file and recompile it to turn off debugging.

Also, next time fill out the issue template please, to give us some info about the SourceBans++ version you are running and your environment (and if you find the issue template useless, then better use the [discord](https://discord.gg/4Bhj6NU))
