### ISSUE TITLE
Help a new person

### ISSUE THREAD

**Issue by nuck98** [sbpp/sourcebans-pp#589]
What are the steps to reproduce this issue?
-------------------------------------------
1.
2.
3.
4.

What happens?
-------------
Hi, i'm new in sourcebans or any theme about APIs. So i don't know how to install or active Sourcebans in my server, can anybody help me?
Important Datas: 
My server is of CSGO
My server are hosted for GarrysHost i mean its 24/7 online, i pay for it
I'm new again xd
I had read the " https://sbpp.github.io/docs/ " but anyway i cant.
I tried see videos on youtube but the videos are very olds and i don't know if i cant because i'm new or because i'm stupid.

Oh and another important fact: My default bans system is defective, or at least this was communicated to me by other people who had the same problem with the same Host, to which I am going, they recommended that I install SB but I don't know how.
An example: I shot it! Ban 0 KrapZZi Hacks
And when the map changes, the ban is gone

What were you expecting to happen?
----------------------------------

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------
My steam: https://steamcommunity.com/id/krapzzi/
My Discord: KrapZZi#5088

I say it back, I'm new!
The problem of origin is that my bans system is wrong by default, so I was recommended to install Sourcebans, but the only thing I did (which I think was little because of that does not work for me) was to move what would be the "Game" folder all to their corresponding paths (the plugins folder to the plugins folder, the scripts folder to the scripts folder, that is, the only thing I did was to transfer the files from the .zip to the sv panel, but then do not configure do not touch anything else, do not enter to any .cfg or use keys or anything)
As I am new and I do not understand anything, I would like to know if someone willingly wants it or if it can resolve the issue.

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**

**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**SourceMod Version:**
**MetaMod Version:**

**Comment by geominorai** [comment]
GitHub's issue tracker is not where to go for setup support.  Join the Discord server at https://discord.gg/4Bhj6NU and ping the @Support group in the #help-support channel.
