### ISSUE TITLE
OpenID Login bscub() Error

### ISSUE THREAD

**Issue by romkazor** [sbpp/sourcebans-pp#59]
Hello, when i try login with OpenID i get
Fatal error: Call to undefined function bcsub() in /var/www/html/mysite/sourcebans/steamopenid.php on line 41

**Comment by sarabveer** [comment]
PHP Version, need 5.4 or higher

**Comment by romkazor** [comment]
yes, 5.4.16

**Comment by sarabveer** [comment]
do you have a modified php, since this function is from php4

should be working

**Comment by romkazor** [comment]
just need install php-bcmath
but after login i return to my site and nothing

**Comment by sarabveer** [comment]
steam_0 or steam_1

**Comment by romkazor** [comment]
I dont uderstand about steam_0

**Comment by sarabveer** [comment]
In SourceBans, did you put your ID in as STEAM_0:X:XXXXXXXXX Or STEAM_1:X;XXXXXXXX

It's supposed to be STEAM_0:X:XXXXXXXXX

**Comment by WildCard65** [comment]
Why not make SB not care what the number after STEAM_ before the first : is

**Comment by sarabveer** [comment]
SB does care:

If a game uses STEAM_1, it inputs STEAM_1 into the game.

If a game uses STEAM_0, it inputs STEAM _0 into the game.

But the ID on the webpanel has to be STEAM_0

**Comment by WildCard65** [comment]
I'm pretty sure SM doesn't care about that number so why should SB care?

**Comment by sarabveer** [comment]
Well, SB doesnt care, the OpenID does. It only gives back a STEAM_0 response.

**Comment by WildCard65** [comment]
Then make SB handle the OpenID response to uncare about it.

**Comment by sarabveer** [comment]
Its not OpenID, its Steam Implementation OpenID

The SteamID API only gives back STEAM_0.

**Comment by duhow** [comment]
Despite SB has a OpenID library, is only used for Steam login. It has to associate something with the answer (in this case, Steam ID with users / admins registered). If you want to login using other OpenID authentications (like Google Account or others), it has to be developed.

**Comment by sarabveer** [comment]
@duhow We don't need Google or any other OpenID login since every account has a steamid, not every account has a gmail, or etc

Can the OP please update if the issue is Fixed?

**Comment by duhow** [comment]
I know, I was just explaining it... ;)

**Comment by romkazor** [comment]
Ok, i changed steam id format in web sourcebans and its work!
