### ISSUE TITLE
Feature Request - Integration to forums software

### ISSUE THREAD

**Issue by shadowtor** [sbpp/sourcebans-pp#597]
Feature Request
Would be great to have some sort of integration to the different Forum software (e.g. IPBoard)
Allowing a simple interface to a-sync when a user is banned from the forums or permissions on forums - sourcebans etc.

**Comment by rumblefrog** [comment]
I think this goes way beyond the scope of the project. 

Would not likely be feasible for core project and would probably better off as a plugin, but unfortunately, we don't have a plugin system yet.

**Comment by Groruk** [comment]
Just like @rumblefrog said, forum integration isn't really realizable for the core SBPP team, there are too many different forums (some of them quite expensive) and in the end it would cost hundreds of hours for the implementation and maintenance of those integrations.

That is something the end user has to do (most forums offer plugin support and most of the important data in SourceBans++ lives in the underlying MySQL database)
