### ISSUE TITLE
Squard/non-source

### ISSUE THREAD

**Issue by shadowtor** [sbpp/sourcebans-pp#598]
Describe the solution you'd like
--------------------------------
Integration of non-source Games or have dummy servers/globals to select from so users can still appeal/report bans per usual
Specifically I am looking to have squad/arma/Minecraft connected to sourcebans and have it there so it works in with current good servers (1 system for bans/appeals)

**Comment by Hackmastr** [comment]
Your only goal is for players to be able to appeal/report bans?

**Comment by shadowtor** [comment]
Mmm sorry, was trying to explain as much as I could process in my head...

But maybe allow for admins to add manual bans, but users can report (for admin to review) and appeal to a ban

Tbh, squad has rcon connectivity so would be interested if SB++ could connect anyway? Just haven't looked though enough of the code to see where can modify the connections and game settings.
________________________________

**Comment by The-Doggy** [comment]
So you just want a web panel to manually ban users and have reports/appeals? Seems like something that could be done with just forum software tbh and way out of scope for this project. If you want something like that you'd be better off making it yourself
