### ISSUE TITLE
Security: IP Displays to users not logged in

### ISSUE THREAD

**Issue by matternz** [sbpp/sourcebans-pp#599]
IP of banned player is displayed in the url to users not logged in.
I've only managed to test this on SourceBans++ Version:1.5.4.7. If anyone else can test on later versions would be appreciated.

What are the steps to reproduce this issue?
-------------------------------------------
1.  IP Ban a Player
2. Log out, click on that player from dashboard
3.  url contains the ip address but doesn't display it on the browser just in the url.
index.php?p=banlist&advSearch=XXX.XXX.XXX.XXX&advType=ip&Submit

**Comment by rumblefrog** [comment]
Can confirm it still exists within 1.7.0.931
