### ISSUE TITLE
Error - Query_VerifyBlock failed

### ISSUE THREAD

**Issue by RED4911** [sbpp/sourcebans-pp#6]
The logs are constantly gives an error .

L 01/17/2015 - 17:30:29: SourceMod error session started
L 01/17/2015 - 17:30:29: Info (map "de_dust2") (file "errors_20150117.log")
L 01/17/2015 - 17:30:29: [sourcecomms.smx] Lost connection to DB. Reconnect after delay.
L 01/17/2015 - 17:30:29: [sourcecomms.smx] Query_VerifyBlock failed: Lost connection to MySQL server at 'reading authorization packet', system error: 0
L 01/17/2015 - 18:35:51: Error log file session closed.

**Comment by sarabveer** [comment]
It means your Server is lost connection to your MySQL server. Nothing to be worried about. Unless there is an network issue, or an issue with your MySQL server.
