### ISSUE TITLE
ModSecurity for Apache is blocking some pages of the WebPanel

### ISSUE THREAD

**Issue by borzaka** [sbpp/sourcebans-pp#600]
What are the steps to reproduce this issue?
-------------------------------------------
1. configure [ModSecurity for Apache](https://phoenixnap.com/kb/setup-configure-modsecurity-on-apache)
2. use the recommended, latest [OWASP ModSecurity Rules](https://github.com/SpiderLabs/owasp-modsecurity-crs)
3. login to the WebPanel
4. try to edit an existing Web Admin or Server Admin group
`index.php?p=admin&c=groups&o=edit&type=web&id=1`
or
`index.php?p=admin&c=groups&o=edit&type=srv&id=1`

What happens?
-------------
The page goes `403 Forbidden`

What were you expecting to happen?
----------------------------------
Fully working WebPanel as when the ModSecurity was disabled.

Any logs, error output, etc.?
----------------------------
`/var/log/apache2/error.log`
```
[Fri Sep 13 22:52:10.559881 2019] [:error] [pid 19383] [client x.x.x.x:52711] [client x.x.x.x] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/modsecurity/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "696"] [id "920350"] [msg "Host header is a numeric IP address"] [data "xxx.xxx.xxx.xxx"] [severity "WARNING"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "xxx.xxx.xxx.xxx"] [uri "/~sourcebans/index.php"] [unique_id "XXwBeqyOMyD1AQFb1yX7zAAAAAU"]
[Fri Sep 13 22:52:10.574475 2019] [:error] [pid 19383] [client x.x.x.x:52711] [client x.x.x.x] ModSecurity: Warning. Match of "rx (?:\\\\x1f\\\\x8b\\\\x08|\\\\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\\\\b|gif)|B(?:%pdf|\\\\.ra)\\\\b)" against "RESPONSE_BODY" required. [file "/etc/modsecurity/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "105"] [id "953120"] [msg "PHP source code leakage"] [data "Matched Data: <? found within RESPONSE_BODY: <!DOCTYPE html>\\x0a<html>\\x0a    <head>\\x0a        <meta http-equiv=\\x22Content-Type\\x22 content=\\x22text/html; charset=utf-8\\x22 />\\x0a        <title>Edit Groups | SourceBans++</title>\\x0a        <link rel=\\x22Shortcut Icon\\x22 href=\\x22themes/default/images/favicon.ico\\x22 />\\x0a        <script type=\\x22text/javascript\\x22 src=\\x22./scripts/fontawesome-all.min.js\\x22></script>\\x0a        <script type=\\x22text/javascript\\x22 src=\\x22./scripts/sourcebans.js\\x2..."] [severity "ERROR"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "OWASP_CRS"] [tag "OWASP_CRS/LEAKAGE/ [hostname "xxx.xxx.xxx.xxx"] [uri "/~sourcebans/index.php"] [unique_id "XXwBeqyOMyD1AQFb1yX7zAAAAAU"]
[Fri Sep 13 22:52:10.575329 2019] [:error] [pid 19383] [client x.x.x.x:52711] [client x.x.x.x] ModSecurity: Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/modsecurity/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "75"] [id "959100"] [msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] [tag "anomaly-evaluation"] [hostname "xxx.xxx.xxx.xxx"] [uri "/~sourcebans/index.php"] [unique_id "XXwBeqyOMyD1AQFb1yX7zAAAAAU"]
[Fri Sep 13 22:52:10.575480 2019] [:error] [pid 19383] [client x.x.x.x:52711] [client x.x.x.x] ModSecurity: Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/modsecurity/rules/RESPONSE-980-CORRELATION.conf"] [line "96"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (score 4): individual paranoia level scores: 4, 0, 0, 0"] [tag "event-correlation"] [hostname "xxx.xxx.xxx.xxx"] [uri "/~sourcebans/index.php"] [unique_id "XXwBeqyOMyD1AQFb1yX7zAAAAAU"]
```

Any other comments?
-------------------
I don't fully understand ModSecurity and how it's working exactly. Looks like it's scoring some events and findings, and if it's reaching some level, blocks further access to that page.
I don't know it's related or not, but I used HTTPS.
I don't have a domain, I use the IP address for reaching the WebPanel.

Disturbing ModSecurity error message:
> PHP source code leakage

What versions of software are you using?
----------------------------------------
**Operating System:** `Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux`
**SourceBans++ Version:** `1.7.0 | Git: 931`
**PHP Version:** `7.3.4-2`
**MySQL Version:** `mariadb  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
**Link to your project:** Sorry, I don't want to post it here.
**Link to a phpinfo() output:** ModSecurity also blocking phpinfo(), but I don't want to post it here. 

If you need the last two info, contact me on Discord.

**Comment by rumblefrog** [comment]
No idea what it's referring to, also 95* rules to trigger a lot of false-positives with other projects as well.
