### ISSUE TITLE
Pressing the Comms/Delete Block or Bans/Delete Ban button does not delete Block/Ban

### ISSUE THREAD

**Issue by monsterbnd** [sbpp/sourcebans-pp#607]
What are the steps to reproduce this issue?
-------------------------------------------
1. Pressing the Comms/Delete Block or Bans/Delete Ban button does not delete Block/Ban.
2. Pressing the Comms/Unmute or Bans/Unban button does not Unmute/Unban.

What happens?
-------------
Pressing the Comms/Delete Block or Bans/Delete Ban button does not delete Block/Ban.
Pressing the Comms/Unmute or Bans/Unban button does not Unmute/Unban.

What were you expecting to happen?
----------------------------------
Fix error.

Any logs, error output, etc.?
----------------------------
Browser console log.
Uncaught SyntaxError: Unexpected end of input			index.php?p=commslist:680
Uncaught SyntaxError: Unexpected end of input 			index.php?p=banlist:800 

Any other comments?
-------------------
none

What versions of software are you using?
----------------------------------------
**Operating System:**
Distribution Name: Ubuntu
Distribution Version: 18.04.2 LTS (Bionic Beaver)
Linux Kernel: 4.15.0-58-generic
**SourceBans++ Version:**
SourceBans++ 1.7.0 | Git: 931
**PHP Version:**
php-fpm: PHP Version 7.3.9-1+ubuntu18.04.1+deb.sury.org+1
**MySQL Version:**
mysqld Ver 5.7.27-0ubuntu0.18.04.1 for Linux on x86_64
**Link to your project:**
xxx
**Link to a phpinfo() output:**
https://drive.google.com/open?id=1x8jG9DT4y0Q82KMmKJnT4xhfPivhIbxt

**Comment by Hackmastr** [comment]
If you open the browser console, do you see any errors?

**Comment by CrazyHackGUT** [comment]
Strange question.
Issue creator already attached console error log.

**Comment by Hackmastr** [comment]
Ah thank you @CrazyHackGUT . I missed it.

**Comment by borzaka** [comment]
I'am experiencing the same issue. I try to add some additional info.
I have problem when clicking on the `Unban` button.

The generated link looks like this in the source code:
`<a href='#' onclick='UnbanBan('9', '9b275dab95f516d0507e7511922496d5', '', 'Amickor Lövöck Remegeck', 1, false);return false;' target='_self'> <i class="fas fa-undo fa-lg"></i> Unban </a>`

Google Chrome says `Uncaught SyntaxError: Unexpected end of input` in the console when clicking on the button.

Google Chrome sees the link as this:
![image](https://user-images.githubusercontent.com/1230402/66069303-60c1c700-e54f-11e9-9dfa-75bf132fda00.png)

Clearly some wrong `'` and `"` placement somewhere here probably:
https://github.com/sbpp/sourcebans-pp/blob/4eb027059a9b72d85d199546356bd519db1528a3/web/pages/page.banlist.php#L566

I'am using the latest master downloaded yesterday (2019.10.02.)
