### ISSUE TITLE
Replace IpToCountry.csv with maxmind's mmdb

### ISSUE THREAD

**Issue by Groruk** [sbpp/sourcebans-pp#609]
Is your feature request related to a problem? Please describe.
-------------------------------------------------------------

Right now the IpToCountry function is extremly slow caused by the CSV parsing / crawling speed

Edit: after longer discussion mmdb from maxmind sounds like a good alternative

Describe the solution you'd like
--------------------------------

Moving the IpToCountry data into the database would drastically improve performance. 

Describe alternatives you've considered
---------------------------------------

Additional context
------------------

**Comment by Hackmastr** [comment]
I'd suggest using sqlite provided by maxmind. 
https://github.com/maxmind/GeoIP2-php

**Comment by rumblefrog** [comment]
What's the feasibility of upgrading the database down the road? Will we bundle it with the updater?

**Comment by Groruk** [comment]
>Will we bundle it with the updater?

Yes, basically another subroutine when the updater detects an older database version, it will also update the GeoIP table

**Comment by geominorai** [comment]
I also recommend the local file approach.  No need to worry about how to update it -- just occasionally pop in a new GeoLite2 file to the repo or release zip like SourceMod.  Or if we don't want to bundle it, have the installer fetch the latest copy off https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
