### ISSUE TITLE
mysqli_real_connect library mismatch

### ISSUE THREAD

**Issue by Xbonnik** [sbpp/sourcebans-pp#62]
Hey

Im getting this error, what to do?

Warning: mysqli_real_connect(): Headers and client library minor version mismatch. Headers:50544 Library:50625 in /var/www/sourcebans/includes/adodb/drivers/adodb-mysqli.inc.php on line 117

**Comment by sarabveer** [comment]
MariaDB is the culprit

**EDIT:** Its not MariaDB, diff error.

**Comment by duhow** [comment]
Are you sure that it's using MariaDB? Seems like using **old MySQL**.

**Comment by sarabveer** [comment]
@duhow Does ADOdb support detecting either MySQL or MariaDB?

**Comment by duhow** [comment]
You should already know it, you are using it... xD

> ADOdb is a database abstraction library for PHP
> 
> It currently supports an amazing number of databases, thanks to the wonderful ADOdb community: **MySQL**, PostgreSQL, Interbase, Firebird, Informix, Oracle, MS SQL, Foxpro, Access, ADO, Sybase, FrontBase, DB2, SAP DB, SQLite, Netezza, LDAP, and generic ODBC, ODBTP.

**Comment by Xbonnik** [comment]
Im using MySQL. 5.6

 "5.6.25-1~dotdeb+7.1"

**Comment by sarabveer** [comment]
@duhow Doesn't say MariaDB lol

**Comment by duhow** [comment]
Try [googling it](http://bfy.tw/1t7s). Maybe you need to update PHP, as you are using a **dev version of MySQL**.

**Comment by Xbonnik** [comment]
Got it to work by downgrade libmysqlclient.

Here is a guide for downgrade libmysqlclient:
https://www.dotdeb.org/2014/04/04/about-the-mysql_connect-headers-and-client-library-minor-version-mismatch-warning-2/

**Comment by askovpen** [comment]
why downgrade to old mysql?
