### ISSUE TITLE
Different Steam ID reported by ingame and by Web Panel for the same person

### ISSUE THREAD

**Issue by borzaka** [sbpp/sourcebans-pp#621]
What are the steps to reproduce this issue?
-------------------------------------------
1. Ban/Block comms a player from ingame 
2. Ban/Block comms the same player from the Web Panel

What happens?
-------------
The Steam ID is different for the same person depends where you have banned/comms blocked him.

What were you expecting to happen?
----------------------------------
Use the same Steam ID for the same person, and the correct one.

Any logs, error output, etc.?
----------------------------
### Silenced from ingame:
SourceMod log:
`L 10/04/2019 - 19:40:54: [basecomm.smx] "Krisz<198><STEAM_1:0:198597633><>" silenced "ToT_T1-<196><STEAM_1:1:425368471><>"`

Game log:
`L 10/03/2019 - 20:10:04: "ToT_T1-<153><STEAM_1:1:425368471><>" STEAM USERID validated`

What it looks like in the Web Panel:
![image](https://user-images.githubusercontent.com/1230402/66349086-5f7e0900-e958-11e9-9639-d6fe1daa4df8.png)

### Silenced from Web Panel:
What it looks like in the Web Panel:
![image](https://user-images.githubusercontent.com/1230402/66349574-76712b00-e959-11e9-8c94-54c55594b619.png)

It wasn't edited, just right click -> Block Comms and set reason + length.

Any other comments?
-------------------
If banning from ingame: `STEAM_1:1`,
if banning from Web Panel: `STEAM_0:1`
for the same user.

**Probably the users with starting Steam ID `STEAM_1` are affected only.**

Problems because of this:
- previous bans/block count (Total Blocks and searching) are not valid
- probably the bans are not working because wrong Steam ID?

Probably related:
#568
#604

I would be happy to fix this different Steam ID Universe changing first, then move to another Steam ID format.

What versions of software are you using?
----------------------------------------
**Operating System:** `Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux` (Debian 10.1)
**SourceBans++ Version:** `1.7.0 | Git: 931`
**PHP Version:** `7.3.4-2`
**MySQL Version:** `mariadb  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
**Link to your project:** Sorry, I don't want to post it here.
**Link to a phpinfo() output:** I don't want to post it here. 

If you need the last two info, contact me on Discord.

**Comment by CrazyHackGUT** [comment]
> If banning from ingame: STEAM_1:1,
if banning from Web Panel: STEAM_0:1
for the same user.

This is not problem.
Problem in this case - plugin inserts `STEAM_1` in database instead `STEAM_0`.

**Comment by borzaka** [comment]
But in the game logs it's `STEAM_1`:
`L 10/03/2019 - 20:10:04: "ToT_T1-<153><STEAM_1:1:425368471><>" STEAM USERID validated`

Only the Web Panel messes up, and changes it to `STEAM_0`, not? And changes when editing to.

**Comment by Bara** [comment]
I strongly recommend this change #604 to avoid more issues with the different steamids

**Comment by borzaka** [comment]
Before the transition, I think this 0-1 problem should be fixed first.
Changing to a different Steam ID usage can cause many additional problems, database migration, etc.

**Comment by rumblefrog** [comment]
Steam ID 2 has a lot of discrepancies, especially with them varying from different source engine versions. We should not even worry about the universe when checking, which is precisely what #604 talks about.

**Comment by borzaka** [comment]
I'am using only CS:GO servers, and I still have this Universe changes...
The game log and SourceBans++ WebPanel shows different Steam ID-s for the same person. But it's clear in the logs which one is the correct.

**Comment by rumblefrog** [comment]
Which is why we are moving away to a universal identification, because there's no real "correct" universe, the panel calculates it; differently, the ID varies per engine.

Even though a standard account is on universe one, there's no correct in terms of on different engines.
