### ISSUE TITLE
[WEB][BUG] Can not connect to server...

### ISSUE THREAD

**Issue by Drmohammad11** [sbpp/sourcebans-pp#630]
What are the steps to reproduce this issue?
-------------------------------------------
1. download last update [2019 oct 20]
2. install web panel
3. add a server and admin
4. go to edite admin > edite server access > save changes
5.  you see error [Can not connect to server...]

What happens?
-------------
you see will not any change on server and sb_admins.cfg
but will save changes on web panel and database

What were you expecting to happen?
----------------------------------
save all changes on server and sb_admins.cfg

Any logs, error output, etc.?
----------------------------

http://uupload.ir/files/uzh_capture12.png

Any other comments?
-------------------
no, thank you

What versions of software are you using?
----------------------------------------
**Operating System:** windows server 2008 r2
**SourceBans++ Version:** 1.7.0 | Git: 931
**PHP Version:** 7.3.9
**MySQL Version:** 5.6
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by rumblefrog** [comment]
https://sbpp.dev/docs/debugging_connection/

**Comment by Drmohammad11** [comment]
i think this is the problem from web panel:

> [+] SourceBans "Error Connecting()" Debug starting for server XXX.XXX.XXX.XXX:27015
> 
> [+] Trying to establish UDP connection
> [+] UDP connection successfull!
> [+] Trying to write to the socket
> [+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
> [+] Got an response! Server: *********** | Public #1 Server [Pro Player][!ws]
> 
> [+] Trying to establish TCP connection
> [+] TCP connection successfull!
> [+] Trying to write to TCP socket and authenticate via rcon
> [+] Successfully sent authentication request. Reading...
> [+] Got an response!
> [+] Password correct!

**Comment by rumblefrog** [comment]
GMP Extension

**Comment by Drmohammad11** [comment]
> GMP Extension

i again checked php.ini but this extension enabled:
extension=gmp

i have this problem after update web panel. before update i didn't have this problem

**Comment by rumblefrog** [comment]
Then provide PHP log and phpinfo like asked in the template.

**Comment by Drmohammad11** [comment]
> Then provide PHP log and phpinfo like asked in the template.

please check this page :
dashboard/phpinfo.php

**Comment by rumblefrog** [comment]
And php log?

**Comment by Drmohammad11** [comment]
> And php log?

i can not find this log. where dir??

**Comment by rumblefrog** [comment]
Consult your system administrator or OS/Distro/Web server documentation.

**Comment by aavram93** [comment]
I was on this situation few weeks ago, my problem was from the server! Was not permited to be interogated to I recommand you to check add on server.cfg 
// Host Information
//
host_info_show 2
host_name_store 1
host_players_show 2

And check Linux Server where is hosted your server to accepting incoming traffic

**Comment by Drmohammad11** [comment]
> I was on this situation few weeks ago, my problem was from the server! Was not permited to be interogated to I recommand you to check add on server.cfg
> // Host Information
> //
> host_info_show 2
> host_name_store 1
> host_players_show 2
> 
> And check Linux Server where is hosted your server to accepting incoming traffic

dont work :/
