### ISSUE TITLE
Some help ?

### ISSUE THREAD

**Issue by Joez252** [sbpp/sourcebans-pp#631]
Warning: get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php on line 298

Warning: get_headers(): This function may only be used against URLs in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php on line 298

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php on line 323

Warning: file_get_contents(https://steamcommunity.com/openid): failed to open stream: no suitable wrapper could be found in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php on line 323

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php on line 323

Warning: file_get_contents(https://steamcommunity.com/openid): failed to open stream: no suitable wrapper could be found in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php on line 323

Fatal error: Uncaught exception 'ErrorException' with message 'No OpenID Server found at https://steamcommunity.com/openid' in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php:486 Stack trace: #0 /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php(608): LightOpenID->discover('https://steamco...') #1 /home/webs/web_16797/backtogaming.eu/www/test/steamopenid.php(43): LightOpenID->authUrl() #2 /home/webs/web_16797/backtogaming.eu/www/test/steamopenid.php(71): steamOauth() #3 {main} thrown in /home/webs/web_16797/backtogaming.eu/www/test/includes/openid.php on line 486

**Comment by Express93** [comment]
For faster help @joez252 join the Discord: https://discord.gg/4Bhj6NU

Either way, your error is right at the top of the file:
https:// wrapper is disabled in the server configuration by allow_url_fopen=0

Your host is blocking the function we require.
