### ISSUE TITLE
sbpp_sleuth does not ban duplicate accounts

### ISSUE THREAD

**Issue by monsterbnd** [sbpp/sourcebans-pp#634]
What are the steps to reproduce this issue?
-------------------------------------------
1. Ban your account.
2. Connect to the server from the same IP, but from a different account.

What happens?
-------------
I checked all the plugin variables on my tf2 servers - that's right.
After that I got into the code.
Code into function "public void OnClientPostAdminCheck (int client)" should form a query to the database when the player joins the server.
However, the condition "if (CanUseSourcebans && !IsFakeClient (client))" is always false and the request to select from the database about the connected player does not pass.

What were you expecting to happen?
----------------------------------
Restore performance.

Any logs, error output, etc.?
----------------------------

no

Any other comments?
-------------------
no

What versions of software are you using?
----------------------------------------
#define PLUGIN_VERSION "1.7.0"

**Comment by monsterbnd** [comment]
Oh. I don’t know what was the matter, but now it worked as it should. You can delete the issue.

**Comment by CrazyHackGUT** [comment]
Issues on GitHub can't be deleted.

**Comment by rumblefrog** [comment]
Yes, they can be with administrators.

![yfQDYMM](https://user-images.githubusercontent.com/6960234/69921407-6c524100-145f-11ea-9038-c230fd89a8b6.png)

**Comment by CrazyHackGUT** [comment]
I don't see no one reason why issues should be deleted. But this is my opinion.
