### ISSUE TITLE
how to clear expired bans?

### ISSUE THREAD

**Issue by lugaamn** [sbpp/sourcebans-pp#636]
What are the steps to reproduce this issue?
-------------------------------------------
1.
2.
3.
4.

What happens?
-------------

What were you expecting to happen?
----------------------------------

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**

**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**SourceMod Version:**
**MetaMod Version:**

**Comment by The-Doggy** [comment]
Use mysql event scheduler to delete them. Also issues are not the place to ask for support. In the future please use https://discord.gg/4Bhj6NU for any questions relating to sbpp.

**Comment by rumblefrog** [comment]
Typically, PruneBan would run to purge them
