### ISSUE TITLE
Support different IP/hostname for UDP and TCP ports

### ISSUE THREAD

**Issue by MPV** [sbpp/sourcebans-pp#639]
Is your feature request related to a problem? Please describe.
-------------------------------------------------------------
I'm running my servers (including SourceBans++) in Kubernetes, and due to a current limitation there, it's not possible to have the same external IP for the UDP and TCP ports being exposed (if you're curious, see https://github.com/kubernetes/kubernetes/pull/75831).

For example HLstatsXCE supports having a separate "public ip/hostname" for a server (compared to the sometimes private RCON port):

Describe the solution you'd like
--------------------------------
Separate IP for RCON and game server ports. I.e. a different address for the join server links.

Describe alternatives you've considered
---------------------------------------
Today I must add my servers using the TCP port so RCON integration works, but join links don't work, since I don't expose the same server on the UDP port on that hostname/IP.

Additional context
------------------

Example of how HLstatsX CE does it:
<img width="1367" alt="Skärmavbild 2020-01-05 kl  12 54 51" src="https://user-images.githubusercontent.com/62675/71779842-921cb980-2fba-11ea-820e-711717fa82b7.png">

**Comment by rumblefrog** [comment]
This is a pretty edge case scenario. Wouldn't it be better to wait for the upstream fix? It looks like it's already done and waiting to resolve the conflicts.

**Comment by MPV** [comment]
Despite there being a pull-request for it, it's unclear if and when that change will make it there. Currently there's been requests for creating a ["KEP" (Kubernetes Enhancement Proposal)](https://github.com/kubernetes/enhancements/tree/master/keps) for that change first.

Looking at it again now, there seems to be some potential workarounds there though. I'll review and see if I can get any of those to work.
