### ISSUE TITLE
Bug edit admin i think

### ISSUE THREAD

**Issue by stefanx111** [sbpp/sourcebans-pp#642]
What are the steps to reproduce this issue?
-------------------------------------------
1. Go Admin panel
2. Go Admin Management
3. Go Admin Server Access
4. Checking the box 

What happens?
-------------
I want to add or delete the admin and gave me this

https://prnt.sc/qsr9xa
https://prnt.sc/qsrar0

on the 1.6.3 version i dont have this issue

What were you expecting to happen?
----------------------------------

https://prnt.sc/qsr9xa
https://prnt.sc/qsrar0
Any logs, error output, etc.?
----------------------------

[+] SourceBans "Error Connecting()" Debug starting for server serverip:27015

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: SERVERNAME*
[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!
Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** Linux 
**SourceBans++ Version:** 1.7.0
**PHP Version:** 7.1
**MySQL Version:** mysql  Ver 14.14 Distrib 5.6.46,
**Link to your project:** i change version to the 1.6.3 until fix
**Link to a phpinfo() output:**

**Comment by Electr0** [comment]
i am can confirm, have same while edit admin permissions

**Comment by Groruk** [comment]
Both issues have been addressed in #648 and #672
