### ISSUE TITLE
AJAX Call Failed! get_magic_quotes_gpc()

### ISSUE THREAD

**Issue by Official-Instructions** [sbpp/sourcebans-pp#650]
What are the steps to reproduce this issue?
-------------------------------------------
1. docker-compose.yml excerpt
```
sb-wp-stack:
	image: php:7.4.3-apache-buster
	ports:
	- 80:80
	- 443:443
	restarts: always
	volumes: 
	- ./web:/var/www/
```
2. Configure the php enviornment
3. curl -Lo sb.tar.gz https://github.com/sbpp/sourcebans-pp/releases/download/1.6.3/sourcebans-pp-1.6.3.Full.tar.gz ; tar xf sb.tar.gz
4. Copy web/ to html/sbinstall and go through installation using the quick start [guide](https://sbpp.dev/docs/quickstart/) with the full install going to http://example.com/sourcebans
5. Try to Log in with the admin account built during install

What happens?
-------------
Recieve an error. In logs below.

What were you expecting to happen?
----------------------------------
The login to occur and to head to the admin panel.

Any logs, error output, etc.?
----------------------------
```
Error: the XML response that was returned from the server is invalid. Received:
Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/html/sourcebans/includes/xajax.inc.php on line 705

Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/html/sourcebans/includes/xajax.inc.php on line 705

Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/html/sourcebans/includes/xajax.inc.php on line 705

Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/html/sourcebans/includes/xajax.inc.php on line 705

Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/html/sourcebans/includes/xajax.inc.php on line 705

Warning: session_name(): Cannot change session name when headers already sent in /var/www/html/sourcebans/includes/SessionManager.php on line 6

Warning: session_set_cookie_params(): Cannot change session cookie parameters when headers already sent in /var/www/html/sourcebans/includes/SessionManager.php on line 11

Warning: session_start(): Cannot start session when headers already sent in /var/www/html/sourcebans/includes/SessionManager.php on line 12

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/sourcebans/includes/xajax.inc.php:705) in /var/www/html/sourcebans/includes/xajax.inc.php on line 766
$('msg-red').setStyle('display', 'none');
```

Any other comments?
-------------------
I see that there is some [talk](https://github.com/sbpp/sourcebans-pp/issues/635) about [get_magic_quotes_gpc()](https://github.com/sbpp/sourcebans-pp/pull/646)
and the pull request had been merged up to that point, however - this is still happening on the latest release for some reason.

I am not using TLS at this time since it hadn't fully been setup yet. Would that affect this issue?

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 18.04 (Using Docker, on a php:7.4.3-apache-buster image, also containing a Wordpress Server on main directory)
**SourceBans++ Version:** 1.6.3

**PHP Version:** 7.4.3
**MySQL Version:** 10.2.31 MariaDB (Also dockerized)
**Link to a phpinfo() output:** [Here.](https://gist.github.com/Official-Instructions/02daa555598598e54f030e4235f24757)

**Comment by borzaka** [comment]
The PHP version is too new. Try with 7.3

The SB++ version you are using is released on Apr 10, 2018
The merge request you referenced is in the latest master (merged on Feb this year), which is not stable yet to release.

I have learnt this infos from the official SB++ Discord channel: https://discord.gg/4Bhj6NU

**Comment by Official-Instructions** [comment]
Thank you @borzaka
I have been searching further into this issue and it seems the ajax php library is unmaintained on the latest stable release.

[Issue #40](https://github.com/Xajax/Xajax/issues/40#issuecomment-361978212) on the Xajax github repo recommends using [Jaxon](https://www.jaxon-php.org/)

> It's a fork of the Xajax library, it's PHP7-compatible, it's actively developed, and it provides many plugins and integration packages for PHP frameworks.
