### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by Thormi** [sbpp/sourcebans-pp#651]
This is the issue I get all the time and nothing works: SQLSTATE[HY000] [2002] No such file or directory

Please help,

**Comment by rumblefrog** [comment]
Use a search engine next time: https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

https://stackoverflow.com/questions/29695450/pdoexception-sqlstatehy000-2002-no-such-file-or-directory
