### ISSUE TITLE
Banlist Import doesnt work via admin panel

### ISSUE THREAD

**Issue by BestNoob** [sbpp/sourcebans-pp#659]
Warning: file(): Filename cannot be empty in X:\XXXXXXXXXX\pages\admin.bans.php on line 38
Warning: Invalid argument supplied for foreach() in X:\XXXXXXXXX\pages\admin.bans.php on line 41

I cannot import banlist after setup via admin panel it always brings up a green windows with this message "0 bans have been imported and posted."

I have limited the banlist to 80 000 per file because of your import file limitation to ~8MB

Warning
: POST Content-Length of 31332318 bytes exceeds the limit of 8388608 bytes in
Unknown
on line
0

Does this depend onto MYSQL size of databases ? so it should be below 4MB not 8MB ?!

*i have created a banlist with over 300 000 banned cheaters/crossban for my CoD4x Server
https://github.com/callofduty4x/CoD4x_Server/wiki/Banlists-in-version-15.9--and-other-changes

It should work also with the up to date sourcebans version or not ?

**Comment by Groruk** [comment]
> I have limited the banlist to 80 000 per file because of your import file limitation to ~8MB

Why do you think 80.000 lines in a file correspond to 8mb?
SourceBans++ also isn't setting any limits to file upload sizes that comes straight from your PHP configuration.

You have 2 options to fix your problem:
1.) Actually split your banlist into 8mb chunks and import them separately
> POST Content-Length of 31332318 bytes exceeds the limit of 8388608 bytes
The file content is actually 31.33mb big, not 8mb which is the default PHP limit.

Or

2.) Take a look at your [php.ini](https://www.php.net/manual/en/ini.core.php) config and change the limit according to your needs.
- [upload-max-filesize](https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize)
- [post-max-size](https://www.php.net/manual/en/ini.core.php#ini.post-max-size)

are the two config parameters you are looking for.
