### ISSUE TITLE
Option to customize messages sent by email

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#663]
Implement the option for users to be able to edit emails that the Web Interface sends to emails.

Recently I started to use the Web Interface more, I realized that it has some pretty cool features, like Report, Appeal de Bans and many others in the Web interface. However, by default it sends the emails with the messages, it would be possible to implement something so that users can edit as they want the messages that will be sent in the emails.

I currently focus on the Recover Password, Ban Appeal and Report Player options.

**Comment by Hackmastr** [comment]
https://github.com/sbpp/sourcebans-pp/commit/6eb6828a8c740d3fde3b2a65b9d30dfd7f7536a7

Thanks!
