### ISSUE TITLE
Error Connecting

### ISSUE THREAD

**Issue by xBarbarionX** [sbpp/sourcebans-pp#664]
What are the steps to reproduce this issue?
-------------------------------------------
1. just put the ip of my server in the admin panel and it doesn't work

What happens?
-------------
[+] SourceBans "Error Connecting()" Debug starting for server 185.249.197.33:27015

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[-] Error getting server info. Can't read from UDP stream. Port is possibly blocked.

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!

What were you expecting to happen?
----------------------------------
UDP to work so my server can send info to the webpanel

Any logs, error output, etc.?
----------------------------

idk how to get that sorry

Any other comments?
-------------------
Im hosting my Game Server on a VPS and i tried to make rules into Windows Firewall
 so UDP can work with the port 27015, but then also tried to disable the whole firewall to see if it works and there's nothing changing ( i was using sb_debug_connection.php to test all of this )

What versions of software are you using?
----------------------------------------
**Operating System:** windows 10
**SourceBans++ Version:** 1.6.3
**SourceMod Version:** 1.10 - build 6482
**MetaMod Version:** 1.10 - build 971

**Comment by distratul** [comment]
I had the same problem...i submit a ticket to my Web Host and they ENABLED the UDP port. Now my problem is solved. 


![Untitled](https://user-images.githubusercontent.com/33494107/81437426-d2ac5f80-9173-11ea-826d-03f15d74d59d.png)

**Comment by Groruk** [comment]
> [-] Error getting server info. Can't read from UDP stream. Port is possibly blocked.

> I had the same problem...i submit a ticket to my Web Host and they ENABLED the UDP port.

Best thing to do in this case is to talk to your host about opening UDP ports.
