### ISSUE TITLE
Update sm_ban, sm_gag, sm_silence and sm_mute to display the menu when issued without arguments

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#666]
SourceMod has already implemented this improvement in standard plugins, would it be possible to bring it to SourceBans++ too?

**Comment by TheByKotik** [comment]
**P.S. Not tested. But you can test it!**

1. `sm_kick` is not implemented in sbpp plugins.
2. `sm_ban` required only this change:

https://github.com/sbpp/sourcebans-pp/blob/a7de6e41f41a641c655b436485bb63a5aefa91b6/game/addons/sourcemod/scripting/sbpp_main.sp#L404-L415
To:
```
if ( !args && client )
{
	DisplayBanTargetMenu(client);
	return Plugin_Handled;
}
else if ( args < 2 )
{
	ReplyToCommand(client, "%sUsage: sm_ban <#userid|name> <time|0> [reason]", Prefix);
	return Plugin_Handled;
}
```
3. `sm_gag ... and etc`required only this change:
https://github.com/sbpp/sourcebans-pp/blob/a7de6e41f41a641c655b436485bb63a5aefa91b6/game/addons/sourcemod/scripting/sbpp_comms.sp#L544-L550
To:
```
if (args < 1)
{
	ReplyToCommand(client, "%sUsage: %s <#userid|name> %s", PREFIX, command, type <= TYPE_SILENCE ? "[time|0] [reason]" : "[reason]");
	if (type <= TYPE_SILENCE)
		ReplyToCommand(client, "%sUsage: %s <#userid|name> [reason]", PREFIX, command);
	AdminMenu_Target( client, type );
	return Plugin_Stop;
}
```

**Comment by crashzk** [comment]
@TheByKotik thanks, I will test these changes, working I notice and try to do a PR.

**Comment by crashzk** [comment]
Putz, this change is in the latest development version, I use version 1.6.3. kkk

I'll download the latest version and try it out.

**Comment by crashzk** [comment]
@TheByKotik thanks, it worked.
![image](https://user-images.githubusercontent.com/32937653/80282094-ed97c200-86e5-11ea-9051-46b2bf69157d.png)

However, I believe that I will remove the messages that it shows when typing only the commands, since it will open the menu just by typing them, it no longer needs to appear as each command must be used.

**Comment by TheByKotik** [comment]
Very interesting. Double print. >Four years of this function.

Try this for sbpp_comms:
```
if ( !args && client )
{
	AdminMenu_Target( client, type );
	return Plugin_Stop;
}
else if ( args < 1 )
{
	ReplyToCommand( client, "%sUsage: %s <#userid|name> %s", PREFIX, command, type > TYPE_SILENCE ? "[reason]" : "[time|0] [reason]" );
	return Plugin_Stop;
}
```

**Comment by crashzk** [comment]
It worked, now it doesn't show the messages in the chat.

Soon I will make a PR for the `master` branch here, thanks for the help.

**Comment by crashzk** [comment]
@TheByKotik thanks for all the help, i requested a PR, and put the due credits for you.

Thanks again for your time and help.
