### ISSUE TITLE
Commlist Page Has No Checkboxes

### ISSUE THREAD

**Issue by nikooo777** [sbpp/sourcebans-pp#68]
The communication ban list has no checkboxes. Hence it's not possible to mass-delete/mass-unsilence players.

an example can be found on my installation:
https://bans.elite-hunterz.info/index.php?p=commslist

here is how it looks for the ban list: 
http://scrn.storni.info/2015-10-08_22-35-16.png

and here how it looks like for the comm list:
http://scrn.storni.info/2015-10-08_22-35-40.png

I hope it's a simple fix.

Greetings

**Comment by duhow** [comment]
That's not a _simple fix_. Enhancement? Sure.
But that needs to change function from processing one to process all in array.
(Depending on how it is coded, as I didn't had a look at the function...)

It should look for unique users and then process an action (a select input with the proper action).

**Comment by nikooo777** [comment]
thanks for looking into it!

**Comment by sarabveer** [comment]
Ask @d-ai, a.k.a [raleks](https://steamcommunity.com/id/raleks).

Ask him to add it, since he is the developer of SourceComms.

**Comment by nikooo777** [comment]
Hey, @d-ai looks inactive on the project. I'm not going to bother a developer that doesn't seem to have enough time for the project anymore. I think that if you have some time you should handle this.

It's obviously up to you, but by closing this issue and asking me to ask him, we both know that it will never happen to be added.

Greetings

**Comment by sarabveer** [comment]
He is inactive because SourceComms is stable and it has no issues at the moment. What else is there to add? Just ask @d-ai.

**Comment by ppalex7** [comment]
I no longer playing in the Team Fortress. I haven't time and incentive to develop the project further.
I was very disappointed that the Sourcebans 2 development stopped

**Comment by sarabveer** [comment]
@d-ai SourceComms was TF2 only??? I never knew.

**Comment by ppalex7** [comment]
@Sarabveer, No, it seems to works with all the games on source engine, but i played only in tf2. No playing - no sourcecomms usage / testing  -  no development

**Comment by nikooo777** [comment]
That's the point @Sarabveer.
His work is amazing and your work is too. You used his code and integrated it in your UI which is very nice. However d-ai is now inactive on the project, and a project that isn't under development or being maintained is fated to die.

I think that you shouldn't let this happen and if you find some time, you should take a look at that code.

Greetings,
Niko

**Comment by sarabveer** [comment]
Well @stickz is looking at the Plugin side of things, and he is rewriting the plugins, function by function to use the SM1.7 api.

**Comment by ppalex7** [comment]
jfyi: i'm still open for pull requests.

**Comment by 404UserNotFound** [comment]
@Sarabveer Checkboxes are not a plugin-based side of things (to my knowledge). Look at the pages.bans.php file and see how it handles checkboxes. I may of course be wrong (and if I am, I admit that fully) but I don't think the plugin controls the checkbox handling.

**Comment by sarabveer** [comment]
@404UserNotFound I know, but I'm just talking about how the plugin is still being managed.

I'm kinda inactive right now, so sorry man.

**Comment by 404UserNotFound** [comment]
@Sarabveer No no it's ok, I understand. I wasn't trying to be all "in your face" about it. Now I feel bad :( I think it should be somewhat simple to do but I haven't myself looked into it.

**Comment by sarabveer** [comment]
@404UserNotFound Have a Hug

(づ｡◕‿‿◕｡)づ

**Comment by 404UserNotFound** [comment]
@Sarabveer  (づ｡◕‿‿◕｡)づ

**Comment by nikooo777** [comment]
I'd gladly help but my skills in php are as good as my dancing skills -> almost none.

I can help out with the plugin side in case. but as @404UserNotFound said, the plugin doesn't even "talk" to the UI, it goes directly through the database.

**Comment by 404UserNotFound** [comment]
Why'd you close this? Sarabveer and I are gonna look at it.

**Comment by nikooo777** [comment]
Oh my bad! Sorry i misclicked the button. I was wondering too why it was again "closed".

**Comment by 404UserNotFound** [comment]
S'all good :P It's that time of the morning where mistakes are easily made in our groggy states :P

**Comment by nikooo777** [comment]
you have that excuse if you live in america hahaha. Here in switzerland it's the end of the day... that time where you're tired of just being in class programming.

**Comment by sarabveer** [comment]
Stop blowing up my Inbox!

**Comment by duhow** [comment]
Then... Filter messages. :laughing: 
Do it the way I told you on the comment, look for unique users based on Entry ID, and then process an action (a select input with the proper action). Send input array [] and process foreach in PHP. Simple.

**Comment by obtoon** [comment]
I'll add this when my current pr is closed/merged.

EDIT: This is possible, you'd have to add some Javascript for this, and then heavily modify the ungag/unmute functions in the PHP, as they are only coded for single unmutes/ungags.

**Comment by sarabveer** [comment]
@presskoala Are you going to work on this?

**Comment by obtoon** [comment]
yes.

**Comment by nikooo777** [comment]
has there been any progress in this enhancement?

**Comment by sarabveer** [comment]
nope

**Comment by sarabveer** [comment]
Development is done on 1.0
