### ISSUE TITLE
Stuck with forever - Please Wait... / Querying Server Data...

### ISSUE THREAD

**Issue by orafal-dev** [sbpp/sourcebans-pp#692]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install SBPP 1.7.0 GIT 959
2. Add server

What happens?
-------------
Info about versions gets stuck on "Please wait..."
![image](https://user-images.githubusercontent.com/37925892/91764219-30f3c700-ebd7-11ea-9eb1-99e1a38c0549.png)

And server(s) at "Querying Server Data..."
![image](https://user-images.githubusercontent.com/37925892/91764256-45d05a80-ebd7-11ea-9889-dc0bfee66acb.png)

What were you expecting to happen?
----------------------------------
Get versions and get server info.

Any logs, error output, etc.?
----------------------------
none (no errors)

Any other comments?
-------------------
Got GMP module, chmods and chowns are set, there are no firewalls running during the setup, testing (clicking around) and overall - no firewall. Server is publicly visible, everyone can join and it's visible perfectly on gametracker for example, or LGSM `./csgoserver details` (gamedig), or via [https://bans.14hvh.club/sb_debug_connection.php](https://bans.14hvh.club/sb_debug_connection.php) - which passes

What versions of software are you using?
----------------------------------------
**Operating System:** Debian 10 (buster)
**SourceBans++ Version:** 1.7.0
**PHP Version:** 7.4.9
**MySQL Version:** 8.0.21 for Linux on x86_64
**Link to your project:** https://bans.14hvh.club
**Link to a phpinfo() output:** https://bans.14hvh.club/phpinfo.php

**Web server:** nginx 1.14.2-2+deb10u3

**Comment by orafal-dev** [comment]
I've noticed something towards a fix;

1. Go to [https://bans.14hvh.club/index.php?p=servers](https://bans.14hvh.club/index.php?p=servers)
2. Don't close the first tab, open new incognito window and go to [https://bans.14hvh.club/index.php?p=servers](https://bans.14hvh.club/index.php?p=servers)
3. On incognito - once it will show the details, but after reload you'll get again `Querying Server Data...`

edit:
noticed that when you click a link from this comment, it works once too - till page refresh.

**Comment by orafal-dev** [comment]
Still not solved, bumping issue. Software is unusable.

**Comment by Groruk** [comment]
![Capture](https://user-images.githubusercontent.com/5796460/92135848-93cda400-ee0b-11ea-8a0f-84b8c4c223f6.PNG)

Your Content Security Policy is blocking `eval()` calls from the Xajax.js library, which is currently used to handle ajax requests in SourceBans++. To use SourceBans++ you will need to configure your CSP settings to allow script execution from `'unsafe-eval'` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) until Xajax is replaced in a future release from SourceBans++

**Comment by orafal-dev** [comment]
Thanks @Groruk that solved the issue. Might be worth adding it to troubleshooting guide till next major release then.
