### ISSUE TITLE
Formatting error in translations/sbpp_comms.phrases.txt

### ISSUE THREAD

**Issue by trollollol123** [sbpp/sourcebans-pp#702]
Multiple formatting errors in translations/sbpp_comms.phrases.txt
In some places u have } instead of ) 

https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/translations/sbpp_comms.phrases.txt

**Comment by walliski** [comment]
Can you give an example of such occurrences?
Can you explain what kind of problem this causes?
Is it relevant to one language, or multiple?

**Comment by rumblefrog** [comment]
Please include some examples of these "some places" and try to adhere to the issue template.

**Comment by trollollol123** [comment]
https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/translations/sbpp_comms.phrases.txt#L1293
https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/translations/sbpp_comms.phrases.txt#L1265
https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/translations/sbpp_comms.phrases.txt#L1237

I think thats an error right? Im not sure if there were more.

**Comment by Tiagoquix** [comment]
@Groruk #746
