### ISSUE TITLE
[SECURITY VULNERABILITY] Missing adodb-mysqli.inc.php leaks MySQL login info

### ISSUE THREAD

**Issue by CosmicHikari** [sbpp/sourcebans-pp#709]
What are the steps to reproduce this issue?
-------------------------------------------
1. Delete adodb-mysqli.inc.php in /includes/adodb/drivers
2. Visit your webpage

What happens?
-------------
You get Fatal error: Could not load the database driver for mysqli://MYSQLUSERNAME.PASSWORD@IP:PORT/DBNAME

What were you expecting to happen?
----------------------------------
The website should Error 500 instead of leaking personal MySQL login details

Any logs, error output, etc.?
----------------------------

![image](https://user-images.githubusercontent.com/16886014/102699489-07988e80-41fa-11eb-8c56-0b1af3798af7.png)

Any other comments?
-------------------
***I understand to the normal user, this wouldn't happen and as such this is a fairly low priority vulnerability. However, I figure I should mention it as this happened to me whilst I was restoring a webserver backup. The issue went away quite quickly (in under a few seconds) but thought I should still mention it.***

What versions of software are you using?
----------------------------------------
**Operating System:** Debian 10

**Sourcebans++ Version:** 1.6.3

**PHP Version:** 7.4.13
**MySQL Version:** mariadb-server-10.3 
**Link to your project:** https://bans.firehostredux.com
**Link to a phpinfo() output:**

**SourceMod Version:**
**MetaMod Version:**

**Comment by rumblefrog** [comment]
You should configure your web server not to show errors publicly, which is the de facto standard for production settings.

**Comment by CrazyHackGUT** [comment]
I just leave this here.
https://github.com/sbpp/sourcebans-pp/blob/fcb2cc00e10c3ef92e90117cf0c5ad4d63997179/web/init.php#L105-L106

**Comment by CosmicHikari** [comment]
> I just leave this here.
> https://github.com/sbpp/sourcebans-pp/blob/fcb2cc00e10c3ef92e90117cf0c5ad4d63997179/web/init.php#L105-L106

That should be 0 in my case then right?



> You should configure your web server not to show errors publicly, which is the de facto standard for production settings.

I do suppose trusting apache2's devs to have errors off by default isn't always the best idea. Will fix. Thanks for the feedback.

**Comment by CrazyHackGUT** [comment]
> That should be 0 in my case then right?

1. This code shouldn't be here at all. He overrides the PHP configuration. If you disable error displaying in PHP, it will continue display your error with database credentials, because in `init.php` someone overrides this parameters.
2. Yes, in your case, this should be `0`.
