### ISSUE TITLE
sourcebans 1.5.3: error banlist

### ISSUE THREAD

**Issue by HanGos** [sbpp/sourcebans-pp#71]
<p><strong>Hello, after installing sourcebans 1.5.3 not displayed page bans, writes the following error:</strong></p>

[256] mysqli error: [1231: Variable 'optimizer_switch' can't be set to the value of 'block_nested_loop=off'] in EXECUTE("set session optimizer_switch='block_nested_loop=off';") 
Fatal error on line 77 in file /sourcebans/includes/adodb/adodb-errorhandler.inc.php
/sourcebans/includes/adodb/adodb-errorhandler.inc.php - 77
/sourcebans/includes/adodb/adodb.inc.php - 1071
/sourcebans/includes/adodb/adodb.inc.php - 1046
/sourcebans/pages/page.banlist.php - 42

<p><strong>how you can correct this error?</strong></p>

**Comment by sarabveer** [comment]
Don't use MariaDB
