### ISSUE TITLE
Error after adding Server or in Server Setting

### ISSUE THREAD

**Issue by mrnoahfink** [sbpp/sourcebans-pp#712]
What are the steps to reproduce this issue?
-------------------------------------------
1. Made server in Server Setting
2. Add Server 
3. Error pop-up

What happens?
-------------
Error not able add as log error

What were you expecting to happen?
----------------------------------
Add Server

Any logs, error output, etc.?
----------------------------
Error: the XML response that was returned from the server is invalid. Received:
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/vol9_7/unaux.com/unaux_27575795/htdocs/includes/xajax.inc.php on line 705
Error connecting (24.149.29.4:27015) Help]]>

[Server Setting Error]
Error: the XML response that was returned from the server is invalid. Received:
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/vol9_7/unaux.com/unaux_27575795/htdocs/includes/xajax.inc.php on line 705
Error connecting (24.149.29.4:27025) Help]]>$('sinfo_2').setStyle('display', 'none');$('noplayer_2').setStyle('display', 'block');$('serverwindow_2').setStyle('height', '64px');if($('sid_2'))$('sid_2').setStyle('color', '#adadad');
Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:*idk*
**SourceBans++ Version:*1.6.3*
**PHP Version:**
**MySQL Version:*7.5.1?*
http://www.owlcommunitybans.unaux.com/index.php?p=home
https://profreehost.com/ (That what I am using)

**Comment by mrnoahfink** [comment]
I currently delete all of them and reinstall them.

**Comment by ashort96** [comment]
This is covered in the quickstart (https://sbpp.github.io/docs/quickstart). Your PHP version is too new. Use the current build of the main branch of this repo and you will no longer have this issue, or downgrade to PHP 7.3.

**Comment by mrnoahfink** [comment]
Look like I am not getting error anymore! however, I can't open any tabs or add server still
![sourcebanadmins](https://user-images.githubusercontent.com/66857858/103373560-1e58a400-4a8a-11eb-8447-af22393b67e8.png)

and server tab error
![sourceservertab](https://user-images.githubusercontent.com/66857858/103373651-58c24100-4a8a-11eb-9c4b-27464e005f51.png)

http://www.owlcommunitybans.unaux.com/index.php?p=home

**Comment by ashort96** [comment]
Caching issue. The function exists in scripts/sourcebans.js (which I verified is on your web server). Visit incognito / clear your cache. 

In the future, you can use our Discord for support. https://discord.gg/4Bhj6NU

**Comment by mrnoahfink** [comment]
Look like it working! sadly my tf2 servers are online but still problem connecting also saying it max_user_connections, 

If you wonder I am using free website hosting.

**Comment by mrnoahfink** [comment]
I am moving to a different host

**Comment by mrnoahfink** [comment]
I am changing to Heroku,
=======================ERROR LOG==========================
-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/php.tgz
       
 !     ERROR: Application not supported by this buildpack!
 !     
 !     The 'heroku/php' buildpack is set on this application, but was
 !     unable to detect a PHP codebase.
 !     
 !     A PHP app on Heroku requires a 'composer.json' at the root of
 !     the directory structure, or an 'index.php' for legacy behavior.
 !     
 !     If you are trying to deploy a PHP application, ensure that one
 !     of these files is present at the top level directory.
 !     
 !     If you are trying to deploy an application written in another
 !     language, you need to change the list of buildpacks set on your
 !     Heroku app using the 'heroku buildpacks' command.
 !     
 !     For more information, refer to the following documentation:
 !     https://devcenter.heroku.com/articles/buildpacks
 !     https://devcenter.heroku.com/articles/php-support#activation
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

**Comment by mrnoahfink** [comment]
but it hes composer.json in sourcebans? right?

**Comment by Groruk** [comment]
Composer support has only recently been added to the master branch, see PR #693 for more info.

But I think this discussion is better suited for the SourceBans++ discord (https://discord.gg/4Bhj6NU) then GitHub issues.
