### ISSUE TITLE
Duplicated account bann and same gateway

### ISSUE THREAD

**Issue by Nerus87** [sbpp/sourcebans-pp#719]
Is your feature request related to a problem? Please describe.
-------------------------------------------------------------
There is a problem if someone gets the ban on the server and some other will get ban because is connecting from the same gateway (same public address for different places).

Describe the solution you'd like
--------------------------------
The problem could be solved by checking that admin unban a specific player, so this specific player will not be able to get the ban for a duplicated accounts (the plugin will skip this player in checking).

Describe alternatives you've considered
---------------------------------------
There is no other way to check that player is the same player, we can only pray to the good and have to trust admins.

Additional context
------------------
Thank you for your time.

**Comment by ashort96** [comment]
If you want to unban someone that shares the same IP as someone that is banned, either remove the sbpp_sleuth plugin or change the IP address of the person that was originally banned so anyone sharing that IP does not get banned upon joining... this is the point of the sbpp_sleuth plugin.

**Comment by Nerus87** [comment]
If someone will connect from the same gateway and is not in correlation with other accounts and this player can be innocent admin should be able to unban especially this account and the plugin will be able to skip this check because the player was unbanned. But still, we wish to prevent other banned persons from joining the server. Do you understand this case?

About the solution with changing the IP address in DB is ridiculous, if I will change the IP address and will not match with other accounts created by the banned person we will never detect smurf.

**Comment by Groruk** [comment]
You can use the SourceSleuth whitelist.
That way you can exclude certain SteamIDs from being checked by the sbpp_sleuth plugin.

https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/configs/sourcebans/sourcesleuth_whitelist.cfg
