### ISSUE TITLE
PHP v8.0.2 - Fatal Error: ...undefined function get_magic_quotes_gpc()

### ISSUE THREAD

**Issue by k0nan** [sbpp/sourcebans-pp#723]
_get_magic_quotes_gpc_ was depreciated in PHP 7.4 and removed as of PHP v8.0.0.

What are the steps to reproduce this issue?
-------------------------------------------
1. Run Sourcebans++ v1.6.3 on PHP v8.0.0 or above
2. Navigate to the webpanel

What happens?
-------------
![image](https://user-images.githubusercontent.com/11669545/109654160-24d6cb00-7b62-11eb-99e7-71c49f740a8f.png)

What versions of software are you using?
----------------------------------------
**Operating System:** Debian 9.13
**SourceBans++ Version:** 1.6.3
**PHP Version:** 8.0.2

**Comment by Groruk** [comment]
This has been fix already on the current master branch version 1.7.0

See PR #646 for more info.

**Comment by k0nan** [comment]
> This has been fix already on the current master branch version 1.7.0
> 
> See PR #646 for more info.

I'm not too familiar with GIT. Where can I find the 1.7.0 branch for download?
