### ISSUE TITLE
Xajax error

### ISSUE THREAD

**Issue by kubo997** [sbpp/sourcebans-pp#724]
![image](https://user-images.githubusercontent.com/58640055/110053067-f3742000-7d58-11eb-8b74-443c37d074b8.png)

What should I do?

**Comment by ashort96** [comment]
[The prerequisites](https://sbpp.dev/docs/quickstart/#prerequisites) should answer your question; PHP versions 7.4 and above are not supported as that function is deprecated. Use the latest code from the main branch or downgrade your PHP version.

Duplicate of #723 and others as well.

**Comment by kubo997** [comment]
> [The prerequisites](https://sbpp.dev/docs/quickstart/#prerequisites) should answer your question; PHP versions 7.4 and above are not supported as that function is deprecated. Use the latest code from the main branch or downgrade your PHP version.
> 
> Duplicate of #723 and others as well.

So I copy and pasted latest files and install php 7.4 version. Now getting this error:
![image](https://user-images.githubusercontent.com/58640055/110100890-39ee6c80-7da3-11eb-97e5-cb0ce93228b0.png)
![image](https://user-images.githubusercontent.com/58640055/110100991-568aa480-7da3-11eb-810b-81a68b94cc5e.png)

**Comment by KrillinsWorld** [comment]
Update adodb and xajax files and those errors will disappear. (not sure if old package has updated them or not in the past 3 years). Google them and you will find them, download them, unzip them and replace them in sourcebans/includes as necessary. Files are attached below.
[xajax.inc.zip](https://github.com/sbpp/sourcebans-pp/files/6154585/xajax.inc.zip)
[adodb-5.20.19.zip](https://github.com/sbpp/sourcebans-pp/files/6154594/adodb-5.20.19.zip)

**Comment by Groruk** [comment]
> could not find driver

This is a `PDOException` so make sure that you have the `pdo_mysql` extension installed for PHP 7.4
