### ISSUE TITLE
Problem loading subsequent pages in Sourcebans Submissions & Protests archive  

### ISSUE THREAD

**Issue by mmethot** [sbpp/sourcebans-pp#730]
What are the steps to reproduce this issue?
-------------------------------------------
1. Log in to Sourcebans as an admin user;
2. Navigate to the _admin panel > bans_ section;
3. Click on either _Submissions_ or _Protest_ sections;
4. Click on the _Archive_ tab;
5. (You need to have more than one page of submissions or protests archives);
6. Click on either the _next_ link or select another page from the drop down list to view another page;

What happens?
-------------
The Web view sends the user back to the _Add ban_ interface.

What were you expecting to happen?
----------------------------------
The Web view should show the next page of submissions or protests (or the selected page if from the dropdown list).

Any logs, error output, etc.?
----------------------------
No logs are shown on the Web console.

What versions of software are you using?
----------------------------------------
**Web Host Operating System:** Linux
**Client Operating System (mine):** Windows
**SourceBans++ Version:** 1.7.0
**PHP Version:** 7.3.27
**MySQL Version:** 5.0.12-dev
**Link to your project:** https://oldfartscommunity.com/sb
**Link to a phpinfo() output:** https://oldfartscommunity.com/admins/phpinfo.php

**Comment by sunnus01** [comment]
Same here, still redirecting back to Add Ban page

**Comment by shaikhnedab** [comment]
same here. its not specific to submissions or archives only. it happens on system log page in webpanel settings.

**Comment by Rushaway** [comment]
Still happen on php81 branch.
