### ISSUE TITLE
[SOLVED ]I'm getting a php error

### ISSUE THREAD

**Issue by KunnyestFid** [sbpp/sourcebans-pp#739]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install sourcebans++ as normal
2. Do the web setup
3. remove the installer and updater when done with web setup as you are told
4. refresh

What happens?
-------------
I get a php error

What were you expecting to happen?
----------------------------------
I was expecting to be on the sourcebans++ home page

Any logs, error output, etc.?
----------------------------
Fatal error: Uncaught Error: Call to undefined function mysqli_connect_errno() in /home/wy3occk9/public_html/bans/includes/adodb/drivers/adodb-mysqli.inc.php:812 Stack trace: #0 /home/wy3occk9/public_html/bans/includes/adodb/adodb.inc.php(670): ADODB_mysqli->ErrorNo() #1 /home/wy3occk9/public_html/bans/includes/adodb/adodb.inc.php(4812): ADOConnection->Connect() #2 /home/wy3occk9/public_html/bans/init.php(149): ADONewConnection() #3 /home/wy3occk9/public_html/bans/index.php(28): include_once('/home/wy3occk9/...') #4 {main} thrown in /home/wy3occk9/public_html/bans/includes/adodb/drivers/adodb-mysqli.inc.php on line 812

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System: windows**
**SourceBans++ Version: 1.6.2 (I also tried 1.6.3 and got the same thing)**
**PHP Version: 7.3.28**
**MySQL Version: 5.7.31**
**Link to your project: ????**
**Link to a phpinfo() output: ????**

**Comment by Hackmastr** [comment]
Looks like you don't have the [mysqli ](https://www.php.net/manual/en/mysqli.installation.php)extension enabled. Check with your hosting provider.
