### ISSUE TITLE
Ban List not displaying in Sourcebans 

### ISSUE THREAD

**Issue by Bonkorn** [sbpp/sourcebans-pp#74]
Hi I'm using SourceBans++ 1.5.3 with SourceBans Default Theme (next gen style), I clicked on the 'Bans' from Tab (with dashboard, servers...)
It shows empty on the page, I also switched theme and try again it doesn't display anything.

**Comment by sarabveer** [comment]
Stop using MariaDB.

**Comment by Bonkorn** [comment]
It's localhost... with XAMPP

**Comment by sarabveer** [comment]
![](http://puu.sh/l6Okc/983ca1b133.png)

Should I say more?

**Comment by duhow** [comment]
@Sarabveer is having nightmares everyday because of **MariaDB**... :laughing:

**Comment by sarabveer** [comment]
@duhow Make the bans page detect if it is using MariaDB or MySQL.

**Comment by duhow** [comment]
OK, I'll try it! :P
