### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by ZeroCPU** [sbpp/sourcebans-pp#743]
I added an administrator to sourebans, but he was unable to execute permissions in the game, so I deleted him and executed the two checked servers when deleted. As a result, sourebans could not display the server status normally, and there was an error connecting, and my levels ranks Web could not be displayed normally

**Comment by ZeroCPU** [comment]
I think I found the problem. It should be that my frequent operations led to the server banip blocking my local IP

**Comment by rmerac92** [comment]
Hmm, I tried rcon listip but that didn't help --- it's empty. Were there other things you tried before the banip thing?

--- EDIT

Just also tried ufw to open port 3306 for both tcp but still getting the same error connecting issue. 
I'm using Rasbian OS which is like Debian. What OS were/are you using?

**Comment by crashzk** [comment]
I believe it is a duplicate of these issues: https://github.com/sbpp/sourcebans-pp/issues/686
