### ISSUE TITLE
Sourcebans does query running L4D2 servers due to Valve query protcol change

### ISSUE THREAD

**Issue by BBG-BigBangTheory** [sbpp/sourcebans-pp#745]
What are the steps to reproduce this issue?
-------------------------------------------
1. have sourcebans-pp  query a running L4D2 server
2.
3.
4.

What happens?
-------------
Due to Valve's recent change to the L4D2 query protocol, Sourcebans-pp does not see L4D2 servers that are indeed online.

What were you expecting to happen?
----------------------------------
sbpp not have error connecting to the running server 

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 18.04
**SourceBans++ Version:** 1.6.3

**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**SourceMod Version:**
**MetaMod Version:**

**Comment by Groruk** [comment]
This issue has already been fixed in the current dev version 1.7
See #738 for more information.
