### ISSUE TITLE
Possibly a "Latest Players Blocked" attack.

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#747]
What are the steps to reproduce this issue?
-------------------------------------------
1. Get banned, doesn't matter if you have permanent ban or not.
2. Change your name to the following on Steam `<?php echo ""; ?>`
3. Reconnect to the server

What happens?
-------------
Latest Players Blocked tab doesn't display name.
I'm not a genius or anything like that, was actually a friend of mine that pointed it out. This could be used as a vulernability, ex, an XSS attack.

What were you expecting to happen?
----------------------------------
Well, i would expect you to blacklist the "<" and ">" to prevent these things.
I wasn't actually expecting that it wouldn't register anything.

Any logs, error output, etc.?
----------------------------

Nothing to report

Any other comments?
-------------------
Yes, please fix. I have already tried contacting UNLOZE through their shoutbox as guwi and warn them.
This was tested on their server, just out of curiosity.

What versions of software are you using?
----------------------------------------
**Operating System:** Unknown
**SourceBans++ Version:** 1.6.3, but works on 1.7.++ too.
**PHP Version:** Unknown
**MySQL Version:** Unknown
**Link to your project:** Unknown
**Link to a phpinfo() output:** Unknown

Kind regards:
**Guwi**

**Comment by lunatixxx** [comment]
So is it fixed?

**Comment by Hackmastr** [comment]
Hello,

Yes, this has been is fixed.
