### ISSUE TITLE
Error:Install Sourcebans step5 Fital Error.

### ISSUE THREAD

**Issue by KevonLin** [sbpp/sourcebans-pp#749]
What are the steps to reproduce this issue?
-------------------------------------------
1.install->step6

What happens?
-------------
An error occurred during normal installation.

What were you expecting to happen?
----------------------------------
successful.

Any logs, error output, etc.?
----------------------------

Notice: Constant IN_SB already defined in /var/www/html/install/includes/converter.inc.php on line 28
Converting sb_bans...
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'player_ip' in 'field list' in /var/www/html/includes/Database.php:70 Stack trace: #0 /var/www/html/includes/Database.php(70): PDOStatement->execute() #1 /var/www/html/includes/Database.php(75): Database->execute() #2 /var/www/html/install/includes/converter.inc.php(45): Database->resultset() #3 /var/www/html/install/template/page.6.php(15): convertAmxbans(Object(Database), Object(Database)) #4 /var/www/html/install/includes/page-builder.php(62): include('/var/www/html/i...') #5 /var/www/html/install/index.php(31): include_once('/var/www/html/i...') #6 {main} thrown in /var/www/html/includes/Database.php on line 70

Any other comments?
-------------------
nothing

What versions of software are you using?
----------------------------------------
**Operating System:**
Ububtu 20.04.2 LTS
**SourceBans++ Version:**
sourcebans-pp-1.6.3.Full
**PHP Version:**
PHP 7.2.24-0
**MySQL Version:**
5.7.34-0
**Link to your project:**
http://81.71.93.145/install/index.php
**Link to a phpinfo() output:**
![step5](https://user-images.githubusercontent.com/81147695/130823858-4a336bd1-6b2d-43fc-b165-ba39181af447.png)

**Comment by crashzk** [comment]
If you have verified that you have all the requirements for installation?

* Webserver
  o PHP 7.4 or higher
    * ini setting: memory_limit greater than or equal to 64M
    * GMP extension
  o MySQL 5.6 or MariaDB 10 and higher
* Source Dedicated Server
  o MetaMod: Source
  o SourceMod: Greater Than or Equal To 1.7

Error that shows in the image says that you don't have some columns in your database.

Try doing a clean install, from scratch again.

Tried using PHP 7.3 too

**Comment by Groruk** [comment]
Step 6 in the installer is optional and you only need to use it if you have an old AMXbans Database that you want to import.

**Comment by NanakaFathry** [comment]
我也遇到了一样的错误：
报错原文：
AMXBans Import

Warning: Constant IN_SB already defined in /var/www/site4_com/sbpp/1.7.0/install/includes/converter.inc.php on line 28
Converting sb_bans...
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'player_ip' in 'field list' in /var/www/site4_com/sbpp/1.7.0/includes/Database.php:117 Stack trace: #0 /var/www/site4_com/sbpp/1.7.0/includes/Database.php(117): PDOStatement->execute() #1 /var/www/site4_com/sbpp/1.7.0/includes/Database.php(127): Database->execute() #2 /var/www/site4_com/sbpp/1.7.0/install/includes/converter.inc.php(45): Database->resultset() #3 /var/www/site4_com/sbpp/1.7.0/install/template/page.6.php(10): convertAmxbans() #4 /var/www/site4_com/sbpp/1.7.0/install/includes/routing.php(21): require_once('...') #5 /var/www/site4_com/sbpp/1.7.0/install/index.php(14): build() #6 {main} thrown in /var/www/site4_com/sbpp/1.7.0/includes/Database.php on line 117

错误经历：
是在第六步填写后（下图）
![1](https://github.com/sbpp/sourcebans-pp/assets/108194610/51d8184e-4813-4956-9620-c8402758b942)
就报这个错误：
![2](https://github.com/sbpp/sourcebans-pp/assets/108194610/8ecef3ad-c86f-43e3-b7dd-aa527e2c230c)

环境如下：

Ubuntu:20.04

PHP：
PHP 8.1.27 (cli) (built: Dec 21 2023 20:19:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies

SQL：
mysql  Ver 15.1 Distrib 10.3.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

metamod: source
SourceMod (1.11.0.6913) by AlliedModders LLC

**Comment by NanakaFathry** [comment]
> 我也遇到了一样的错误： 报错原文： AMXBans Import
> 
> Warning: Constant IN_SB already defined in /var/www/site4_com/sbpp/1.7.0/install/includes/converter.inc.php on line 28 Converting sb_bans... Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'player_ip' in 'field list' in /var/www/site4_com/sbpp/1.7.0/includes/Database.php:117 Stack trace: #0 /var/www/site4_com/sbpp/1.7.0/includes/Database.php(117): PDOStatement->execute() #1 /var/www/site4_com/sbpp/1.7.0/includes/Database.php(127): Database->execute() #2 /var/www/site4_com/sbpp/1.7.0/install/includes/converter.inc.php(45): Database->resultset() #3 /var/www/site4_com/sbpp/1.7.0/install/template/page.6.php(10): convertAmxbans() #4 /var/www/site4_com/sbpp/1.7.0/install/includes/routing.php(21): require_once('...') #5 /var/www/site4_com/sbpp/1.7.0/install/index.php(14): build() #6 {main} thrown in /var/www/site4_com/sbpp/1.7.0/includes/Database.php on line 117
> 
> 错误经历： 是在第六步填写后（下图） ![1](https://private-user-images.githubusercontent.com/108194610/293616506-51d8184e-4813-4956-9620-c8402758b942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjEzMTgsIm5iZiI6MTcwNDE2MTAxOCwicGF0aCI6Ii8xMDgxOTQ2MTAvMjkzNjE2NTA2LTUxZDgxODRlLTQ4MTMtNDk1Ni05NjIwLWM4NDAyNzU4Yjk0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwMjAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDAxZDQ3NGQwNmViNjNmMTFkNTUwYzFlNzNhNGU3YWU0YWU5ZDIyYWJiMDM1NTg3N2IxZWE4YWVlNzA4MjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Lr7i3dHi_wzPhoAB1c3zFlXO4jxNLavk-bxzgUdgso) 就报这个错误： ![2](https://private-user-images.githubusercontent.com/108194610/293616529-8ecef3ad-c86f-43e3-b7dd-aa527e2c230c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjEzMTgsIm5iZiI6MTcwNDE2MTAxOCwicGF0aCI6Ii8xMDgxOTQ2MTAvMjkzNjE2NTI5LThlY2VmM2FkLWM4NmYtNDNlMy1iN2RkLWFhNTI3ZTJjMjMwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwMjAzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjQ2OWM1YzA4YTE0M2YyYTUxNzA3NTgwNDM5YzVkZTAzYzBjZmZkOTI5YjRhZmNhMTcxODAzNjcxZDYwMzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvfcClAJwHWfaN-EDGH8AmeCoaKv4ZGaja03aB9m8JU)
> 
> 环境如下：
> 
> Ubuntu:20.04
> 
> PHP： PHP 8.1.27 (cli) (built: Dec 21 2023 20:19:26) (NTS) Copyright (c) The PHP Group Zend Engine v4.1.27, Copyright (c) Zend Technologies with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies
> 
> SQL： mysql Ver 15.1 Distrib 10.3.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
> 
> metamod: source SourceMod (1.11.0.6913) by AlliedModders LLC

补充：
SourceBans++ Version:
sourcebans-pp-1.7.0 full

**Comment by Rushaway** [comment]
@NanakaFathry Sourcebans 1.7.0 was not designed to run PHP 8+
Use sbpp 1.8.0 for that.

**Comment by NanakaFathry** [comment]
> @NanakaFathry Sourcebans 1.7.0 was not designed to run PHP 8+ Use sbpp 1.8.0 for that.
I tried to use 'sourcebans-pp-php81', but the same problem still exists
![Uploading 2024-01-04 024848.png…]()
Also after the sixth step

**Comment by NanakaFathry** [comment]
I also tried reinstalling the Database-MySQL and PHP-7.4, but it still doesn't work and the same error persists
