### ISSUE TITLE
sb_admin_groups.cfg does not update on servers after group change in web interface

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#751]
What happens?
-------------
We changed the privilege groups on the web interface, changing the group name for example and not updating on servers, for example.

I had created the privilege group `vip`, then changed everything to `VIP` in capital letters, but on servers the groups do not update, everything remains small.

I changed it to other names, `VIPP`, `VIPPP` so it updates normally, but if I leave only `VIP` it goes back to tiny.

I already deleted the files to create from scratch and nothing, same problem.

What were you expecting to happen?
----------------------------------
Atualizase o no do grupo de privilégios para `VIP`, atualizar para como eu configurei no caso.

Any logs, error output, etc.?
----------------------------

```
L 09/20/2021 - 14:50:35: [sbpp_admcfg.smx] Error(s) Detected Parsing addons/sourcemod/configs/sourcebans/sb_admins.cfg
L 09/20/2021 - 14:50:35: [sbpp_admcfg.smx]  (line 110) Unknown group "VIP"
L 09/20/2021 - 14:50:35: [sbpp_admcfg.smx]  (line 128) Unknown group "VIP"
L 09/20/2021 - 14:50:35: [sbpp_admcfg.smx]  (line 134) Unknown group "VIP"
L 09/20/2021 - 14:50:35: [sbpp_admcfg.smx]  (line 146) Unknown group "VIP"
```

Any other comments?
-------------------
![image](https://user-images.githubusercontent.com/32937653/134053677-6225840d-bbd0-4301-8e24-6ea91871e288.png)

![image](https://user-images.githubusercontent.com/32937653/134053755-f221b89c-4b62-4a61-a505-817697949649.png)

This only happens in the privilege group list, in the privileged players list it is updating normally.

![image](https://user-images.githubusercontent.com/32937653/134053874-901c03dc-7c65-4241-b546-d0c2bb93c3b6.png)

I believe it is the same problem mentioned here: https://github.com/sbpp/sourcebans-pp/issues/727

What versions of software are you using?
----------------------------------------
**Operating System:** Server CSGO Linux | Hosting Web Linux
**SourceBans++ Version:** 1.7.0
**SourceMod Version:** 1.10.0.6510
**MetaMod Version:** 1.11 - build 1145
**PHP Version:** 7.3
**MySQL Version:** 10.3.31-MariaDB

**Comment by crashzk** [comment]
I deleted the group in question from the web interface, turned off the servers and turned it back on.

Then I created the group again, same name, everything in capital letters and still nothing, it's still small.

![image](https://user-images.githubusercontent.com/32937653/134181603-8bce8d9d-9179-4126-aa6c-0ae60af9d421.png)

![image](https://user-images.githubusercontent.com/32937653/134181668-7ed3c35b-3be8-4719-930c-30c15c652436.png)

**Comment by CrazyHackGUT** [comment]
This is Source Engine issue, not SB++ and not SourceMod.
Reason - used format for storing administrators and groups. Valve KeyValues caches first read capital and forces them for any operations like writing into files. This issue appears only in keys. Some details can be found on [HLmod](https://hlmod.ru/threads/problema-group-mexanika-keyvalues.42802/) (russian forum), also SM devs confirmed this issue on [AM](https://forums.alliedmods.net/showthread.php?p=2362727#post2362727).

As possible solution - use any another format, such as JSON (requires installing additional extension, like smjansson or REST in Pawn) or create binary format. I did latest variant in my custom SB plugins recently, and it showed yourself as "stable solution". I can adopt code for SB++ plugins, and make a Pull Request, if SB++ maintainers interested in this.
