### ISSUE TITLE
Sourcebans++ plugins don't start after update

### ISSUE THREAD

**Issue by leonhartm47** [sbpp/sourcebans-pp#755]
What are the steps to reproduce this issue?
-------------------------------------------
1. extracted achieve file
2. uploaded server plugins
3. rebooted server
4. plugins didn't load

What happens?
-------------
I updated from 1.6.3 to 1.6.4 and upon completion the webside was fine and responded as expected... however the server plugins didn't start.

What were you expecting to happen?
----------------------------------
Well the plugins to start; I've checked all the requirements and as far as I can see it should have worked.

Any logs, error output, etc.?
----------------------------

L 10/22/2021 - 15:09:59: [SM] Failed to load plugin "sbpp_admcfg.smx": Unable to load plugin (no debug string table).
L 10/22/2021 - 15:09:59: [SM] Failed to load plugin "sbpp_checker.smx": Unable to load plugin (no debug string table).
L 10/22/2021 - 15:09:59: [SM] Failed to load plugin "sbpp_comms.smx": Unable to load plugin (no debug string table).
L 10/22/2021 - 15:09:59: [SM] Failed to load plugin "sbpp_main.smx": Unable to load plugin (no debug string table).
L 10/22/2021 - 15:09:59: [SM] Failed to load plugin "sbpp_report.smx": Unable to load plugin (no debug string table).
L 10/22/2021 - 15:09:59: [SM] Failed to load plugin "sbpp_sleuth.smx": Unable to load plugin (no debug string table). 

Any other comments?
-------------------
In order to reactivate the admin list and allow interaction between the server and sourcebans++ I had to revert the server plugins and scripts back to version 1.6.3 which seems to have corrected the issues.  I've left the web server on 1.6.4 because it currently despite the above seems stable.

What versions of software are you using?
----------------------------------------
**Operating System:** Windows / Dedicated Server
**SourceBans++ Version:** 1.6.4 (server due to the above issues is currently 1.6.3)
**SourceMod Version:** 1.9.0.6275
**MetaMod Version:** 1.10.7-devV

The game in question is GE:S (GoldenEye:Source)

**Comment by CrazyHackGUT** [comment]
Update SourceMod or recompile plugins manually for your version.

**Comment by leonhartm47** [comment]
I had a feeling that someone would say that, because the above hints that it's not compatible with the version it's being run on.. but I would have thought that since it says it should run on this version that it would run.  Since GE:S can be temperamental I think I'll just attempt to recompile them I guess.

**Comment by geominorai** [comment]
Good point.  The plugins bundled in the 1.6.4 release package were compiled for SM 1.10, but this was not mentioned in the notes, so the fallback would have been the [readme](https://github.com/sbpp/sourcebans-pp/blob/63637f0d3c4c73805d4fbb484ba431ac7d23b462/README.md?plain=1#L35) also bundled that still mentioned SM 1.7.

**Comment by leonhartm47** [comment]
I decided to backup the whole server and go ahead with upgrading to the newest stable version of sourcemod (SM 1.10) and all the plugins (including the new ones for sourcebans++) are now being detected.  The readme and supported version information do still need to be changed though because I thought this was going to be a quick patch to the current server configuration.
