### ISSUE TITLE
Error connecting since CSGO/steam a2s_info changes.

### ISSUE THREAD

**Issue by asdfxD** [sbpp/sourcebans-pp#759]
as title says, since the csgo/steam update my server list shows "error connecting".

https://steamcommunity.com/discussions/forum/14/2974028351344359625/?ctp=4

EDIT: updated to 1.6.4 -> it works again.

**Comment by KillerRoi** [comment]
The Update solved it? I'm running the same build but it's not working for me

**Comment by asdfxD** [comment]
Yes, install and use 1.6.4 sloves it for me.

https://github.com/sbpp/sourcebans-pp/releases/tag/1.6.4

![sb163-164](https://user-images.githubusercontent.com/24253340/142975759-afa2ca83-de40-4635-b6fc-1dcdd2d5d9c3.png)

**Comment by KillerRoi** [comment]
I was using the latest branch build but still the same error

**Comment by borzaka** [comment]
Updating the `SourceQuery.php` from this Gist helped me:
https://gist.github.com/iBoonie/7f4ebe8146e0234844ec77ed10203ec0
