### ISSUE TITLE
Error when adding server

### ISSUE THREAD

**Issue by ZeraXx97** [sbpp/sourcebans-pp#761]
Hi, I just installed SourceBan 1.6.4
When I try to add new server i get this error

`Error: the XML response that was returned from the server is invalid. Received:
Fatal error: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysql' at line 1] in EXECUTE("INSERT INTO sb_log(type,title,message, function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'function, query, aid, host, created)\r\n VALUES (\'m\',\'Server Added\',\'Server (\' at line 1] in EXECUTE(\"INSERT INTO sb_log(type,title,message, function, query, aid, host, created)\r\n VALUES (\'m\',\'Server Added\',\'Server (185.119.89.84:27025) has been added\',\'/home/dh_irt7q5/ekipica.info/banovi/includes/xajax.inc.php - 1090
/home/dh_irt7q5/ekipica.info/banovi/includes/xajax.inc.php - 739
/home/dh_irt7q5/ekipica.info/banovi/index.php - 33
\',\'N/A\',\'1\ in /home/dh_irt7q5/ekipica.info/banovi/includes/adodb/adodb-errorhandler.inc.php on line 79
You have whitespace in your response.`

When I reload page, my server is there. And when i try to delete server i get same error. 
And again when i reload page my server is deleted.

**Comment by CrazyHackGUT** [comment]
Don't use MySQL 8. It isn't supported officially.

**Comment by ZeraXx97** [comment]
Im on DreamHost hosting. Is there any chance to change mysql version

**Comment by SugarD-x** [comment]
Are there plans to support it? Telling people to not use it when it is the latest release version doesn't really seem like the best solution here.

**Comment by CrazyHackGUT** [comment]
> Telling people to not use it when it is the latest release version doesn't really seem like the best solution here.

SM doesn't support fulfilly MySQL 8.0 too. For example, you need change a default authentication method to less secure (previous auth gen). Why you don't asked them, when default authentication method will be supported?

**Comment by ZeraXx97** [comment]
So i fix this problem. Now i have new problem. When try to login to my acc after instalation nothing happen. Just go to main page without logging. When i put wrong pass say error. Can someone tell me what to do

**Comment by ZeraXx97** [comment]
Well I found one way to fix this
On GoogleChrome dont work, but in Mozilla Firefox login xD

**Comment by SugarD-x** [comment]
> > Telling people to not use it when it is the latest release version doesn't really seem like the best solution here.
> 
> SM doesn't support fulfilly MySQL 8.0 too. For example, you need change a default authentication method to less secure (previous auth gen). Why you don't asked them, when default authentication method will be supported?


My whole concern is not the lack of current support, but the implied lack of desire to *ever* support the latest softwares in the future.

As for the authentication method, that is the only major thing to my knowledge that is preventing MySQL 8 from being used, aside from other small bugs. It still runs on MySQL 8 without breaking. It's likely just a matter of updating the authentication support and probably cleaning up some query code.

Edit: 1.7.0 seems to work with MySQL 8.0.27. There are just some bugs breaking the features related to database queries, which is likely just outdated query code and PHP 7.4+ stuff that needs fixing. Even caching_sha2_password is working fine for me. As long as the plan is to support these fully, I have no complaints here. I'm hoping this argument is nothing more than a miscommunication.

**Comment by CrazyHackGUT** [comment]
> My whole concern is not the lack of current support, but the implied lack of desire to ever support the latest softwares in the future.

I'm not a developer SB++, so...

> Even caching_sha2_password is working fine for me.

Now try start SRCDS and pass this database to plugin. You may be unpleasantly surprised. It just don't connect because "Authentication plugin can't be loaded".
```
L 02/27/2021 - 10:57:00: [sbpp_main.smx] Database failure: [2059]: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/local/mysql/lib/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```
Of course, you can install on your game server MySQL client libraries, but this isn't available for all users.
So, issue author can receive new problems in near future, if they use game hosting (not a VDS/DS).

So, my recommendation remains the same: don't use fresh software versions if they don't supported officially.
Latest SM dev don't support MySQL 8.0 `caching_sha2_password` without installing additional libraries.
Latest SB++ supports partially, but don't fully.
