### ISSUE TITLE
can't login with steam

### ISSUE THREAD

**Issue by imenergie** [sbpp/sourcebans-pp#767]
Hello, i have 1.6.4 version and when i try to login in with steam 
nothing happens only go to my website and that's it. takes me to the main page and I have to log in again. all my respect!
solved! I switched to 1.7.0

**Comment by Risusama** [comment]
From my experience with similar behaviour, it's usually caused by having sourcebans open in multiple tabs. (I usually have to login as many times as I have sourcebans open.)

**Comment by lunatixxx** [comment]
I confirm that login with steam does not work i arrive on a steam page with "Invalid return protocol"
