### ISSUE TITLE
AJAX Call Failed

### ISSUE THREAD

**Issue by dkoz** [sbpp/sourcebans-pp#772]
What are the steps to reproduce this issue?
-------------------------------------------
1. Just going into admin panel
2. Clicking on any admin setting

What happens?
-------------
Everything in the admin panel takes a long time to load. The SourceBans fails to grab the version information and causes and AJAX call failed.

What were you expecting to happen?
----------------------------------
Expecting responsive load times when going through admin settings.

Any logs, error output, etc.?
----------------------------
AJAX Call Failed!
 Error: the XML response that was returned from the server is invalid. Received:
Warning: file_get_contents(https://sbpp.github.io/version.json): failed to open stream: Connection timed out in /home/xxx/domains/bans.xxx.gg/public_html/includes/sb-callback.php on line 2325
Error]]>Error Retrieving Latest Release.]]>

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** CentOS 8
**SourceBans++ Version:** 1.6.4
**PHP Version:** 7.4
**MySQL Version:** 10.5.15
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by LsLoki** [comment]
Encountered the same, how did you fix it?
