### ISSUE TITLE
Composer fails to run on php 8

### ISSUE THREAD

**Issue by justinnobledev** [sbpp/sourcebans-pp#773]
What are the steps to reproduce this issue?
-------------------------------------------
Installing sourcebans web with php 8+ will cause composer to fail to install

What happens?
-------------
Composer will fail to run the install script due to `lcobucci/jwt` version not being compatible with php 8

What were you expecting to happen?
----------------------------------
The composer script to successfully run

Any logs, error output, etc.?
----------------------------

   - lcobucci/jwt is locked to version 3.3.3 and an update of this package was not requested.
   - lcobucci/jwt 3.3.3 requires php ^5.6 || ^7.0 -> your php version (8.0.17) does not satisfy that requirement.

Any other comments?
-------------------
I was able to get the composer to sucessfully run by editing the php to allow php 8.0, but upgrading the jwt library to 4.x should fix it since the by default allow php 8

What versions of software are you using?
----------------------------------------
**Operating System:** Linux
**SourceBans++ Version:** Latest

**PHP Version:**  8.0.17
**MySQL Version:** 10.3.34-MariaDB

**Comment by Rushaway** [comment]
Use https://github.com/sbpp/sourcebans-pp/tree/php81
