### ISSUE TITLE
BUG System Log

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#774]
What are the steps to reproduce this issue?
-------------------------------------------
1. Complete installation of the sourcebans web part;
2. Then just check the logs, having more than 1 page, the bug already happens;
3. Then just click to go to the next page of sourcebans logs or choose the page you want, the bug happens;

What happens?
-------------

When we click to see the oldest logs, page 2, 3, 4 and so on the page reloads to the `Main Settings` page and when we click to see the `System Log` again it shows that it is on the other page of the log.

Even if I switch straight to the page I want, the bug still happens.

What were you expecting to happen?
----------------------------------
The next pages of the logs are shown directly, without going back to **Main Settings**.

Any logs, error output, etc.?
----------------------------

![image](https://user-images.githubusercontent.com/32937653/147513523-0ed42cdc-760d-402d-944c-de93c5438d31.png)

![image](https://user-images.githubusercontent.com/32937653/147513561-a49e069a-9642-4fa4-8fab-3aa603d867b7.png)

Any other comments?
-------------------
Tested on official theme too, same bug happens too.

What versions of software are you using?
----------------------------------------
**Operating System:** Linux
**SourceBans++ Version:** 1.7.0 | Git: 1145
**PHP Version:** 7.4.22
**MySQL Version:** 10.2.40-MariaDB
**Link to your project:** https://sourcebans.zkservidores.com/
**Link to a phpinfo() output:** https://zkservidores.com/phpinfo.php

**Comment by Rushaway** [comment]
This problem also appear with the default theme.
This is not related to a custom theme.

**Comment by crashzk** [comment]
Duplicate https://github.com/sbpp/sourcebans-pp/issues/730
