### ISSUE TITLE
Error Connecting()

### ISSUE THREAD

**Issue by johnoclockdk** [sbpp/sourcebans-pp#778]
What are the steps to reproduce this issue?
-------------------------------------------
1. fresh install on webserver i use no ports is blocked
2. file the  sb_debug_connection
3. it returns 

`[+] SourceBans "Error Connecting()" Debug starting for server 88.198.69.239:27015

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server:

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!`
4.

What happens?
-------------

What were you expecting to happen?
----------------------------------
it 

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System: ** debian 10
**SourceBans++ ** Version: [SourceBans++](https://sbpp.github.io/) 1.7.0 | Git: 1145
**PHP Version: ** 7.4 fpm*
**MySQL Version: ** mariadb  Ver 15.1 Distrib 10.3.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**Link to your project:**
**Link to a phpinfo() output:** https://bans.theicelegion.dk/phpinfo.php

**Comment by Hackmastr** [comment]
This is due to one of the following:
- Missing PHP extensions (mainly: php_gmp/bcmath)
- Blocked ports on the game/web server.
