### ISSUE TITLE
AJAX Calls when new admin info save

### ISSUE THREAD

**Issue by SsSAtonioSsS** [sbpp/sourcebans-pp#779]
What are the steps to reproduce this issue?
-------------------------------------------
1. Admin Management
2. Add new admin
3. Save

What happens?
-------------
AJAX errors when info saved

> And a new record is added to the database.

What were you expecting to happen?
----------------------------------
No error?

Any logs, error output, etc.?
----------------------------

### $('name.msg').setStyle('display', 'none');$('steam.msg').setStyle('display', 'none');$('email.msg').setStyle('display', 'none');$('password.msg').setStyle('display', 'none');$('password2.msg').setStyle('display', 'none');$('a_serverpass.msg').setStyle('display', 'none');$('server.msg').setStyle('display', 'none');$('web.msg').setStyle('display', 'none');

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 20.04.4 LTS
**SourceBans++ Version:** 1.7.0 | Git: 1145
**PHP Version:** 8.0.18
**MySQL Version:** 10.6.7-MariaDB-1:10.6.7+maria

**Comment by platchford** [comment]
I got the same thing going on with my sourcebans when adding a new admin 

Error: the XML response that was returned from the server is invalid. Received:
Warning: Trying to access array offset on value of type bool in /home/platchford/public_html/includes/CUserManager.php on line 254

Warning: Trying to access array offset on value of type bool in /home/platchford/public_html/includes/CUserManager.php on line 267

**Comment by JimTR** [comment]
I think the whole software needs a refactor to work correctly with php 8.x and mysql 8.x I re coded the whole thing to get it to work with php 8.x

**Comment by Rushaway** [comment]
SourcebansPP isn't fully support in PHP 8.X.
Better use PHP 7.4

**Comment by JimTR** [comment]
PHP 7.4 is end of life 28 November 2022, why is out of date versions of PHP

**Comment by Rushaway** [comment]
Maintainer doesn't update it. Even if someone update it to Php 8.x, idk they will accept any MR..

**Comment by Hackmastr** [comment]
Fixed in the php81 branch.
Thanks.
