### ISSUE TITLE
No nickname present

### ISSUE THREAD

**Issue by oethanx** [sbpp/sourcebans-pp#780]
What are the steps to reproduce this issue?
-------------------------------------------
1.
2.
3.
4.

What happens?
-------------
nick name does not shows up on the site with sm_addban usage 

What were you expecting to happen?
----------------------------------
Player's nick to show up on the webpage

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**
**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by eyal282** [comment]
> ## What are the steps to reproduce this issue?
> 
> ## What happens?
> nick name does not shows up on the site with sm_addban usage
> 
> ## What were you expecting to happen?
> Player's nick to show up on the webpage
> 
> ## Any logs, error output, etc.?
> ## Any other comments?
> ## What versions of software are you using?
> **Operating System:** **SourceBans++ Version:** **PHP Version:** **MySQL Version:** **Link to your project:** **Link to a phpinfo() output:**

This is already solved in another plugin. You can ask Sourcebans to take inspiration from my fix. This makes ANY ban added fire a forward to fill missing info. Even if you use sm_addban, even if you use a proper BanIdentity native, anything that gives access allows it.

https://github.com/eyal282/SQLite-Bans/blob/master/addons/scripting/SQLiteBans.sp#L1080

It should be noted that this was opened back in 2021, and it was not addressed.

https://github.com/sbpp/sourcebans-pp/issues/728

Feel free to address my issue to get it to happen. I will immediately take actions to support making my ban disconnected, which is the only reasonable alternative.

**Comment by lunatixxx** [comment]
if player name is: < something >

no nickname will be present, unintended i guess.

**Comment by Hackmastr** [comment]
Fixed in the php81 branch.
Thanks.
