### ISSUE TITLE
Comms performed from WebPanel doesn't work immediatly

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#784]
What are the steps to reproduce this issue?
-------------------------------------------
1. Perform a comms block from WebPanel (ex: gag)
2. Wait for player founds..
3. The player still can write in chat until he reconnect
4. Same for mute/silence

What happens?
-------------
A player can still use his comms if he didnt reconnect (or map change) when a comms block is performed from the WebPanel.

What were you expecting to happen?
----------------------------------
Like for bans, players has been found and block start apply immediatly.

Any logs, error output, etc.?
----------------------------

N/O.

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**GameServer Operating System:** Ubuntu 20.04
**Web Operating System:** nginx/1.20.2
**PHP Version:** 7.4.29
**MySQL Version:** 7.4.28
**SourceBans++ Version:** 1.7.0 Git 1145
**SourceMod Version:** 1.11.0.50
**MetaMod Version:** 1.11.0 dev 1144

**Comment by Hackmastr** [comment]
Make sure the panel can RCON into the game server.

**Comment by Rushaway** [comment]
I tested, the panel can RCON correctly. But still have this issue.
