### ISSUE TITLE
SourceBans++ Login Ajax XML Error

### ISSUE THREAD

**Issue by OfficialAudite** [sbpp/sourcebans-pp#790]
What are the steps to reproduce this issue?
-------------------------------------------
1. (VPS - Ubuntu) Apache2 server with php 8.0 install
2. Csgo server installed
3. Installed dev version of sourcebans web downloaded from this repo, not the release.
4. Trying to login

What happens?
-------------
So, trying to log in throws a error 
![image](https://user-images.githubusercontent.com/10171579/183010898-94946164-c33d-45e8-a37b-defbe0e64ad6.png)
The url is the VPS ip address. And doesn't log in the user.

What were you expecting to happen?
----------------------------------
To login and see the dashboard.

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu
**SourceBans++ Version:** Current from this repo (not the release downloads but the code download)
**PHP Version:** 8.0.21
**MySQL Version:** Latest MariaDB
**Link to your project:** 
**Link to a phpinfo() output:** http://129.151.201.209/test.php

**Comment by Rushaway** [comment]
Still happen since you are on php 7.4 ?

**Comment by OfficialAudite** [comment]
Nope.
