### ISSUE TITLE
doesn't work to add new server

### ISSUE THREAD

**Issue by 69toory** [sbpp/sourcebans-pp#792]
What are the steps to reproduce this issue?
-------------------------------------------
1.it doesnt work to add new server
2.
3.
4.

What happens?
-------------
i'm new of this sb webpanel i do all the steps and when i want to add new server , i cant 

What were you expecting to happen?
----------------------------------

Any logs, error output, etc.?
----------------------------
cant add the new server

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Debian**
**SourceBans++1.7.0
![unknown](https://user-images.githubusercontent.com/111207342/184517152-33f862cb-e713-4819-93c5-c3c48c0298af.png)
**

**PHP Version:**
**MySQL Version:**
**Link to your project:**
**Link to a phpinfo() output:**

**SourceMod Version:**
**MetaMod Version:**

**Comment by ashort96** [comment]
Not enough detail provided, help like this can be given in the SourceBans++ Discord.
