### ISSUE TITLE
[8.1] templates_c error with dashboard.tpl

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#794]
What are the steps to reproduce this issue?
-------------------------------------------
1. Fresh install.
2. Add a comms mute from Web with valid steamid
3. Go on dashboard

What happens?
-------------
![image](https://user-images.githubusercontent.com/11679883/188903034-3d98baa8-bd8f-497f-972c-83552139c8d9.png)

What were you expecting to happen?
----------------------------------

Any logs, error output, etc.?
----------------------------

https://gist.github.com/Rushaway/5b72c91c01a6f74857c64c6c6f736f32

Any other comments?
-------------------
This issue happen on any themes (default or custom)

What versions of software are you using?
----------------------------------------
**Operating System:** nginx
**SourceBans++ Version:** 1.7.0 (php 8.1 branch) with the lastest release.
**PHP Version:** 8.1.10
**MySQL Version:** 10.6.7-MariaDB-2ubuntu1 - Ubuntu 22.04
**Link to your project:** https://upgradebans.nide.gg/index.php
**Link to a phpinfo() output:** https://upgradebans.nide.gg/phpinfo.php

**Comment by Hackmastr** [comment]
Fixed in [4604aae](https://github.com/sbpp/sourcebans-pp/commit/4604aae1872720e1023cbda8927b207713d64ec7).

Thank you!
