### ISSUE TITLE
Error connecting webserver but every connection successfull.

### ISSUE THREAD

**Issue by Thormi** [sbpp/sourcebans-pp#797]
What are the steps to reproduce this issue?
-------------------------------------------
Installed everything normally, followed the guide https://sbpp.dev/docs/adding_server/. I let the webhost open up the 20175 port and 3306 port for sourcebans. 

What happens?
-------------
It says Error connecting but when I debug nothing seems wrong:
[+] SourceBans "Error Connecting()" Debug starting for server 54.37.94.28:27015

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: ValhallaHub Retakes #3 - !ws, !knife, !gloves, !agents

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!

What were you expecting to happen?
----------------------------------
The name of the server to show, plus server info, now there is nothing. Just error connecting.

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:**
Linux
**SourceBans++ Version:**
1.6.4

**PHP Version:** 
7.4
**MySQL Version:**
10.3.15-MariaDB-1-log - Debian 10

**Link to your project:**
http://www.valhallahub.eu/
**Link to a phpinfo() output:**

**SourceMod Version:**
**MetaMod Version:**

**Comment by Hackmastr** [comment]
This is due to one of the following:

Missing PHP extensions (mainly: php_gmp/bcmath)
Blocked ports on the game/web server.
