### ISSUE TITLE
[8.1] Server Admins List

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#798]
What are the steps to reproduce this issue?
-------------------------------------------
1. Go on Server Management
2. Select in Actions 'Admins'
3. Error.

What happens?
-------------
Return error.

What were you expecting to happen?
----------------------------------
Display the admins list on this server.

Any logs, error output, etc.?
----------------------------

```
Fatal error: Uncaught TypeError: count():
Argument #1 ($value) must be of type Countable|array, null given in /pages/admin.srvadmins.php:40
Stack trace: #0 /includes/page-builder.php(143): require_once() 
#1 /index.php(29): build() 
#2 {main} thrown in /pages/admin.srvadmins.php on line 40
```

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** nginx
**SourceBans++ Version:** 1.7.0 (php 8.1 branch) with the lastest release.
**PHP Version:** 8.1.10
**MySQL Version:** 10.6.7-MariaDB-2ubuntu1 - Ubuntu 22.04
**Link to your project:** https://upgradebans.nide.gg/index.php
**Link to a phpinfo() output:** https://upgradebans.nide.gg/phpinfo.php

**Comment by Hackmastr** [comment]
Fixed. Thanks!
