### ISSUE TITLE
[8.1] $rcon is not defined

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#799]
What are the steps to reproduce this issue?
-------------------------------------------
1. Try to sent an rcon command from sbpp webpanel server
2. Return error (see the end of report for screenshoot)

What happens?
-------------
$rcon is not defined

What were you expecting to happen?
----------------------------------
Solve this error without disable ajax call report.

Any logs, error output, etc.?
----------------------------

Line 2538 `Log::add("m", "RCON Sent", "RCON Command was sent to server ($rcon[ip]:$rcon[port])");`

Any other comments?
-------------------

Not tested on 7.4.
![image](https://user-images.githubusercontent.com/11679883/189729342-86e03611-2801-4358-af1f-72b6d2eef0a5.png)

What versions of software are you using?
----------------------------------------
**Operating System:** nginx
**SourceBans++ Version:** 1.7.0 (php 8.1 branch) with the lastest release.
**PHP Version:** 8.1.10
**MySQL Version:** 10.6.7-MariaDB-2ubuntu1 - Ubuntu 22.04
**Link to your project:** https://upgradebans.nide.gg/index.php
**Link to a phpinfo() output:** https://upgradebans.nide.gg/phpinfo.php

**Comment by Hackmastr** [comment]
Fixed. Thanks!
