### ISSUE TITLE
Rcon log doesn't work correctly

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#800]
What are the steps to reproduce this issue?
-------------------------------------------
1. Sent an rcon command from sbpp webpanel server
2. Check system logs
3. Doesn't display the command used.

What happens?
-------------------------------------------

The command sent is display as ':' instead of the command sent.
` Details | RCON Command was sent to server (:)`

What were you expecting to happen?
----------------------------------
Print the command used in log details.

Any logs, error output, etc.?
----------------------------

N/A

Any other comments?
-------------------
Issue happen on all SBPP Version. (master and 8.1 branch)

What versions of software are you using?
----------------------------------------
**Operating System:** nginx
**SourceBans++ Version:** 1.7.0 (php 8.1 branch) with the lastest release.
**PHP Version:** 8.1.10
**MySQL Version:** 10.6.7-MariaDB-2ubuntu1 - Ubuntu 22.04
**Link to your project:** https://upgradebans.nide.gg/index.php
**Link to a phpinfo() output:** https://upgradebans.nide.gg/phpinfo.php

**Comment by Hackmastr** [comment]
Fixed. Thanks!
