### ISSUE TITLE
mysqli_result could not be converted to int

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#819]
What are the steps to reproduce this issue?
-------------------------------------------
1. Use https://github.com/sbpp/sourcebans-pp/commit/4a9371512a8ce21229a0830619fcef19c8881f94
2. Go on banslist
3. Error

What happens?
-------------
Update depencies generating this issue. Hopefull a patch already exist. It was just not released yet.

Any logs, error output, etc.?
----------------------------

Notice: Object of class mysqli_result could not be converted to int in /includes/vendor/adodb/adodb-php/adodb.inc.php on line 3946

Any other comments?
-------------------
Related to https://github.com/ADOdb/ADOdb/issues/848
**Can be fixed by apply this change.** https://github.com/ADOdb/ADOdb/commit/19ad1135642f44d57b8d01914e4c47c9cc16b008

What versions of software are you using?
----------------------------------------
**Operating System:** nginx
**SourceBans++ Version:** 1.7.0 (php 8.1 branch) with the lastest release.
**PHP Version:** 8.1.10
**MySQL Version:** 10.6.7-MariaDB-2ubuntu1 - Ubuntu 22.04
**Link to your project:** https://upgradebans.nide.gg/index.php
**Link to a phpinfo() output:** https://upgradebans.nide.gg/phpinfo.php

**Comment by Rushaway** [comment]
Waiting for ADOdb 5.22.4 to be release to updates dependencies on this repo.

**Comment by Hackmastr** [comment]
Partially reverted #816, downgraded to 5.22.2 for the time being.

**Comment by Rushaway** [comment]
@Hackmastr Fixed and release. You can update to 5.22.4
