### ISSUE TITLE
Steam Login not working

### ISSUE THREAD

**Issue by janssenb** [sbpp/sourcebans-pp#82]
When i try to login through steam i'm getting redirected to our sourcebans website but i'm not logged in.
How can i fix this ? cant find any errors in apache logfile.

**Comment by duhow** [comment]
Try with other users and check if they have the same problem.

Also, check if there is any PHP error logged.

**Comment by janssenb** [comment]
happened for other users as well. got zero php errors.

Thanks for your quick reply!

**Comment by sarabveer** [comment]
Does it work, any reply?

**Comment by janssenb** [comment]
Nope

Am 10. November 2015 16:42:42 schrieb Sarabveer Singh 
notifications@github.com:

**Comment by ghost** [comment]
i can login fine via steam. When i login the redirect is wrong <site>/<site> but once i remove the redundant <site> i am logged in properly.
