### ISSUE TITLE
Error Connecting()

### ISSUE THREAD

**Issue by NotOfek** [sbpp/sourcebans-pp#830]
What are the steps to reproduce this issue?
-------------------------------------------
i install sourceban normally i open ports tcp and udp and i get Error Connection at servers

What happens?
-------------
It says Error connecting but when I debug nothing seems wrong:
[+] SourceBans "Error Connecting()" Debug starting for server 129.159.149.125:10000

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server:

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!

What were you expecting to happen?
----------------------------------
The name of the server to show + server info

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System: Ubuntu 20.04.4 LTS**
**SourceBans++ Version: 1.6.4**
**PHP Version: 7.4**
**MySQL Version: mariadb 10.6**
**Link to your project: https://sb.cs-il.xyz**
**Link to a phpinfo() output: https://sb.cs-il.xyz/phpinfo.php**

**Comment by Rushaway** [comment]
According your sourcebans website. It works.
Also you are using PHP 7.2 instead of 7.4. (Security Support will end on 28 Nov 2022)
**(Note: Security Support for PHP 7.2 Ended 1 year and 10 months ago (30 Nov 2020))**
https://www.php.net/supported-versions.php

**Comment by LsLoki** [comment]
Error connecting....
UDP 
[+] Trying to establish UDP connection
[+] UDP connection successful!
[+] Trying to write to the socket
[-] Error writing.

Error writing! Is this something owned by the game server host, or the web server host?

**Comment by Hackmastr** [comment]
Please read the docs: https://sbpp.dev/docs/debugging_connection/
Thanks.
