### ISSUE TITLE
Error Connecting Pterodactyl Issue

### ISSUE THREAD

**Issue by mattcyb3r** [sbpp/sourcebans-pp#831]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install CSGO Server on Pterodactyl 
2.Open UDP And TCP port 
3.type in the startup script "-usercon"
4.Sourcebans not connecting 

What happens?
-------------
Error connecting (45.77.163.238:25568)

What were you expecting to happen?
----------------------------------
For the Error Connecting to server not show and the server actually lods

Any logs, error output, etc.?
----------------------------
[+] SourceBans "Error Connecting()" Debug starting for server 45.77.163.238:25568

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[-] Error writing.

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!
Error writing I'm using pterodactyl

Any other comments?
-------------------
Pterodactyl Discord Server says its a issue with sourcebans and Socket Connections 

What versions of software are you using?
----------------------------------------
OS
**Ubuntu 20.04**
Version
**1.6.4**

PHP
**7.4**
****
**tlsservers.com/bans**

**Comment by Hackmastr** [comment]
Please read: https://sbpp.dev/docs/debugging_connection/
Thanks.
