### ISSUE TITLE
warning 209: function has explicit 'int' tag but does not return a value

### ISSUE THREAD

**Issue by BlagoYar** [sbpp/sourcebans-pp#832]
When I try to compile plugins for Sourcemod, I get such warnings

/// sbpp_comms.sp
//
// sbpp_comms.sp(335) : warning 242: function "Event_OnPlayerName" should return an explicit value
// sbpp_comms.sp(596) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(607) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(618) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(629) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(640) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(651) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(662) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(673) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(798) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(848) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(898) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(970) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(1138) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(1229) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_comms.sp(1781) : warning 242: function "ClientRecheck" should return an explicit value
// sbpp_comms.sp(1781) : warning 242: function "ClientRecheck" should return an explicit value
// sbpp_comms.sp(1797) : warning 242: function "Timer_MuteExpire" should return an explicit value
// sbpp_comms.sp(1797) : warning 242: function "Timer_MuteExpire" should return an explicit value
// sbpp_comms.sp(1819) : warning 242: function "Timer_GagExpire" should return an explicit value
// sbpp_comms.sp(1819) : warning 242: function "Timer_GagExpire" should return an explicit value
// sbpp_comms.sp(1841) : warning 242: function "Timer_StopWait" should return an explicit value
// Code size:         89148 bytes
// Data size:         99868 bytes
// Stack/heap size:      27796 bytes
// Total requirements:  216812 bytes
//
// 22 Warnings.
//
// Compilation Time: 0,47 sec
// ----------------------------------------

//// sbpp_report.sp
//
// sbpp_report.sp(86) : warning 209: function has explicit 'int' tag but does not return a value
// Code size:         7428 bytes
// Data size:         3748 bytes
// Stack/heap size:      16684 bytes
// Total requirements:   27860 bytes
//
// 1 Warning.
//
// Compilation Time: 0,2 sec
// ----------------------------------------

//// sbpp_main.sp
//
// sbpp_main.sp(782) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_main.sp(782) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_main.sp(782) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_main.sp(827) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_main.sp(875) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_main.sp(2139) : warning 242: function "ProcessQueue" should return an explicit value
// sbpp_main.sp(2331) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_main.sp(2331) : warning 209: function has explicit 'int' tag but does not return a value
// sbpp_main.sp(2764) : warning 246: function CreateFlagLetters returns an array but return type is not marked as an array
// Code size:         70716 bytes
// Data size:         19104 bytes
// Stack/heap size:      18288 bytes
// Total requirements:  108108 bytes
//
// 9 Warnings.
//
// Compilation Time: 0,61 sec
// ----------------------------------------

version SM - sourcemod-1.11.0-git6917-windows

Will this affect the work of the plugins or do it need to be fixed?

**Comment by Rushaway** [comment]
Please check.
https://github.com/sbpp/sourcebans-pp/tree/php81/game/addons/sourcemod/scripting

**Comment by BlagoYar** [comment]
> Please check. https://github.com/sbpp/sourcebans-pp/tree/php81/game/addons/sourcemod/scripting

Thanks
