### ISSUE TITLE
Admin Management Text Error

### ISSUE THREAD

**Issue by fearts** [sbpp/sourcebans-pp#833]
What are the steps to reproduce this issue?
-------------------------------------------
1. Click on Admins at the very top of the page.
2. Click on any admin on the Admin List.

What happens?
-------------

There is a text error. Under "Server Admin Permissions" in blue it should say "Server Permissions" but it says "Web Permissions". This is the same for "Web Admin Permissions". The text in blue needs to be swapped.

https://gyazo.com/1f95f7e33fc37811ade38a63f86b0f39

**Comment by Rushaway** [comment]
@Hackmastr See: https://github.com/Rushaway/sourcebans-pp/commit/f0b51dd1b11e73e140b94b0e7a054aed28328a48

**Comment by Hackmastr** [comment]
Fixed by @Rushaway 
Thanks!
