### ISSUE TITLE
There is no response when I click Add new server

### ISSUE THREAD

**Issue by jiahao2333** [sbpp/sourcebans-pp#839]
What are the steps to reproduce this issue?
-------------------------------------------
1.Install SourceBans++
2.Delete install and update
3.Visit SourceBans++ and log in
4.add new server

What happens?
-------------
There is no response when I click Add new server

What were you expecting to happen?
----------------------------------
Click Add new server to work

Any logs, error output, etc.?
----------------------------

No.....

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:*Ubuntu 20.04.5*
**SourceBans++ Version:*Git: 1145|latest php81*
**PHP Version:*8.1*
**MySQL Version:*MySQL 5.6.50*
**Link to your project:**
**Link to a phpinfo() output:*https://gist.github.com/jiahao2333/d35803c7b1e175732a86315059aa659d*

**Comment by Rushaway** [comment]
Did you use SB 2.0.0b?
A link to your project can help us.
A correct phpinfo link is require. 
This issue occure on another browser aswell?

**Comment by jiahao2333** [comment]
> 

wow thank my current browser is Chrome version 108.0.5359.125 when I switch to miceosoft edge the problem is solved

**Comment by jiahao2333** [comment]
> 你用的是 SB 2.0.0b 吗？ 指向您的项目的链接可以帮助我们。 需要一个正确的 phpinfo 链接。 这个问题也发生在另一个浏览器上？

这是我的项目链接http://csgo.jiahao.cloud/
这是phpinfo链接http://csgo.jiahao.cloud/phpinfo.php
