### ISSUE TITLE
Add Steam3 ID to Banlist/Commlist

### ISSUE THREAD

**Issue by Speciesx** [sbpp/sourcebans-pp#84]
Currently Banlist shows only steam id.

**Comment by sarabveer** [comment]
I was going to add this sooner or later

**Comment by obtoon** [comment]
Speaking of which, we adding a comm block from the servers page, it auto fills the form with the users Steam3 ID, then doesn't accept it as a valid ID upon submission, need to change this.

**Comment by sarabveer** [comment]
@presskoala Hello, u there?

**Comment by obtoon** [comment]
Yes captain. Would you like me to do this?

**Comment by Sarabveer** [comment]
@presskoala Pls add this for me! And have a cookie!
