### ISSUE TITLE
at Bantime, error but then

### ISSUE THREAD

**Issue by Trice1984** [sbpp/sourcebans-pp#840]
Hello, 

i use the SB 1.7 at my Server so i will test.

Its all fine, but some error when people Timeban its there.

At Bantime, its an Error but after a timeban correct display when time is up, i send a photo thats the best way to show the problem.

![SBerror](https://user-images.githubusercontent.com/62850342/210106155-89c0a26f-58e0-489f-9b14-30e6e088abfe.png)

Many thats for our time!

**Comment by Rushaway** [comment]
Hello.
Can you provide us the full code page related to your error displayed?

**Comment by Trice1984** [comment]
Hello,

its only in the Dashbord, in BANS i see the correct Ban/Time

in Line 65 is:

`<td class="listtable_1<?php if ($this->_tpl_vars['player']['unbanned']): ?>_unbanned<?php elseif ($this->_tpl_vars['player']['perm']): ?>_permanent<?php elseif ($this->_tpl_vars['player']['temp']): ?>_banned<?php endif; ?>"><?php echo $this->_tpl_vars['player']['length']; ?>`



What versions of software are you using?

Operating System:
Ubuntu 22.04 LTS
SourceBans++ Version:
[SourceBans++]1.7.0 | Git: 1145
PHP Version:
8.0.26
MySQL Version:
MariaDB 10.6.11

![Dashbord](https://user-images.githubusercontent.com/62850342/210129962-faf73742-8234-42eb-bbd4-41c015505845.png)
![BANS](https://user-images.githubusercontent.com/62850342/210129963-79388cda-41d6-4e64-8638-45a34719639e.png)

**Comment by Rushaway** [comment]
Well spotted. Thanks !

**Comment by Rushaway** [comment]
Please use PHP 8.1 if you are running the dev branch. 
Or use PHP 7.4 is you use the master branch. 

_The dev branch wasn't made for PHP 8.0. It was for 8.1_

**Comment by Trice1984** [comment]
Hi,

at 8.1 its error Time, i can new install the SB?

Deprecated
: Constant FILTER_SANITIZE_STRING is deprecated in
/var/www/vhosts/XXXXX/httpdocs/SBban/includes/page-builder.php
on line
10


Deprecated
: Constant FILTER_SANITIZE_STRING is deprecated in
/var/www/vhosts/XXXXX/httpdocs/SBban/includes/page-builder.php
on line
11


Deprecated
: Constant FILTER_SANITIZE_STRING is deprecated in
/var/www/vhosts/XXXXXX/httpdocs/SBban/includes/page-builder.php
on line
12


Deprecated
: Function strftime() is deprecated in
/var/www/vhosts/XXXXXX/httpdocs/SBban/includes/vendor/smarty/smarty/libs/Smarty_Compiler.class.php
on line
394

**Comment by Rushaway** [comment]
@Hackmastr https://github.com/sbpp/sourcebans-pp/issues/840#issuecomment-1368272878 https://stackoverflow.com/a/69207369

**Comment by Rushaway** [comment]
Please upgrade to the last version of sbpp (1.8.0) to solve this error with PHP 8.1 support.
Can be closed @Hackmastr
