### ISSUE TITLE
Cache folder not present

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#843]
What are the steps to reproduce this issue?
-------------------------------------------
1. Run the installer
2. Step 3 will say Cache Writable : NO

What happens?
-------------
The cache folder doesn't exist on the structure.

What were you expecting to happen?
----------------------------------
Having a cache folder, like for demos.

Any logs, error output, etc.?
----------------------------

![image](https://user-images.githubusercontent.com/11679883/210118485-0f6c1853-a95d-4abf-b616-a5426c80cfdd.png)

Any other comments?
-------------------
Cache folder is in .gitignore. idk why?
+ Will save you some useless support on discord. Yay!

What versions of software are you using?
----------------------------------------
**Operating System:** nginx
**SourceBans++ Version:** 1.7.0 (php 8.1 branch) with the lastest release.
**PHP Version:** 8.1.10
**MySQL Version:** 10.6.7-MariaDB-2ubuntu1 - Ubuntu 22.04
**Link to your project:** https://upgradebans.nide.gg/index.php
**Link to a phpinfo() output:** https://upgradebans.nide.gg/phpinfo.php

**Comment by bobbanc25** [comment]
Did you find a solution to the problem?

**Comment by Rushaway** [comment]
@bobbanc25 Until a modification is made on this repo you just have to create manually the folder.

**Comment by bobbanc25** [comment]
@Rushaway Alright thanks mate:D
