### ISSUE TITLE
[SourceBans] This player has not been verified. Please wait thirty seconds before retrying.

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#848]
What are the steps to reproduce this issue?
-------------------------------------------
1.type " sm_ban #3 10 aimbot " in comsole
2.return "[SourceBans] This player has not been verified. Please wait thirty seconds before retrying."

What happens?
-------------
ban is not successful

What were you expecting to happen?
----------------------------------
ban #3

Any logs, error output, etc.?
----------------------------
ban from web and return
Error: the XML response that was returned from the server is invalid. Received:
Fatal error: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysql' at line 1] in EXECUTE("INSERT INTO p6oy_log(type,title,message, function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'function, query, aid, host, created)\r\n VALUES (\'m\',\'Ban Added\',\'Ban against\' at line 1] in EXECUTE(\"INSERT INTO p6oy_log(type,title,message, function, query, aid, host, created)\r\n VALUES (\'m\',\'Ban Added\',\'Ban against (STEAM_0:1:535667458) has been added, reason: Aimbot, length: 10\',\'E:\\\\wwwroot\\\\cs.p6oy.top\\\\includes\\\\xajax.inc.php - 1090
E:\\\\wwwroot\\\\cs.p6oy.top\\\\includes\\\\xajax.inc.php - 739
E:\\\\wwwroot\\\\cs.p6oy.top\\\\index.p in E:\wwwroot\cs.p6oy.top\includes\adodb\adodb-errorhandler.inc.php on line 79
You have whitespace in your response.

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System: win2012**
**SourceBans++ Version: 1.6.4**
**SourceMod Version: 1.11.0-git6927**
**MetaMod Version: 1.11.0-git1148**

**Comment by Rushaway** [comment]
It's because the player targeted can't be verified. That mean plugin can't retrive a valid SteamID.
You should check by using `status` in console if your target isn't in `STEAM_ID_PENDING` or `STEAM_ID_STOP_IGNORING_RETVALS`
This issue can occure on cracked css version and on non steam server.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/39212482/211195981-569891bf-1dc6-4141-a035-628eeb40a0ef.png)
i type "status" first and ban, and it is again

**Comment by Rushaway** [comment]
Can you provide us more details about your mysql version, your php version, also the plugin version.

**Comment by ghost** [comment]
php ver 7.4.30
sm ver 1.11.0-git6927
sb ver 1.6.4
i type "status" and "sm_ban" in the console, and it is still that.
![image](https://user-images.githubusercontent.com/39212482/211236178-fd0b5c94-93de-4323-918b-ff14a9e2dffe.png)
but it works if i type "!admin" in chat and ban with menu

**Comment by ghost** [comment]
when i remove all files about sb++, i can use sm_ban

**Comment by Cruze03** [comment]
I'm facing the same since 1-2 weeks. Does anybody have some solution to it? Game: CSGO

**Comment by q1085909155** [comment]
Again, does anyone have a solution

**Comment by InSelfControll** [comment]
> Can you provide us more details about your mysql version, your php version, also the plugin version.

I have the same issue.
OS: Rocky linux 9
MariaDB: 10.5
Sourcemod: 1.12 - latest dev ver
Metamod latest version
Latest Sourcebans++

Can't ban / mute /gag peoples.
Error:
[SourceComms++] •vGans has not been verified. Please wait thirty seconds before retrying.

And I get in SB another strange thing while trying to edit server permissions:
Rehashing Admin and Group data on all related servers...
Server #1 (1/1): Can't connect to server..

I checked with sb_debug_connection.php and the results are ok.

[+] SourceBans "Error Connecting()" Debug starting for server 0.0.0.0:27016

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: Bhop-IL.net | Bhop [ Tier 1 - 6 ] 128 Tick | Styles | 1000+ Maps

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!
Looks like everything working but still getting this issue

I checked the Sourcebans without nginx proxy and with nginx proxy, same result and with cloudflare and without cloudflare same result too.

I guess it's a bug on sourcebans.
Sourcebans and CSGO on same server

**Comment by sarahkittyy** [comment]
This is infuriating and a serious issue. Happens to random users from time to time and it's the worst. They can continue to troll or cause a problem or do whatever caused them to need to be banned and you're stuck until you type in banid manually.
