### ISSUE TITLE
Unable Import banned_user.cfg 

### ISSUE THREAD

**Issue by Mopper-Smurf** [sbpp/sourcebans-pp#849]
What are the steps to reproduce this issue?
-------------------------------------------
1. Login admin
2. Click admin panel
3. Click bans
4. Click import bans
5. Select file ( banned_user.cfg in my case )
6. Cick import

What happens?
----------------
Top screen a little screen pop up with the text: 0 bans have been imported and posted. 

What were you expecting to happen?
----------------------------------
That the ban list is imported and written to the database.

Any logs, error output, etc.?
----------------------------
No. The small screen disappears after a few seconds and thats it.

Any other comments?
-------------------
Full new install does not solve the problem.
I searched around, and found a similar problem with the old version of SB++

(https://forums.alliedmods.net/showthread.php?t=310811)

I compared the files, but this is not the solution for 1.7. 

What versions of software are you using?
----------------------------------------
**Operating System:** >> Linux 20.04 lts
**SourceBans++ Version:** >> SourceBans++ 1.7.0 | Git: 1145 
**PHP Version:** >> 8.0.26
**MySQL Version:** >>  15.1 (10.3.37) Maria DB
**Link to your project:**
**Link to a phpinfo() output:**

**Comment by Rushaway** [comment]
If you use 1.7.0 you should use PHP 7.4
If you want to use PHP 8 you have to run PHP 8.1 with Web 2.0.0b

**Comment by Mopper-Smurf** [comment]
> If you use 1.7.0 you should use PHP 7.4 If you want to use PHP 8 you have to run PHP 8.1 with Web 2.0.0b

I tried PHP 7.4, same result.
