### ISSUE TITLE
Multigroup Support

### ISSUE THREAD

**Issue by ghost** [sbpp/sourcebans-pp#85]
I'd like to request an enhancement to allow users to belong to multiple groups.

Example. I have a group of GMOD servers and a group of CSGO servers. Users can be admin level 3 in csgo but only admin level 1 for gmod. Currently we have things like csgol3gmodl1 and it's quite a mess. Being able to add a user to multiple groups would allow us to keep this organized.

**Comment by duhow** [comment]
That means to have permissions per server, not globally... If accepted, a
bit of work to do (table with SteamID and ServerID with selected
permissions)

**Comment by ghost** [comment]
is it possible to assign permissions to a server group rather than individual servers?
not sure if that would reduce the burden. table would then have steamid, group_id and permissions. seems like this would be more efficient (or take less space at the least)

**Comment by duhow** [comment]
The problem is that, from outside the server, we cannot know what server
groups are set (GMod, TF2...)

At least not without using the game addon.

But, you can make manual groups and set their permissions.

**Comment by ghost** [comment]
ah my bad. I was looking at the correlation between sb_admins, sb_srvgroups, sb_groups, and sb_admins_servers_groups. It seemed like with sb_admins.aid=sb_admins_servers_groups.admin_id, sb_srvgroups.id=sb_admins_servers_groups.group_id, and sb_groups.gid=sb_admins_servers_groups.srv_group_id we could just take the flags from sb_admins and apply to all servers within the sb_groups you're a member of.     

I'll back out and let the pros handle it, I had just drawn this up previously and thought it might help. thanks guys!
