### ISSUE TITLE
Banlist page is empty when using MariaDB

### ISSUE THREAD

**Issue by publicENEMY** [sbpp/sourcebans-pp#86]
Im using xampp for hosting. xampp is using MariaDB. banlist page still empty even after doing all 3 steps documented in your faqs. 

this post describe the solution.

https://forums.alliedmods.net/showpost.php?p=2310681&postcount=39

**Comment by sarabveer** [comment]
MariaDB isn't supported right now

**Comment by publicENEMY** [comment]
Maybe you could add some notes in the faq, just in case. As a workaround.
