### ISSUE TITLE
Mail error 500

### ISSUE THREAD

**Issue by flxrin1337** [sbpp/sourcebans-pp#864]
What are the steps to reproduce this issue?
-------------------------------------------
1. Just go to "Forgot your password?" in the Login page, type your e-mail, and you get the error.

What happens?
-------------
I get error 500 with no further explanation about what is wrong with it.

What were you expecting to happen?
----------------------------------
I expected to get an e-mail regarding password reset

Any logs, error output, etc.?
----------------------------

Idk where to find them

Any other comments?
-------------------
-

What versions of software are you using?
----------------------------------------
**Operating System: Linux**
**SourceBans++ Version:1.8.0**
**PHP Version:8.2**
**MySQL Version:Latest**
**Link to your project:-**
**Link to a phpinfo() output: I have no access**

**Comment by flxrin1337** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/37021829/221380774-9e804445-45d2-4a02-9029-4c4cdccce302.png)
A screenshot regarding this issue.

**Comment by walidkhaddoum** [comment]
could you provide us code with hiding your credentials ?

**Comment by flxrin1337** [comment]
> could you provide us code with hiding your credentials ?

Sure!
Here is the settings given to me by cPanel:
![Screenshot_4](https://user-images.githubusercontent.com/37021829/221381824-4bbd3911-b7b2-4f8d-aaac-7754725357c3.png)

And here is the settings that I saved in sb:
![Screenshot_3](https://user-images.githubusercontent.com/37021829/221381836-8edd0930-6380-48a3-a2f7-42b1ce663e52.png)

**Comment by DeUltima** [comment]
Did you find a solution to this issue? Because, I'm having the same problem.

**Comment by Sarrus1** [comment]
Now that this has been merged https://github.com/sbpp/sourcebans-pp/pull/884, try to see if it fixed your issue.

**Comment by DeUltima** [comment]
> Now that this has been merged #884, try to see if it fixed your issue.

Oh nice, yes! Renaming the mail folder to Mail did solve the issue for me. Thank you!
