### ISSUE TITLE
Web Terminal Error

### ISSUE THREAD

**Issue by IG-PhantomX** [sbpp/sourcebans-pp#872]
What are the steps to reproduce this issue?
-------------------------------------------
1.  Upgraded Sourcebans 

What happens?
-------------
After running the updater and deleting the installer/updater, when I try to load the web page for sb it throws this error:

Fatal error: Uncaught Error: Call to undefined function ADONewConnection() in /usr/www/mywebiste/bans/init.php:109 Stack trace: #0 /usr/www/mywebsite/bans/index.php(20): include_once() #1 {main} thrown in /usr/www/mywebsite/bans/init.php on line 109

**Comment by Rushaway** [comment]
Hello.
What was your original version and your new version.
Did you run the update.php?
Are you using another theme than the default one? More infos will be helpful if you need help.
That why you have a template to follow when you create an issue.

**Comment by IG-PhantomX** [comment]
Thank you for the response.

I ended up attempting a fresh installation of SB - so it should be all
default.  The installer worked fine - it setup the database, deleted the
installer/updater.

PHP 8.1.12
Linux 5.15.79 (gentoo distro)
Hosted on NFOServers Managed Server
MySQLlnd 8.1.12
Composer 2.5.4

Is there any other info that would be helpful?

When I try to load the webpage it gives this error:

*Fatal error*: Uncaught Error: Call to undefined function
ADONewConnection() in /usr/www/mysite/bans/init.php:109 Stack trace: #0
/usr/www/ mysite/bans/index.php(20): include_once() #1 {main} thrown in
*/usr/www/*mysite*/bans/init.php* on line *109*

**Comment by Rushaway** [comment]
It's related to NFO Hosting Service.
Contact them, they are missing the sodium extension required in the version bump for JWT in Composer dependencies.

**Comment by IG-PhantomX** [comment]
To help others, I managed to get past this hurdle.  I have encountered a new issue, but here is what I did:

updated composer using --ignore-platform-req=ext-sodium
