### ISSUE TITLE
Sourcebans Install 1.7.0 Error

### ISSUE THREAD

**Issue by Fate970730** [sbpp/sourcebans-pp#873]
What happens?
-------------
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in C:\xampp\htdocs\bans\install\includes\routing.php on line 5

**Comment by rumblefrog** [comment]
Please follow the issue template

**Comment by trollollol123** [comment]
I have the same issue.

**Comment by Rushaway** [comment]
@BrutalCSEjziponken Open an issue and follow the template. And tell us how to reproduct it.

**Comment by huyudai** [comment]
me too.l dont know how to fix it
