### ISSUE TITLE
Mute from webpanel not working

### ISSUE THREAD

**Issue by NickCloudAT** [sbpp/sourcebans-pp#880]
What are the steps to reproduce this issue?
-------------------------------------------
1. Place comms MUTE on a player from webpanel

What happens?
-------------
The mute gets added successfully on the panel, the server itself also receives the following message:
![image](https://user-images.githubusercontent.com/20370962/227795779-d26c34ea-5767-4c49-8819-7663448d6043.png)

If I look into the "View Punishments" ingame, the client is also not listed there (yes the client is online and he can still use chat).

When I delete the mute, it even says he's not muted in console:
![image](https://user-images.githubusercontent.com/20370962/227795928-ea2036dd-dc0d-4def-b527-ed2e17f7fef2.png)

What were you expecting to happen?
----------------------------------
Player should be muted

Any logs, error output, etc.?
----------------------------
There are no errors

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** For the Server: Ubuntu 20.04
**SourceBans++ Version:**1.8.0
**PHP Version:** 8.1.17
**MySQL Version:** 10.3.18-MariaDB

**Comment by AlekseyMur** [comment]
The problem still remains. I have the same problem. Apparently there is no solution yet.
I found out that it only works when the player restarts the game.
