### ISSUE TITLE
Not able to login in...

### ISSUE THREAD

**Issue by mrnoahfink** [sbpp/sourcebans-pp#895]
What are the steps to reproduce this issue?
-------------------------------------------
1. Got to sourceban website
2. Login into the admin account

What happens?
-------------
After login in, nothing happened beside return to the dashboard. No admin panel show up.

What were you expecting to happen?
----------------------------------
I was expecting login into my account then I should have access to the admin panel.

Any logs, error output, etc.?
----------------------------
There no errors, but here access log - 
[access.log](https://github.com/sbpp/sourcebans-pp/files/11571327/access.log)

Any other comments?
-------------------
Here video of me doing it.

https://youtu.be/KbFAZk5G3bE

What versions of software are you using?
----------------------------------------
**Operating System:** <---- Ubuntu 22.04
**SourceBans++ Version:** <----- 1.8.0 | Git: 1294
**PHP Version:** 8.1
**MySQL Version:** MaraiaDB 10.9.6

**Comment by Rushaway** [comment]
Can you check your php modules and send us the results? 
`php - m`

**Comment by mrnoahfink** [comment]
Yep! Just did that. 

[hereresult.txt](https://github.com/sbpp/sourcebans-pp/files/11571988/hereresult.txt)

**Comment by Squallqt** [comment]
same problem here with debian 11 also tested with php 8.1-8.2 and lot of maria db
running from apache2

**Comment by mrnoahfink** [comment]
Also sourcebans running from nginx. I hope this rings a bell...

**Comment by mrnoahfink** [comment]
Bumped. Any idea when this is going to be fixed?

**Comment by mrnoahfink** [comment]
Here more access log info if need. Don't worry about ip address as it is private.

[access.log](https://github.com/sbpp/sourcebans-pp/files/11619642/access.log)

**Comment by mrnoahfink** [comment]
#899 Seem fixed the logging issue! I will leave this open if there still more issue come by.

Thank wrossmann!

**Comment by ry1nffx11** [comment]
how you fixed it ?

**Comment by ry1nffx11** [comment]
> #899 Seem fixed the logging issue! I will leave this open if there still more issue come by.
> 
> Thank wrossmann!

how you fixed it

**Comment by fbef0102** [comment]
same here. can't login, even the password is correct

Edit: Solved, download the current master branch version

**Comment by Rushaway** [comment]
Can be closed, solved in 0594a24

**Comment by mrnoahfink** [comment]
This should have been closed a long time ago. Closing now.
