### ISSUE TITLE
Report Player Page Broken

### ISSUE THREAD

**Issue by kilroy98** [sbpp/sourcebans-pp#90]
After MariaDB fix, report player page don't work
http://i5.imageban.ru/out/2015/12/04/df0ae4264d2d8d505767c6370d60b749.jpg
Version SB - 1.5.4-dev-git309

**Comment by sarabveer** [comment]
Please Reinstall SourceBans WebPanel from Scratch.

**Comment by kilroy98** [comment]
I'm download latest version and now page works
