### ISSUE TITLE
Sidepanel menu buttons don't work after 1.7 update

### ISSUE THREAD

**Issue by Dragonissa** [sbpp/sourcebans-pp#904]
What are the steps to reproduce this issue?
-------------------------------------------
1. Upgrade to 1.7
2. Go to Admin Panel -> Any Page with the side panel menu (webpanel settings)
3. Click button

![image](https://github.com/sbpp/sourcebans-pp/assets/4233773/07c7cbcb-0a22-4624-8537-4fa2371ee1a0)

What happens?
-------------
Nothing. The only button that works is the Back button

What were you expecting to happen?
----------------------------------
Automatic scroll or switch to the feature clicked

Any logs, error output, etc.?
----------------------------

https://gist.github.com/Dragonisser/8c9e482d3f409849e36b27177c573c6a
![image](https://github.com/sbpp/sourcebans-pp/assets/4233773/a93719d3-b3fc-43d8-9861-dce63e2b49ac)

What versions of software are you using?
----------------------------------------
**Operating System:** ubuntu 20.04.3
**SourceBans++ Version:** 1.7 (latest)
**PHP Version:** 8.1

**Comment by Rushaway** [comment]
Do you have any extensions or plugins who can disable/block some JS?

**Comment by Dragonissa** [comment]
> Do you have any extensions or plugins who can disable/block some JS?

I've disabled those that could cause such issues (though, i don't even block JS by default) but that didn't really change much. I can try a different browser.

---
Edit:

Oddly it works with Firefox.

**It was a caching issue. ctrl+shift+r fixed it.**
