### ISSUE TITLE
Comms not working from in-game

### ISSUE THREAD

**Issue by InSelfControll** [sbpp/sourcebans-pp#907]
I have the same issue.
OS: Rocky linux 9 - fully updated
Selinux - disabled
MariaDB: 10.5
Sourcemod: 1.12 - latest dev ver
Metamod latest version
Latest Sourcebans++ - 1.7.0
PHP - 8.2

Can't mute /gag peoples.
Error:
[SourceComms++] •vGans has not been verified. Please wait thirty seconds before retrying.

And I get in SB another strange thing while trying to edit server permissions:
Rehashing Admin and Group data on all related servers...
Server #1 (1/1): Can't connect to server..

I checked with sb_debug_connection.php and the results are ok.

[+] SourceBans "Error Connecting()" Debug starting for server 0.0.0.0:27016

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server: Bhop-IL.net | Bhop [ Tier 1 - 6 ] 128 Tick | Styles | 1000+ Maps

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!
Looks like everything working but still getting this issue

I checked the Sourcebans without nginx proxy and with nginx proxy, same result and with cloudflare and without cloudflare same result too.

There is nothing in sourcebans logs.

I guess it's a bug on sourcebans.
Sourcebans and CSGO on same server

**Comment by crashzk** [comment]
Yes, the same error I encountered when I installed the latest version of the [php81](https://github.com/sbpp/sourcebans-pp) branch.

However, in the sourcebans discord about this error, they informed me to install this version: https://cdn.discordapp.com/attachments/642124427894456325/1126785918162964530/sbpp_comms.smx

![image](https://github.com/sbpp/sourcebans-pp/assets/32937653/a5c86b5f-2534-45fe-8f1d-4b686020138b)

I believe there are already some issues and PR about this issue.

https://github.com/sbpp/sourcebans-pp/issues/870
https://github.com/sbpp/sourcebans-pp/pull/893
