### ISSUE TITLE
Most recent ban list does not show nick of some players

### ISSUE THREAD

**Issue by crashzk** [sbpp/sourcebans-pp#909]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install SourceBans from branch [php81](https://github.com/sbpp/sourcebans-pp)
2. Ban any player that has a different font in their nick

What happens?
-------------
Some fonts that players use in their nicks are not showing up in the latest sourcebans web ban list.

![image](https://github.com/sbpp/sourcebans-pp/assets/32937653/0222c6b1-7347-403c-a1f9-99c0e03882e1)

What were you expecting to happen?
----------------------------------
Version 1.7.0 correctly showed player nicks. no matter what font they used in the nick, it was only when I upgraded to the php81 branch that this bug started.

Any logs, error output, etc.?
----------------------------
![image](https://github.com/sbpp/sourcebans-pp/assets/32937653/3112a1a9-055e-4c0a-b131-77e0d7641288)

Any other comments?
-------------------
This error only happens in the most recent bans list, when I click on the user who was banned that does not show the nick to obtain more information about the ban the nick shows normally and in the bans tab it also shows everything right.

![image](https://github.com/sbpp/sourcebans-pp/assets/32937653/a9b35fd3-0acb-4ee2-ac20-2b4a4b49ce6d)

What versions of software are you using?
----------------------------------------
**Operating System:** Linux
**SourceBans++ Version:** 1.8.0 | Git: 1294
**PHP Version:** php81
**MySQL Version:** 10.3.39-MariaDB
**Link to your project:** https://sourcebans.zkservidores.com
**Link to a phpinfo() output:**

**Comment by Rushaway** [comment]
Hello.
This issue occure aswell when you switch on default theme ?

**Comment by crashzk** [comment]
> Hello. This issue occure aswell when you switch on default theme ?

Hello yes. Forgot to mention, but it does happen in the default theme as well.

**Comment by Rushaway** [comment]
I can't access to your site (from france)
Could you provide a list of name who doesn't works properly?
Regards.

**Comment by crashzk** [comment]
@Rushaway could you try accessing again, I believe it was an error on the part of my host, here it was also giving an error.

In any case, here is the list of names that are not showing.

- ☂𝕝𝕖𝕝𝕠𝕒𝟙♡ - https://steamcommunity.com/profiles/76561198123158443
- ♥ 𝚂𝚙𝚘𝚝𝚣𝚒𝚗 - https://steamcommunity.com/profiles/76561198949930530
- υ̲̅я̲̅є̲̅т̲̅
- ❤ 𝙄𝙨𝙖
- ♥ 𝙄𝙨𝙖
- ❤ kat

Just an observation, I said that it would only be in the most recent bans list, but it is in all the most recent lists, whether bans, comms and even those that the server blocked the entry.

![image](https://github.com/sbpp/sourcebans-pp/assets/32937653/921a577a-25ce-4c7e-9d72-0bea310a2b2d)
![image](https://github.com/sbpp/sourcebans-pp/assets/32937653/56327420-e579-4a5f-8801-64b31c5d07c4)

**Comment by ohathar** [comment]
To add to the list of usernames that don't appear on the dashboard (but do on the bans page)
[SGT] 爱补枪的沃小德
dashboard
![image](https://github.com/sbpp/sourcebans-pp/assets/6678917/821f0fc3-b1d1-475e-b200-1b1e46ad8928)
vs bans page
![image](https://github.com/sbpp/sourcebans-pp/assets/6678917/80ce1c6a-d78f-4382-a83e-292bf2db9ad4)

Thanks for all the hard work on SBPP! It's truly a lifesaver <3
