### ISSUE TITLE
Sourcebans Ban list not showing anymore

### ISSUE THREAD

**Issue by rodopoulos1** [sbpp/sourcebans-pp#912]
Sourcebans Ban list not showing anymore. This days appeared normal but last week this happens!

I dont know if thi is a bug but i need help!
![imagesbpp](https://github.com/sbpp/sourcebans-pp/assets/101236856/809b81ab-9089-4817-949d-67e2b50393cd)

**Comment by Rushaway** [comment]
Hello.
Search in your sb_bans table a ban with a bad steamid (like a bot) and delete it.

**Comment by mihaigsm2003** [comment]
some problems if ban is on IP, how to solve?

**Comment by Rushaway** [comment]
Need a better explain, wdym by "if ban is on IP" ?

**Comment by mihaigsm2003** [comment]
if use command in console sm_addban <ip> banlist not show, anyway, i solve by delete ban from database.

**Comment by Rushaway** [comment]
Alright, you can close this issue.
Have a great day.
