### ISSUE TITLE
Mute/Gag not applied in game when permanently muted/gaged on Sourceban database 

### ISSUE THREAD

**Issue by khalik38** [sbpp/sourcebans-pp#913]
Since the latest TF2 update (20th July 2023)

Mute/Gag not being applied in game when a steamid is permanently muted/gaged on Sourceban database.

Can someone look into this.

**Comment by Rushaway** [comment]
Did you try to recompile the plugins with the new max players for TF2? It was increased to 100 players max. https://github.com/alliedmodders/sourcemod/commit/d83c498a8fb9958a62de9ebb90e7e1b0795a34af 
Sadly I don't have any TF2 servers to test it.

**Comment by khalik38** [comment]
TF2 actual game does not support 100 players as far as I am aware, even if Sourcemod supports it.

Am I missing something?
________________________________

**Comment by khalik38** [comment]
Fixed

Re-downloaded 1.6.4 (server only files)

[https://github.com/sbpp/sourcebans-p...ases/tag/1.6.4](https://github.com/sbpp/sourcebans-pp/releases/tag/1.6.4)
__________________

**Comment by Rushaway** [comment]
This issue was due to web panel sending the steamid format as type 3 and plugin try to match a SteamID 2 format. 
Will be fixed in the next release.
