### ISSUE TITLE
Blocked Ban List

### ISSUE THREAD

**Issue by pepethugs** [sbpp/sourcebans-pp#93]
After the latest version of CS:GO have a problem with the "blocked" on the ban list repeats several times the player's name.
I've done the update SourceMod, I have done update in the admin panel SourceBans.
How can I resolve the situation and delete these "blocked"?
I also have another problem I can not solve it gives me errors on servers with admins groups ([sb_admcfg.smx](line 7) Unknown group "Master")
And another problem with the plugin "sb_viewbans" it gives me this error: Unable to load plugin "sb_viewbans.smx": Native "SB_Connect" was not found.

I thank you all the help you can give.

**Comment by sarabveer** [comment]
There is no such plugin as sb_viewbans

**Comment by sarabveer** [comment]
You are using SB2.0 plugins and SB++ plugins at the same time.

Please delete all SourceBans plugins and install the SourceBans++ plugins.

**Comment by pepethugs** [comment]
Thank you for your help.
And as the list of "blocked Connections" How can I solve the problem?
