### ISSUE TITLE
Blocked Connections on Ban Page (CS:GO Update Dec, 2015)

### ISSUE THREAD

**Issue by pepethugs** [sbpp/sourcebans-pp#94]
Sorry Sarabveer.
But can not correct the error of repeating the name of the players on ban list (Blocked Connections) this was after the update CS: GO.
I've read people who have this error and the problem was fixed with the update SourceMod but I already did the update and remains the same and the worst is that when I give ban on the player appears many messages in chat inside the server.
Can you help me?
Sorry to open another topic but I really need help.

**Comment by sarabveer** [comment]
Please recompile the plugins

**Comment by pepethugs** [comment]
It worked.
But now how do I delete the list of "blocked Connections" ?

**Comment by sarabveer** [comment]
Well, you have to delete the duplicate blocked connections yourself using some type of DB software, like PHPMyAdmin

**Comment by pepethugs** [comment]
Thanks my friend you are the best :)
