### ISSUE TITLE
bug: Negative ban lenght

### ISSUE THREAD

**Issue by Rushaway** [sbpp/sourcebans-pp#949]
What are the steps to reproduce this issue?
-------------------------------------------
1. `sm_ban @me -1 test`

What happens?
-------------
You get banned for the session. But it's useless the ban is automatically expire.

What were you expecting to happen?
----------------------------------
Abort the ban, duration is incorrect. 

Any logs, error output, etc.?
----------------------------

N/A

Any other comments?
-------------------
N/A

What versions of software are you using?
----------------------------------------
**Operating System:** ubuntu 20.04
**SourceBans++ Version:** latest
**SourceMod Version:** 1.12
**MetaMod Version:** 1.12

**Comment by sunstep** [comment]
This issue will be solved soon. Check out PR #953

**Comment by Rushaway** [comment]
Fixed in bf5303b
