### ISSUE TITLE
No shows a list of bans

### ISSUE THREAD

**Issue by Pomelo322** [sbpp/sourcebans-pp#95]
Hello,
When upgrading from 1.4.11 to 1.5.3 encountered a problem with a list of bans, which does not see.
Everything works fine, but included in the list of bans, we have just a blank page.
http://4funcsgo.cs-classic.pl/index.php?p=banlist

I tried to install the same version 1.5.3, but I have the same problem

**Comment by sarabveer** [comment]
https://forums.alliedmods.net/showpost.php?p=2373587&postcount=441
