### ISSUE TITLE
Add STEAM ID3 when adding admins

### ISSUE THREAD

**Issue by iGreen123** [sbpp/sourcebans-pp#96]
hi, can you please add steam id 3 support when adding admins? because it says invalid steam id, so how in the world am i going to add admins ?

**Comment by obtoon** [comment]
You're supposed to add admins using SteamID32, thats the only SteamID format Sourcemod will take. 

Nevertheless I spent about 10 minutes looking into implementing something like this (but site wide) a few hours ago. Might be able to implement this soonish.

**Comment by sarabveer** [comment]
Just use the old Steam2 ID

**Comment by iGreen123** [comment]
ok thanks, but would be nice if you could add posibility for steam3 to web interface when adding admins. thanks :)

**Comment by sarabveer** [comment]
Just google a steamid finder and they convert steam3 to steam2. No need to add steam3 to adding admins.
