### ISSUE TITLE
SB cannot connect to server

### ISSUE THREAD

**Issue by iNilo** [sbpp/sourcebans-pp#97]
sb_debug_connection.php log ->

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[-] Error getting server info. Can't read from UDP stream. Port is possibly blocked.

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response! 
[+] Password correct!

Sourcebans sits at -> Querying Server Data...

Im using the master repo

**Comment by sarabveer** [comment]
This is not a SourceBans problem, its a problem with your webhost blocking ports or the game server blocking ur webserver.

I can't help you.

**Comment by iNilo** [comment]
why did sb_debug_connection.php work ? and why is 1.5.3 working but 1.5.4-dev not ?

**Comment by sarabveer** [comment]
Well why didn't you tell us that before.

Check the Webhosts PHP Logs and the System Logs on the Admin Panel in SB++
