### ISSUE TITLE
Feature Request: Kickit but for communication blocks

### ISSUE THREAD

**Issue by Wheretf2** [sbpp/sourcebans-pp#983]
Is your feature request related to a problem? Please describe.
-------------------------------------------------------------
When moderators post communication blocks via webpage and a player is in a server without their knowledge, the blocked player is still able to communicate freely until they reconnect.

Describe the solution you'd like
--------------------------------
I'd like to see the kickit feature added for communication blocks as well. When a ban is posted from webpage, it will kick the player if they are in a server; I would like communication to work the same in either a kick forcing them to rejoin, or ideally just blocking communication access for the duration of the block as if they had rejoined.

Describe alternatives you've considered
---------------------------------------
I don't have any alternatives in mind, I think the kickit feature if perfect for what it does, and would like to see it used for communication punishments as well.

Additional context
------------------
N/A

**Comment by Rushaway** [comment]
It should be already the case, when a comms is performed via web panel, player is mute/gagged ingame directly. 
What version of web + sbcomms are you using ?

**Comment by Wheretf2** [comment]
Web: Latest release: 1.8.0
Latest Git: 1320
You have the Latest Release.
A New Dev Version is Available.
Also using [Fluent theme](https://github.com/Rushaway/sourcebans-web-theme-fluent)
Server:
Version: 1.8.1

I have seen blocks that I've deleted get removed in real time, however seemingly not when they are posted

**Comment by Wheretf2** [comment]
I also just discovered that despite seeing the rcon command come through in game console when unmuting myself from panel after muting myself in-game, that I am still unable to chat, even though rcon did run sc_fw_ungag mysteamid

**Comment by Rushaway** [comment]
Could you give a try with latest release ? For me it was because you're running an old version of the web panel or game server plugins outdated. We're missing informations to help you.

**Comment by Wheretf2** [comment]
Hello,

After updating the latest game plugins, the issue is no longer present

Thank you
