### ISSUE TITLE
Font Size is too Big (Git: 316)

### ISSUE THREAD

**Issue by kilroy98** [sbpp/sourcebans-pp#99]
Installed latest version. This is on all pages, the text is too large and the page is very stretched down. In general all seen in the screenshots.
http://i2.imageban.ru/out/2015/12/31/cdd7bed560302579d219292b373e17ad.jpg
http://i6.imageban.ru/out/2015/12/31/d6f65b1c3fb11d14f209eb954ddf4eef.jpg
P.S. Google Translate.

**Comment by sarabveer** [comment]
Try the git before this one

**Comment by sarabveer** [comment]
https://github.com/Sarabveer/SourceBans-Fork/commit/d75cb7fd47344f953add32208d9c4e57343b1b21

**Comment by kilroy98** [comment]
Install git317 and mistakes remained. And login to account not working =\ (on git316 also not working)
P.S. Google Translate =(

**Comment by sarabveer** [comment]
git317 wasn't a fix.

**Comment by kilroy98** [comment]
Only on me such problem? =((

**Comment by sarabveer** [comment]
I have the problem also (https://game.sarabveer.me/down/bans)

I am looking into it
